// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A ring buffer of 8 u8 entries indexed by u8 head/tail (& wrap).
#include "loomcc-test.h"
#define CAP 8
static u8 buf[CAP];
static u8 head, tail, count;
static u8 push(u8 v) { if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) & 7); count++; return 1; }
static u8 pop(u8 *v) { if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) & 7); count--; return 1; }
int main(void) {
  u8 v = 0;
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(push(228) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 228);
  CHECK(push(111) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 111);
  CHECK(pop(&v) == 0);
  CHECK(push(99) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 99);
  CHECK(push(221) == 1);
  CHECK(push(231) == 1);
  CHECK(push(10) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 221);
  CHECK(pop(&v) == 1); CHECK(v == 231);
  CHECK(push(177) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 10);
  CHECK(push(120) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 177);
  CHECK(pop(&v) == 1); CHECK(v == 120);
  CHECK(pop(&v) == 0);
  CHECK(push(201) == 1);
  CHECK(push(219) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 201);
  CHECK(push(153) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 219);
  CHECK(pop(&v) == 1); CHECK(v == 153);
  CHECK(pop(&v) == 0);
  CHECK(push(85) == 1);
  CHECK(push(29) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 85);
  CHECK(pop(&v) == 1); CHECK(v == 29);
  CHECK(pop(&v) == 0);
  CHECK(push(253) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 253);
  CHECK(pop(&v) == 0);
  CHECK(push(20) == 1);
  CHECK(push(240) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 20);
  CHECK(pop(&v) == 1); CHECK(v == 240);
  CHECK(pop(&v) == 0);
  CHECK(push(255) == 1);
  CHECK(push(168) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 255);
  CHECK(pop(&v) == 1); CHECK(v == 168);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(push(14) == 1);
  CHECK(push(61) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 14);
  CHECK(pop(&v) == 1); CHECK(v == 61);
  CHECK(push(251) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 251);
  CHECK(push(119) == 1);
  CHECK(push(84) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 119);
  CHECK(pop(&v) == 1); CHECK(v == 84);
  CHECK(pop(&v) == 0);
  return 0;
}
