// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// i8 op i8 stored into a i16: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile i8 a, b;
static volatile i16 d;
int main(void) {
  a = -128; b = 0; d = a + b; CHECK(d == (i16)((-128)));
  a = -1; b = 127; d = a & b; CHECK(d == (i16)((127)));
  a = -128; b = -128; d = a & b; CHECK(d == (i16)((-128)));
  a = -128; b = 2; d = a | b; CHECK(d == (i16)((-126)));
  a = -1; b = -127; d = a ^ b; CHECK(d == (i16)((126)));
  a = 2; b = 127; d = a ^ b; CHECK(d == (i16)((125)));
  a = -128; b = -127; d = a ^ b; CHECK(d == (i16)((1)));
  a = 0; b = -128; d = a & b; CHECK(d == (i16)((0)));
  a = 100; b = 100; d = a | b; CHECK(d == (i16)((100)));
  a = 1; b = -127; d = a ^ b; CHECK(d == (i16)((-128)));
  a = 2; b = 1; d = a + b; CHECK(d == (i16)((3)));
  a = 2; b = 2; d = a - b; CHECK(d == (i16)((0)));
  a = 0; b = -128; d = a + b; CHECK(d == (i16)((-128)));
  a = -1; b = -3; d = a & b; CHECK(d == (i16)((-3)));
  a = -1; b = -127; d = a + b; CHECK(d == (i16)((-128)));
  a = 2; b = 2; d = a | b; CHECK(d == (i16)((2)));
  a = 2; b = -3; d = a - b; CHECK(d == (i16)((5)));
  a = 2; b = 127; d = a | b; CHECK(d == (i16)((127)));
  a = 0; b = -3; d = a + b; CHECK(d == (i16)((-3)));
  a = -128; b = -1; d = a & b; CHECK(d == (i16)((-128)));
  a = -3; b = -127; d = a + b; CHECK(d == (i16)((-130)));
  a = -3; b = -127; d = a & b; CHECK(d == (i16)((-127)));
  a = -3; b = 0; d = a & b; CHECK(d == (i16)((0)));
  a = 2; b = 127; d = a | b; CHECK(d == (i16)((127)));
  return 0;
}
