// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// u16 op u16 stored into a u16: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile u16 a, b;
static volatile u16 d;
int main(void) {
  a = 65535; b = 255; d = a - b; CHECK(d == (u16)(65280u));
  a = 32768; b = 32768; d = a + b; CHECK(d == (u16)(0u));
  a = 32767; b = 0; d = a & b; CHECK(d == (u16)(0u));
  a = 2; b = 1; d = a | b; CHECK(d == (u16)(3u));
  a = 256; b = 255; d = a | b; CHECK(d == (u16)(511u));
  a = 255; b = 1; d = a - b; CHECK(d == (u16)(254u));
  a = 255; b = 40000; d = a + b; CHECK(d == (u16)(40255u));
  a = 40000; b = 32767; d = a ^ b; CHECK(d == (u16)(58303u));
  a = 1000; b = 1000; d = a + b; CHECK(d == (u16)(2000u));
  a = 1; b = 1000; d = a | b; CHECK(d == (u16)(1001u));
  a = 255; b = 1; d = a + b; CHECK(d == (u16)(256u));
  a = 40000; b = 1000; d = a & b; CHECK(d == (u16)(64u));
  a = 32768; b = 255; d = a + b; CHECK(d == (u16)(33023u));
  a = 1000; b = 256; d = a | b; CHECK(d == (u16)(1000u));
  a = 256; b = 65535; d = a + b; CHECK(d == (u16)(255u));
  a = 1; b = 256; d = a | b; CHECK(d == (u16)(257u));
  a = 40000; b = 255; d = a & b; CHECK(d == (u16)(64u));
  a = 40000; b = 32768; d = a ^ b; CHECK(d == (u16)(7232u));
  a = 1000; b = 32767; d = a & b; CHECK(d == (u16)(1000u));
  a = 255; b = 65535; d = a ^ b; CHECK(d == (u16)(65280u));
  a = 65535; b = 255; d = a & b; CHECK(d == (u16)(255u));
  a = 2; b = 255; d = a - b; CHECK(d == (u16)(65283u));
  a = 0; b = 0; d = a & b; CHECK(d == (u16)(0u));
  a = 40000; b = 65535; d = a ^ b; CHECK(d == (u16)(25535u));
  return 0;
}
