// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// u8 op u8 stored into a u16: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile u8 a, b;
static volatile u16 d;
int main(void) {
  a = 100; b = 0; d = a & b; CHECK(d == (u16)((0)));
  a = 100; b = 7; d = a & b; CHECK(d == (u16)((4)));
  a = 255; b = 2; d = a & b; CHECK(d == (u16)((2)));
  a = 100; b = 1; d = a & b; CHECK(d == (u16)((0)));
  a = 200; b = 127; d = a & b; CHECK(d == (u16)((72)));
  a = 0; b = 1; d = a | b; CHECK(d == (u16)((1)));
  a = 128; b = 127; d = a ^ b; CHECK(d == (u16)((255)));
  a = 200; b = 2; d = a + b; CHECK(d == (u16)((202)));
  a = 255; b = 1; d = a | b; CHECK(d == (u16)((255)));
  a = 200; b = 0; d = a | b; CHECK(d == (u16)((200)));
  a = 255; b = 1; d = a ^ b; CHECK(d == (u16)((254)));
  a = 200; b = 255; d = a + b; CHECK(d == (u16)((455)));
  a = 7; b = 127; d = a ^ b; CHECK(d == (u16)((120)));
  a = 2; b = 200; d = a + b; CHECK(d == (u16)((202)));
  a = 1; b = 200; d = a | b; CHECK(d == (u16)((201)));
  a = 100; b = 255; d = a + b; CHECK(d == (u16)((355)));
  a = 255; b = 7; d = a ^ b; CHECK(d == (u16)((248)));
  a = 0; b = 100; d = a & b; CHECK(d == (u16)((0)));
  a = 200; b = 128; d = a + b; CHECK(d == (u16)((328)));
  a = 1; b = 255; d = a & b; CHECK(d == (u16)((1)));
  a = 200; b = 255; d = a ^ b; CHECK(d == (u16)((55)));
  a = 100; b = 128; d = a - b; CHECK(d == (u16)((-28)));
  a = 1; b = 1; d = a & b; CHECK(d == (u16)((1)));
  a = 100; b = 128; d = a ^ b; CHECK(d == (u16)((228)));
  return 0;
}
