// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// u8 op u8 stored into a i16: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile u8 a, b;
static volatile i16 d;
int main(void) {
  a = 255; b = 127; d = a + b; CHECK(d == (i16)((382)));
  a = 1; b = 128; d = a ^ b; CHECK(d == (i16)((129)));
  a = 0; b = 127; d = a & b; CHECK(d == (i16)((0)));
  a = 0; b = 128; d = a ^ b; CHECK(d == (i16)((128)));
  a = 100; b = 7; d = a ^ b; CHECK(d == (i16)((99)));
  a = 7; b = 200; d = a ^ b; CHECK(d == (i16)((207)));
  a = 200; b = 200; d = a ^ b; CHECK(d == (i16)((0)));
  a = 0; b = 2; d = a & b; CHECK(d == (i16)((0)));
  a = 200; b = 0; d = a + b; CHECK(d == (i16)((200)));
  a = 128; b = 200; d = a & b; CHECK(d == (i16)((128)));
  a = 200; b = 100; d = a ^ b; CHECK(d == (i16)((172)));
  a = 1; b = 100; d = a + b; CHECK(d == (i16)((101)));
  a = 2; b = 128; d = a ^ b; CHECK(d == (i16)((130)));
  a = 200; b = 128; d = a - b; CHECK(d == (i16)((72)));
  a = 255; b = 255; d = a ^ b; CHECK(d == (i16)((0)));
  a = 127; b = 255; d = a + b; CHECK(d == (i16)((382)));
  a = 128; b = 200; d = a & b; CHECK(d == (i16)((128)));
  a = 255; b = 2; d = a | b; CHECK(d == (i16)((255)));
  a = 0; b = 2; d = a & b; CHECK(d == (i16)((0)));
  a = 2; b = 1; d = a | b; CHECK(d == (i16)((3)));
  a = 128; b = 0; d = a - b; CHECK(d == (i16)((128)));
  a = 200; b = 2; d = a & b; CHECK(d == (i16)((0)));
  a = 128; b = 0; d = a & b; CHECK(d == (i16)((0)));
  a = 2; b = 1; d = a & b; CHECK(d == (i16)((0)));
  return 0;
}
