// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// u8 op u8 stored into a u8: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile u8 a, b;
static volatile u8 d;
int main(void) {
  a = 127; b = 1; d = a | b; CHECK(d == (u8)((127)));
  a = 255; b = 200; d = a & b; CHECK(d == (u8)((200)));
  a = 127; b = 100; d = a & b; CHECK(d == (u8)((100)));
  a = 128; b = 128; d = a & b; CHECK(d == (u8)((128)));
  a = 0; b = 128; d = a + b; CHECK(d == (u8)((128)));
  a = 1; b = 0; d = a ^ b; CHECK(d == (u8)((1)));
  a = 200; b = 255; d = a + b; CHECK(d == (u8)((455)));
  a = 127; b = 128; d = a - b; CHECK(d == (u8)((-1)));
  a = 7; b = 255; d = a & b; CHECK(d == (u8)((7)));
  a = 127; b = 200; d = a - b; CHECK(d == (u8)((-73)));
  a = 0; b = 255; d = a ^ b; CHECK(d == (u8)((255)));
  a = 127; b = 127; d = a & b; CHECK(d == (u8)((127)));
  a = 7; b = 7; d = a + b; CHECK(d == (u8)((14)));
  a = 2; b = 127; d = a + b; CHECK(d == (u8)((129)));
  a = 127; b = 128; d = a & b; CHECK(d == (u8)((0)));
  a = 255; b = 100; d = a + b; CHECK(d == (u8)((355)));
  a = 7; b = 127; d = a - b; CHECK(d == (u8)((-120)));
  a = 200; b = 1; d = a | b; CHECK(d == (u8)((201)));
  a = 127; b = 100; d = a - b; CHECK(d == (u8)((27)));
  a = 255; b = 100; d = a ^ b; CHECK(d == (u8)((155)));
  a = 255; b = 0; d = a | b; CHECK(d == (u8)((255)));
  a = 100; b = 128; d = a ^ b; CHECK(d == (u8)((228)));
  a = 255; b = 7; d = a & b; CHECK(d == (u8)((7)));
  a = 1; b = 7; d = a | b; CHECK(d == (u8)((7)));
  return 0;
}
