// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [300] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[300];
  u16 i, s;
  for (i = 0; i < 300; i++) a0[i] = (u8)(i * 3 + 0);
  s = 0; for (i = 0; i < 300; i++) s = (u16)(s + a0[i]); CHECK(s == 35478u); CHECK(a0[299] == 129);
}
int main(void) { work(); return 0; }
