// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [200, 70] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[200];
  u8 a1[70];
  u16 i, s;
  for (i = 0; i < 200; i++) a0[i] = (u8)(i * 3 + 0);
  for (i = 0; i < 70; i++) a1[i] = (u8)(i * 4 + 1);
  s = 0; for (i = 0; i < 200; i++) s = (u16)(s + a0[i]); CHECK(s == 23092u); CHECK(a0[199] == 85);
  s = 0; for (i = 0; i < 70; i++) s = (u16)(s + a1[i]); CHECK(s == 8194u); CHECK(a1[69] == 21);
}
int main(void) { work(); return 0; }
