// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [16, 16, 16, 16] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[16];
  u8 a1[16];
  u8 a2[16];
  u8 a3[16];
  u16 i, s;
  for (i = 0; i < 16; i++) a0[i] = (u8)(i * 3 + 0);
  for (i = 0; i < 16; i++) a1[i] = (u8)(i * 4 + 1);
  for (i = 0; i < 16; i++) a2[i] = (u8)(i * 5 + 2);
  for (i = 0; i < 16; i++) a3[i] = (u8)(i * 6 + 3);
  s = 0; for (i = 0; i < 16; i++) s = (u16)(s + a0[i]); CHECK(s == 360u); CHECK(a0[15] == 45);
  s = 0; for (i = 0; i < 16; i++) s = (u16)(s + a1[i]); CHECK(s == 496u); CHECK(a1[15] == 61);
  s = 0; for (i = 0; i < 16; i++) s = (u16)(s + a2[i]); CHECK(s == 632u); CHECK(a2[15] == 77);
  s = 0; for (i = 0; i < 16; i++) s = (u16)(s + a3[i]); CHECK(s == 768u); CHECK(a3[15] == 93);
}
int main(void) { work(); return 0; }
