// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 7-state machine over 3 inputs from ROM tables, fed 17 inputs.
#include "loomcc-test.h"
static const u8 next_state[7][3] = {
  { 1, 4, 4 },
  { 3, 0, 4 },
  { 5, 2, 0 },
  { 2, 1, 1 },
  { 2, 3, 3 },
  { 3, 5, 3 },
  { 3, 2, 0 }
};
static const u8 action[7][3] = {
  { 3, 4, 3 },
  { 3, 4, 3 },
  { 1, 4, 0 },
  { 3, 3, 0 },
  { 3, 4, 3 },
  { 2, 2, 0 },
  { 2, 2, 2 }
};
static const u8 inputs[17] = { 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 0, 0 };
static u8 visits[7];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 17; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 2);
  CHECK(score == 121u);
  CHECK(visits[0] == 3);
  CHECK(visits[1] == 4);
  CHECK(visits[2] == 1);
  CHECK(visits[3] == 5);
  CHECK(visits[4] == 4);
  CHECK(visits[5] == 0);
  CHECK(visits[6] == 0);
  return 0;
}
