// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 2-state machine over 3 inputs from ROM tables, fed 7 inputs.
#include "loomcc-test.h"
static const u8 next_state[2][3] = {
  { 1, 0, 0 },
  { 1, 1, 1 }
};
static const u8 action[2][3] = {
  { 4, 4, 1 },
  { 1, 0, 1 }
};
static const u8 inputs[7] = { 2, 0, 2, 2, 2, 2, 0 };
static u8 visits[2];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 7; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 1);
  CHECK(score == 15u);
  CHECK(visits[0] == 1);
  CHECK(visits[1] == 6);
  return 0;
}
