// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 4-state machine over 3 inputs from ROM tables, fed 36 inputs.
#include "loomcc-test.h"
static const u8 next_state[4][3] = {
  { 3, 3, 1 },
  { 1, 0, 1 },
  { 3, 1, 1 },
  { 2, 3, 0 }
};
static const u8 action[4][3] = {
  { 3, 0, 2 },
  { 2, 0, 1 },
  { 3, 3, 3 },
  { 3, 1, 0 }
};
static const u8 inputs[36] = { 2, 2, 1, 0, 2, 2, 1, 2, 0, 1, 0, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 2, 2, 1, 0, 2, 2, 1, 2, 2, 0, 1, 0, 2, 1 };
static u8 visits[4];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 36; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 3);
  CHECK(score == 56u);
  CHECK(visits[0] == 13);
  CHECK(visits[1] == 17);
  CHECK(visits[2] == 0);
  CHECK(visits[3] == 6);
  return 0;
}
