// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Results through pointers to a struct member, an array element and a local.
#include "loomcc-test.h"
static const i16 data[3] = { 7640, -28558, 6562 };
typedef struct { i16 lo; u8 pad; i16 hi; } Range;
static void scan(const i16 *p, u8 n, i16 *lo, i16 *hi, i16 *sum) {
  u8 i;
  *lo = *hi = p[0];
  *sum = 0;
  for (i = 0; i < n; i++) { if (p[i] < *lo) *lo = p[i]; if (p[i] > *hi) *hi = p[i]; *sum = (i16)(*sum + p[i]); }
}
int main(void) {
  Range r;
  i16 sums[3];
  i16 hi2;
  scan(data, 3, &r.lo, &r.hi, &sums[1]);
  CHECK(r.lo == (-28558) && r.hi == (7640) && sums[1] == (-14356));
  scan(data + 1, 2, &sums[0], &hi2, &sums[2]);
  CHECK(sums[0] == (-28558) && hi2 == (6562) && sums[2] == (-21996));
  return 0;
}
