// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Pointer walks over a const ROM table of 30 records (u8):
// by pointer increment to an end pointer, by index, and backwards.
#include "loomcc-test.h"
typedef struct {
  u8 f0;
} Rec;
static const Rec table[30] = {
  { 123 },
  { 121 },
  { 73 },
  { 206 },
  { 38 },
  { 226 },
  { 79 },
  { 149 },
  { 131 },
  { 131 },
  { 146 },
  { 73 },
  { 108 },
  { 126 },
  { 180 },
  { 227 },
  { 249 },
  { 248 },
  { 205 },
  { 7 },
  { 150 },
  { 178 },
  { 221 },
  { 12 },
  { 49 },
  { 135 },
  { 135 },
  { 175 },
  { 71 },
  { 254 }
};
static const Rec *const table_end = table + 30;
static i32 sum_forward(u8 field) {
  const Rec *p;
  i32 s = 0;
  for (p = table; p != table_end; p++) {
    switch (field) {
    case 0: s += p->f0; break;
    }
  }
  return s;
}
static const Rec *last_max(void) {
  const Rec *p = table_end, *best = table;
  while (p != table) {
    p--;
    if (p->f0 > best->f0) best = p;
  }
  return best;
}
int main(void) {
  u8 i;
  CHECK(sum_forward(0) == (i32)4226LL);
  for (i = 0; i < 30; i++) CHECK(&table[i] - table == i);
  CHECK(table_end - table == 30);
  CHECK(last_max() - table == 29);
  return 0;
}
