// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 12x12 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 12
#define H 12
static const u8 map[W * H] = {
  0, 0, 7, 0, 3, 255, 1, 0, 0, 3, 0, 3,
  7, 255, 7, 0, 0, 1, 3, 0, 0, 0, 255, 2,
  0, 3, 3, 7, 3, 0, 0, 2, 0, 1, 7, 7,
  2, 0, 3, 1, 0, 2, 1, 3, 0, 0, 1, 0,
  7, 255, 1, 255, 0, 1, 0, 3, 3, 7, 3, 2,
  3, 2, 255, 255, 0, 7, 0, 3, 0, 0, 0, 2,
  0, 0, 3, 1, 0, 0, 255, 2, 7, 0, 0, 2,
  0, 1, 0, 7, 255, 2, 0, 7, 255, 7, 1, 3,
  2, 0, 255, 2, 2, 0, 255, 1, 0, 0, 0, 7,
  0, 255, 3, 0, 0, 0, 0, 0, 0, 3, 1, 2,
  0, 0, 3, 255, 3, 0, 0, 255, 255, 255, 0, 0,
  255, 255, 7, 0, 1, 0, 2, 0, 3, 0, 255, 2
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(58, 65) == 1); CHECK(solid(58, 65) == 1);
  CHECK(tile_at(76, 9) == 0); CHECK(solid(76, 9) == 0);
  CHECK(tile_at(96, 73) == 1); CHECK(solid(96, 73) == 1);
  CHECK(tile_at(6, 61) == 0); CHECK(solid(6, 61) == 0);
  CHECK(tile_at(28, 27) == 1); CHECK(solid(28, 27) == 1);
  CHECK(tile_at(7, 15) == 7); CHECK(solid(7, 15) == 1);
  CHECK(tile_at(33, 5) == 3); CHECK(solid(33, 5) == 1);
  CHECK(tile_at(26, 17) == 7); CHECK(solid(26, 17) == 1);
  CHECK(tile_at(51, 2) == 1); CHECK(solid(51, 2) == 1);
  CHECK(tile_at(85, 26) == 1); CHECK(solid(85, 26) == 1);
  CHECK(tile_at(51, -3) == 1); CHECK(solid(51, -3) == 1);
  CHECK(tile_at(43, 66) == 0); CHECK(solid(43, 66) == 0);
  CHECK(tile_at(37, 78) == 0); CHECK(solid(37, 78) == 0);
  CHECK(tile_at(37, 64) == 2); CHECK(solid(37, 64) == 1);
  CHECK(tile_at(63, 22) == 2); CHECK(solid(63, 22) == 1);
  CHECK(tile_at(65, -7) == 1); CHECK(solid(65, -7) == 1);
  CHECK(tile_at(39, 17) == 3); CHECK(solid(39, 17) == 1);
  CHECK(tile_at(-6, 102) == 1); CHECK(solid(-6, 102) == 1);
  CHECK(tile_at(72, 69) == 0); CHECK(solid(72, 69) == 0);
  CHECK(tile_at(11, 95) == 255); CHECK(solid(11, 95) == 0);
  CHECK(tile_at(29, 51) == 1); CHECK(solid(29, 51) == 1);
  CHECK(tile_at(17, 100) == 1); CHECK(solid(17, 100) == 1);
  CHECK(tile_at(103, 63) == 1); CHECK(solid(103, 63) == 1);
  CHECK(tile_at(93, 80) == 0); CHECK(solid(93, 80) == 0);
  return 0;
}
