// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 64x4 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 64
#define H 4
static const u8 map[W * H] = {
  2, 1, 1, 3, 3, 0, 0, 7, 3, 7, 2, 0, 255, 7, 255, 7, 1, 1, 1, 0, 1, 3, 3, 0, 3, 7, 3, 7, 7, 7, 2, 7, 1, 2, 2, 2, 0, 0, 255, 0, 0, 2, 3, 7, 0, 255, 7, 3, 3, 2, 2, 3, 0, 2, 7, 3, 1, 3, 3, 0, 0, 3, 0, 0,
  0, 0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 255, 1, 7, 0, 7, 2, 255, 0, 2, 3, 1, 255, 7, 0, 0, 2, 7, 255, 0, 2, 7, 3, 0, 0, 255, 7, 1, 3, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 0, 255, 1, 7, 0, 1, 1, 1, 3, 1, 2, 3,
  255, 0, 7, 0, 3, 0, 7, 2, 1, 255, 7, 7, 255, 0, 255, 2, 2, 0, 255, 3, 2, 1, 0, 7, 255, 0, 0, 3, 7, 3, 7, 7, 2, 7, 2, 0, 255, 7, 0, 3, 3, 0, 255, 0, 7, 7, 7, 7, 255, 2, 2, 0, 0, 255, 2, 7, 0, 0, 0, 7, 1, 1, 1, 2,
  1, 0, 0, 7, 0, 2, 3, 7, 7, 0, 255, 0, 1, 7, 255, 2, 255, 255, 3, 0, 3, 0, 255, 0, 0, 1, 0, 2, 7, 1, 0, 3, 0, 1, 2, 0, 2, 0, 3, 1, 3, 0, 0, 2, 0, 255, 0, 0, 255, 1, 7, 3, 1, 255, 1, 0, 0, 1, 0, 0, 7, 3, 255, 1
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(175, 26) == 0); CHECK(solid(175, 26) == 0);
  CHECK(tile_at(192, 0) == 3); CHECK(solid(192, 0) == 1);
  CHECK(tile_at(65, 23) == 1); CHECK(solid(65, 23) == 1);
  CHECK(tile_at(137, 1) == 1); CHECK(solid(137, 1) == 1);
  CHECK(tile_at(426, 8) == 255); CHECK(solid(426, 8) == 0);
  CHECK(tile_at(417, 3) == 0); CHECK(solid(417, 3) == 0);
  CHECK(tile_at(314, 18) == 3); CHECK(solid(314, 18) == 1);
  CHECK(tile_at(367, -3) == 1); CHECK(solid(367, -3) == 1);
  CHECK(tile_at(311, 24) == 3); CHECK(solid(311, 24) == 1);
  CHECK(tile_at(459, 23) == 0); CHECK(solid(459, 23) == 0);
  CHECK(tile_at(429, -1) == 1); CHECK(solid(429, -1) == 1);
  CHECK(tile_at(141, 34) == 1); CHECK(solid(141, 34) == 1);
  CHECK(tile_at(427, 10) == 255); CHECK(solid(427, 10) == 0);
  CHECK(tile_at(96, -5) == 1); CHECK(solid(96, -5) == 1);
  CHECK(tile_at(189, -5) == 1); CHECK(solid(189, -5) == 1);
  CHECK(tile_at(346, 28) == 2); CHECK(solid(346, 28) == 1);
  CHECK(tile_at(402, 16) == 2); CHECK(solid(402, 16) == 1);
  CHECK(tile_at(40, -1) == 1); CHECK(solid(40, -1) == 1);
  CHECK(tile_at(139, 5) == 1); CHECK(solid(139, 5) == 1);
  CHECK(tile_at(112, -5) == 1); CHECK(solid(112, -5) == 1);
  CHECK(tile_at(233, 25) == 1); CHECK(solid(233, 25) == 1);
  CHECK(tile_at(169, 15) == 0); CHECK(solid(169, 15) == 0);
  CHECK(tile_at(114, 28) == 255); CHECK(solid(114, 28) == 0);
  CHECK(tile_at(278, 13) == 7); CHECK(solid(278, 13) == 1);
  return 0;
}
