// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 12x12 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 12
#define H 12
static const u8 map[W * H] = {
  3, 2, 0, 0, 0, 255, 2, 255, 255, 3, 0, 255,
  7, 1, 1, 0, 255, 0, 3, 255, 0, 0, 2, 7,
  3, 7, 0, 3, 0, 1, 0, 2, 1, 1, 0, 1,
  2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 7, 3,
  255, 255, 3, 2, 0, 255, 0, 0, 2, 1, 0, 7,
  0, 1, 0, 2, 3, 0, 2, 2, 255, 0, 0, 1,
  2, 0, 2, 255, 0, 0, 2, 0, 2, 0, 7, 7,
  3, 255, 0, 2, 3, 1, 2, 0, 255, 3, 0, 255,
  0, 0, 0, 0, 3, 0, 0, 2, 255, 7, 0, 0,
  0, 255, 1, 2, 1, 3, 0, 7, 0, 7, 2, 0,
  3, 7, 3, 1, 0, 1, 255, 1, 255, 0, 7, 2,
  1, 1, 255, 3, 0, 2, 0, 1, 0, 0, 255, 0
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(79, 11) == 0); CHECK(solid(79, 11) == 0);
  CHECK(tile_at(53, 82) == 255); CHECK(solid(53, 82) == 0);
  CHECK(tile_at(84, 38) == 0); CHECK(solid(84, 38) == 0);
  CHECK(tile_at(88, 33) == 7); CHECK(solid(88, 33) == 1);
  CHECK(tile_at(84, 82) == 7); CHECK(solid(84, 82) == 1);
  CHECK(tile_at(53, 50) == 2); CHECK(solid(53, 50) == 1);
  CHECK(tile_at(53, 44) == 2); CHECK(solid(53, 44) == 1);
  CHECK(tile_at(54, 13) == 3); CHECK(solid(54, 13) == 1);
  CHECK(tile_at(27, 73) == 2); CHECK(solid(27, 73) == 1);
  CHECK(tile_at(49, 12) == 3); CHECK(solid(49, 12) == 1);
  CHECK(tile_at(31, 59) == 2); CHECK(solid(31, 59) == 1);
  CHECK(tile_at(50, 92) == 0); CHECK(solid(50, 92) == 0);
  CHECK(tile_at(82, 66) == 0); CHECK(solid(82, 66) == 0);
  CHECK(tile_at(96, 102) == 1); CHECK(solid(96, 102) == 1);
  CHECK(tile_at(100, 95) == 1); CHECK(solid(100, 95) == 1);
  CHECK(tile_at(98, 63) == 1); CHECK(solid(98, 63) == 1);
  CHECK(tile_at(51, 17) == 0); CHECK(solid(51, 17) == 0);
  CHECK(tile_at(81, 55) == 7); CHECK(solid(81, 55) == 1);
  CHECK(tile_at(6, 92) == 1); CHECK(solid(6, 92) == 1);
  CHECK(tile_at(-3, 58) == 1); CHECK(solid(-3, 58) == 1);
  CHECK(tile_at(70, 8) == 0); CHECK(solid(70, 8) == 0);
  CHECK(tile_at(82, -7) == 1); CHECK(solid(82, -7) == 1);
  CHECK(tile_at(96, 22) == 1); CHECK(solid(96, 22) == 1);
  CHECK(tile_at(48, 1) == 2); CHECK(solid(48, 1) == 1);
  return 0;
}
