// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 12x12 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 12
#define H 12
static const u8 map[W * H] = {
  7, 7, 0, 0, 3, 0, 1, 1, 3, 7, 7, 0,
  0, 0, 2, 255, 0, 1, 0, 2, 7, 1, 255, 2,
  1, 0, 1, 7, 0, 0, 3, 255, 0, 1, 0, 0,
  0, 0, 0, 2, 0, 7, 255, 2, 0, 2, 2, 3,
  3, 255, 3, 0, 0, 255, 1, 2, 255, 2, 2, 0,
  1, 7, 0, 0, 7, 255, 3, 1, 7, 255, 3, 7,
  0, 1, 1, 0, 0, 255, 2, 1, 2, 255, 7, 3,
  7, 7, 0, 0, 0, 0, 255, 0, 2, 0, 2, 0,
  0, 0, 3, 255, 0, 1, 0, 1, 255, 3, 0, 7,
  7, 2, 7, 255, 0, 255, 0, 0, 0, 0, 3, 3,
  2, 0, 0, 0, 1, 0, 0, 2, 0, 7, 3, 0,
  1, 1, 7, 0, 255, 0, 0, 3, 3, 2, 7, 255
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(50, 64) == 0); CHECK(solid(50, 64) == 0);
  CHECK(tile_at(38, 37) == 0); CHECK(solid(38, 37) == 0);
  CHECK(tile_at(5, 35) == 3); CHECK(solid(5, 35) == 1);
  CHECK(tile_at(14, 47) == 7); CHECK(solid(14, 47) == 1);
  CHECK(tile_at(-7, -7) == 1); CHECK(solid(-7, -7) == 1);
  CHECK(tile_at(82, 56) == 2); CHECK(solid(82, 56) == 1);
  CHECK(tile_at(32, 43) == 7); CHECK(solid(32, 43) == 1);
  CHECK(tile_at(12, 18) == 0); CHECK(solid(12, 18) == 0);
  CHECK(tile_at(44, -2) == 1); CHECK(solid(44, -2) == 1);
  CHECK(tile_at(94, 80) == 0); CHECK(solid(94, 80) == 0);
  CHECK(tile_at(6, 38) == 3); CHECK(solid(6, 38) == 1);
  CHECK(tile_at(68, 28) == 0); CHECK(solid(68, 28) == 0);
  CHECK(tile_at(43, 68) == 1); CHECK(solid(43, 68) == 1);
  CHECK(tile_at(44, -1) == 1); CHECK(solid(44, -1) == 1);
  CHECK(tile_at(77, -4) == 1); CHECK(solid(77, -4) == 1);
  CHECK(tile_at(-8, 71) == 1); CHECK(solid(-8, 71) == 1);
  CHECK(tile_at(50, 77) == 0); CHECK(solid(50, 77) == 0);
  CHECK(tile_at(11, -4) == 1); CHECK(solid(11, -4) == 1);
  CHECK(tile_at(60, 98) == 1); CHECK(solid(60, 98) == 1);
  CHECK(tile_at(39, 14) == 0); CHECK(solid(39, 14) == 0);
  CHECK(tile_at(93, -7) == 1); CHECK(solid(93, -7) == 1);
  CHECK(tile_at(72, 69) == 3); CHECK(solid(72, 69) == 1);
  CHECK(tile_at(100, 101) == 1); CHECK(solid(100, 101) == 1);
  CHECK(tile_at(39, -7) == 1); CHECK(solid(39, -7) == 1);
  return 0;
}
