// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 20x10 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 20
#define H 10
static const u8 map[W * H] = {
  0, 1, 0, 255, 0, 0, 255, 0, 0, 0, 0, 2, 255, 7, 2, 7, 1, 1, 0, 3,
  255, 3, 3, 0, 0, 255, 0, 0, 7, 0, 255, 3, 0, 3, 0, 255, 0, 7, 7, 255,
  1, 0, 3, 255, 0, 0, 3, 1, 0, 3, 3, 7, 0, 0, 0, 0, 0, 3, 2, 0,
  0, 255, 0, 0, 2, 2, 7, 1, 0, 0, 0, 0, 0, 0, 255, 0, 255, 255, 0, 3,
  3, 3, 3, 2, 3, 2, 7, 0, 0, 1, 7, 0, 7, 2, 1, 0, 3, 7, 0, 255,
  255, 3, 1, 0, 0, 255, 1, 7, 1, 255, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0,
  1, 255, 3, 1, 0, 255, 0, 255, 255, 255, 0, 7, 0, 0, 2, 0, 0, 0, 2, 0,
  0, 255, 0, 255, 7, 0, 2, 7, 7, 1, 7, 0, 0, 1, 0, 0, 1, 1, 1, 7,
  0, 0, 0, 0, 0, 2, 255, 0, 0, 0, 0, 3, 0, 7, 7, 3, 7, 1, 2, 255,
  1, 1, 2, 3, 1, 0, 0, 7, 0, 255, 7, 0, 255, 7, 0, 3, 255, 7, 7, 2
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(160, 5) == 1); CHECK(solid(160, 5) == 1);
  CHECK(tile_at(100, 80) == 1); CHECK(solid(100, 80) == 1);
  CHECK(tile_at(-1, 83) == 1); CHECK(solid(-1, 83) == 1);
  CHECK(tile_at(160, 46) == 1); CHECK(solid(160, 46) == 1);
  CHECK(tile_at(125, 27) == 0); CHECK(solid(125, 27) == 0);
  CHECK(tile_at(85, 74) == 7); CHECK(solid(85, 74) == 1);
  CHECK(tile_at(95, 65) == 3); CHECK(solid(95, 65) == 1);
  CHECK(tile_at(133, -3) == 1); CHECK(solid(133, -3) == 1);
  CHECK(tile_at(38, 30) == 2); CHECK(solid(38, 30) == 1);
  CHECK(tile_at(47, 18) == 0); CHECK(solid(47, 18) == 0);
  CHECK(tile_at(160, 48) == 1); CHECK(solid(160, 48) == 1);
  CHECK(tile_at(166, 4) == 1); CHECK(solid(166, 4) == 1);
  CHECK(tile_at(54, -2) == 1); CHECK(solid(54, -2) == 1);
  CHECK(tile_at(27, 65) == 0); CHECK(solid(27, 65) == 0);
  CHECK(tile_at(102, 10) == 0); CHECK(solid(102, 10) == 0);
  CHECK(tile_at(126, 87) == 1); CHECK(solid(126, 87) == 1);
  CHECK(tile_at(6, 52) == 1); CHECK(solid(6, 52) == 1);
  CHECK(tile_at(17, 85) == 1); CHECK(solid(17, 85) == 1);
  CHECK(tile_at(143, 85) == 1); CHECK(solid(143, 85) == 1);
  CHECK(tile_at(20, 15) == 3); CHECK(solid(20, 15) == 1);
  CHECK(tile_at(127, 18) == 0); CHECK(solid(127, 18) == 0);
  CHECK(tile_at(34, 77) == 1); CHECK(solid(34, 77) == 1);
  CHECK(tile_at(66, -3) == 1); CHECK(solid(66, -3) == 1);
  CHECK(tile_at(-5, 55) == 1); CHECK(solid(-5, 55) == 1);
  return 0;
}
