// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 13 u8 indices by a u8 key table.
#include "loomcc-test.h"
static const u8 key[13] = { 54, 0, 196, 0, 132, 203, 168, 182, 185, 244, 0, 0, 246 };
static const u8 want[13] = { 1, 3, 10, 11, 0, 4, 6, 7, 8, 2, 5, 9, 12 };
static u8 idx[13];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 13; i++) idx[i] = i;
  for (i = 1; i < 13; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 13; i++) CHECK(idx[i] == want[i]);
  return 0;
}
