// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 5 u8 indices by a u16 key table.
#include "loomcc-test.h"
static const u16 key[5] = { 3258, 58302, 53952, 0, 38787 };
static const u8 want[5] = { 3, 0, 4, 2, 1 };
static u8 idx[5];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 5; i++) idx[i] = i;
  for (i = 1; i < 5; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 5; i++) CHECK(idx[i] == want[i]);
  return 0;
}
