// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 13 u8 indices by a i8 key table.
#include "loomcc-test.h"
static const i8 key[13] = { 109, 17, -44, 20, 81, 0, 0, -117, 0, -6, 65, 0, 86 };
static const u8 want[13] = { 7, 2, 9, 5, 6, 8, 11, 1, 3, 10, 4, 12, 0 };
static u8 idx[13];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 13; i++) idx[i] = i;
  for (i = 1; i < 13; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 13; i++) CHECK(idx[i] == want[i]);
  return 0;
}
