// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 3 outer records, each with 2 inner records, in ROM and copied to WRAM.
#include "loomcc-test.h"
typedef struct { i16 v; u8 f; } In;
typedef struct { u8 tag; In in[2]; } Out;
static const Out rom[3] = {
  { 174, { { -14955, 102 }, { 32642, 16 } } },
  { 27, { { -20923, 211 }, { 27567, 44 } } },
  { 27, { { 28943, 149 }, { 8777, 55 } } }
};
static Out ram[3];
static volatile u8 vi, vj;
int main(void) {
  u8 i, j;
  u16 total = 0;
  for (i = 0; i < 3; i++) ram[i] = rom[i];
  for (i = 0; i < 3; i++) for (j = 0; j < 2; j++) total = (u16)(total + (u16)ram[i].in[j].v);
  CHECK(total == 62051u);
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(32642) && rom[vi].in[vj].f == 16 && ram[vi].tag == (u8)(174));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(32642) && rom[vi].in[vj].f == 16 && ram[vi].tag == (u8)(174));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27567) && rom[vi].in[vj].f == 44 && ram[vi].tag == (u8)(27));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27567) && rom[vi].in[vj].f == 44 && ram[vi].tag == (u8)(27));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  vi = 2; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(28943) && rom[vi].in[vj].f == 149 && ram[vi].tag == (u8)(27));
  vi = 2; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(8777) && rom[vi].in[vj].f == 55 && ram[vi].tag == (u8)(27));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27567) && rom[vi].in[vj].f == 44 && ram[vi].tag == (u8)(27));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27567) && rom[vi].in[vj].f == 44 && ram[vi].tag == (u8)(27));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27567) && rom[vi].in[vj].f == 44 && ram[vi].tag == (u8)(27));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-20923) && rom[vi].in[vj].f == 211 && ram[vi].tag == (u8)(27));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-14955) && rom[vi].in[vj].f == 102 && ram[vi].tag == (u8)(174));
  return 0;
}
