[package]
name = "loomcc"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "loomcc"
path = "src/main.rs"

[dependencies]
loomcc-pp = { path = "../pp" }
loomcc-parse = { path = "../parse" }
loomcc-sema = { path = "../sema" }
loomcc-ir = { path = "../ir" }
loomcc-w65816 = { path = "../w65816" }
serde_json = "1"
