// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 9 live u8 locals updated together 2 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  u8 v0 = (u8)(143);
  u8 v1 = (u8)(24);
  u8 v2 = (u8)(90);
  u8 v3 = (u8)(123);
  u8 v4 = (u8)(75);
  u8 v5 = (u8)(136);
  u8 v6 = (u8)(59);
  u8 v7 = (u8)(123);
  u8 v8 = (u8)(10);
  u8 n0, n1, n2, n3, n4, n5, n6, n7, n8;
  u8 s;
  u16 total;
  for (s = 0; s < 2; s++) {
    n0 = (u8)(v0 + 1 * (v1 & 7));
    n1 = (u8)(v1 + 1 * (v2 & 7));
    n2 = (u8)(v2 + 2 * (v3 & 7));
    n3 = (u8)(v3 + 3 * (v4 & 7));
    n4 = (u8)(v4 + 1 * (v5 & 7));
    n5 = (u8)(v5 + 1 * (v6 & 7));
    n6 = (u8)(v6 + 1 * (v7 & 7));
    n7 = (u8)(v7 + 1 * (v8 & 7));
    n8 = (u8)(v8 + 1 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7; v8 = n8;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7 + (u16)v8);
  CHECK(total == 856u);
  CHECK(v0 == (u8)(145) && v8 == (u8)(24));
  return 0;
}
