// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned (*v0)(void);
typedef unsigned (*T0)(void);
extern int (*v1[11][7])[3];
typedef int (*T1[11][7])[3];
extern unsigned char *(*(*v2)(void))[5];
typedef unsigned char *(*(*T2)(void))[5];
extern int v3;
typedef int T3;
extern unsigned (*v4[2])(void);
typedef unsigned (*T4[2])(void);
extern int v5[3];
typedef int T5[3];
extern long v6;
typedef long T6;
extern int (*v7)(void);
typedef int (*T7)(void);
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (*)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 11 * (7 * (sizeof(void *))));
STATIC_CHECK(sizeof(v1[1]) == 7 * (sizeof(void *)));
STATIC_CHECK(sizeof(v1[1][1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v1[1][1])) == 3 * (sizeof(int)));
STATIC_CHECK(sizeof((*v1[1][1])[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*[11][7])[3]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2)())) == 5 * (sizeof(void *)));
STATIC_CHECK(sizeof((*(*v2)())[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v2)())[1])) == 1);
STATIC_CHECK(sizeof(unsigned char *(*(*)(void))[5]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == 2 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v4[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4[1])()) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (*[2])(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 3 * (sizeof(int)));
STATIC_CHECK(sizeof(v5[1]) == sizeof(int));
STATIC_CHECK(sizeof(int [3]) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v7)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
