// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short (*v0)(void);
typedef unsigned short (*T0)(void);
extern long (*(**v1)(void))[2];
typedef long (*(**T1)(void))[2];
extern unsigned short v2[11];
typedef unsigned short T2[11];
extern signed char **v3;
typedef signed char **T3;
extern signed char **v4;
typedef signed char **T4;
extern long (*v5)(void);
typedef long (*T5)(void);
extern int *v6[7];
typedef int *T6[7];
extern char v7;
typedef char T7;
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short (*)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v1))()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v1))())) == 2 * (sizeof(long)));
STATIC_CHECK(sizeof((*(*(*v1))())[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (*(**)(void))[2]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 11 * (sizeof(short)));
STATIC_CHECK(sizeof(v2[1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short [11]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v3))) == 1);
STATIC_CHECK(sizeof(signed char **) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v4))) == 1);
STATIC_CHECK(sizeof(signed char **) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5)()) == sizeof(long));
STATIC_CHECK(sizeof(long (*)(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 7 * (sizeof(void *)));
STATIC_CHECK(sizeof(v6[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v6[1])) == sizeof(int));
STATIC_CHECK(sizeof(int *[7]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
