// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short *v0[2];
typedef unsigned short *T0[2];
extern long v1[2];
typedef long T1[2];
extern char v2;
typedef char T2;
extern unsigned char (*v3)(void);
typedef unsigned char (*T3)(void);
extern unsigned char v4;
typedef unsigned char T4;
extern int (*v5)(void);
typedef int (*T5)(void);
extern unsigned (*v6)[11];
typedef unsigned (*T6)[11];
extern char v7;
typedef char T7;
STATIC_CHECK(sizeof(v0) == 2 * (sizeof(void *)));
STATIC_CHECK(sizeof(v0[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v0[1])) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *[2]) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 2 * (sizeof(long)));
STATIC_CHECK(sizeof(v1[1]) == sizeof(long));
STATIC_CHECK(sizeof(long [2]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v3)()) == 1);
STATIC_CHECK(sizeof(unsigned char (*)(void)) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 11 * (sizeof(unsigned)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (*)[11]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
