// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern signed char (*(*v0)(void))(void);
typedef signed char (*(*T0)(void))(void);
extern unsigned char (*(*v1)(void))(void);
typedef unsigned char (*(*T1)(void))(void);
extern short *v2;
typedef short *T2;
extern unsigned short (*v3)[11];
typedef unsigned short (*T3)[11];
extern int v4;
typedef int T4;
extern short v5;
typedef short T5;
extern long v6;
typedef long T6;
extern int v7[2];
typedef int T7[2];
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v0)())()) == 1);
STATIC_CHECK(sizeof(signed char (*(*)(void))(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v1)()) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v1)())()) == 1);
STATIC_CHECK(sizeof(unsigned char (*(*)(void))(void)) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void *));
STATIC_CHECK(sizeof((*v2)) == sizeof(short));
STATIC_CHECK(sizeof(short *) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == 11 * (sizeof(short)));
STATIC_CHECK(sizeof((*v3)[1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short (*)[11]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(short));
STATIC_CHECK(sizeof(short) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 2 * (sizeof(int)));
STATIC_CHECK(sizeof(v7[1]) == sizeof(int));
STATIC_CHECK(sizeof(int [2]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
