// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern int (*(*v0)(void))[5];
typedef int (*(*T0)(void))[5];
extern unsigned char v1;
typedef unsigned char T1;
extern short **v2;
typedef short **T2;
extern signed char v3;
typedef signed char T3;
extern long (**(*v4)(void))(void);
typedef long (**(*T4)(void))(void);
extern unsigned short v5;
typedef unsigned short T5;
extern signed char *(*v6)[7];
typedef signed char *(*T6)[7];
extern unsigned char (*v7)[3];
typedef unsigned char (*T7)[3];
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0)())) == 5 * (sizeof(int)));
STATIC_CHECK(sizeof((*(*v0)())[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*(*)(void))[5]) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void *));
STATIC_CHECK(sizeof((*v2)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2))) == sizeof(short));
STATIC_CHECK(sizeof(short **) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 1);
STATIC_CHECK(sizeof(signed char) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v4)())) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*(*v4)()))()) == sizeof(long));
STATIC_CHECK(sizeof(long (**(*)(void))(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 7 * (sizeof(void *)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6)[1])) == 1);
STATIC_CHECK(sizeof(signed char *(*)[7]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == 3 * (1));
STATIC_CHECK(sizeof((*v7)[1]) == 1);
STATIC_CHECK(sizeof(unsigned char (*)[3]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
