// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned *v0[5][2];
typedef unsigned *T0[5][2];
extern long (**(*v1)[2])[5];
typedef long (**(*T1)[2])[5];
extern long v2;
typedef long T2;
extern long v3;
typedef long T3;
extern unsigned (**v4)(void);
typedef unsigned (**T4)(void);
extern unsigned v5;
typedef unsigned T5;
extern int (*v6)[3];
typedef int (*T6)[3];
extern signed char v7[3][5];
typedef signed char T7[3][5];
STATIC_CHECK(sizeof(v0) == 5 * (2 * (sizeof(void *))));
STATIC_CHECK(sizeof(v0[1]) == 2 * (sizeof(void *)));
STATIC_CHECK(sizeof(v0[1][1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v0[1][1])) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned *[5][2]) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == 2 * (sizeof(void *)));
STATIC_CHECK(sizeof((*v1)[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v1)[1])) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v1)[1]))) == 5 * (sizeof(long)));
STATIC_CHECK(sizeof((*(*(*v1)[1]))[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (**(*)[2])[5]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v4))()) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (**)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 3 * (sizeof(int)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*)[3]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 3 * (5 * (1)));
STATIC_CHECK(sizeof(v7[1]) == 5 * (1));
STATIC_CHECK(sizeof(v7[1][1]) == 1);
STATIC_CHECK(sizeof(signed char [3][5]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
