// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short ***v0;
typedef unsigned short ***T0;
extern char (*(*v1)(void))(void);
typedef char (*(*T1)(void))(void);
extern unsigned **(*v2)(void);
typedef unsigned **(*T2)(void);
extern unsigned char v3;
typedef unsigned char T3;
extern char (*v4)(void);
typedef char (*T4)(void);
extern signed char v5[2];
typedef signed char T5[2];
extern int v6[2][11];
typedef int T6[2][11];
extern char (*v7)(void);
typedef char (*T7)(void);
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v0)))) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short ***) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v1)()) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v1)())()) == 1);
STATIC_CHECK(sizeof(char (*(*)(void))(void)) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2)())) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v2)()))) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned **(*)(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 2 * (1));
STATIC_CHECK(sizeof(v5[1]) == 1);
STATIC_CHECK(sizeof(signed char [2]) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 2 * (11 * (sizeof(int))));
STATIC_CHECK(sizeof(v6[1]) == 11 * (sizeof(int)));
STATIC_CHECK(sizeof(v6[1][1]) == sizeof(int));
STATIC_CHECK(sizeof(int [2][11]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v7)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
