// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short v0;
typedef unsigned short T0;
extern unsigned char v1;
typedef unsigned char T1;
extern unsigned short **(*v2)(void);
typedef unsigned short **(*T2)(void);
extern int *v3;
typedef int *T3;
extern short (*v4)[11];
typedef short (*T4)[11];
extern char (*v5)(void);
typedef char (*T5)(void);
extern int (*v6)(void);
typedef int (*T6)(void);
extern int (*v7)[11];
typedef int (*T7)[11];
STATIC_CHECK(sizeof(v0) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2)())) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v2)()))) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short **(*)(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == sizeof(int));
STATIC_CHECK(sizeof(int *) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == 11 * (sizeof(short)));
STATIC_CHECK(sizeof((*v4)[1]) == sizeof(short));
STATIC_CHECK(sizeof(short (*)[11]) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == 11 * (sizeof(int)));
STATIC_CHECK(sizeof((*v7)[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*)[11]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
