// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern signed char (*(*v0)(void))[3];
typedef signed char (*(*T0)(void))[3];
extern long (**v1)[7];
typedef long (**T1)[7];
extern long v2;
typedef long T2;
extern long (*v3)(void);
typedef long (*T3)(void);
extern int v4;
typedef int T4;
extern int ***v5;
typedef int ***T5;
extern short *(*v6)(void);
typedef short *(*T6)(void);
extern long v7;
typedef long T7;
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0)())) == 3 * (1));
STATIC_CHECK(sizeof((*(*v0)())[1]) == 1);
STATIC_CHECK(sizeof(signed char (*(*)(void))[3]) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v1))) == 7 * (sizeof(long)));
STATIC_CHECK(sizeof((*(*v1))[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (**)[7]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v3)()) == sizeof(long));
STATIC_CHECK(sizeof(long (*)(void)) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void *));
STATIC_CHECK(sizeof((*v5)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v5))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v5)))) == sizeof(int));
STATIC_CHECK(sizeof(int ***) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6)())) == sizeof(short));
STATIC_CHECK(sizeof(short *(*)(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
