// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S29_0 {
  const i16 * m0;
  i16 m1;
  u8 * m2;
};
struct S29_1 {
  i16 m0[5];
  i32 m1;
  i8 m2;
  i8 m3;
};
struct S29_2 {
  u8 * m0[5];
};
struct S29_3 {
  void (*m0)(void);
  const i16 * m1;
  int m2;
  struct S29_0 m3;
};
struct S29_4 {
  const i16 * m0;
  i16 m1;
  struct S29_3 m2;
};
struct S29_5 {
  const i16 * m0[2];
};
STATIC_CHECK(sizeof(struct S29_0) == 12);
STATIC_CHECK(sizeof(struct S29_0[3]) == 36);
STATIC_CHECK(offsetof(struct S29_0, m0) == 0);
STATIC_CHECK(offsetof(struct S29_0, m1) == 4);
STATIC_CHECK(offsetof(struct S29_0, m2) == 8);
STATIC_CHECK(sizeof(struct S29_1) == 20);
STATIC_CHECK(sizeof(struct S29_1[3]) == 60);
STATIC_CHECK(offsetof(struct S29_1, m0) == 0);
STATIC_CHECK(offsetof(struct S29_1, m1) == 12);
STATIC_CHECK(offsetof(struct S29_1, m2) == 16);
STATIC_CHECK(offsetof(struct S29_1, m3) == 17);
STATIC_CHECK(sizeof(struct S29_2) == 20);
STATIC_CHECK(sizeof(struct S29_2[3]) == 60);
STATIC_CHECK(offsetof(struct S29_2, m0) == 0);
STATIC_CHECK(sizeof(struct S29_3) == 24);
STATIC_CHECK(sizeof(struct S29_3[3]) == 72);
STATIC_CHECK(offsetof(struct S29_3, m0) == 0);
STATIC_CHECK(offsetof(struct S29_3, m1) == 4);
STATIC_CHECK(offsetof(struct S29_3, m2) == 8);
STATIC_CHECK(offsetof(struct S29_3, m3) == 12);
STATIC_CHECK(sizeof(struct S29_4) == 32);
STATIC_CHECK(sizeof(struct S29_4[3]) == 96);
STATIC_CHECK(offsetof(struct S29_4, m0) == 0);
STATIC_CHECK(offsetof(struct S29_4, m1) == 4);
STATIC_CHECK(offsetof(struct S29_4, m2) == 8);
STATIC_CHECK(sizeof(struct S29_5) == 8);
STATIC_CHECK(sizeof(struct S29_5[3]) == 24);
STATIC_CHECK(offsetof(struct S29_5, m0) == 0);
