// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S53_0 {
  u8 * m0;
};
struct S53_1 {
  struct S53_0 m0;
  i16 m1[5];
};
struct S53_2 {
  i8 m0[5];
  int m1[1];
  i32 m2[2];
  i16 m3;
};
struct S53_3 {
  u8 * m0;
  i16 m1;
  int m2;
  void (*m3)(void);
  i8 m4;
  i16 m5[1];
};
struct S53_4 {
  const i16 * m0[2];
  i16 m1;
  void (*m2)(void);
  u8 * m3;
};
struct S53_5 {
  int m0;
  int m1;
};
STATIC_CHECK(sizeof(struct S53_0) == 4);
STATIC_CHECK(sizeof(struct S53_0[3]) == 12);
STATIC_CHECK(offsetof(struct S53_0, m0) == 0);
STATIC_CHECK(sizeof(struct S53_1) == 16);
STATIC_CHECK(sizeof(struct S53_1[3]) == 48);
STATIC_CHECK(offsetof(struct S53_1, m0) == 0);
STATIC_CHECK(offsetof(struct S53_1, m1) == 4);
STATIC_CHECK(sizeof(struct S53_2) == 20);
STATIC_CHECK(sizeof(struct S53_2[3]) == 60);
STATIC_CHECK(offsetof(struct S53_2, m0) == 0);
STATIC_CHECK(offsetof(struct S53_2, m1) == 6);
STATIC_CHECK(offsetof(struct S53_2, m2) == 8);
STATIC_CHECK(offsetof(struct S53_2, m3) == 16);
STATIC_CHECK(sizeof(struct S53_3) == 16);
STATIC_CHECK(sizeof(struct S53_3[3]) == 48);
STATIC_CHECK(offsetof(struct S53_3, m0) == 0);
STATIC_CHECK(offsetof(struct S53_3, m1) == 4);
STATIC_CHECK(offsetof(struct S53_3, m2) == 6);
STATIC_CHECK(offsetof(struct S53_3, m3) == 8);
STATIC_CHECK(offsetof(struct S53_3, m4) == 12);
STATIC_CHECK(offsetof(struct S53_3, m5) == 14);
STATIC_CHECK(sizeof(struct S53_4) == 20);
STATIC_CHECK(sizeof(struct S53_4[3]) == 60);
STATIC_CHECK(offsetof(struct S53_4, m0) == 0);
STATIC_CHECK(offsetof(struct S53_4, m1) == 8);
STATIC_CHECK(offsetof(struct S53_4, m2) == 12);
STATIC_CHECK(offsetof(struct S53_4, m3) == 16);
STATIC_CHECK(sizeof(struct S53_5) == 4);
STATIC_CHECK(sizeof(struct S53_5[3]) == 12);
STATIC_CHECK(offsetof(struct S53_5, m0) == 0);
STATIC_CHECK(offsetof(struct S53_5, m1) == 2);
