// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S54_0 {
  u8 * m0;
  i8 m1;
  const i16 * m2;
};
struct S54_1 {
  i8 m0[5];
};
struct S54_2 {
  int m0;
  i16 m1[5];
  u16 m2[5];
  const i16 * m3[5];
  u8 m4;
  u8 m5[5];
};
struct S54_3 {
  u16 m0;
  i16 m1[2];
  struct S54_0 m2;
};
struct S54_4 {
  struct S54_0 m0;
  u8 * m1;
};
struct S54_5 {
  struct S54_2 m0;
  i32 m1[3];
  int m2;
  void (*m3)(void);
  i8 m4;
  i32 m5;
};
STATIC_CHECK(sizeof(struct S54_0) == 12);
STATIC_CHECK(sizeof(struct S54_0[3]) == 36);
STATIC_CHECK(offsetof(struct S54_0, m0) == 0);
STATIC_CHECK(offsetof(struct S54_0, m1) == 4);
STATIC_CHECK(offsetof(struct S54_0, m2) == 8);
STATIC_CHECK(sizeof(struct S54_1) == 5);
STATIC_CHECK(sizeof(struct S54_1[3]) == 15);
STATIC_CHECK(offsetof(struct S54_1, m0) == 0);
STATIC_CHECK(sizeof(struct S54_2) == 52);
STATIC_CHECK(sizeof(struct S54_2[3]) == 156);
STATIC_CHECK(offsetof(struct S54_2, m0) == 0);
STATIC_CHECK(offsetof(struct S54_2, m1) == 2);
STATIC_CHECK(offsetof(struct S54_2, m2) == 12);
STATIC_CHECK(offsetof(struct S54_2, m3) == 24);
STATIC_CHECK(offsetof(struct S54_2, m4) == 44);
STATIC_CHECK(offsetof(struct S54_2, m5) == 45);
STATIC_CHECK(sizeof(struct S54_3) == 20);
STATIC_CHECK(sizeof(struct S54_3[3]) == 60);
STATIC_CHECK(offsetof(struct S54_3, m0) == 0);
STATIC_CHECK(offsetof(struct S54_3, m1) == 2);
STATIC_CHECK(offsetof(struct S54_3, m2) == 8);
STATIC_CHECK(sizeof(struct S54_4) == 16);
STATIC_CHECK(sizeof(struct S54_4[3]) == 48);
STATIC_CHECK(offsetof(struct S54_4, m0) == 0);
STATIC_CHECK(offsetof(struct S54_4, m1) == 12);
STATIC_CHECK(sizeof(struct S54_5) == 80);
STATIC_CHECK(sizeof(struct S54_5[3]) == 240);
STATIC_CHECK(offsetof(struct S54_5, m0) == 0);
STATIC_CHECK(offsetof(struct S54_5, m1) == 52);
STATIC_CHECK(offsetof(struct S54_5, m2) == 64);
STATIC_CHECK(offsetof(struct S54_5, m3) == 68);
STATIC_CHECK(offsetof(struct S54_5, m4) == 72);
STATIC_CHECK(offsetof(struct S54_5, m5) == 76);
