// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S42_0 {
  i8 m0;
};
struct S42_1 {
  void (*m0[3])(void);
  i8 m1;
  void (*m2)(void);
  i32 m3;
};
struct S42_2 {
  void (*m0[2])(void);
  void (*m1)(void);
};
struct S42_3 {
  i32 m0;
  struct S42_1 m1[2];
  struct S42_2 m2[2];
  struct S42_2 m3;
  i16 m4;
  struct S42_0 m5;
};
struct S42_4 {
  u8 m0;
  u16 m1[2];
  i16 m2;
  struct S42_0 m3;
  i16 m4;
  struct S42_1 m5;
};
struct S42_5 {
  struct S42_3 m0[3];
  u8 * m1;
  i32 m2[3];
  u8 m3;
  void (*m4)(void);
  void (*m5)(void);
};
STATIC_CHECK(sizeof(struct S42_0) == 1);
STATIC_CHECK(sizeof(struct S42_0[3]) == 3);
STATIC_CHECK(offsetof(struct S42_0, m0) == 0);
STATIC_CHECK(sizeof(struct S42_1) == 24);
STATIC_CHECK(sizeof(struct S42_1[3]) == 72);
STATIC_CHECK(offsetof(struct S42_1, m0) == 0);
STATIC_CHECK(offsetof(struct S42_1, m1) == 12);
STATIC_CHECK(offsetof(struct S42_1, m2) == 16);
STATIC_CHECK(offsetof(struct S42_1, m3) == 20);
STATIC_CHECK(sizeof(struct S42_2) == 12);
STATIC_CHECK(sizeof(struct S42_2[3]) == 36);
STATIC_CHECK(offsetof(struct S42_2, m0) == 0);
STATIC_CHECK(offsetof(struct S42_2, m1) == 8);
STATIC_CHECK(sizeof(struct S42_3) == 92);
STATIC_CHECK(sizeof(struct S42_3[3]) == 276);
STATIC_CHECK(offsetof(struct S42_3, m0) == 0);
STATIC_CHECK(offsetof(struct S42_3, m1) == 4);
STATIC_CHECK(offsetof(struct S42_3, m2) == 52);
STATIC_CHECK(offsetof(struct S42_3, m3) == 76);
STATIC_CHECK(offsetof(struct S42_3, m4) == 88);
STATIC_CHECK(offsetof(struct S42_3, m5) == 90);
STATIC_CHECK(sizeof(struct S42_4) == 36);
STATIC_CHECK(sizeof(struct S42_4[3]) == 108);
STATIC_CHECK(offsetof(struct S42_4, m0) == 0);
STATIC_CHECK(offsetof(struct S42_4, m1) == 2);
STATIC_CHECK(offsetof(struct S42_4, m2) == 6);
STATIC_CHECK(offsetof(struct S42_4, m3) == 8);
STATIC_CHECK(offsetof(struct S42_4, m4) == 10);
STATIC_CHECK(offsetof(struct S42_4, m5) == 12);
STATIC_CHECK(sizeof(struct S42_5) == 304);
STATIC_CHECK(sizeof(struct S42_5[3]) == 912);
STATIC_CHECK(offsetof(struct S42_5, m0) == 0);
STATIC_CHECK(offsetof(struct S42_5, m1) == 276);
STATIC_CHECK(offsetof(struct S42_5, m2) == 280);
STATIC_CHECK(offsetof(struct S42_5, m3) == 292);
STATIC_CHECK(offsetof(struct S42_5, m4) == 296);
STATIC_CHECK(offsetof(struct S42_5, m5) == 300);
