// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S30_0 {
  u8 * m0;
  void (*m1)(void);
  int m2;
  i16 m3;
};
struct S30_1 {
  i8 m0;
};
struct S30_2 {
  u8 * m0;
  int m1;
  const i16 * m2[1];
};
struct S30_3 {
  i32 m0;
  i32 m1;
  i16 m2;
  i8 m3[5];
  u8 m4[5];
};
struct S30_4 {
  struct S30_1 m0;
  u8 * m1;
  void (*m2)(void);
  const i16 * m3;
  i16 m4;
  i16 m5[2];
};
struct S30_5 {
  void (*m0)(void);
  void (*m1[1])(void);
  void (*m2[2])(void);
};
STATIC_CHECK(sizeof(struct S30_0) == 12);
STATIC_CHECK(sizeof(struct S30_0[3]) == 36);
STATIC_CHECK(offsetof(struct S30_0, m0) == 0);
STATIC_CHECK(offsetof(struct S30_0, m1) == 4);
STATIC_CHECK(offsetof(struct S30_0, m2) == 8);
STATIC_CHECK(offsetof(struct S30_0, m3) == 10);
STATIC_CHECK(sizeof(struct S30_1) == 1);
STATIC_CHECK(sizeof(struct S30_1[3]) == 3);
STATIC_CHECK(offsetof(struct S30_1, m0) == 0);
STATIC_CHECK(sizeof(struct S30_2) == 12);
STATIC_CHECK(sizeof(struct S30_2[3]) == 36);
STATIC_CHECK(offsetof(struct S30_2, m0) == 0);
STATIC_CHECK(offsetof(struct S30_2, m1) == 4);
STATIC_CHECK(offsetof(struct S30_2, m2) == 8);
STATIC_CHECK(sizeof(struct S30_3) == 20);
STATIC_CHECK(sizeof(struct S30_3[3]) == 60);
STATIC_CHECK(offsetof(struct S30_3, m0) == 0);
STATIC_CHECK(offsetof(struct S30_3, m1) == 4);
STATIC_CHECK(offsetof(struct S30_3, m2) == 8);
STATIC_CHECK(offsetof(struct S30_3, m3) == 10);
STATIC_CHECK(offsetof(struct S30_3, m4) == 15);
STATIC_CHECK(sizeof(struct S30_4) == 24);
STATIC_CHECK(sizeof(struct S30_4[3]) == 72);
STATIC_CHECK(offsetof(struct S30_4, m0) == 0);
STATIC_CHECK(offsetof(struct S30_4, m1) == 4);
STATIC_CHECK(offsetof(struct S30_4, m2) == 8);
STATIC_CHECK(offsetof(struct S30_4, m3) == 12);
STATIC_CHECK(offsetof(struct S30_4, m4) == 16);
STATIC_CHECK(offsetof(struct S30_4, m5) == 18);
STATIC_CHECK(sizeof(struct S30_5) == 16);
STATIC_CHECK(sizeof(struct S30_5[3]) == 48);
STATIC_CHECK(offsetof(struct S30_5, m0) == 0);
STATIC_CHECK(offsetof(struct S30_5, m1) == 4);
STATIC_CHECK(offsetof(struct S30_5, m2) == 8);
