// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S14_0 {
  i32 m0;
  void (*m1)(void);
  u8 * m2;
};
struct S14_1 {
  void (*m0)(void);
  u16 m1[2];
  const i16 * m2[3];
  struct S14_0 m3[3];
  u16 m4;
  void (*m5)(void);
};
struct S14_2 {
  void (*m0)(void);
  u8 m1;
  u8 m2;
  u8 * m3;
};
struct S14_3 {
  struct S14_2 m0[2];
  u8 m1;
  u16 m2;
  int m3[1];
  int m4;
  u8 m5;
};
struct S14_4 {
  u16 m0;
  struct S14_2 m1;
  void (*m2[5])(void);
};
struct S14_5 {
  u16 m0;
  int m1;
};
STATIC_CHECK(sizeof(struct S14_0) == 12);
STATIC_CHECK(sizeof(struct S14_0[3]) == 36);
STATIC_CHECK(offsetof(struct S14_0, m0) == 0);
STATIC_CHECK(offsetof(struct S14_0, m1) == 4);
STATIC_CHECK(offsetof(struct S14_0, m2) == 8);
STATIC_CHECK(sizeof(struct S14_1) == 64);
STATIC_CHECK(sizeof(struct S14_1[3]) == 192);
STATIC_CHECK(offsetof(struct S14_1, m0) == 0);
STATIC_CHECK(offsetof(struct S14_1, m1) == 4);
STATIC_CHECK(offsetof(struct S14_1, m2) == 8);
STATIC_CHECK(offsetof(struct S14_1, m3) == 20);
STATIC_CHECK(offsetof(struct S14_1, m4) == 56);
STATIC_CHECK(offsetof(struct S14_1, m5) == 60);
STATIC_CHECK(sizeof(struct S14_2) == 12);
STATIC_CHECK(sizeof(struct S14_2[3]) == 36);
STATIC_CHECK(offsetof(struct S14_2, m0) == 0);
STATIC_CHECK(offsetof(struct S14_2, m1) == 4);
STATIC_CHECK(offsetof(struct S14_2, m2) == 5);
STATIC_CHECK(offsetof(struct S14_2, m3) == 8);
STATIC_CHECK(sizeof(struct S14_3) == 36);
STATIC_CHECK(sizeof(struct S14_3[3]) == 108);
STATIC_CHECK(offsetof(struct S14_3, m0) == 0);
STATIC_CHECK(offsetof(struct S14_3, m1) == 24);
STATIC_CHECK(offsetof(struct S14_3, m2) == 26);
STATIC_CHECK(offsetof(struct S14_3, m3) == 28);
STATIC_CHECK(offsetof(struct S14_3, m4) == 30);
STATIC_CHECK(offsetof(struct S14_3, m5) == 32);
STATIC_CHECK(sizeof(struct S14_4) == 36);
STATIC_CHECK(sizeof(struct S14_4[3]) == 108);
STATIC_CHECK(offsetof(struct S14_4, m0) == 0);
STATIC_CHECK(offsetof(struct S14_4, m1) == 4);
STATIC_CHECK(offsetof(struct S14_4, m2) == 16);
STATIC_CHECK(sizeof(struct S14_5) == 4);
STATIC_CHECK(sizeof(struct S14_5[3]) == 12);
STATIC_CHECK(offsetof(struct S14_5, m0) == 0);
STATIC_CHECK(offsetof(struct S14_5, m1) == 2);
