// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S43_0 {
  int m0;
  u16 m1[1];
  int m2;
  i32 m3;
  i16 m4[1];
  void (*m5[2])(void);
};
struct S43_1 {
  struct S43_0 m0;
  i16 m1;
  struct S43_0 m2;
  struct S43_0 m3;
  const i16 * m4;
};
struct S43_2 {
  int m0;
};
struct S43_3 {
  struct S43_0 m0;
  void (*m1)(void);
  i16 m2;
  const i16 * m3[5];
};
struct S43_4 {
  void (*m0[1])(void);
  u8 m1;
  void (*m2[1])(void);
};
struct S43_5 {
  u8 * m0;
  i8 m1[3];
  u16 m2;
};
STATIC_CHECK(sizeof(struct S43_0) == 24);
STATIC_CHECK(sizeof(struct S43_0[3]) == 72);
STATIC_CHECK(offsetof(struct S43_0, m0) == 0);
STATIC_CHECK(offsetof(struct S43_0, m1) == 2);
STATIC_CHECK(offsetof(struct S43_0, m2) == 4);
STATIC_CHECK(offsetof(struct S43_0, m3) == 8);
STATIC_CHECK(offsetof(struct S43_0, m4) == 12);
STATIC_CHECK(offsetof(struct S43_0, m5) == 16);
STATIC_CHECK(sizeof(struct S43_1) == 80);
STATIC_CHECK(sizeof(struct S43_1[3]) == 240);
STATIC_CHECK(offsetof(struct S43_1, m0) == 0);
STATIC_CHECK(offsetof(struct S43_1, m1) == 24);
STATIC_CHECK(offsetof(struct S43_1, m2) == 28);
STATIC_CHECK(offsetof(struct S43_1, m3) == 52);
STATIC_CHECK(offsetof(struct S43_1, m4) == 76);
STATIC_CHECK(sizeof(struct S43_2) == 2);
STATIC_CHECK(sizeof(struct S43_2[3]) == 6);
STATIC_CHECK(offsetof(struct S43_2, m0) == 0);
STATIC_CHECK(sizeof(struct S43_3) == 52);
STATIC_CHECK(sizeof(struct S43_3[3]) == 156);
STATIC_CHECK(offsetof(struct S43_3, m0) == 0);
STATIC_CHECK(offsetof(struct S43_3, m1) == 24);
STATIC_CHECK(offsetof(struct S43_3, m2) == 28);
STATIC_CHECK(offsetof(struct S43_3, m3) == 32);
STATIC_CHECK(sizeof(struct S43_4) == 12);
STATIC_CHECK(sizeof(struct S43_4[3]) == 36);
STATIC_CHECK(offsetof(struct S43_4, m0) == 0);
STATIC_CHECK(offsetof(struct S43_4, m1) == 4);
STATIC_CHECK(offsetof(struct S43_4, m2) == 8);
STATIC_CHECK(sizeof(struct S43_5) == 12);
STATIC_CHECK(sizeof(struct S43_5[3]) == 36);
STATIC_CHECK(offsetof(struct S43_5, m0) == 0);
STATIC_CHECK(offsetof(struct S43_5, m1) == 4);
STATIC_CHECK(offsetof(struct S43_5, m2) == 8);
