// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S61_0 {
  i16 m0;
  u8 * m1;
  void (*m2)(void);
  u8 m3;
  void (*m4[5])(void);
};
struct S61_1 {
  u16 m0[5];
  struct S61_0 m1;
  u8 * m2;
  u8 m3;
  i8 m4;
  struct S61_0 m5[2];
};
struct S61_2 {
  u8 * m0;
  u16 m1[5];
  const i16 * m2[3];
  i16 m3[2];
};
struct S61_3 {
  u8 * m0[5];
  struct S61_1 m1;
  i8 m2[5];
};
struct S61_4 {
  i32 m0;
  i16 m1[2];
  u8 * m2[3];
  u8 * m3;
};
struct S61_5 {
  u16 m0[3];
  struct S61_1 m1[3];
  u8 m2;
};
STATIC_CHECK(sizeof(struct S61_0) == 36);
STATIC_CHECK(sizeof(struct S61_0[3]) == 108);
STATIC_CHECK(offsetof(struct S61_0, m0) == 0);
STATIC_CHECK(offsetof(struct S61_0, m1) == 4);
STATIC_CHECK(offsetof(struct S61_0, m2) == 8);
STATIC_CHECK(offsetof(struct S61_0, m3) == 12);
STATIC_CHECK(offsetof(struct S61_0, m4) == 16);
STATIC_CHECK(sizeof(struct S61_1) == 128);
STATIC_CHECK(sizeof(struct S61_1[3]) == 384);
STATIC_CHECK(offsetof(struct S61_1, m0) == 0);
STATIC_CHECK(offsetof(struct S61_1, m1) == 12);
STATIC_CHECK(offsetof(struct S61_1, m2) == 48);
STATIC_CHECK(offsetof(struct S61_1, m3) == 52);
STATIC_CHECK(offsetof(struct S61_1, m4) == 53);
STATIC_CHECK(offsetof(struct S61_1, m5) == 56);
STATIC_CHECK(sizeof(struct S61_2) == 32);
STATIC_CHECK(sizeof(struct S61_2[3]) == 96);
STATIC_CHECK(offsetof(struct S61_2, m0) == 0);
STATIC_CHECK(offsetof(struct S61_2, m1) == 4);
STATIC_CHECK(offsetof(struct S61_2, m2) == 16);
STATIC_CHECK(offsetof(struct S61_2, m3) == 28);
STATIC_CHECK(sizeof(struct S61_3) == 156);
STATIC_CHECK(sizeof(struct S61_3[3]) == 468);
STATIC_CHECK(offsetof(struct S61_3, m0) == 0);
STATIC_CHECK(offsetof(struct S61_3, m1) == 20);
STATIC_CHECK(offsetof(struct S61_3, m2) == 148);
STATIC_CHECK(sizeof(struct S61_4) == 24);
STATIC_CHECK(sizeof(struct S61_4[3]) == 72);
STATIC_CHECK(offsetof(struct S61_4, m0) == 0);
STATIC_CHECK(offsetof(struct S61_4, m1) == 4);
STATIC_CHECK(offsetof(struct S61_4, m2) == 8);
STATIC_CHECK(offsetof(struct S61_4, m3) == 20);
STATIC_CHECK(sizeof(struct S61_5) == 396);
STATIC_CHECK(sizeof(struct S61_5[3]) == 1188);
STATIC_CHECK(offsetof(struct S61_5, m0) == 0);
STATIC_CHECK(offsetof(struct S61_5, m1) == 8);
STATIC_CHECK(offsetof(struct S61_5, m2) == 392);
