// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S46_0 {
  i8 m0[5];
};
struct S46_1 {
  i8 m0;
};
struct S46_2 {
  const i16 * m0;
  struct S46_1 m1;
};
struct S46_3 {
  struct S46_2 m0[2];
};
struct S46_4 {
  u8 m0;
  const i16 * m1;
  const i16 * m2;
  i16 m3;
  u16 m4;
};
struct S46_5 {
  u8 m0;
  u8 * m1;
  struct S46_0 m2[2];
  const i16 * m3;
  void (*m4)(void);
  i8 m5[5];
};
STATIC_CHECK(sizeof(struct S46_0) == 5);
STATIC_CHECK(sizeof(struct S46_0[3]) == 15);
STATIC_CHECK(offsetof(struct S46_0, m0) == 0);
STATIC_CHECK(sizeof(struct S46_1) == 1);
STATIC_CHECK(sizeof(struct S46_1[3]) == 3);
STATIC_CHECK(offsetof(struct S46_1, m0) == 0);
STATIC_CHECK(sizeof(struct S46_2) == 8);
STATIC_CHECK(sizeof(struct S46_2[3]) == 24);
STATIC_CHECK(offsetof(struct S46_2, m0) == 0);
STATIC_CHECK(offsetof(struct S46_2, m1) == 4);
STATIC_CHECK(sizeof(struct S46_3) == 16);
STATIC_CHECK(sizeof(struct S46_3[3]) == 48);
STATIC_CHECK(offsetof(struct S46_3, m0) == 0);
STATIC_CHECK(sizeof(struct S46_4) == 16);
STATIC_CHECK(sizeof(struct S46_4[3]) == 48);
STATIC_CHECK(offsetof(struct S46_4, m0) == 0);
STATIC_CHECK(offsetof(struct S46_4, m1) == 4);
STATIC_CHECK(offsetof(struct S46_4, m2) == 8);
STATIC_CHECK(offsetof(struct S46_4, m3) == 12);
STATIC_CHECK(offsetof(struct S46_4, m4) == 14);
STATIC_CHECK(sizeof(struct S46_5) == 36);
STATIC_CHECK(sizeof(struct S46_5[3]) == 108);
STATIC_CHECK(offsetof(struct S46_5, m0) == 0);
STATIC_CHECK(offsetof(struct S46_5, m1) == 4);
STATIC_CHECK(offsetof(struct S46_5, m2) == 8);
STATIC_CHECK(offsetof(struct S46_5, m3) == 20);
STATIC_CHECK(offsetof(struct S46_5, m4) == 24);
STATIC_CHECK(offsetof(struct S46_5, m5) == 28);
