// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S18_0 {
  u16 m0;
  u8 * m1;
};
struct S18_1 {
  u8 * m0;
};
struct S18_2 {
  i8 m0;
};
struct S18_3 {
  u8 * m0;
};
struct S18_4 {
  int m0[3];
  void (*m1)(void);
  void (*m2)(void);
  u16 m3;
};
struct S18_5 {
  i8 m0;
  u16 m1;
  u8 m2;
  struct S18_1 m3;
  struct S18_2 m4;
};
STATIC_CHECK(sizeof(struct S18_0) == 8);
STATIC_CHECK(sizeof(struct S18_0[3]) == 24);
STATIC_CHECK(offsetof(struct S18_0, m0) == 0);
STATIC_CHECK(offsetof(struct S18_0, m1) == 4);
STATIC_CHECK(sizeof(struct S18_1) == 4);
STATIC_CHECK(sizeof(struct S18_1[3]) == 12);
STATIC_CHECK(offsetof(struct S18_1, m0) == 0);
STATIC_CHECK(sizeof(struct S18_2) == 1);
STATIC_CHECK(sizeof(struct S18_2[3]) == 3);
STATIC_CHECK(offsetof(struct S18_2, m0) == 0);
STATIC_CHECK(sizeof(struct S18_3) == 4);
STATIC_CHECK(sizeof(struct S18_3[3]) == 12);
STATIC_CHECK(offsetof(struct S18_3, m0) == 0);
STATIC_CHECK(sizeof(struct S18_4) == 20);
STATIC_CHECK(sizeof(struct S18_4[3]) == 60);
STATIC_CHECK(offsetof(struct S18_4, m0) == 0);
STATIC_CHECK(offsetof(struct S18_4, m1) == 8);
STATIC_CHECK(offsetof(struct S18_4, m2) == 12);
STATIC_CHECK(offsetof(struct S18_4, m3) == 16);
STATIC_CHECK(sizeof(struct S18_5) == 16);
STATIC_CHECK(sizeof(struct S18_5[3]) == 48);
STATIC_CHECK(offsetof(struct S18_5, m0) == 0);
STATIC_CHECK(offsetof(struct S18_5, m1) == 2);
STATIC_CHECK(offsetof(struct S18_5, m2) == 4);
STATIC_CHECK(offsetof(struct S18_5, m3) == 8);
STATIC_CHECK(offsetof(struct S18_5, m4) == 12);
