// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S34_0 {
  const i16 * m0;
  i32 m1;
  i8 m2[3];
};
struct S34_1 {
  u16 m0;
};
struct S34_2 {
  u16 m0;
  u16 m1;
  struct S34_1 m2[3];
  i8 m3;
};
struct S34_3 {
  struct S34_1 m0[3];
  u8 * m1;
};
struct S34_4 {
  u16 m0;
  const i16 * m1[2];
  i16 m2[1];
  i8 m3;
  u8 m4;
  int m5[5];
};
struct S34_5 {
  u16 m0[3];
  const i16 * m1;
  struct S34_2 m2[3];
};
STATIC_CHECK(sizeof(struct S34_0) == 12);
STATIC_CHECK(sizeof(struct S34_0[3]) == 36);
STATIC_CHECK(offsetof(struct S34_0, m0) == 0);
STATIC_CHECK(offsetof(struct S34_0, m1) == 4);
STATIC_CHECK(offsetof(struct S34_0, m2) == 8);
STATIC_CHECK(sizeof(struct S34_1) == 2);
STATIC_CHECK(sizeof(struct S34_1[3]) == 6);
STATIC_CHECK(offsetof(struct S34_1, m0) == 0);
STATIC_CHECK(sizeof(struct S34_2) == 12);
STATIC_CHECK(sizeof(struct S34_2[3]) == 36);
STATIC_CHECK(offsetof(struct S34_2, m0) == 0);
STATIC_CHECK(offsetof(struct S34_2, m1) == 2);
STATIC_CHECK(offsetof(struct S34_2, m2) == 4);
STATIC_CHECK(offsetof(struct S34_2, m3) == 10);
STATIC_CHECK(sizeof(struct S34_3) == 12);
STATIC_CHECK(sizeof(struct S34_3[3]) == 36);
STATIC_CHECK(offsetof(struct S34_3, m0) == 0);
STATIC_CHECK(offsetof(struct S34_3, m1) == 8);
STATIC_CHECK(sizeof(struct S34_4) == 28);
STATIC_CHECK(sizeof(struct S34_4[3]) == 84);
STATIC_CHECK(offsetof(struct S34_4, m0) == 0);
STATIC_CHECK(offsetof(struct S34_4, m1) == 4);
STATIC_CHECK(offsetof(struct S34_4, m2) == 12);
STATIC_CHECK(offsetof(struct S34_4, m3) == 14);
STATIC_CHECK(offsetof(struct S34_4, m4) == 15);
STATIC_CHECK(offsetof(struct S34_4, m5) == 16);
STATIC_CHECK(sizeof(struct S34_5) == 48);
STATIC_CHECK(sizeof(struct S34_5[3]) == 144);
STATIC_CHECK(offsetof(struct S34_5, m0) == 0);
STATIC_CHECK(offsetof(struct S34_5, m1) == 8);
STATIC_CHECK(offsetof(struct S34_5, m2) == 12);
