// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S12_0 {
  i32 m0;
};
struct S12_1 {
  u16 m0;
  u16 m1;
};
struct S12_2 {
  int m0;
};
struct S12_3 {
  i32 m0[5];
  void (*m1)(void);
  int m2;
};
struct S12_4 {
  i16 m0[1];
  i16 m1[2];
  i16 m2;
  struct S12_0 m3[3];
};
struct S12_5 {
  const i16 * m0;
  i32 m1[2];
};
STATIC_CHECK(sizeof(struct S12_0) == 4);
STATIC_CHECK(sizeof(struct S12_0[3]) == 12);
STATIC_CHECK(offsetof(struct S12_0, m0) == 0);
STATIC_CHECK(sizeof(struct S12_1) == 4);
STATIC_CHECK(sizeof(struct S12_1[3]) == 12);
STATIC_CHECK(offsetof(struct S12_1, m0) == 0);
STATIC_CHECK(offsetof(struct S12_1, m1) == 2);
STATIC_CHECK(sizeof(struct S12_2) == 2);
STATIC_CHECK(sizeof(struct S12_2[3]) == 6);
STATIC_CHECK(offsetof(struct S12_2, m0) == 0);
STATIC_CHECK(sizeof(struct S12_3) == 28);
STATIC_CHECK(sizeof(struct S12_3[3]) == 84);
STATIC_CHECK(offsetof(struct S12_3, m0) == 0);
STATIC_CHECK(offsetof(struct S12_3, m1) == 20);
STATIC_CHECK(offsetof(struct S12_3, m2) == 24);
STATIC_CHECK(sizeof(struct S12_4) == 20);
STATIC_CHECK(sizeof(struct S12_4[3]) == 60);
STATIC_CHECK(offsetof(struct S12_4, m0) == 0);
STATIC_CHECK(offsetof(struct S12_4, m1) == 2);
STATIC_CHECK(offsetof(struct S12_4, m2) == 6);
STATIC_CHECK(offsetof(struct S12_4, m3) == 8);
STATIC_CHECK(sizeof(struct S12_5) == 12);
STATIC_CHECK(sizeof(struct S12_5[3]) == 36);
STATIC_CHECK(offsetof(struct S12_5, m0) == 0);
STATIC_CHECK(offsetof(struct S12_5, m1) == 4);
