// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S9_0 {
  u8 * m0[3];
  u8 * m1[5];
  int m2;
};
struct S9_1 {
  struct S9_0 m0[2];
  struct S9_0 m1;
  u8 * m2[5];
  struct S9_0 m3[3];
  const i16 * m4;
  u8 m5[3];
};
struct S9_2 {
  i32 m0;
  struct S9_0 m1;
  i8 m2[5];
};
struct S9_3 {
  const i16 * m0;
  const i16 * m1;
  struct S9_0 m2;
  const i16 * m3;
  struct S9_2 m4;
};
struct S9_4 {
  i8 m0;
  u16 m1[1];
};
struct S9_5 {
  const i16 * m0[3];
  struct S9_1 m1;
  u8 m2;
  i8 m3[2];
  int m4;
};
STATIC_CHECK(sizeof(struct S9_0) == 36);
STATIC_CHECK(sizeof(struct S9_0[3]) == 108);
STATIC_CHECK(offsetof(struct S9_0, m0) == 0);
STATIC_CHECK(offsetof(struct S9_0, m1) == 12);
STATIC_CHECK(offsetof(struct S9_0, m2) == 32);
STATIC_CHECK(sizeof(struct S9_1) == 244);
STATIC_CHECK(sizeof(struct S9_1[3]) == 732);
STATIC_CHECK(offsetof(struct S9_1, m0) == 0);
STATIC_CHECK(offsetof(struct S9_1, m1) == 72);
STATIC_CHECK(offsetof(struct S9_1, m2) == 108);
STATIC_CHECK(offsetof(struct S9_1, m3) == 128);
STATIC_CHECK(offsetof(struct S9_1, m4) == 236);
STATIC_CHECK(offsetof(struct S9_1, m5) == 240);
STATIC_CHECK(sizeof(struct S9_2) == 48);
STATIC_CHECK(sizeof(struct S9_2[3]) == 144);
STATIC_CHECK(offsetof(struct S9_2, m0) == 0);
STATIC_CHECK(offsetof(struct S9_2, m1) == 4);
STATIC_CHECK(offsetof(struct S9_2, m2) == 40);
STATIC_CHECK(sizeof(struct S9_3) == 96);
STATIC_CHECK(sizeof(struct S9_3[3]) == 288);
STATIC_CHECK(offsetof(struct S9_3, m0) == 0);
STATIC_CHECK(offsetof(struct S9_3, m1) == 4);
STATIC_CHECK(offsetof(struct S9_3, m2) == 8);
STATIC_CHECK(offsetof(struct S9_3, m3) == 44);
STATIC_CHECK(offsetof(struct S9_3, m4) == 48);
STATIC_CHECK(sizeof(struct S9_4) == 4);
STATIC_CHECK(sizeof(struct S9_4[3]) == 12);
STATIC_CHECK(offsetof(struct S9_4, m0) == 0);
STATIC_CHECK(offsetof(struct S9_4, m1) == 2);
STATIC_CHECK(sizeof(struct S9_5) == 264);
STATIC_CHECK(sizeof(struct S9_5[3]) == 792);
STATIC_CHECK(offsetof(struct S9_5, m0) == 0);
STATIC_CHECK(offsetof(struct S9_5, m1) == 12);
STATIC_CHECK(offsetof(struct S9_5, m2) == 256);
STATIC_CHECK(offsetof(struct S9_5, m3) == 257);
STATIC_CHECK(offsetof(struct S9_5, m4) == 260);
