// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S19_0 {
  void (*m0)(void);
  i16 m1[1];
  int m2;
};
struct S19_1 {
  const i16 * m0;
  i8 m1;
  struct S19_0 m2[2];
  int m3[1];
  const i16 * m4;
};
struct S19_2 {
  i8 m0;
  i32 m1;
  struct S19_0 m2;
  const i16 * m3;
};
struct S19_3 {
  i8 m0;
  struct S19_1 m1[2];
};
struct S19_4 {
  i32 m0;
  void (*m1)(void);
  i32 m2[3];
  void (*m3[5])(void);
  struct S19_3 m4;
  struct S19_3 m5[3];
};
struct S19_5 {
  i16 m0;
  struct S19_2 m1;
};
STATIC_CHECK(sizeof(struct S19_0) == 8);
STATIC_CHECK(sizeof(struct S19_0[3]) == 24);
STATIC_CHECK(offsetof(struct S19_0, m0) == 0);
STATIC_CHECK(offsetof(struct S19_0, m1) == 4);
STATIC_CHECK(offsetof(struct S19_0, m2) == 6);
STATIC_CHECK(sizeof(struct S19_1) == 32);
STATIC_CHECK(sizeof(struct S19_1[3]) == 96);
STATIC_CHECK(offsetof(struct S19_1, m0) == 0);
STATIC_CHECK(offsetof(struct S19_1, m1) == 4);
STATIC_CHECK(offsetof(struct S19_1, m2) == 8);
STATIC_CHECK(offsetof(struct S19_1, m3) == 24);
STATIC_CHECK(offsetof(struct S19_1, m4) == 28);
STATIC_CHECK(sizeof(struct S19_2) == 20);
STATIC_CHECK(sizeof(struct S19_2[3]) == 60);
STATIC_CHECK(offsetof(struct S19_2, m0) == 0);
STATIC_CHECK(offsetof(struct S19_2, m1) == 4);
STATIC_CHECK(offsetof(struct S19_2, m2) == 8);
STATIC_CHECK(offsetof(struct S19_2, m3) == 16);
STATIC_CHECK(sizeof(struct S19_3) == 68);
STATIC_CHECK(sizeof(struct S19_3[3]) == 204);
STATIC_CHECK(offsetof(struct S19_3, m0) == 0);
STATIC_CHECK(offsetof(struct S19_3, m1) == 4);
STATIC_CHECK(sizeof(struct S19_4) == 312);
STATIC_CHECK(sizeof(struct S19_4[3]) == 936);
STATIC_CHECK(offsetof(struct S19_4, m0) == 0);
STATIC_CHECK(offsetof(struct S19_4, m1) == 4);
STATIC_CHECK(offsetof(struct S19_4, m2) == 8);
STATIC_CHECK(offsetof(struct S19_4, m3) == 20);
STATIC_CHECK(offsetof(struct S19_4, m4) == 40);
STATIC_CHECK(offsetof(struct S19_4, m5) == 108);
STATIC_CHECK(sizeof(struct S19_5) == 24);
STATIC_CHECK(sizeof(struct S19_5[3]) == 72);
STATIC_CHECK(offsetof(struct S19_5, m0) == 0);
STATIC_CHECK(offsetof(struct S19_5, m1) == 4);
