// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S17_0 {
  const i16 * m0[3];
  void (*m1)(void);
  i16 m2[1];
  void (*m3[2])(void);
};
struct S17_1 {
  u16 m0[5];
};
struct S17_2 {
  u8 m0[5];
};
struct S17_3 {
  u8 * m0;
  struct S17_0 m1[2];
};
struct S17_4 {
  i8 m0;
  i16 m1[2];
};
struct S17_5 {
  const i16 * m0;
  i8 m1;
};
STATIC_CHECK(sizeof(struct S17_0) == 28);
STATIC_CHECK(sizeof(struct S17_0[3]) == 84);
STATIC_CHECK(offsetof(struct S17_0, m0) == 0);
STATIC_CHECK(offsetof(struct S17_0, m1) == 12);
STATIC_CHECK(offsetof(struct S17_0, m2) == 16);
STATIC_CHECK(offsetof(struct S17_0, m3) == 20);
STATIC_CHECK(sizeof(struct S17_1) == 10);
STATIC_CHECK(sizeof(struct S17_1[3]) == 30);
STATIC_CHECK(offsetof(struct S17_1, m0) == 0);
STATIC_CHECK(sizeof(struct S17_2) == 5);
STATIC_CHECK(sizeof(struct S17_2[3]) == 15);
STATIC_CHECK(offsetof(struct S17_2, m0) == 0);
STATIC_CHECK(sizeof(struct S17_3) == 60);
STATIC_CHECK(sizeof(struct S17_3[3]) == 180);
STATIC_CHECK(offsetof(struct S17_3, m0) == 0);
STATIC_CHECK(offsetof(struct S17_3, m1) == 4);
STATIC_CHECK(sizeof(struct S17_4) == 6);
STATIC_CHECK(sizeof(struct S17_4[3]) == 18);
STATIC_CHECK(offsetof(struct S17_4, m0) == 0);
STATIC_CHECK(offsetof(struct S17_4, m1) == 2);
STATIC_CHECK(sizeof(struct S17_5) == 8);
STATIC_CHECK(sizeof(struct S17_5[3]) == 24);
STATIC_CHECK(offsetof(struct S17_5, m0) == 0);
STATIC_CHECK(offsetof(struct S17_5, m1) == 4);
