// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S38_0 {
  u16 m0;
  const i16 * m1;
  const i16 * m2;
  int m3;
  u8 * m4;
};
struct S38_1 {
  u16 m0;
  u16 m1;
};
struct S38_2 {
  struct S38_0 m0;
};
struct S38_3 {
  i32 m0[3];
  void (*m1[2])(void);
  i32 m2[3];
};
struct S38_4 {
  void (*m0)(void);
  i32 m1[1];
  i16 m2;
  i16 m3;
  i8 m4;
  struct S38_3 m5[3];
};
struct S38_5 {
  i16 m0;
  u8 m1;
  i8 m2;
  i16 m3;
};
STATIC_CHECK(sizeof(struct S38_0) == 20);
STATIC_CHECK(sizeof(struct S38_0[3]) == 60);
STATIC_CHECK(offsetof(struct S38_0, m0) == 0);
STATIC_CHECK(offsetof(struct S38_0, m1) == 4);
STATIC_CHECK(offsetof(struct S38_0, m2) == 8);
STATIC_CHECK(offsetof(struct S38_0, m3) == 12);
STATIC_CHECK(offsetof(struct S38_0, m4) == 16);
STATIC_CHECK(sizeof(struct S38_1) == 4);
STATIC_CHECK(sizeof(struct S38_1[3]) == 12);
STATIC_CHECK(offsetof(struct S38_1, m0) == 0);
STATIC_CHECK(offsetof(struct S38_1, m1) == 2);
STATIC_CHECK(sizeof(struct S38_2) == 20);
STATIC_CHECK(sizeof(struct S38_2[3]) == 60);
STATIC_CHECK(offsetof(struct S38_2, m0) == 0);
STATIC_CHECK(sizeof(struct S38_3) == 32);
STATIC_CHECK(sizeof(struct S38_3[3]) == 96);
STATIC_CHECK(offsetof(struct S38_3, m0) == 0);
STATIC_CHECK(offsetof(struct S38_3, m1) == 12);
STATIC_CHECK(offsetof(struct S38_3, m2) == 20);
STATIC_CHECK(sizeof(struct S38_4) == 112);
STATIC_CHECK(sizeof(struct S38_4[3]) == 336);
STATIC_CHECK(offsetof(struct S38_4, m0) == 0);
STATIC_CHECK(offsetof(struct S38_4, m1) == 4);
STATIC_CHECK(offsetof(struct S38_4, m2) == 8);
STATIC_CHECK(offsetof(struct S38_4, m3) == 10);
STATIC_CHECK(offsetof(struct S38_4, m4) == 12);
STATIC_CHECK(offsetof(struct S38_4, m5) == 16);
STATIC_CHECK(sizeof(struct S38_5) == 6);
STATIC_CHECK(sizeof(struct S38_5[3]) == 18);
STATIC_CHECK(offsetof(struct S38_5, m0) == 0);
STATIC_CHECK(offsetof(struct S38_5, m1) == 2);
STATIC_CHECK(offsetof(struct S38_5, m2) == 3);
STATIC_CHECK(offsetof(struct S38_5, m3) == 4);
