// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S59_0 {
  void (*m0)(void);
  i16 m1[3];
  int m2;
  void (*m3)(void);
};
struct S59_1 {
  u8 * m0[2];
  i16 m1;
  u16 m2[1];
  i8 m3;
  u8 m4;
};
struct S59_2 {
  int m0;
  i32 m1;
  i16 m2;
  i16 m3[2];
  u8 m4;
  int m5[5];
};
struct S59_3 {
  struct S59_1 m0;
  struct S59_1 m1;
};
struct S59_4 {
  i32 m0[5];
  struct S59_1 m1;
};
struct S59_5 {
  i8 m0;
  struct S59_2 m1;
};
STATIC_CHECK(sizeof(struct S59_0) == 16);
STATIC_CHECK(sizeof(struct S59_0[3]) == 48);
STATIC_CHECK(offsetof(struct S59_0, m0) == 0);
STATIC_CHECK(offsetof(struct S59_0, m1) == 4);
STATIC_CHECK(offsetof(struct S59_0, m2) == 10);
STATIC_CHECK(offsetof(struct S59_0, m3) == 12);
STATIC_CHECK(sizeof(struct S59_1) == 16);
STATIC_CHECK(sizeof(struct S59_1[3]) == 48);
STATIC_CHECK(offsetof(struct S59_1, m0) == 0);
STATIC_CHECK(offsetof(struct S59_1, m1) == 8);
STATIC_CHECK(offsetof(struct S59_1, m2) == 10);
STATIC_CHECK(offsetof(struct S59_1, m3) == 12);
STATIC_CHECK(offsetof(struct S59_1, m4) == 13);
STATIC_CHECK(sizeof(struct S59_2) == 28);
STATIC_CHECK(sizeof(struct S59_2[3]) == 84);
STATIC_CHECK(offsetof(struct S59_2, m0) == 0);
STATIC_CHECK(offsetof(struct S59_2, m1) == 4);
STATIC_CHECK(offsetof(struct S59_2, m2) == 8);
STATIC_CHECK(offsetof(struct S59_2, m3) == 10);
STATIC_CHECK(offsetof(struct S59_2, m4) == 14);
STATIC_CHECK(offsetof(struct S59_2, m5) == 16);
STATIC_CHECK(sizeof(struct S59_3) == 32);
STATIC_CHECK(sizeof(struct S59_3[3]) == 96);
STATIC_CHECK(offsetof(struct S59_3, m0) == 0);
STATIC_CHECK(offsetof(struct S59_3, m1) == 16);
STATIC_CHECK(sizeof(struct S59_4) == 36);
STATIC_CHECK(sizeof(struct S59_4[3]) == 108);
STATIC_CHECK(offsetof(struct S59_4, m0) == 0);
STATIC_CHECK(offsetof(struct S59_4, m1) == 20);
STATIC_CHECK(sizeof(struct S59_5) == 32);
STATIC_CHECK(sizeof(struct S59_5[3]) == 96);
STATIC_CHECK(offsetof(struct S59_5, m0) == 0);
STATIC_CHECK(offsetof(struct S59_5, m1) == 4);
