// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S23_0 {
  i32 m0[2];
  const i16 * m1;
};
struct S23_1 {
  u8 * m0[1];
  void (*m1[1])(void);
};
struct S23_2 {
  u16 m0;
  u8 * m1;
  u8 * m2;
  struct S23_0 m3;
  struct S23_0 m4;
  u8 m5;
};
struct S23_3 {
  int m0;
  int m1;
};
struct S23_4 {
  void (*m0)(void);
  i32 m1;
  i32 m2;
  struct S23_1 m3;
  struct S23_0 m4[2];
};
struct S23_5 {
  i8 m0[2];
};
STATIC_CHECK(sizeof(struct S23_0) == 12);
STATIC_CHECK(sizeof(struct S23_0[3]) == 36);
STATIC_CHECK(offsetof(struct S23_0, m0) == 0);
STATIC_CHECK(offsetof(struct S23_0, m1) == 8);
STATIC_CHECK(sizeof(struct S23_1) == 8);
STATIC_CHECK(sizeof(struct S23_1[3]) == 24);
STATIC_CHECK(offsetof(struct S23_1, m0) == 0);
STATIC_CHECK(offsetof(struct S23_1, m1) == 4);
STATIC_CHECK(sizeof(struct S23_2) == 40);
STATIC_CHECK(sizeof(struct S23_2[3]) == 120);
STATIC_CHECK(offsetof(struct S23_2, m0) == 0);
STATIC_CHECK(offsetof(struct S23_2, m1) == 4);
STATIC_CHECK(offsetof(struct S23_2, m2) == 8);
STATIC_CHECK(offsetof(struct S23_2, m3) == 12);
STATIC_CHECK(offsetof(struct S23_2, m4) == 24);
STATIC_CHECK(offsetof(struct S23_2, m5) == 36);
STATIC_CHECK(sizeof(struct S23_3) == 4);
STATIC_CHECK(sizeof(struct S23_3[3]) == 12);
STATIC_CHECK(offsetof(struct S23_3, m0) == 0);
STATIC_CHECK(offsetof(struct S23_3, m1) == 2);
STATIC_CHECK(sizeof(struct S23_4) == 44);
STATIC_CHECK(sizeof(struct S23_4[3]) == 132);
STATIC_CHECK(offsetof(struct S23_4, m0) == 0);
STATIC_CHECK(offsetof(struct S23_4, m1) == 4);
STATIC_CHECK(offsetof(struct S23_4, m2) == 8);
STATIC_CHECK(offsetof(struct S23_4, m3) == 12);
STATIC_CHECK(offsetof(struct S23_4, m4) == 20);
STATIC_CHECK(sizeof(struct S23_5) == 2);
STATIC_CHECK(sizeof(struct S23_5[3]) == 6);
STATIC_CHECK(offsetof(struct S23_5, m0) == 0);
