// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S8_0 {
  i8 m0;
};
struct S8_1 {
  u16 m0;
  u16 m1;
  i16 m2;
  u8 * m3;
  u16 m4;
};
struct S8_2 {
  int m0;
  struct S8_0 m1;
  i8 m2;
};
struct S8_3 {
  u16 m0;
  u8 * m1;
};
struct S8_4 {
  i32 m0[2];
  i16 m1;
  i8 m2;
  i32 m3;
  u8 * m4;
};
struct S8_5 {
  struct S8_4 m0;
  struct S8_0 m1;
  u16 m2;
};
STATIC_CHECK(sizeof(struct S8_0) == 1);
STATIC_CHECK(sizeof(struct S8_0[3]) == 3);
STATIC_CHECK(offsetof(struct S8_0, m0) == 0);
STATIC_CHECK(sizeof(struct S8_1) == 16);
STATIC_CHECK(sizeof(struct S8_1[3]) == 48);
STATIC_CHECK(offsetof(struct S8_1, m0) == 0);
STATIC_CHECK(offsetof(struct S8_1, m1) == 2);
STATIC_CHECK(offsetof(struct S8_1, m2) == 4);
STATIC_CHECK(offsetof(struct S8_1, m3) == 8);
STATIC_CHECK(offsetof(struct S8_1, m4) == 12);
STATIC_CHECK(sizeof(struct S8_2) == 4);
STATIC_CHECK(sizeof(struct S8_2[3]) == 12);
STATIC_CHECK(offsetof(struct S8_2, m0) == 0);
STATIC_CHECK(offsetof(struct S8_2, m1) == 2);
STATIC_CHECK(offsetof(struct S8_2, m2) == 3);
STATIC_CHECK(sizeof(struct S8_3) == 8);
STATIC_CHECK(sizeof(struct S8_3[3]) == 24);
STATIC_CHECK(offsetof(struct S8_3, m0) == 0);
STATIC_CHECK(offsetof(struct S8_3, m1) == 4);
STATIC_CHECK(sizeof(struct S8_4) == 20);
STATIC_CHECK(sizeof(struct S8_4[3]) == 60);
STATIC_CHECK(offsetof(struct S8_4, m0) == 0);
STATIC_CHECK(offsetof(struct S8_4, m1) == 8);
STATIC_CHECK(offsetof(struct S8_4, m2) == 10);
STATIC_CHECK(offsetof(struct S8_4, m3) == 12);
STATIC_CHECK(offsetof(struct S8_4, m4) == 16);
STATIC_CHECK(sizeof(struct S8_5) == 24);
STATIC_CHECK(sizeof(struct S8_5[3]) == 72);
STATIC_CHECK(offsetof(struct S8_5, m0) == 0);
STATIC_CHECK(offsetof(struct S8_5, m1) == 20);
STATIC_CHECK(offsetof(struct S8_5, m2) == 22);
