// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((30) == (30));
STATIC_CHECK((0 ? 16 & 19 || 29 : 22 ? 24 / 17 : 10 / 13) == (1));
STATIC_CHECK((6 != (26 ? 38 > (36 <= 39) : ((7) <= 36) % (37 || 6))) == (1));
STATIC_CHECK((- ~ 26) == (27));
STATIC_CHECK(((30 / (0 <= (23 || 17)) < (32 % 37 != (38 && 22)) - 25) & ((19) + 35 <= 13 - 24 & 39 | ((38 ? 31 > 18 : 19 | 18)) >= (37 || 38) >> (0 >= 35))) == (0));
STATIC_CHECK((9) == (9));
STATIC_CHECK((10) == (10));
STATIC_CHECK((((34 + 17 ^ ! 30) > ~ 37) - 27) == (-26));
STATIC_CHECK((24) == (24));
STATIC_CHECK(((29 == 1) >= 3) == (0));
STATIC_CHECK((((16) && 10) == 33) == (0));
STATIC_CHECK((-(3 ^ 6)) == (-5));
STATIC_CHECK(((25 & 31 ^ 31 != 14 ? 7 < (0 == 18) : 10 < 5 && 14) != (31 & 9 * (1 / 9))) == (0));
STATIC_CHECK((13 < 31 > ((29) > 11)) == (0));
STATIC_CHECK((~ ~ ~((25) != 14 || 36)) == (-2));
STATIC_CHECK((11) == (11));
STATIC_CHECK((14) == (14));
STATIC_CHECK((29) == (29));
STATIC_CHECK((22 > (9 > 3 && 1) < ((21) == (32 ? 15 : 25) ? (10 ? 6 : 12) > (14 ? 39 : 39) : 38 / 30 == 9 >= 12) ? ((! 26 <= (21 <= 18)) >= 11) * (25 > 28) : 3 < -((9 + 8) == (8 != 36))) == (0));
STATIC_CHECK(((0) > 25 & ! 28) == (0));
STATIC_CHECK((11) == (11));
STATIC_CHECK((25) == (25));
STATIC_CHECK((26) == (26));
STATIC_CHECK((8) == (8));
STATIC_CHECK((11) == (11));
