// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((9) == (9));
STATIC_CHECK(((33 ^ (18 | 8 ? 3 : (16) + 18)) < (33 != - 14 * 22)) == (0));
STATIC_CHECK((!((9 ? 30 : 2) ? 25 < 22 : 25 - 7)) == (1));
STATIC_CHECK((8) == (8));
STATIC_CHECK((30) == (30));
STATIC_CHECK((32) == (32));
STATIC_CHECK((18 % 29 ^ 3) == (17));
STATIC_CHECK((! 8 == !((37) - 23)) == (1));
STATIC_CHECK(((19 != 37) < ((8) | 37)) == (1));
STATIC_CHECK(((17 && 16) / (34 >= 34) & ! - 31) == (0));
STATIC_CHECK(((20 != 29) >= ~ 22) == (1));
STATIC_CHECK(((1) || ~(23 >> 8)) == (1));
STATIC_CHECK((35) == (35));
STATIC_CHECK((34 - (20 | 9) != -(11 * 4)) == (1));
STATIC_CHECK(((20 <= 25 >= (28 > 16)) << (30 | 18 || 34 + 9) | 20 - - 23 <= (12 == 29) >> (13 & 11) || 11) == (1));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((5 || 22) / 9 < 33) == (1));
STATIC_CHECK((35) == (35));
STATIC_CHECK(((22 != 23) <= (26 == 21) && (26 ? 11 : 32)) == (0));
STATIC_CHECK(((~ 34 != (30 ? 7 : 34)) < (20 >= 33 ? (22) && 20 : 17)) == (1));
STATIC_CHECK((0 >= (- 9 < 19) * (! 29 ? (19 ? 3 : 12) : 13 % 16) >= ~((23) >= 23 > (0 ^ 23) ? 38 / 26 | 5 : 12 || 0 / 17)) == (1));
STATIC_CHECK((18) == (18));
STATIC_CHECK(((14 ^ (37 ? 16 : 16) > (16 != 12)) < 16) == (1));
STATIC_CHECK(((37 == (29 | 22)) + 16 != 17) == (1));
STATIC_CHECK((34) == (34));
