// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((37 == 13) == (0));
STATIC_CHECK(((~ ~ 17 != ((20 >= 12) == 19 % 2)) > (9 ^ 33 < (16 || 15))) == (0));
STATIC_CHECK(((5 <= (5 ^ 12) || ! 33) + (((2) % 21 == 38 != ((38) * 12 ? 38 : 27)) >= (14 - 26 - (10 - 31) > ! 27))) == (2));
STATIC_CHECK(((11 || ! 2 || 31 + 22 & 14 + 33) ^ 0 << (25 != 4) > ! 30 && 8) == (1));
STATIC_CHECK((28 < 33 > ~ 29 < (5) >> 8 > 35) == (0));
STATIC_CHECK((((30 | 19) == 21 * (29 && 33) / (- 39 != 20)) / (13 - ((13 | 15) << (17 && 21)) && (37 - ((12) - 35) ? 31 : 27 >> 2 || 39 * 0))) == (0));
STATIC_CHECK((14) == (14));
STATIC_CHECK(((38 ? 34 : 5) || 37) == (1));
STATIC_CHECK(((26 | 27) ^ 13 % 24 | 5 > 14 ^ 7 >= 32) == (22));
STATIC_CHECK((7) == (7));
STATIC_CHECK((26) == (26));
STATIC_CHECK((15 > 4 >= 31) == (0));
STATIC_CHECK((2 * (18 * 35)) == (1260));
STATIC_CHECK((! 13 % 35 ? 28 - 15 != 23 * 12 : 16) == (16));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((((12 | 2) / (29 + 18) | 19)) >> (18 * 27 >= 13 - 7 && 36)) == (9));
STATIC_CHECK((36 + 11) == (47));
STATIC_CHECK(((11 > 26 < 17 ? (21 | 8) == (0 ^ 33) : (38 >= 22) + (14 == 2)) % 18) == (0));
STATIC_CHECK(((! 36 || ! ! 12) * (39 & (5 | 32) > (17 == 12))) == (1));
STATIC_CHECK((16) == (16));
STATIC_CHECK((7) == (7));
STATIC_CHECK((9 > (21 == ! 34) > 16) == (0));
STATIC_CHECK(((8 > (13 ? 25 : 1) <= 25) / 8 <= (18 <= (5 >= 5) % (5 ? 15 : 35) | 2)) == (1));
STATIC_CHECK((-(2 && 32)) == (-1));
STATIC_CHECK(((38 != 5) / (5 != 33) - 25 < 21) == (1));
