// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK(((35 ? 21 < 26 : 5 >> 14) << ((29) | 23 || 13 / 34)) == (2));
STATIC_CHECK(((26 ^ 36) / - 21) == (-2));
STATIC_CHECK(((35) + 19) == (54));
STATIC_CHECK(((33 & 19) > (8 ? 17 : 32)) == (0));
STATIC_CHECK(((29 & 1) >= (35 < 37)) == (1));
STATIC_CHECK(((7 & 36) >= ~ 34 > (- 28 && 14 ^ 1)) == (0));
STATIC_CHECK((22) == (22));
STATIC_CHECK((7 >= 26) == (0));
STATIC_CHECK((7) == (7));
STATIC_CHECK((~((39 && 31 && 12) | (23 - 13 ? 25 ^ 7 : 33))) == (-32));
STATIC_CHECK(((33 + ((9) | 13) > (37 >> 10 ? 31 | 5 : 5 << 6) || ~(31 >> 11) - !(35 ^ 17)) != 3 * 32) == (1));
STATIC_CHECK((10) == (10));
STATIC_CHECK(((33 && 2) | ~(31 % 5) > 30) == (1));
STATIC_CHECK(((39 & 8 - 0) < (18 && 28) / (27 ^ 11) > ~ ~ 32 << (33 + 5 && 14) || 2 == 38 * (19 & 14 - 27)) == (0));
STATIC_CHECK((12) == (12));
STATIC_CHECK(((11) == 0 == (29 ? 37 : 0)) == (0));
STATIC_CHECK((~(19 == 3 && 11 == 13)) == (-1));
STATIC_CHECK((-((12 >= 28) < (1 != 38)) < ((3 ^ ! 26) != ((39 / 39) || 20 * 26))) == (1));
STATIC_CHECK((11) == (11));
STATIC_CHECK((((0 | 36) & - 36) % ((28) & 37)) == (0));
STATIC_CHECK(((33 | 8) % 3) == (2));
STATIC_CHECK((38) == (38));
STATIC_CHECK((6) == (6));
STATIC_CHECK(((33 <= 0) - ((28) >> 10)) == (0));
STATIC_CHECK(((4 > 9 < (24 <= 0)) >> 8 ^ 30) == (30));
