// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((-(30 <= 8)) == (0));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((34 ? 31 : 12) <= 18 >= (34 > 3 > 38)) == (1));
STATIC_CHECK((! ~ !((11 != 30) / (22 | 8))) == (0));
STATIC_CHECK((~(34 > 36) < ((39 == 19) | (15 ? 22 : 26))) == (1));
STATIC_CHECK((25) == (25));
STATIC_CHECK(((14 ? 26 : 11) == 2 < 6) == (0));
STATIC_CHECK((6) == (6));
STATIC_CHECK((19 ? 31 : ! 24) == (31));
STATIC_CHECK((37 * (27 || 1) > (26 * 0 >= (30 ^ 24))) == (1));
STATIC_CHECK((13) == (13));
STATIC_CHECK((~(((9 ? 17 : - 22) > (35 <= 15 ^ 13 + 34)) - ~((1 + 11) * (8 * 10)))) == (-962));
STATIC_CHECK((27) == (27));
STATIC_CHECK((~(23 * (22 / 1 | (8 ? 24 : 0)))) == (-691));
STATIC_CHECK((~(29 % 11)) == (-8));
STATIC_CHECK(((19) / 28 < 32 ? ((0 ? 1 : 18) ? (21) < 8 : 27) : 10) == (0));
STATIC_CHECK((~ 12) == (-13));
STATIC_CHECK((30) == (30));
STATIC_CHECK((~(! ! 16 < (8 || 27) << (30 || 12))) == (-2));
STATIC_CHECK((35 & 9) == (1));
STATIC_CHECK(((32 | ~(12 * 34)) & 1) == (1));
STATIC_CHECK(((30) % 26 ? 17 : 22 ? 28 : 6) == (17));
STATIC_CHECK((7 - ((13 != 0) || 5 & 27)) == (6));
STATIC_CHECK((16) == (16));
STATIC_CHECK((39 ^ ~(37 ^ 9 ? (12 ? 22 : 31) : 1 || 36) || (23 || (21 | (30) != 7) <= 12)) == (1));
