// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((((30 && 29)) / (15 < 24) ? ~(35 && 37) : 16 / 29 ? 7 + 32 : 12) == (-2));
STATIC_CHECK(((13 - 37 + 13 % 31) % (! 38 ? 26 : 20 - 19)) == (0));
STATIC_CHECK((10) == (10));
STATIC_CHECK((((29 && 38) & 39 - 10) - (5 + 27 >= (14 ^ 11))) == (0));
STATIC_CHECK((39) == (39));
STATIC_CHECK((!(((10 && 29)) ^ 24 >= 1 > 6 + 16)) == (0));
STATIC_CHECK((38) == (38));
STATIC_CHECK((21) == (21));
STATIC_CHECK((((0 || 25 > 2) || 15 % 9) << (22 % ((20) & 17) > 13)) == (1));
STATIC_CHECK(((((22 ? 24 : 13) != - 18) != !(16 > 33)) < (21 < 35 != 33 ? 9 : 12 * 32 > 34)) == (1));
STATIC_CHECK((-((14 >= 6 > 6) * (30 >> (4) / 21)) > (0 <= 10 >= ((19 ? 7 : 8) >= 10 < (26 <= 19 && 31)))) == (0));
STATIC_CHECK((((10) == 11 || 13) < ((31 ? 37 : 12)) + 34) == (1));
STATIC_CHECK(((((29 % 16 <= ((22 >= 35) ^ (19 || 28)))) + 28) % (((9 != 23)) >= ((! 15) ^ 7) ? 21 : 5)) == (3));
STATIC_CHECK((27) == (27));
STATIC_CHECK((16) == (16));
STATIC_CHECK((15) == (15));
STATIC_CHECK((39 ? 20 & 35 : ~ 33) == (0));
STATIC_CHECK((15 | 29 != (2 <= 13 & (24 & 36))) == (15));
STATIC_CHECK((10 >= 28) == (0));
STATIC_CHECK((- 8 / ((26 ^ 35) / (14 | 14)) ? 2 - 18 + 22 - 38 : 30) == (-32));
STATIC_CHECK((27 + (14 - ((7 != 13) - (5 != 0)) >= 27)) == (27));
STATIC_CHECK((18 | 37) == (55));
STATIC_CHECK((~ 28 != (18 ^ 3)) == (1));
STATIC_CHECK((-(((8 | 35) ^ 35 != 38) & (5 || 23) > 7)) == (0));
STATIC_CHECK((1) == (1));
