// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// u32 << (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(0))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(1))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(8))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(15))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(16))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)0LL)) << ((u8)(31))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(0))) == ((u32)1LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(1))) == ((u32)2LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(8))) == ((u32)256LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(15))) == ((u32)32768LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(16))) == ((u32)65536LL));
STATIC_CHECK(((u32)(((u32)1LL)) << ((u8)(31))) == ((u32)2147483648LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(0))) == ((u32)65535LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(1))) == ((u32)131070LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(8))) == ((u32)16776960LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(15))) == ((u32)2147450880LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(16))) == ((u32)4294901760LL));
STATIC_CHECK(((u32)(((u32)65535LL)) << ((u8)(31))) == ((u32)2147483648LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(0))) == ((u32)65536LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(1))) == ((u32)131072LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(8))) == ((u32)16777216LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(15))) == ((u32)2147483648LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(16))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)65536LL)) << ((u8)(31))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(0))) == ((u32)100000LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(1))) == ((u32)200000LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(8))) == ((u32)25600000LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(15))) == ((u32)3276800000LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(16))) == ((u32)2258632704LL));
STATIC_CHECK(((u32)(((u32)100000LL)) << ((u8)(31))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(0))) == ((u32)2147483647LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(1))) == ((u32)4294967294LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(8))) == ((u32)4294967040LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(15))) == ((u32)4294934528LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(16))) == ((u32)4294901760LL));
STATIC_CHECK(((u32)(((u32)2147483647LL)) << ((u8)(31))) == ((u32)2147483648LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(0))) == ((u32)2147483648LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(1))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(8))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(15))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(16))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)2147483648LL)) << ((u8)(31))) == ((u32)0LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(0))) == ((u32)4294967295LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(1))) == ((u32)4294967294LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(8))) == ((u32)4294967040LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(15))) == ((u32)4294934528LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(16))) == ((u32)4294901760LL));
STATIC_CHECK(((u32)(((u32)4294967295LL)) << ((u8)(31))) == ((u32)2147483648LL));
