// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// i32 << (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(0))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(1))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(8))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(15))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(16))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) << ((u8)(31))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) << ((u8)(0))) == ((i32)1LL));
STATIC_CHECK(((i32)(((i32)1LL)) << ((u8)(1))) == ((i32)2LL));
STATIC_CHECK(((i32)(((i32)1LL)) << ((u8)(8))) == ((i32)256LL));
STATIC_CHECK(((i32)(((i32)1LL)) << ((u8)(15))) == ((i32)32768LL));
STATIC_CHECK(((i32)(((i32)1LL)) << ((u8)(16))) == ((i32)65536LL));
STATIC_CHECK(((i32)(((i32)65535LL)) << ((u8)(0))) == ((i32)65535LL));
STATIC_CHECK(((i32)(((i32)65535LL)) << ((u8)(1))) == ((i32)131070LL));
STATIC_CHECK(((i32)(((i32)65535LL)) << ((u8)(8))) == ((i32)16776960LL));
STATIC_CHECK(((i32)(((i32)65535LL)) << ((u8)(15))) == ((i32)2147450880LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) << ((u8)(0))) == ((i32)2147483647LL));
