// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// i32 >> (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(0))) == ((i32)-2147483648LL));
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(1))) == ((i32)-1073741824LL));
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(8))) == ((i32)-8388608LL));
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(15))) == ((i32)-65536LL));
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(16))) == ((i32)-32768LL));
STATIC_CHECK(((i32)(((i32)-2147483648LL)) >> ((u8)(31))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(0))) == ((i32)-100000LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(1))) == ((i32)-50000LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(8))) == ((i32)-391LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(15))) == ((i32)-4LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(16))) == ((i32)-2LL));
STATIC_CHECK(((i32)(((i32)-100000LL)) >> ((u8)(31))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(0))) == ((i32)-65536LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(1))) == ((i32)-32768LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(8))) == ((i32)-256LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(15))) == ((i32)-2LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(16))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-65536LL)) >> ((u8)(31))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(0))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(1))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(8))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(15))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(16))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)-1LL)) >> ((u8)(31))) == ((i32)-1LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(0))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(1))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(8))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(15))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(16))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)0LL)) >> ((u8)(31))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(0))) == ((i32)1LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(1))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(8))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(15))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(16))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)1LL)) >> ((u8)(31))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(0))) == ((i32)65535LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(1))) == ((i32)32767LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(8))) == ((i32)255LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(15))) == ((i32)1LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(16))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)65535LL)) >> ((u8)(31))) == ((i32)0LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(0))) == ((i32)2147483647LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(1))) == ((i32)1073741823LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(8))) == ((i32)8388607LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(15))) == ((i32)65535LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(16))) == ((i32)32767LL));
STATIC_CHECK(((i32)(((i32)2147483647LL)) >> ((u8)(31))) == ((i32)0LL));
