// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// u16 >> (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((u16)(0u) >> ((u8)(0))) == 0u);
STATIC_CHECK(((u16)(0u) >> ((u8)(1))) == 0u);
STATIC_CHECK(((u16)(0u) >> ((u8)(3))) == 0u);
STATIC_CHECK(((u16)(0u) >> ((u8)(7))) == 0u);
STATIC_CHECK(((u16)(0u) >> ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(0u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(1u) >> ((u8)(0))) == 1u);
STATIC_CHECK(((u16)(1u) >> ((u8)(1))) == 0u);
STATIC_CHECK(((u16)(1u) >> ((u8)(3))) == 0u);
STATIC_CHECK(((u16)(1u) >> ((u8)(7))) == 0u);
STATIC_CHECK(((u16)(1u) >> ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(1u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(2u) >> ((u8)(0))) == 2u);
STATIC_CHECK(((u16)(2u) >> ((u8)(1))) == 1u);
STATIC_CHECK(((u16)(2u) >> ((u8)(3))) == 0u);
STATIC_CHECK(((u16)(2u) >> ((u8)(7))) == 0u);
STATIC_CHECK(((u16)(2u) >> ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(2u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(255u) >> ((u8)(0))) == 255u);
STATIC_CHECK(((u16)(255u) >> ((u8)(1))) == 127u);
STATIC_CHECK(((u16)(255u) >> ((u8)(3))) == 31u);
STATIC_CHECK(((u16)(255u) >> ((u8)(7))) == 1u);
STATIC_CHECK(((u16)(255u) >> ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(255u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(256u) >> ((u8)(0))) == 256u);
STATIC_CHECK(((u16)(256u) >> ((u8)(1))) == 128u);
STATIC_CHECK(((u16)(256u) >> ((u8)(3))) == 32u);
STATIC_CHECK(((u16)(256u) >> ((u8)(7))) == 2u);
STATIC_CHECK(((u16)(256u) >> ((u8)(8))) == 1u);
STATIC_CHECK(((u16)(256u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(0))) == 1000u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(1))) == 500u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(3))) == 125u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(7))) == 7u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(8))) == 3u);
STATIC_CHECK(((u16)(1000u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(0))) == 32767u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(1))) == 16383u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(3))) == 4095u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(7))) == 255u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(8))) == 127u);
STATIC_CHECK(((u16)(32767u) >> ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(0))) == 32768u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(1))) == 16384u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(3))) == 4096u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(7))) == 256u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(8))) == 128u);
STATIC_CHECK(((u16)(32768u) >> ((u8)(15))) == 1u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(0))) == 40000u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(1))) == 20000u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(3))) == 5000u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(7))) == 312u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(8))) == 156u);
STATIC_CHECK(((u16)(40000u) >> ((u8)(15))) == 1u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(0))) == 65535u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(1))) == 32767u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(3))) == 8191u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(7))) == 511u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(8))) == 255u);
STATIC_CHECK(((u16)(65535u) >> ((u8)(15))) == 1u);
