// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u8 counter from 224 in steps of 3, 25 iterations, leaving at 10.
#include "loomcc-test.h"
static volatile u8 limit = 25;
int main(void) {
  u8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u8)(224), n = 0; n < limit; i = (u8)(i + (3)), n++) {
    if (n == 10) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 2375u);
  CHECK(iters == 10);
  return 0;
}
