// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i8 counter from 94 in steps of -2, 58 iterations, leaving at 16.
#include "loomcc-test.h"
static volatile u8 limit = 58;
int main(void) {
  i8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i8)(94), n = 0; n < limit; i = (i8)(i + (-2)), n++) {
    if (n == 16) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 1264u);
  CHECK(iters == 16);
  return 0;
}
