// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i8 counter from 28 in steps of 1, 59 iterations.
#include "loomcc-test.h"
static volatile u8 limit = 59;
int main(void) {
  i8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i8)(28), n = 0; n < limit; i = (i8)(i + (1)), n++) {
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 3363u);
  CHECK(iters == 59);
  CHECK(i == (i8)(87));
  return 0;
}
