// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u16 counter from 62 in steps of 1, 39 iterations.
#include "loomcc-test.h"
static volatile u8 limit = 39;
int main(void) {
  u16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u16)(62), n = 0; n < limit; i = (u16)(i + (1)), n++) {
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 3159u);
  CHECK(iters == 39);
  CHECK(i == (u16)(101));
  return 0;
}
