// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i8 counter from -125 in steps of -1, 13 iterations, leaving at 2.
#include "loomcc-test.h"
static volatile u8 limit = 13;
int main(void) {
  i8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i8)(-125), n = 0; n < limit; i = (i8)(i + (-1)), n++) {
    if (n == 2) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 65285u);
  CHECK(iters == 2);
  return 0;
}
