// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u8 counter from 90 in steps of -1, 47 iterations, leaving at 40.
#include "loomcc-test.h"
static volatile u8 limit = 47;
int main(void) {
  u8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u8)(90), n = 0; n < limit; i = (u8)(i + (-1)), n++) {
    if (n == 40) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 2820u);
  CHECK(iters == 40);
  return 0;
}
