// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i16 counter from -129 in steps of 5, 31 iterations, leaving at 15.
#include "loomcc-test.h"
static volatile u8 limit = 31;
int main(void) {
  i16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i16)(-129), n = 0; n < limit; i = (i16)(i + (5)), n++) {
    if (n == 15) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 64126u);
  CHECK(iters == 15);
  return 0;
}
