// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u16 counter from 46 in steps of -2, 59 iterations, leaving at 50.
#include "loomcc-test.h"
static volatile u8 limit = 59;
int main(void) {
  u16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u16)(46), n = 0; n < limit; i = (u16)(i + (-2)), n++) {
    if (n == 50) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 65386u);
  CHECK(iters == 50);
  return 0;
}
