// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u16 counter from 94 in steps of 5, 31 iterations, leaving at 17.
#include "loomcc-test.h"
static volatile u8 limit = 31;
int main(void) {
  u16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u16)(94), n = 0; n < limit; i = (u16)(i + (5)), n++) {
    if (n == 17) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 2278u);
  CHECK(iters == 17);
  return 0;
}
