// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i16 counter from 106 in steps of -4, 45 iterations, leaving at 9.
#include "loomcc-test.h"
static volatile u8 limit = 45;
int main(void) {
  i16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i16)(106), n = 0; n < limit; i = (i16)(i + (-4)), n++) {
    if (n == 9) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 810u);
  CHECK(iters == 9);
  return 0;
}
