// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u16 counter from 65474 in steps of -4, 10 iterations, leaving at 0.
#include "loomcc-test.h"
static volatile u8 limit = 10;
int main(void) {
  u16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u16)(65474), n = 0; n < limit; i = (u16)(i + (-4)), n++) {
    if (n == 0) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 0u);
  CHECK(iters == 0);
  return 0;
}
