// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a i8 counter from 70 in steps of 1, 7 iterations.
#include "loomcc-test.h"
static volatile u8 limit = 7;
int main(void) {
  i8 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (i8)(70), n = 0; n < limit; i = (i8)(i + (1)), n++) {
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 511u);
  CHECK(iters == 7);
  CHECK(i == (i8)(77));
  return 0;
}
