// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A counted loop over a u16 counter from 120 in steps of 5, 18 iterations, leaving at 14.
#include "loomcc-test.h"
static volatile u8 limit = 18;
int main(void) {
  u16 i;
  u8 n;
  u16 acc = 0, iters = 0;
  for (i = (u16)(120), n = 0; n < limit; i = (u16)(i + (5)), n++) {
    if (n == 14) break;
    acc = (u16)(acc + (u16)i);
    iters++;
  }
  CHECK(acc == 2135u);
  CHECK(iters == 14);
  return 0;
}
