// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 7 fields of widths [3, 1, 2, 2, 1, 5, 2] packed into a u16 and unpacked.
#include "loomcc-test.h"
static const u8 f_rom[7] = { 4, 1, 2, 3, 0, 26, 3 };
static u8 f[7];
int main(void) {
  u8 i;
  u16 p;
  for (i = 0; i < 7; i++) f[i] = f_rom[i];
  p = (u16)(((u16)f[0] << 0) | ((u16)f[1] << 3) | ((u16)f[2] << 4) | ((u16)f[3] << 6) | ((u16)f[4] << 8) | ((u16)f[5] << 9) | ((u16)f[6] << 14));
  CHECK(p == 62700u);
  CHECK((u16)((p >> 0) & 7u) == 4);
  CHECK((u16)((p >> 3) & 1u) == 1);
  CHECK((u16)((p >> 4) & 3u) == 2);
  CHECK((u16)((p >> 6) & 3u) == 3);
  CHECK((u16)((p >> 8) & 1u) == 0);
  CHECK((u16)((p >> 9) & 31u) == 26);
  CHECK((u16)((p >> 14) & 3u) == 3);
  return 0;
}
