// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 8 fields of widths [2, 6, 5, 7, 7, 2, 2, 1] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[8] = { 1, 47, 21, 53, 0, 3, 1, 0 };
static u8 f[8];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 8; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 2) | ((u32)f[2] << 8) | ((u32)f[3] << 13) | ((u32)f[4] << 20) | ((u32)f[5] << 27) | ((u32)f[6] << 29) | ((u32)f[7] << 31));
  CHECK(p == (u32)939963837ULL);
  CHECK((u16)((p >> 0) & 3u) == 1);
  CHECK((u16)((p >> 2) & 63u) == 47);
  CHECK((u16)((p >> 8) & 31u) == 21);
  CHECK((u16)((p >> 13) & 127u) == 53);
  CHECK((u16)((p >> 20) & 127u) == 0);
  CHECK((u16)((p >> 27) & 3u) == 3);
  CHECK((u16)((p >> 29) & 3u) == 1);
  CHECK((u16)((p >> 31) & 1u) == 0);
  return 0;
}
