// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 6 fields of widths [2, 6, 1, 3, 3, 1] packed into a u16 and unpacked.
#include "loomcc-test.h"
static const u8 f_rom[6] = { 1, 36, 1, 1, 7, 0 };
static u8 f[6];
int main(void) {
  u8 i;
  u16 p;
  for (i = 0; i < 6; i++) f[i] = f_rom[i];
  p = (u16)(((u16)f[0] << 0) | ((u16)f[1] << 2) | ((u16)f[2] << 8) | ((u16)f[3] << 9) | ((u16)f[4] << 12) | ((u16)f[5] << 15));
  CHECK(p == 29585u);
  CHECK((u16)((p >> 0) & 3u) == 1);
  CHECK((u16)((p >> 2) & 63u) == 36);
  CHECK((u16)((p >> 8) & 1u) == 1);
  CHECK((u16)((p >> 9) & 7u) == 1);
  CHECK((u16)((p >> 12) & 7u) == 7);
  CHECK((u16)((p >> 15) & 1u) == 0);
  return 0;
}
