// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 8 fields of widths [7, 3, 5, 2, 3, 7, 3, 2] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[8] = { 21, 3, 27, 3, 4, 39, 6, 3 };
static u8 f[8];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 8; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 7) | ((u32)f[2] << 10) | ((u32)f[3] << 15) | ((u32)f[4] << 17) | ((u32)f[5] << 20) | ((u32)f[6] << 27) | ((u32)f[7] << 30));
  CHECK(p == (u32)4068076949ULL);
  CHECK((u16)((p >> 0) & 127u) == 21);
  CHECK((u16)((p >> 7) & 7u) == 3);
  CHECK((u16)((p >> 10) & 31u) == 27);
  CHECK((u16)((p >> 15) & 3u) == 3);
  CHECK((u16)((p >> 17) & 7u) == 4);
  CHECK((u16)((p >> 20) & 127u) == 39);
  CHECK((u16)((p >> 27) & 7u) == 6);
  CHECK((u16)((p >> 30) & 3u) == 3);
  return 0;
}
