// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 5 fields of widths [4, 6, 4, 1, 1] packed into a u16 and unpacked.
#include "loomcc-test.h"
static const u8 f_rom[5] = { 9, 14, 14, 0, 0 };
static u8 f[5];
int main(void) {
  u8 i;
  u16 p;
  for (i = 0; i < 5; i++) f[i] = f_rom[i];
  p = (u16)(((u16)f[0] << 0) | ((u16)f[1] << 4) | ((u16)f[2] << 10) | ((u16)f[3] << 14) | ((u16)f[4] << 15));
  CHECK(p == 14569u);
  CHECK((u16)((p >> 0) & 15u) == 9);
  CHECK((u16)((p >> 4) & 63u) == 14);
  CHECK((u16)((p >> 10) & 15u) == 14);
  CHECK((u16)((p >> 14) & 1u) == 0);
  CHECK((u16)((p >> 15) & 1u) == 0);
  return 0;
}
