// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 8 fields of widths [2, 5, 3, 5, 8, 4, 4, 1] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[8] = { 2, 31, 6, 28, 245, 5, 3, 0 };
static u8 f[8];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 8; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 2) | ((u32)f[2] << 7) | ((u32)f[3] << 10) | ((u32)f[4] << 15) | ((u32)f[5] << 23) | ((u32)f[6] << 27) | ((u32)f[7] << 31));
  CHECK(p == (u32)452653950ULL);
  CHECK((u16)((p >> 0) & 3u) == 2);
  CHECK((u16)((p >> 2) & 31u) == 31);
  CHECK((u16)((p >> 7) & 7u) == 6);
  CHECK((u16)((p >> 10) & 31u) == 28);
  CHECK((u16)((p >> 15) & 255u) == 245);
  CHECK((u16)((p >> 23) & 15u) == 5);
  CHECK((u16)((p >> 27) & 15u) == 3);
  CHECK((u16)((p >> 31) & 1u) == 0);
  return 0;
}
