// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, [2] = 102, 103 };
static const i16 a1[] = { [2] = 102, 103, 104, 105, 106, [12] = 112, [16] = 116 };
static const i16 a2[] = { [10] = 110, 111, [3] = 103, [11] = 111, 112, [2] = 102 };
static const i16 a3[] = { [6] = 106, 107, 108, 109, 110, 111, 112 };
static const i16 a4[] = { 100, [6] = 106, 107, [10] = 110, 111, [2] = 102, 103 };
static const i16 a5[] = { [0] = 100, 101, 102, [3] = 103 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 4);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 17);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 13);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 13);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 12);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 4);
