// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [1] = 101, 102, [3] = 103, [0] = 100, [16] = 116 };
static const i16 a1[] = { 100, 101, 102, [12] = 112, 113, 114 };
static const i16 a2[] = { 100, [18] = 118, [13] = 113, 114, [18] = 118, 119 };
static const i16 a3[] = { [15] = 115, 116, 117, 118 };
static const i16 a4[] = { [18] = 118, [3] = 103, [2] = 102, [3] = 103 };
static const i16 a5[] = { 100 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 17);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 15);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 20);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 19);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 19);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 1);
