// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [2] = 102, [13] = 113, 114, [11] = 111, [4] = 104 };
static const i16 a1[] = { [18] = 118, [14] = 114, [19] = 119, 120, [8] = 108, 109 };
static const i16 a2[] = { [7] = 107, [17] = 117, 118 };
static const i16 a3[] = { 100, 101 };
static const i16 a4[] = { [16] = 116, [13] = 113, [3] = 103, [15] = 115, 116, [14] = 114, [8] = 108 };
static const i16 a5[] = { [0] = 100, [13] = 113, 114, [7] = 107, 108, [19] = 119 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 15);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 21);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 19);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 2);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 17);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 20);
