// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, [16] = 116, [5] = 105, [4] = 104, [17] = 117, [10] = 110, 111 };
static const i16 a1[] = { 100, 101, 102, 103, 104 };
static const i16 a2[] = { 100, 101, [4] = 104, [2] = 102, 103, [6] = 106 };
static const i16 a3[] = { 100, 101, [18] = 118, 119, 120 };
static const i16 a4[] = { [6] = 106, [11] = 111, 112, [11] = 111, 112, [19] = 119 };
static const i16 a5[] = { 100, [1] = 101, 102, [9] = 109 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 18);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 5);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 7);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 21);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 20);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 10);
