// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [3] = 103 };
static const i16 a1[] = { 100 };
static const i16 a2[] = { [18] = 118, [18] = 118, [8] = 108, 109, 110, 111 };
static const i16 a3[] = { [6] = 106 };
static const i16 a4[] = { 100, 101, [16] = 116 };
static const i16 a5[] = { 100, [2] = 102, [0] = 100 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 4);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 1);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 19);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 7);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 17);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 3);
