// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100 };
static const i16 a1[] = { [18] = 118, 119, [15] = 115, 116, [2] = 102 };
static const i16 a2[] = { [3] = 103, 104 };
static const i16 a3[] = { 100 };
static const i16 a4[] = { 100, [15] = 115, [6] = 106, [18] = 118, 119 };
static const i16 a5[] = { [2] = 102, 103, [8] = 108 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 1);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 20);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 5);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 1);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 20);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 9);
