// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, [0] = 100, 101, 102 };
static const i16 a1[] = { 100, 101, 102, [11] = 111, [4] = 104 };
static const i16 a2[] = { 100, [0] = 100, [7] = 107, [19] = 119 };
static const i16 a3[] = { [13] = 113, [5] = 105, [10] = 110, [17] = 117 };
static const i16 a4[] = { 100, [7] = 107 };
static const i16 a5[] = { [2] = 102, [8] = 108 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 3);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 12);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 20);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 18);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 8);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 9);
