// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// i16 op i16 stored into a u8: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile i16 a, b;
static volatile u8 d;
int main(void) {
  a = 255; b = 2; d = a & b; CHECK(d == (u8)((2)));
  a = 2; b = 32767; d = a - b; CHECK(d == (u8)((-32765)));
  a = -1000; b = -256; d = a ^ b; CHECK(d == (u8)((792)));
  a = 0; b = -256; d = a & b; CHECK(d == (u8)((0)));
  a = 2; b = 255; d = a ^ b; CHECK(d == (u8)((253)));
  a = 2; b = -1; d = a ^ b; CHECK(d == (u8)((-3)));
  a = -1; b = -256; d = a + b; CHECK(d == (u8)((-257)));
  a = -1000; b = -256; d = a | b; CHECK(d == (u8)((-232)));
  a = -32767; b = 0; d = a & b; CHECK(d == (u8)((0)));
  a = -256; b = 0; d = a + b; CHECK(d == (u8)((-256)));
  a = -1; b = 255; d = a - b; CHECK(d == (u8)((-256)));
  a = -1; b = 0; d = a - b; CHECK(d == (u8)((-1)));
  a = -1000; b = -32767; d = a - b; CHECK(d == (u8)((31767)));
  a = 32767; b = 255; d = a & b; CHECK(d == (u8)((255)));
  a = 32767; b = -32767; d = a ^ b; CHECK(d == (u8)((-2)));
  a = -32768; b = 0; d = a - b; CHECK(d == (u8)((-32767 - 1)));
  a = -32767; b = 2; d = a ^ b; CHECK(d == (u8)((-32765)));
  a = -32767; b = -1; d = a - b; CHECK(d == (u8)((-32766)));
  a = 32767; b = 2; d = a & b; CHECK(d == (u8)((2)));
  a = -1000; b = -1000; d = a - b; CHECK(d == (u8)((0)));
  a = 255; b = -256; d = a & b; CHECK(d == (u8)((0)));
  a = -1; b = -1; d = a | b; CHECK(d == (u8)((-1)));
  return 0;
}
