// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// i16 op i16 stored into a i16: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile i16 a, b;
static volatile i16 d;
int main(void) {
  a = -1; b = -1; d = a + b; CHECK(d == (i16)((-2)));
  a = 0; b = 0; d = a | b; CHECK(d == (i16)((0)));
  a = -32767; b = -32767; d = a ^ b; CHECK(d == (i16)((0)));
  a = -1; b = 255; d = a - b; CHECK(d == (i16)((-256)));
  a = 2; b = 255; d = a - b; CHECK(d == (i16)((-253)));
  a = 32767; b = 0; d = a - b; CHECK(d == (i16)((32767)));
  a = 0; b = -256; d = a - b; CHECK(d == (i16)((256)));
  a = 2; b = 0; d = a - b; CHECK(d == (i16)((2)));
  a = 1; b = -1000; d = a | b; CHECK(d == (i16)((-999)));
  a = 32767; b = 32767; d = a - b; CHECK(d == (i16)((0)));
  a = -32768; b = 1; d = a | b; CHECK(d == (i16)((-32767)));
  a = -256; b = 1; d = a + b; CHECK(d == (i16)((-255)));
  a = 1; b = 32767; d = a & b; CHECK(d == (i16)((1)));
  a = 1; b = -256; d = a + b; CHECK(d == (i16)((-255)));
  a = -256; b = 2; d = a & b; CHECK(d == (i16)((0)));
  a = -32768; b = 255; d = a ^ b; CHECK(d == (i16)((-32513)));
  a = 2; b = 0; d = a ^ b; CHECK(d == (i16)((2)));
  a = 32767; b = 255; d = a & b; CHECK(d == (i16)((255)));
  a = 1; b = 32767; d = a - b; CHECK(d == (i16)((-32766)));
  a = -32768; b = -256; d = a - b; CHECK(d == (i16)((-32512)));
  a = 2; b = 32767; d = a | b; CHECK(d == (i16)((32767)));
  return 0;
}
