// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// u8 op u8 stored into a i8: the value converts (wraps) on assignment.
#include "loomcc-test.h"
static volatile u8 a, b;
static volatile i8 d;
int main(void) {
  a = 200; b = 100; d = a & b; CHECK(d == (i8)((64)));
  a = 255; b = 2; d = a | b; CHECK(d == (i8)((255)));
  a = 0; b = 2; d = a & b; CHECK(d == (i8)((0)));
  a = 1; b = 1; d = a ^ b; CHECK(d == (i8)((0)));
  a = 255; b = 255; d = a | b; CHECK(d == (i8)((255)));
  a = 128; b = 127; d = a + b; CHECK(d == (i8)((255)));
  a = 100; b = 255; d = a | b; CHECK(d == (i8)((255)));
  a = 127; b = 0; d = a & b; CHECK(d == (i8)((0)));
  a = 7; b = 7; d = a ^ b; CHECK(d == (i8)((0)));
  a = 128; b = 2; d = a - b; CHECK(d == (i8)((126)));
  a = 200; b = 7; d = a - b; CHECK(d == (i8)((193)));
  a = 1; b = 2; d = a & b; CHECK(d == (i8)((0)));
  a = 127; b = 255; d = a | b; CHECK(d == (i8)((255)));
  a = 1; b = 100; d = a | b; CHECK(d == (i8)((101)));
  a = 0; b = 1; d = a | b; CHECK(d == (i8)((1)));
  a = 1; b = 127; d = a + b; CHECK(d == (i8)((128)));
  a = 100; b = 0; d = a - b; CHECK(d == (i8)((100)));
  a = 2; b = 255; d = a | b; CHECK(d == (i8)((255)));
  a = 7; b = 200; d = a & b; CHECK(d == (i8)((0)));
  a = 200; b = 0; d = a + b; CHECK(d == (i8)((200)));
  a = 2; b = 2; d = a & b; CHECK(d == (i8)((2)));
  a = 127; b = 0; d = a & b; CHECK(d == (i8)((0)));
  a = 7; b = 0; d = a | b; CHECK(d == (i8)((7)));
  a = 1; b = 0; d = a + b; CHECK(d == (i8)((1)));
  return 0;
}
