// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.
#include "loomcc-test.h"
typedef struct { i16 x, y; u8 w, h; } Box;
static const Box boxes[8] = {
  { 170, -40, 14, 17 },
  { -52, -282, 60, 29 },
  { -203, 62, 34, 34 },
  { 101, 150, 42, 59 },
  { -205, -147, 21, 54 },
  { 54, 255, 15, 10 },
  { 138, -81, 61, 7 },
  { 234, 261, 57, 17 }
};
static u8 overlap(const Box *a, const Box *b) {
  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;
}
int main(void) {
  u8 a, b, hits = 0;
  for (a = 0; a < 8; a++)
    for (b = (u8)(a + 1); b < 8; b++)
      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));
  CHECK(hits == 0);
  CHECK(overlap(&boxes[1], &boxes[4]) == 0);
  CHECK(overlap(&boxes[1], &boxes[5]) == 0);
  CHECK(overlap(&boxes[1], &boxes[7]) == 0);
  CHECK(overlap(&boxes[2], &boxes[3]) == 0);
  CHECK(overlap(&boxes[3], &boxes[4]) == 0);
  CHECK(overlap(&boxes[3], &boxes[5]) == 0);
  CHECK(overlap(&boxes[3], &boxes[6]) == 0);
  CHECK(overlap(&boxes[5], &boxes[7]) == 0);
  return 0;
}
