// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.
#include "loomcc-test.h"
typedef struct { i16 x, y; u8 w, h; } Box;
static const Box boxes[8] = {
  { -37, 247, 41, 62 },
  { 81, -46, 42, 28 },
  { 129, -156, 2, 3 },
  { 34, -27, 39, 48 },
  { 217, 106, 17, 34 },
  { 227, 6, 40, 25 },
  { -62, 126, 28, 9 },
  { -202, 247, 7, 43 }
};
static u8 overlap(const Box *a, const Box *b) {
  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;
}
int main(void) {
  u8 a, b, hits = 0;
  for (a = 0; a < 8; a++)
    for (b = (u8)(a + 1); b < 8; b++)
      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));
  CHECK(hits == 0);
  CHECK(overlap(&boxes[0], &boxes[4]) == 0);
  CHECK(overlap(&boxes[1], &boxes[3]) == 0);
  CHECK(overlap(&boxes[1], &boxes[5]) == 0);
  CHECK(overlap(&boxes[1], &boxes[7]) == 0);
  CHECK(overlap(&boxes[2], &boxes[3]) == 0);
  CHECK(overlap(&boxes[2], &boxes[7]) == 0);
  return 0;
}
