// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S51_0 {
  u8 m0[1];
  const i16 * m1;
  u8 * m2[2];
  u8 m3;
  i16 m4;
  u8 * m5;
};
struct S51_1 {
  u8 * m0;
  int m1;
  i16 m2[1];
  i32 m3;
  void (*m4)(void);
  struct S51_0 m5;
};
struct S51_2 {
  i8 m0;
  i16 m1;
  int m2;
  struct S51_0 m3;
  int m4[3];
  int m5[2];
};
struct S51_3 {
  i8 m0;
};
struct S51_4 {
  struct S51_1 m0;
  struct S51_3 m1;
  u16 m2[1];
  int m3[5];
  int m4;
  u8 m5;
};
struct S51_5 {
  const i16 * m0;
};
STATIC_CHECK(sizeof(struct S51_0) == 24);
STATIC_CHECK(sizeof(struct S51_0[3]) == 72);
STATIC_CHECK(offsetof(struct S51_0, m0) == 0);
STATIC_CHECK(offsetof(struct S51_0, m1) == 4);
STATIC_CHECK(offsetof(struct S51_0, m2) == 8);
STATIC_CHECK(offsetof(struct S51_0, m3) == 16);
STATIC_CHECK(offsetof(struct S51_0, m4) == 18);
STATIC_CHECK(offsetof(struct S51_0, m5) == 20);
STATIC_CHECK(sizeof(struct S51_1) == 40);
STATIC_CHECK(sizeof(struct S51_1[3]) == 120);
STATIC_CHECK(offsetof(struct S51_1, m0) == 0);
STATIC_CHECK(offsetof(struct S51_1, m1) == 4);
STATIC_CHECK(offsetof(struct S51_1, m2) == 6);
STATIC_CHECK(offsetof(struct S51_1, m3) == 8);
STATIC_CHECK(offsetof(struct S51_1, m4) == 12);
STATIC_CHECK(offsetof(struct S51_1, m5) == 16);
STATIC_CHECK(sizeof(struct S51_2) == 44);
STATIC_CHECK(sizeof(struct S51_2[3]) == 132);
STATIC_CHECK(offsetof(struct S51_2, m0) == 0);
STATIC_CHECK(offsetof(struct S51_2, m1) == 2);
STATIC_CHECK(offsetof(struct S51_2, m2) == 4);
STATIC_CHECK(offsetof(struct S51_2, m3) == 8);
STATIC_CHECK(offsetof(struct S51_2, m4) == 32);
STATIC_CHECK(offsetof(struct S51_2, m5) == 38);
STATIC_CHECK(sizeof(struct S51_3) == 1);
STATIC_CHECK(sizeof(struct S51_3[3]) == 3);
STATIC_CHECK(offsetof(struct S51_3, m0) == 0);
STATIC_CHECK(sizeof(struct S51_4) == 60);
STATIC_CHECK(sizeof(struct S51_4[3]) == 180);
STATIC_CHECK(offsetof(struct S51_4, m0) == 0);
STATIC_CHECK(offsetof(struct S51_4, m1) == 40);
STATIC_CHECK(offsetof(struct S51_4, m2) == 42);
STATIC_CHECK(offsetof(struct S51_4, m3) == 44);
STATIC_CHECK(offsetof(struct S51_4, m4) == 54);
STATIC_CHECK(offsetof(struct S51_4, m5) == 56);
STATIC_CHECK(sizeof(struct S51_5) == 4);
STATIC_CHECK(sizeof(struct S51_5[3]) == 12);
STATIC_CHECK(offsetof(struct S51_5, m0) == 0);
