// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S25_0 {
  u16 m0;
  i8 m1;
};
struct S25_1 {
  const i16 * m0;
  i8 m1;
};
struct S25_2 {
  u16 m0[5];
};
struct S25_3 {
  int m0;
  u16 m1;
};
struct S25_4 {
  i16 m0;
  struct S25_0 m1[3];
  struct S25_2 m2;
  u8 m3;
  struct S25_0 m4;
  struct S25_3 m5;
};
struct S25_5 {
  void (*m0[5])(void);
  u16 m1;
};
STATIC_CHECK(sizeof(struct S25_0) == 4);
STATIC_CHECK(sizeof(struct S25_0[3]) == 12);
STATIC_CHECK(offsetof(struct S25_0, m0) == 0);
STATIC_CHECK(offsetof(struct S25_0, m1) == 2);
STATIC_CHECK(sizeof(struct S25_1) == 8);
STATIC_CHECK(sizeof(struct S25_1[3]) == 24);
STATIC_CHECK(offsetof(struct S25_1, m0) == 0);
STATIC_CHECK(offsetof(struct S25_1, m1) == 4);
STATIC_CHECK(sizeof(struct S25_2) == 10);
STATIC_CHECK(sizeof(struct S25_2[3]) == 30);
STATIC_CHECK(offsetof(struct S25_2, m0) == 0);
STATIC_CHECK(sizeof(struct S25_3) == 4);
STATIC_CHECK(sizeof(struct S25_3[3]) == 12);
STATIC_CHECK(offsetof(struct S25_3, m0) == 0);
STATIC_CHECK(offsetof(struct S25_3, m1) == 2);
STATIC_CHECK(sizeof(struct S25_4) == 34);
STATIC_CHECK(sizeof(struct S25_4[3]) == 102);
STATIC_CHECK(offsetof(struct S25_4, m0) == 0);
STATIC_CHECK(offsetof(struct S25_4, m1) == 2);
STATIC_CHECK(offsetof(struct S25_4, m2) == 14);
STATIC_CHECK(offsetof(struct S25_4, m3) == 24);
STATIC_CHECK(offsetof(struct S25_4, m4) == 26);
STATIC_CHECK(offsetof(struct S25_4, m5) == 30);
STATIC_CHECK(sizeof(struct S25_5) == 24);
STATIC_CHECK(sizeof(struct S25_5[3]) == 72);
STATIC_CHECK(offsetof(struct S25_5, m0) == 0);
STATIC_CHECK(offsetof(struct S25_5, m1) == 20);
