// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S57_0 {
  i16 m0;
};
struct S57_1 {
  i8 m0;
  i16 m1;
  u16 m2;
  struct S57_0 m3[2];
};
struct S57_2 {
  u16 m0[2];
  u8 * m1;
  i32 m2[2];
};
struct S57_3 {
  struct S57_2 m0;
  u16 m1[2];
  struct S57_2 m2;
  struct S57_2 m3[2];
  i16 m4[5];
};
struct S57_4 {
  int m0[3];
  u8 m1;
  u8 * m2;
  u8 m3[2];
  struct S57_3 m4;
};
struct S57_5 {
  u8 * m0;
  u8 * m1;
  const i16 * m2;
  u16 m3[5];
  struct S57_0 m4;
};
STATIC_CHECK(sizeof(struct S57_0) == 2);
STATIC_CHECK(sizeof(struct S57_0[3]) == 6);
STATIC_CHECK(offsetof(struct S57_0, m0) == 0);
STATIC_CHECK(sizeof(struct S57_1) == 10);
STATIC_CHECK(sizeof(struct S57_1[3]) == 30);
STATIC_CHECK(offsetof(struct S57_1, m0) == 0);
STATIC_CHECK(offsetof(struct S57_1, m1) == 2);
STATIC_CHECK(offsetof(struct S57_1, m2) == 4);
STATIC_CHECK(offsetof(struct S57_1, m3) == 6);
STATIC_CHECK(sizeof(struct S57_2) == 16);
STATIC_CHECK(sizeof(struct S57_2[3]) == 48);
STATIC_CHECK(offsetof(struct S57_2, m0) == 0);
STATIC_CHECK(offsetof(struct S57_2, m1) == 4);
STATIC_CHECK(offsetof(struct S57_2, m2) == 8);
STATIC_CHECK(sizeof(struct S57_3) == 80);
STATIC_CHECK(sizeof(struct S57_3[3]) == 240);
STATIC_CHECK(offsetof(struct S57_3, m0) == 0);
STATIC_CHECK(offsetof(struct S57_3, m1) == 16);
STATIC_CHECK(offsetof(struct S57_3, m2) == 20);
STATIC_CHECK(offsetof(struct S57_3, m3) == 36);
STATIC_CHECK(offsetof(struct S57_3, m4) == 68);
STATIC_CHECK(sizeof(struct S57_4) == 96);
STATIC_CHECK(sizeof(struct S57_4[3]) == 288);
STATIC_CHECK(offsetof(struct S57_4, m0) == 0);
STATIC_CHECK(offsetof(struct S57_4, m1) == 6);
STATIC_CHECK(offsetof(struct S57_4, m2) == 8);
STATIC_CHECK(offsetof(struct S57_4, m3) == 12);
STATIC_CHECK(offsetof(struct S57_4, m4) == 16);
STATIC_CHECK(sizeof(struct S57_5) == 24);
STATIC_CHECK(sizeof(struct S57_5[3]) == 72);
STATIC_CHECK(offsetof(struct S57_5, m0) == 0);
STATIC_CHECK(offsetof(struct S57_5, m1) == 4);
STATIC_CHECK(offsetof(struct S57_5, m2) == 8);
STATIC_CHECK(offsetof(struct S57_5, m3) == 12);
STATIC_CHECK(offsetof(struct S57_5, m4) == 22);
