// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S55_0 {
  i32 m0[1];
  u8 m1[3];
  void (*m2[3])(void);
  void (*m3)(void);
  i16 m4[2];
  const i16 * m5;
};
struct S55_1 {
  u8 * m0;
  void (*m1[1])(void);
  i8 m2;
  struct S55_0 m3;
  struct S55_0 m4[2];
  i16 m5;
};
struct S55_2 {
  i16 m0;
  i32 m1[3];
  i8 m2;
  i32 m3;
  struct S55_0 m4;
};
struct S55_3 {
  void (*m0[3])(void);
  i16 m1;
  int m2;
};
struct S55_4 {
  i16 m0[1];
  const i16 * m1;
  struct S55_1 m2[2];
};
struct S55_5 {
  struct S55_0 m0[2];
  const i16 * m1;
  int m2;
  struct S55_0 m3[3];
};
STATIC_CHECK(sizeof(struct S55_0) == 32);
STATIC_CHECK(sizeof(struct S55_0[3]) == 96);
STATIC_CHECK(offsetof(struct S55_0, m0) == 0);
STATIC_CHECK(offsetof(struct S55_0, m1) == 4);
STATIC_CHECK(offsetof(struct S55_0, m2) == 8);
STATIC_CHECK(offsetof(struct S55_0, m3) == 20);
STATIC_CHECK(offsetof(struct S55_0, m4) == 24);
STATIC_CHECK(offsetof(struct S55_0, m5) == 28);
STATIC_CHECK(sizeof(struct S55_1) == 112);
STATIC_CHECK(sizeof(struct S55_1[3]) == 336);
STATIC_CHECK(offsetof(struct S55_1, m0) == 0);
STATIC_CHECK(offsetof(struct S55_1, m1) == 4);
STATIC_CHECK(offsetof(struct S55_1, m2) == 8);
STATIC_CHECK(offsetof(struct S55_1, m3) == 12);
STATIC_CHECK(offsetof(struct S55_1, m4) == 44);
STATIC_CHECK(offsetof(struct S55_1, m5) == 108);
STATIC_CHECK(sizeof(struct S55_2) == 56);
STATIC_CHECK(sizeof(struct S55_2[3]) == 168);
STATIC_CHECK(offsetof(struct S55_2, m0) == 0);
STATIC_CHECK(offsetof(struct S55_2, m1) == 4);
STATIC_CHECK(offsetof(struct S55_2, m2) == 16);
STATIC_CHECK(offsetof(struct S55_2, m3) == 20);
STATIC_CHECK(offsetof(struct S55_2, m4) == 24);
STATIC_CHECK(sizeof(struct S55_3) == 16);
STATIC_CHECK(sizeof(struct S55_3[3]) == 48);
STATIC_CHECK(offsetof(struct S55_3, m0) == 0);
STATIC_CHECK(offsetof(struct S55_3, m1) == 12);
STATIC_CHECK(offsetof(struct S55_3, m2) == 14);
STATIC_CHECK(sizeof(struct S55_4) == 232);
STATIC_CHECK(sizeof(struct S55_4[3]) == 696);
STATIC_CHECK(offsetof(struct S55_4, m0) == 0);
STATIC_CHECK(offsetof(struct S55_4, m1) == 4);
STATIC_CHECK(offsetof(struct S55_4, m2) == 8);
STATIC_CHECK(sizeof(struct S55_5) == 168);
STATIC_CHECK(sizeof(struct S55_5[3]) == 504);
STATIC_CHECK(offsetof(struct S55_5, m0) == 0);
STATIC_CHECK(offsetof(struct S55_5, m1) == 64);
STATIC_CHECK(offsetof(struct S55_5, m2) == 68);
STATIC_CHECK(offsetof(struct S55_5, m3) == 72);
