// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S33_0 {
  i16 m0[1];
};
struct S33_1 {
  struct S33_0 m0[2];
  u8 * m1[5];
  i32 m2[3];
  u8 * m3;
};
struct S33_2 {
  const i16 * m0;
};
struct S33_3 {
  i8 m0;
  i8 m1;
  struct S33_2 m2;
  void (*m3)(void);
};
struct S33_4 {
  struct S33_1 m0;
  i16 m1[2];
  u8 * m2;
  i16 m3;
  u8 * m4;
};
struct S33_5 {
  struct S33_2 m0;
  i8 m1;
};
STATIC_CHECK(sizeof(struct S33_0) == 2);
STATIC_CHECK(sizeof(struct S33_0[3]) == 6);
STATIC_CHECK(offsetof(struct S33_0, m0) == 0);
STATIC_CHECK(sizeof(struct S33_1) == 40);
STATIC_CHECK(sizeof(struct S33_1[3]) == 120);
STATIC_CHECK(offsetof(struct S33_1, m0) == 0);
STATIC_CHECK(offsetof(struct S33_1, m1) == 4);
STATIC_CHECK(offsetof(struct S33_1, m2) == 24);
STATIC_CHECK(offsetof(struct S33_1, m3) == 36);
STATIC_CHECK(sizeof(struct S33_2) == 4);
STATIC_CHECK(sizeof(struct S33_2[3]) == 12);
STATIC_CHECK(offsetof(struct S33_2, m0) == 0);
STATIC_CHECK(sizeof(struct S33_3) == 12);
STATIC_CHECK(sizeof(struct S33_3[3]) == 36);
STATIC_CHECK(offsetof(struct S33_3, m0) == 0);
STATIC_CHECK(offsetof(struct S33_3, m1) == 1);
STATIC_CHECK(offsetof(struct S33_3, m2) == 4);
STATIC_CHECK(offsetof(struct S33_3, m3) == 8);
STATIC_CHECK(sizeof(struct S33_4) == 56);
STATIC_CHECK(sizeof(struct S33_4[3]) == 168);
STATIC_CHECK(offsetof(struct S33_4, m0) == 0);
STATIC_CHECK(offsetof(struct S33_4, m1) == 40);
STATIC_CHECK(offsetof(struct S33_4, m2) == 44);
STATIC_CHECK(offsetof(struct S33_4, m3) == 48);
STATIC_CHECK(offsetof(struct S33_4, m4) == 52);
STATIC_CHECK(sizeof(struct S33_5) == 8);
STATIC_CHECK(sizeof(struct S33_5[3]) == 24);
STATIC_CHECK(offsetof(struct S33_5, m0) == 0);
STATIC_CHECK(offsetof(struct S33_5, m1) == 4);
