// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S58_0 {
  int m0;
  int m1;
  i8 m2;
  i32 m3;
  u8 * m4;
};
struct S58_1 {
  struct S58_0 m0;
};
struct S58_2 {
  struct S58_0 m0;
  const i16 * m1;
  int m2;
  i16 m3;
  u8 * m4;
  i8 m5[2];
};
struct S58_3 {
  u8 * m0;
};
struct S58_4 {
  i8 m0;
  i16 m1;
  struct S58_1 m2;
  u16 m3;
  struct S58_3 m4;
  struct S58_1 m5[2];
};
struct S58_5 {
  u16 m0;
  const i16 * m1[2];
};
STATIC_CHECK(sizeof(struct S58_0) == 16);
STATIC_CHECK(sizeof(struct S58_0[3]) == 48);
STATIC_CHECK(offsetof(struct S58_0, m0) == 0);
STATIC_CHECK(offsetof(struct S58_0, m1) == 2);
STATIC_CHECK(offsetof(struct S58_0, m2) == 4);
STATIC_CHECK(offsetof(struct S58_0, m3) == 8);
STATIC_CHECK(offsetof(struct S58_0, m4) == 12);
STATIC_CHECK(sizeof(struct S58_1) == 16);
STATIC_CHECK(sizeof(struct S58_1[3]) == 48);
STATIC_CHECK(offsetof(struct S58_1, m0) == 0);
STATIC_CHECK(sizeof(struct S58_2) == 32);
STATIC_CHECK(sizeof(struct S58_2[3]) == 96);
STATIC_CHECK(offsetof(struct S58_2, m0) == 0);
STATIC_CHECK(offsetof(struct S58_2, m1) == 16);
STATIC_CHECK(offsetof(struct S58_2, m2) == 20);
STATIC_CHECK(offsetof(struct S58_2, m3) == 22);
STATIC_CHECK(offsetof(struct S58_2, m4) == 24);
STATIC_CHECK(offsetof(struct S58_2, m5) == 28);
STATIC_CHECK(sizeof(struct S58_3) == 4);
STATIC_CHECK(sizeof(struct S58_3[3]) == 12);
STATIC_CHECK(offsetof(struct S58_3, m0) == 0);
STATIC_CHECK(sizeof(struct S58_4) == 60);
STATIC_CHECK(sizeof(struct S58_4[3]) == 180);
STATIC_CHECK(offsetof(struct S58_4, m0) == 0);
STATIC_CHECK(offsetof(struct S58_4, m1) == 2);
STATIC_CHECK(offsetof(struct S58_4, m2) == 4);
STATIC_CHECK(offsetof(struct S58_4, m3) == 20);
STATIC_CHECK(offsetof(struct S58_4, m4) == 24);
STATIC_CHECK(offsetof(struct S58_4, m5) == 28);
STATIC_CHECK(sizeof(struct S58_5) == 12);
STATIC_CHECK(sizeof(struct S58_5[3]) == 36);
STATIC_CHECK(offsetof(struct S58_5, m0) == 0);
STATIC_CHECK(offsetof(struct S58_5, m1) == 4);
