// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S40_0 {
  u16 m0;
  const i16 * m1;
  i16 m2[3];
  i32 m3;
};
struct S40_1 {
  i16 m0;
  i32 m1;
  u8 m2[1];
  int m3;
  int m4;
  struct S40_0 m5;
};
struct S40_2 {
  i8 m0[1];
  int m1;
  struct S40_1 m2[2];
  struct S40_0 m3;
  u16 m4;
  struct S40_1 m5[2];
};
struct S40_3 {
  i32 m0;
  i32 m1;
  struct S40_2 m2[2];
};
struct S40_4 {
  void (*m0[3])(void);
};
struct S40_5 {
  u8 * m0[1];
  i32 m1;
  i32 m2;
  i8 m3[2];
};
STATIC_CHECK(sizeof(struct S40_0) == 20);
STATIC_CHECK(sizeof(struct S40_0[3]) == 60);
STATIC_CHECK(offsetof(struct S40_0, m0) == 0);
STATIC_CHECK(offsetof(struct S40_0, m1) == 4);
STATIC_CHECK(offsetof(struct S40_0, m2) == 8);
STATIC_CHECK(offsetof(struct S40_0, m3) == 16);
STATIC_CHECK(sizeof(struct S40_1) == 36);
STATIC_CHECK(sizeof(struct S40_1[3]) == 108);
STATIC_CHECK(offsetof(struct S40_1, m0) == 0);
STATIC_CHECK(offsetof(struct S40_1, m1) == 4);
STATIC_CHECK(offsetof(struct S40_1, m2) == 8);
STATIC_CHECK(offsetof(struct S40_1, m3) == 10);
STATIC_CHECK(offsetof(struct S40_1, m4) == 12);
STATIC_CHECK(offsetof(struct S40_1, m5) == 16);
STATIC_CHECK(sizeof(struct S40_2) == 172);
STATIC_CHECK(sizeof(struct S40_2[3]) == 516);
STATIC_CHECK(offsetof(struct S40_2, m0) == 0);
STATIC_CHECK(offsetof(struct S40_2, m1) == 2);
STATIC_CHECK(offsetof(struct S40_2, m2) == 4);
STATIC_CHECK(offsetof(struct S40_2, m3) == 76);
STATIC_CHECK(offsetof(struct S40_2, m4) == 96);
STATIC_CHECK(offsetof(struct S40_2, m5) == 100);
STATIC_CHECK(sizeof(struct S40_3) == 352);
STATIC_CHECK(sizeof(struct S40_3[3]) == 1056);
STATIC_CHECK(offsetof(struct S40_3, m0) == 0);
STATIC_CHECK(offsetof(struct S40_3, m1) == 4);
STATIC_CHECK(offsetof(struct S40_3, m2) == 8);
STATIC_CHECK(sizeof(struct S40_4) == 12);
STATIC_CHECK(sizeof(struct S40_4[3]) == 36);
STATIC_CHECK(offsetof(struct S40_4, m0) == 0);
STATIC_CHECK(sizeof(struct S40_5) == 16);
STATIC_CHECK(sizeof(struct S40_5[3]) == 48);
STATIC_CHECK(offsetof(struct S40_5, m0) == 0);
STATIC_CHECK(offsetof(struct S40_5, m1) == 4);
STATIC_CHECK(offsetof(struct S40_5, m2) == 8);
STATIC_CHECK(offsetof(struct S40_5, m3) == 12);
