// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S24_0 {
  const i16 * m0[1];
  u8 m1;
  void (*m2)(void);
  void (*m3)(void);
  int m4;
};
struct S24_1 {
  struct S24_0 m0;
  i8 m1[5];
};
struct S24_2 {
  int m0[2];
  struct S24_1 m1;
  void (*m2[1])(void);
  u16 m3[5];
  struct S24_1 m4;
};
struct S24_3 {
  u8 m0[3];
  u8 * m1;
};
struct S24_4 {
  const i16 * m0[5];
  struct S24_2 m1;
  struct S24_1 m2[2];
  i8 m3;
};
struct S24_5 {
  int m0;
  const i16 * m1;
  u8 * m2;
  int m3;
  const i16 * m4;
  u8 m5;
};
STATIC_CHECK(sizeof(struct S24_0) == 20);
STATIC_CHECK(sizeof(struct S24_0[3]) == 60);
STATIC_CHECK(offsetof(struct S24_0, m0) == 0);
STATIC_CHECK(offsetof(struct S24_0, m1) == 4);
STATIC_CHECK(offsetof(struct S24_0, m2) == 8);
STATIC_CHECK(offsetof(struct S24_0, m3) == 12);
STATIC_CHECK(offsetof(struct S24_0, m4) == 16);
STATIC_CHECK(sizeof(struct S24_1) == 28);
STATIC_CHECK(sizeof(struct S24_1[3]) == 84);
STATIC_CHECK(offsetof(struct S24_1, m0) == 0);
STATIC_CHECK(offsetof(struct S24_1, m1) == 20);
STATIC_CHECK(sizeof(struct S24_2) == 76);
STATIC_CHECK(sizeof(struct S24_2[3]) == 228);
STATIC_CHECK(offsetof(struct S24_2, m0) == 0);
STATIC_CHECK(offsetof(struct S24_2, m1) == 4);
STATIC_CHECK(offsetof(struct S24_2, m2) == 32);
STATIC_CHECK(offsetof(struct S24_2, m3) == 36);
STATIC_CHECK(offsetof(struct S24_2, m4) == 48);
STATIC_CHECK(sizeof(struct S24_3) == 8);
STATIC_CHECK(sizeof(struct S24_3[3]) == 24);
STATIC_CHECK(offsetof(struct S24_3, m0) == 0);
STATIC_CHECK(offsetof(struct S24_3, m1) == 4);
STATIC_CHECK(sizeof(struct S24_4) == 156);
STATIC_CHECK(sizeof(struct S24_4[3]) == 468);
STATIC_CHECK(offsetof(struct S24_4, m0) == 0);
STATIC_CHECK(offsetof(struct S24_4, m1) == 20);
STATIC_CHECK(offsetof(struct S24_4, m2) == 96);
STATIC_CHECK(offsetof(struct S24_4, m3) == 152);
STATIC_CHECK(sizeof(struct S24_5) == 24);
STATIC_CHECK(sizeof(struct S24_5[3]) == 72);
STATIC_CHECK(offsetof(struct S24_5, m0) == 0);
STATIC_CHECK(offsetof(struct S24_5, m1) == 4);
STATIC_CHECK(offsetof(struct S24_5, m2) == 8);
STATIC_CHECK(offsetof(struct S24_5, m3) == 12);
STATIC_CHECK(offsetof(struct S24_5, m4) == 16);
STATIC_CHECK(offsetof(struct S24_5, m5) == 20);
