// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S45_0 {
  i16 m0;
  i8 m1;
};
struct S45_1 {
  void (*m0)(void);
};
struct S45_2 {
  struct S45_0 m0;
  i32 m1;
  void (*m2[2])(void);
};
struct S45_3 {
  const i16 * m0;
  struct S45_1 m1;
  const i16 * m2[5];
  i16 m3;
};
struct S45_4 {
  u16 m0;
  struct S45_2 m1;
  i16 m2;
  i8 m3;
};
struct S45_5 {
  u8 m0;
};
STATIC_CHECK(sizeof(struct S45_0) == 4);
STATIC_CHECK(sizeof(struct S45_0[3]) == 12);
STATIC_CHECK(offsetof(struct S45_0, m0) == 0);
STATIC_CHECK(offsetof(struct S45_0, m1) == 2);
STATIC_CHECK(sizeof(struct S45_1) == 4);
STATIC_CHECK(sizeof(struct S45_1[3]) == 12);
STATIC_CHECK(offsetof(struct S45_1, m0) == 0);
STATIC_CHECK(sizeof(struct S45_2) == 16);
STATIC_CHECK(sizeof(struct S45_2[3]) == 48);
STATIC_CHECK(offsetof(struct S45_2, m0) == 0);
STATIC_CHECK(offsetof(struct S45_2, m1) == 4);
STATIC_CHECK(offsetof(struct S45_2, m2) == 8);
STATIC_CHECK(sizeof(struct S45_3) == 32);
STATIC_CHECK(sizeof(struct S45_3[3]) == 96);
STATIC_CHECK(offsetof(struct S45_3, m0) == 0);
STATIC_CHECK(offsetof(struct S45_3, m1) == 4);
STATIC_CHECK(offsetof(struct S45_3, m2) == 8);
STATIC_CHECK(offsetof(struct S45_3, m3) == 28);
STATIC_CHECK(sizeof(struct S45_4) == 24);
STATIC_CHECK(sizeof(struct S45_4[3]) == 72);
STATIC_CHECK(offsetof(struct S45_4, m0) == 0);
STATIC_CHECK(offsetof(struct S45_4, m1) == 4);
STATIC_CHECK(offsetof(struct S45_4, m2) == 20);
STATIC_CHECK(offsetof(struct S45_4, m3) == 22);
STATIC_CHECK(sizeof(struct S45_5) == 1);
STATIC_CHECK(sizeof(struct S45_5[3]) == 3);
STATIC_CHECK(offsetof(struct S45_5, m0) == 0);
