// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S16_0 {
  i32 m0;
  i16 m1;
  u16 m2[1];
};
struct S16_1 {
  i8 m0[2];
  i8 m1;
  const i16 * m2;
};
struct S16_2 {
  struct S16_1 m0[2];
  struct S16_1 m1[3];
  u16 m2[5];
  u8 m3[3];
  struct S16_0 m4;
  u8 * m5;
};
struct S16_3 {
  i16 m0;
  struct S16_0 m1;
  u8 * m2;
  u8 m3;
};
struct S16_4 {
  void (*m0[1])(void);
  i32 m1[2];
  int m2[3];
  struct S16_0 m3;
  u8 m4[2];
};
struct S16_5 {
  struct S16_1 m0;
  u16 m1;
  void (*m2)(void);
  struct S16_4 m3[2];
  u16 m4;
  void (*m5)(void);
};
STATIC_CHECK(sizeof(struct S16_0) == 8);
STATIC_CHECK(sizeof(struct S16_0[3]) == 24);
STATIC_CHECK(offsetof(struct S16_0, m0) == 0);
STATIC_CHECK(offsetof(struct S16_0, m1) == 4);
STATIC_CHECK(offsetof(struct S16_0, m2) == 6);
STATIC_CHECK(sizeof(struct S16_1) == 8);
STATIC_CHECK(sizeof(struct S16_1[3]) == 24);
STATIC_CHECK(offsetof(struct S16_1, m0) == 0);
STATIC_CHECK(offsetof(struct S16_1, m1) == 2);
STATIC_CHECK(offsetof(struct S16_1, m2) == 4);
STATIC_CHECK(sizeof(struct S16_2) == 68);
STATIC_CHECK(sizeof(struct S16_2[3]) == 204);
STATIC_CHECK(offsetof(struct S16_2, m0) == 0);
STATIC_CHECK(offsetof(struct S16_2, m1) == 16);
STATIC_CHECK(offsetof(struct S16_2, m2) == 40);
STATIC_CHECK(offsetof(struct S16_2, m3) == 50);
STATIC_CHECK(offsetof(struct S16_2, m4) == 56);
STATIC_CHECK(offsetof(struct S16_2, m5) == 64);
STATIC_CHECK(sizeof(struct S16_3) == 20);
STATIC_CHECK(sizeof(struct S16_3[3]) == 60);
STATIC_CHECK(offsetof(struct S16_3, m0) == 0);
STATIC_CHECK(offsetof(struct S16_3, m1) == 4);
STATIC_CHECK(offsetof(struct S16_3, m2) == 12);
STATIC_CHECK(offsetof(struct S16_3, m3) == 16);
STATIC_CHECK(sizeof(struct S16_4) == 32);
STATIC_CHECK(sizeof(struct S16_4[3]) == 96);
STATIC_CHECK(offsetof(struct S16_4, m0) == 0);
STATIC_CHECK(offsetof(struct S16_4, m1) == 4);
STATIC_CHECK(offsetof(struct S16_4, m2) == 12);
STATIC_CHECK(offsetof(struct S16_4, m3) == 20);
STATIC_CHECK(offsetof(struct S16_4, m4) == 28);
STATIC_CHECK(sizeof(struct S16_5) == 88);
STATIC_CHECK(sizeof(struct S16_5[3]) == 264);
STATIC_CHECK(offsetof(struct S16_5, m0) == 0);
STATIC_CHECK(offsetof(struct S16_5, m1) == 8);
STATIC_CHECK(offsetof(struct S16_5, m2) == 12);
STATIC_CHECK(offsetof(struct S16_5, m3) == 16);
STATIC_CHECK(offsetof(struct S16_5, m4) == 80);
STATIC_CHECK(offsetof(struct S16_5, m5) == 84);
