// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit
// integers 4-aligned inside structs, size rounded to the largest alignment):
// the layout Loom's hand-written assembly reads by offset.
// loomcc-ref: tcc
#include <stddef.h>
#include "loomcc-test.h"
struct S28_0 {
  const i16 * m0[3];
  i8 m1[1];
  i16 m2;
  i32 m3;
  i32 m4;
  u8 * m5;
};
struct S28_1 {
  void (*m0)(void);
  const i16 * m1;
  const i16 * m2[5];
  i8 m3[3];
  int m4;
  i32 m5;
};
struct S28_2 {
  i32 m0;
  u8 * m1[2];
  int m2;
  u8 * m3[3];
  struct S28_0 m4;
  const i16 * m5;
};
struct S28_3 {
  i8 m0;
  i8 m1[1];
  i32 m2[5];
  void (*m3)(void);
};
struct S28_4 {
  i8 m0;
  u16 m1;
  u8 * m2[1];
};
struct S28_5 {
  u16 m0;
  struct S28_4 m1[2];
  i16 m2;
  u8 * m3[1];
  i8 m4[2];
  void (*m5)(void);
};
STATIC_CHECK(sizeof(struct S28_0) == 28);
STATIC_CHECK(sizeof(struct S28_0[3]) == 84);
STATIC_CHECK(offsetof(struct S28_0, m0) == 0);
STATIC_CHECK(offsetof(struct S28_0, m1) == 12);
STATIC_CHECK(offsetof(struct S28_0, m2) == 14);
STATIC_CHECK(offsetof(struct S28_0, m3) == 16);
STATIC_CHECK(offsetof(struct S28_0, m4) == 20);
STATIC_CHECK(offsetof(struct S28_0, m5) == 24);
STATIC_CHECK(sizeof(struct S28_1) == 40);
STATIC_CHECK(sizeof(struct S28_1[3]) == 120);
STATIC_CHECK(offsetof(struct S28_1, m0) == 0);
STATIC_CHECK(offsetof(struct S28_1, m1) == 4);
STATIC_CHECK(offsetof(struct S28_1, m2) == 8);
STATIC_CHECK(offsetof(struct S28_1, m3) == 28);
STATIC_CHECK(offsetof(struct S28_1, m4) == 32);
STATIC_CHECK(offsetof(struct S28_1, m5) == 36);
STATIC_CHECK(sizeof(struct S28_2) == 60);
STATIC_CHECK(sizeof(struct S28_2[3]) == 180);
STATIC_CHECK(offsetof(struct S28_2, m0) == 0);
STATIC_CHECK(offsetof(struct S28_2, m1) == 4);
STATIC_CHECK(offsetof(struct S28_2, m2) == 12);
STATIC_CHECK(offsetof(struct S28_2, m3) == 16);
STATIC_CHECK(offsetof(struct S28_2, m4) == 28);
STATIC_CHECK(offsetof(struct S28_2, m5) == 56);
STATIC_CHECK(sizeof(struct S28_3) == 28);
STATIC_CHECK(sizeof(struct S28_3[3]) == 84);
STATIC_CHECK(offsetof(struct S28_3, m0) == 0);
STATIC_CHECK(offsetof(struct S28_3, m1) == 1);
STATIC_CHECK(offsetof(struct S28_3, m2) == 4);
STATIC_CHECK(offsetof(struct S28_3, m3) == 24);
STATIC_CHECK(sizeof(struct S28_4) == 8);
STATIC_CHECK(sizeof(struct S28_4[3]) == 24);
STATIC_CHECK(offsetof(struct S28_4, m0) == 0);
STATIC_CHECK(offsetof(struct S28_4, m1) == 2);
STATIC_CHECK(offsetof(struct S28_4, m2) == 4);
STATIC_CHECK(sizeof(struct S28_5) == 36);
STATIC_CHECK(sizeof(struct S28_5[3]) == 108);
STATIC_CHECK(offsetof(struct S28_5, m0) == 0);
STATIC_CHECK(offsetof(struct S28_5, m1) == 4);
STATIC_CHECK(offsetof(struct S28_5, m2) == 20);
STATIC_CHECK(offsetof(struct S28_5, m3) == 24);
STATIC_CHECK(offsetof(struct S28_5, m4) == 28);
STATIC_CHECK(offsetof(struct S28_5, m5) == 32);
