// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 8-state machine over 2 inputs from ROM tables, fed 34 inputs.
#include "loomcc-test.h"
static const u8 next_state[8][2] = {
  { 0, 7 },
  { 6, 5 },
  { 7, 2 },
  { 0, 1 },
  { 4, 0 },
  { 5, 7 },
  { 5, 1 },
  { 1, 5 }
};
static const u8 action[8][2] = {
  { 3, 2 },
  { 1, 0 },
  { 1, 1 },
  { 1, 2 },
  { 1, 3 },
  { 4, 2 },
  { 4, 0 },
  { 4, 2 }
};
static const u8 inputs[34] = { 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0 };
static u8 visits[8];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 34; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 5);
  CHECK(score == 520u);
  CHECK(visits[0] == 2);
  CHECK(visits[1] == 4);
  CHECK(visits[2] == 0);
  CHECK(visits[3] == 0);
  CHECK(visits[4] == 0);
  CHECK(visits[5] == 17);
  CHECK(visits[6] == 2);
  CHECK(visits[7] == 9);
  return 0;
}
