// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 6-state machine over 5 inputs from ROM tables, fed 34 inputs.
#include "loomcc-test.h"
static const u8 next_state[6][5] = {
  { 4, 3, 1, 0, 5 },
  { 0, 5, 5, 5, 4 },
  { 2, 5, 5, 0, 0 },
  { 1, 1, 1, 4, 0 },
  { 5, 3, 1, 1, 5 },
  { 4, 1, 5, 5, 0 }
};
static const u8 action[6][5] = {
  { 0, 3, 4, 2, 2 },
  { 1, 0, 4, 4, 0 },
  { 4, 3, 0, 0, 3 },
  { 0, 4, 4, 2, 0 },
  { 1, 0, 0, 2, 3 },
  { 0, 0, 2, 3, 0 }
};
static const u8 inputs[34] = { 0, 2, 1, 2, 2, 0, 0, 2, 0, 1, 0, 4, 0, 0, 1, 1, 1, 0, 0, 0, 3, 4, 3, 0, 0, 0, 0, 1, 3, 4, 1, 2, 4, 4 };
static u8 visits[6];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 34; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 5);
  CHECK(score == 127u);
  CHECK(visits[0] == 2);
  CHECK(visits[1] == 6);
  CHECK(visits[2] == 0);
  CHECK(visits[3] == 3);
  CHECK(visits[4] == 11);
  CHECK(visits[5] == 12);
  return 0;
}
