// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 6-state machine over 3 inputs from ROM tables, fed 27 inputs.
#include "loomcc-test.h"
static const u8 next_state[6][3] = {
  { 4, 1, 1 },
  { 3, 1, 4 },
  { 0, 5, 5 },
  { 3, 0, 3 },
  { 3, 2, 0 },
  { 4, 1, 5 }
};
static const u8 action[6][3] = {
  { 0, 2, 2 },
  { 1, 4, 0 },
  { 3, 2, 3 },
  { 1, 1, 2 },
  { 2, 4, 4 },
  { 0, 4, 3 }
};
static const u8 inputs[27] = { 0, 1, 2, 2, 2, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 0, 1 };
static u8 visits[6];
int main(void) {
  u8 s = 0, i;
  u16 score = 0;
  for (i = 0; i < 27; i++) {
    u8 x = inputs[i];
    score = (u16)(score + action[s][x] * (s + 1));
    s = next_state[s][x];
    visits[s]++;
  }
  CHECK(s == 0);
  CHECK(score == 215u);
  CHECK(visits[0] == 4);
  CHECK(visits[1] == 7);
  CHECK(visits[2] == 2);
  CHECK(visits[3] == 4);
  CHECK(visits[4] == 6);
  CHECK(visits[5] == 4);
  return 0;
}
