// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Struct-of-arrays state indexed by a u8 slot (the shape of Loom's animation,
// actor and body tables): capacity 20, positions of type i16.
#include "loomcc-test.h"
#define CAP 20
typedef struct {
  i16 pos[CAP];
  i8 vel[CAP];
  u8 active[CAP];
  u8 count;
  const u8 *names[CAP];
} State;
static State st;
static const u8 name_rom[CAP] = { 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57 };
static const i16 init_pos[CAP] = { -31173, -12637, 17753, -18727, -25592, 4571, -26798, 32427, -26581, 25566, -31247, -20174, 30335, -26701, 7659, -25093, 28878, -30784, -12744, -25049 };
static const i8 init_vel[CAP] = { 1, -3, 5, -1, 0, 4, 0, 2, -4, -4, 2, 2, 2, 2, -1, -4, -3, -4, 0, -1 };
static void setup(void) {
  u8 i;
  for (i = 0; i < CAP; i++) {
    st.pos[i] = init_pos[i];
    st.vel[i] = init_vel[i];
    st.active[i] = (u8)(i & 1);
    st.names[i] = &name_rom[i];
  }
  st.count = CAP;
}
static void step(void) {
  u8 i;
  for (i = 0; i < st.count; i++) {
    if (!st.active[i]) continue;
    st.pos[i] = (i16)(st.pos[i] + st.vel[i]);
  }
}
static u8 argmax(void) {
  u8 i, best = 0;
  for (i = 1; i < st.count; i++)
    if (st.pos[i] > st.pos[best]) best = i;
  return best;
}
int main(void) {
  u16 total = 0;
  u8 i;
  setup();
  step(); step(); step();
  for (i = 0; i < CAP; i++) total = (u16)(total + (u16)st.pos[i]);
  CHECK(total == 30476u);
  CHECK(argmax() == 7);
  CHECK(*st.names[CAP - 1] == 57);
  CHECK(st.pos[19] == (i16)(-25052));
  return 0;
}
