// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 4 fields of widths [6, 8, 1, 1] packed into a u16 and unpacked.
#include "loomcc-test.h"
static const u8 f_rom[4] = { 17, 173, 1, 0 };
static u8 f[4];
int main(void) {
  u8 i;
  u16 p;
  for (i = 0; i < 4; i++) f[i] = f_rom[i];
  p = (u16)(((u16)f[0] << 0) | ((u16)f[1] << 6) | ((u16)f[2] << 14) | ((u16)f[3] << 15));
  CHECK(p == 27473u);
  CHECK((u16)((p >> 0) & 63u) == 17);
  CHECK((u16)((p >> 6) & 255u) == 173);
  CHECK((u16)((p >> 14) & 1u) == 1);
  CHECK((u16)((p >> 15) & 1u) == 0);
  return 0;
}
