// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 9 fields of widths [2, 3, 6, 2, 6, 1, 8, 2, 2] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[9] = { 2, 5, 40, 2, 13, 0, 117, 2, 2 };
static u8 f[9];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 9; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 2) | ((u32)f[2] << 5) | ((u32)f[3] << 11) | ((u32)f[4] << 13) | ((u32)f[5] << 19) | ((u32)f[6] << 20) | ((u32)f[7] << 28) | ((u32)f[8] << 30));
  CHECK(p == (u32)2807149846ULL);
  CHECK((u16)((p >> 0) & 3u) == 2);
  CHECK((u16)((p >> 2) & 7u) == 5);
  CHECK((u16)((p >> 5) & 63u) == 40);
  CHECK((u16)((p >> 11) & 3u) == 2);
  CHECK((u16)((p >> 13) & 63u) == 13);
  CHECK((u16)((p >> 19) & 1u) == 0);
  CHECK((u16)((p >> 20) & 255u) == 117);
  CHECK((u16)((p >> 28) & 3u) == 2);
  CHECK((u16)((p >> 30) & 3u) == 2);
  return 0;
}
