// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 9 fields of widths [2, 8, 3, 3, 4, 8, 2, 1, 1] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[9] = { 3, 79, 2, 3, 1, 15, 2, 1, 1 };
static u8 f[9];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 9; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 2) | ((u32)f[2] << 10) | ((u32)f[3] << 13) | ((u32)f[4] << 16) | ((u32)f[5] << 20) | ((u32)f[6] << 28) | ((u32)f[7] << 30) | ((u32)f[8] << 31));
  CHECK(p == (u32)3773917503ULL);
  CHECK((u16)((p >> 0) & 3u) == 3);
  CHECK((u16)((p >> 2) & 255u) == 79);
  CHECK((u16)((p >> 10) & 7u) == 2);
  CHECK((u16)((p >> 13) & 7u) == 3);
  CHECK((u16)((p >> 16) & 15u) == 1);
  CHECK((u16)((p >> 20) & 255u) == 15);
  CHECK((u16)((p >> 28) & 3u) == 2);
  CHECK((u16)((p >> 30) & 1u) == 1);
  CHECK((u16)((p >> 31) & 1u) == 1);
  return 0;
}
