// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 9 fields of widths [4, 6, 8, 2, 5, 2, 2, 1, 2] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[9] = { 12, 34, 93, 0, 15, 3, 1, 0, 2 };
static u8 f[9];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 9; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 4) | ((u32)f[2] << 10) | ((u32)f[3] << 18) | ((u32)f[4] << 20) | ((u32)f[5] << 25) | ((u32)f[6] << 27) | ((u32)f[7] << 29) | ((u32)f[8] << 30));
  CHECK(p == (u32)2398189100ULL);
  CHECK((u16)((p >> 0) & 15u) == 12);
  CHECK((u16)((p >> 4) & 63u) == 34);
  CHECK((u16)((p >> 10) & 255u) == 93);
  CHECK((u16)((p >> 18) & 3u) == 0);
  CHECK((u16)((p >> 20) & 31u) == 15);
  CHECK((u16)((p >> 25) & 3u) == 3);
  CHECK((u16)((p >> 27) & 3u) == 1);
  CHECK((u16)((p >> 29) & 1u) == 0);
  CHECK((u16)((p >> 30) & 3u) == 2);
  return 0;
}
