// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 8 fields of widths [1, 6, 4, 5, 8, 4, 3, 1] packed into a u32 and unpacked.
// loomcc-ref: host host16
// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.
#include "loomcc-test.h"
static const u8 f_rom[8] = { 0, 59, 2, 9, 88, 10, 2, 1 };
static u8 f[8];
int main(void) {
  u8 i;
  u32 p;
  for (i = 0; i < 8; i++) f[i] = f_rom[i];
  p = (u32)(((u32)f[0] << 0) | ((u32)f[1] << 1) | ((u32)f[2] << 7) | ((u32)f[3] << 11) | ((u32)f[4] << 16) | ((u32)f[5] << 24) | ((u32)f[6] << 28) | ((u32)f[7] << 31));
  CHECK(p == (u32)2857912694ULL);
  CHECK((u16)((p >> 0) & 1u) == 0);
  CHECK((u16)((p >> 1) & 63u) == 59);
  CHECK((u16)((p >> 7) & 15u) == 2);
  CHECK((u16)((p >> 11) & 31u) == 9);
  CHECK((u16)((p >> 16) & 255u) == 88);
  CHECK((u16)((p >> 24) & 15u) == 10);
  CHECK((u16)((p >> 28) & 7u) == 2);
  CHECK((u16)((p >> 31) & 1u) == 1);
  return 0;
}
