// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// i16 << (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((i16)((0)) << ((u8)(0))) == (0));
STATIC_CHECK(((i16)((0)) << ((u8)(1))) == (0));
STATIC_CHECK(((i16)((0)) << ((u8)(3))) == (0));
STATIC_CHECK(((i16)((0)) << ((u8)(7))) == (0));
STATIC_CHECK(((i16)((0)) << ((u8)(8))) == (0));
STATIC_CHECK(((i16)((0)) << ((u8)(15))) == (0));
STATIC_CHECK(((i16)((1)) << ((u8)(0))) == (1));
STATIC_CHECK(((i16)((1)) << ((u8)(1))) == (2));
STATIC_CHECK(((i16)((1)) << ((u8)(3))) == (8));
STATIC_CHECK(((i16)((1)) << ((u8)(7))) == (128));
STATIC_CHECK(((i16)((1)) << ((u8)(8))) == (256));
STATIC_CHECK(((i16)((2)) << ((u8)(0))) == (2));
STATIC_CHECK(((i16)((2)) << ((u8)(1))) == (4));
STATIC_CHECK(((i16)((2)) << ((u8)(3))) == (16));
STATIC_CHECK(((i16)((2)) << ((u8)(7))) == (256));
STATIC_CHECK(((i16)((2)) << ((u8)(8))) == (512));
STATIC_CHECK(((i16)((255)) << ((u8)(0))) == (255));
STATIC_CHECK(((i16)((255)) << ((u8)(1))) == (510));
STATIC_CHECK(((i16)((255)) << ((u8)(3))) == (2040));
STATIC_CHECK(((i16)((255)) << ((u8)(7))) == (32640));
STATIC_CHECK(((i16)((32767)) << ((u8)(0))) == (32767));
