// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// u16 << (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((u16)(0u) << ((u8)(0))) == 0u);
STATIC_CHECK(((u16)(0u) << ((u8)(1))) == 0u);
STATIC_CHECK(((u16)(0u) << ((u8)(3))) == 0u);
STATIC_CHECK(((u16)(0u) << ((u8)(7))) == 0u);
STATIC_CHECK(((u16)(0u) << ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(0u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(1u) << ((u8)(0))) == 1u);
STATIC_CHECK(((u16)(1u) << ((u8)(1))) == 2u);
STATIC_CHECK(((u16)(1u) << ((u8)(3))) == 8u);
STATIC_CHECK(((u16)(1u) << ((u8)(7))) == 128u);
STATIC_CHECK(((u16)(1u) << ((u8)(8))) == 256u);
STATIC_CHECK(((u16)(1u) << ((u8)(15))) == 32768u);
STATIC_CHECK(((u16)(2u) << ((u8)(0))) == 2u);
STATIC_CHECK(((u16)(2u) << ((u8)(1))) == 4u);
STATIC_CHECK(((u16)(2u) << ((u8)(3))) == 16u);
STATIC_CHECK(((u16)(2u) << ((u8)(7))) == 256u);
STATIC_CHECK(((u16)(2u) << ((u8)(8))) == 512u);
STATIC_CHECK(((u16)(2u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(255u) << ((u8)(0))) == 255u);
STATIC_CHECK(((u16)(255u) << ((u8)(1))) == 510u);
STATIC_CHECK(((u16)(255u) << ((u8)(3))) == 2040u);
STATIC_CHECK(((u16)(255u) << ((u8)(7))) == 32640u);
STATIC_CHECK(((u16)(255u) << ((u8)(8))) == 65280u);
STATIC_CHECK(((u16)(255u) << ((u8)(15))) == 32768u);
STATIC_CHECK(((u16)(256u) << ((u8)(0))) == 256u);
STATIC_CHECK(((u16)(256u) << ((u8)(1))) == 512u);
STATIC_CHECK(((u16)(256u) << ((u8)(3))) == 2048u);
STATIC_CHECK(((u16)(256u) << ((u8)(7))) == 32768u);
STATIC_CHECK(((u16)(256u) << ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(256u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(1000u) << ((u8)(0))) == 1000u);
STATIC_CHECK(((u16)(1000u) << ((u8)(1))) == 2000u);
STATIC_CHECK(((u16)(1000u) << ((u8)(3))) == 8000u);
STATIC_CHECK(((u16)(1000u) << ((u8)(7))) == 62464u);
STATIC_CHECK(((u16)(1000u) << ((u8)(8))) == 59392u);
STATIC_CHECK(((u16)(1000u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(32767u) << ((u8)(0))) == 32767u);
STATIC_CHECK(((u16)(32767u) << ((u8)(1))) == 65534u);
STATIC_CHECK(((u16)(32767u) << ((u8)(3))) == 65528u);
STATIC_CHECK(((u16)(32767u) << ((u8)(7))) == 65408u);
STATIC_CHECK(((u16)(32767u) << ((u8)(8))) == 65280u);
STATIC_CHECK(((u16)(32767u) << ((u8)(15))) == 32768u);
STATIC_CHECK(((u16)(32768u) << ((u8)(0))) == 32768u);
STATIC_CHECK(((u16)(32768u) << ((u8)(1))) == 0u);
STATIC_CHECK(((u16)(32768u) << ((u8)(3))) == 0u);
STATIC_CHECK(((u16)(32768u) << ((u8)(7))) == 0u);
STATIC_CHECK(((u16)(32768u) << ((u8)(8))) == 0u);
STATIC_CHECK(((u16)(32768u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(40000u) << ((u8)(0))) == 40000u);
STATIC_CHECK(((u16)(40000u) << ((u8)(1))) == 14464u);
STATIC_CHECK(((u16)(40000u) << ((u8)(3))) == 57856u);
STATIC_CHECK(((u16)(40000u) << ((u8)(7))) == 8192u);
STATIC_CHECK(((u16)(40000u) << ((u8)(8))) == 16384u);
STATIC_CHECK(((u16)(40000u) << ((u8)(15))) == 0u);
STATIC_CHECK(((u16)(65535u) << ((u8)(0))) == 65535u);
STATIC_CHECK(((u16)(65535u) << ((u8)(1))) == 65534u);
STATIC_CHECK(((u16)(65535u) << ((u8)(3))) == 65528u);
STATIC_CHECK(((u16)(65535u) << ((u8)(7))) == 65408u);
STATIC_CHECK(((u16)(65535u) << ((u8)(8))) == 65280u);
STATIC_CHECK(((u16)(65535u) << ((u8)(15))) == 32768u);
