// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// i16 >> (u8, i8, u16, i16) as integer constant expressions at 16-bit int.
// loomcc-ref: clang16
// loomcc-note: no 816-tcc reference: its constant folder does unsigned int
// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).
#include "loomcc-test.h"
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(0))) == (-32767 - 1));
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(1))) == (-16384));
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(3))) == (-4096));
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(7))) == (-256));
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(8))) == (-128));
STATIC_CHECK(((i16)((-32767 - 1)) >> ((u8)(15))) == (-1));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(0))) == (-32767));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(1))) == (-16384));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(3))) == (-4096));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(7))) == (-256));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(8))) == (-128));
STATIC_CHECK(((i16)((-32767)) >> ((u8)(15))) == (-1));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(0))) == (-1000));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(1))) == (-500));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(3))) == (-125));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(7))) == (-8));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(8))) == (-4));
STATIC_CHECK(((i16)((-1000)) >> ((u8)(15))) == (-1));
STATIC_CHECK(((i16)((-256)) >> ((u8)(0))) == (-256));
STATIC_CHECK(((i16)((-256)) >> ((u8)(1))) == (-128));
STATIC_CHECK(((i16)((-256)) >> ((u8)(3))) == (-32));
STATIC_CHECK(((i16)((-256)) >> ((u8)(7))) == (-2));
STATIC_CHECK(((i16)((-256)) >> ((u8)(8))) == (-1));
STATIC_CHECK(((i16)((-256)) >> ((u8)(15))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(0))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(1))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(3))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(7))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(8))) == (-1));
STATIC_CHECK(((i16)((-1)) >> ((u8)(15))) == (-1));
STATIC_CHECK(((i16)((0)) >> ((u8)(0))) == (0));
STATIC_CHECK(((i16)((0)) >> ((u8)(1))) == (0));
STATIC_CHECK(((i16)((0)) >> ((u8)(3))) == (0));
STATIC_CHECK(((i16)((0)) >> ((u8)(7))) == (0));
STATIC_CHECK(((i16)((0)) >> ((u8)(8))) == (0));
STATIC_CHECK(((i16)((0)) >> ((u8)(15))) == (0));
STATIC_CHECK(((i16)((1)) >> ((u8)(0))) == (1));
STATIC_CHECK(((i16)((1)) >> ((u8)(1))) == (0));
STATIC_CHECK(((i16)((1)) >> ((u8)(3))) == (0));
STATIC_CHECK(((i16)((1)) >> ((u8)(7))) == (0));
STATIC_CHECK(((i16)((1)) >> ((u8)(8))) == (0));
STATIC_CHECK(((i16)((1)) >> ((u8)(15))) == (0));
STATIC_CHECK(((i16)((2)) >> ((u8)(0))) == (2));
STATIC_CHECK(((i16)((2)) >> ((u8)(1))) == (1));
STATIC_CHECK(((i16)((2)) >> ((u8)(3))) == (0));
STATIC_CHECK(((i16)((2)) >> ((u8)(7))) == (0));
STATIC_CHECK(((i16)((2)) >> ((u8)(8))) == (0));
STATIC_CHECK(((i16)((2)) >> ((u8)(15))) == (0));
STATIC_CHECK(((i16)((255)) >> ((u8)(0))) == (255));
STATIC_CHECK(((i16)((255)) >> ((u8)(1))) == (127));
STATIC_CHECK(((i16)((255)) >> ((u8)(3))) == (31));
STATIC_CHECK(((i16)((255)) >> ((u8)(7))) == (1));
STATIC_CHECK(((i16)((255)) >> ((u8)(8))) == (0));
STATIC_CHECK(((i16)((255)) >> ((u8)(15))) == (0));
STATIC_CHECK(((i16)((32767)) >> ((u8)(0))) == (32767));
STATIC_CHECK(((i16)((32767)) >> ((u8)(1))) == (16383));
STATIC_CHECK(((i16)((32767)) >> ((u8)(3))) == (4095));
STATIC_CHECK(((i16)((32767)) >> ((u8)(7))) == (255));
STATIC_CHECK(((i16)((32767)) >> ((u8)(8))) == (127));
STATIC_CHECK(((i16)((32767)) >> ((u8)(15))) == (0));
