// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// The type of u16 op T for every integer type T, at 16-bit int and 32-bit
// long: integer promotions and the usual arithmetic conversions (6.3.1).
#include "loomcc-test.h"
STATIC_CHECK(sizeof((u16)0 + (u8)0) == 2);
STATIC_CHECK((((u16)0 + (u8)0) - 1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 + (i8)0) == 2);
STATIC_CHECK((((u16)0 + (i8)0) - 1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 + (u16)0) == 2);
STATIC_CHECK((((u16)0 + (u16)0) - 1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 + (i16)0) == 2);
STATIC_CHECK((((u16)0 + (i16)0) - 1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 + (u32)0) == 4);
STATIC_CHECK((((u16)0 + (u32)0) - 1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 + (i32)0) == 4);
STATIC_CHECK((((u16)0 + (i32)0) - 1 < 0) == 1);
STATIC_CHECK(sizeof(+(u16)0) == 2);
STATIC_CHECK((-(u16)1 < 0) == 0);
STATIC_CHECK(sizeof((u16)0 << 1) == 2);
