// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.
#include "loomcc-test.h"
typedef struct { i16 x, y; u8 w, h; } Box;
static const Box boxes[8] = {
  { 35, 171, 26, 4 },
  { -285, -74, 12, 61 },
  { 116, -109, 21, 5 },
  { -166, -256, 51, 52 },
  { 62, -89, 35, 47 },
  { -178, -133, 29, 33 },
  { -155, -129, 61, 63 },
  { 71, -61, 14, 53 }
};
static u8 overlap(const Box *a, const Box *b) {
  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;
}
int main(void) {
  u8 a, b, hits = 0;
  for (a = 0; a < 8; a++)
    for (b = (u8)(a + 1); b < 8; b++)
      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));
  CHECK(hits == 2);
  CHECK(overlap(&boxes[0], &boxes[1]) == 0);
  CHECK(overlap(&boxes[0], &boxes[6]) == 0);
  CHECK(overlap(&boxes[1], &boxes[2]) == 0);
  CHECK(overlap(&boxes[1], &boxes[4]) == 0);
  CHECK(overlap(&boxes[2], &boxes[7]) == 0);
  CHECK(overlap(&boxes[3], &boxes[4]) == 0);
  CHECK(overlap(&boxes[4], &boxes[6]) == 0);
  CHECK(overlap(&boxes[5], &boxes[6]) == 1);
  return 0;
}
