// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.
#include "loomcc-test.h"
typedef struct { i16 x, y; u8 w, h; } Box;
static const Box boxes[8] = {
  { 167, -292, 54, 50 },
  { -221, -136, 24, 44 },
  { -223, 141, 48, 16 },
  { -118, -95, 32, 55 },
  { 114, 58, 56, 32 },
  { 122, -68, 22, 24 },
  { -293, 74, 4, 36 },
  { -29, 18, 19, 50 }
};
static u8 overlap(const Box *a, const Box *b) {
  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;
}
int main(void) {
  u8 a, b, hits = 0;
  for (a = 0; a < 8; a++)
    for (b = (u8)(a + 1); b < 8; b++)
      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));
  CHECK(hits == 0);
  CHECK(overlap(&boxes[0], &boxes[2]) == 0);
  CHECK(overlap(&boxes[0], &boxes[4]) == 0);
  CHECK(overlap(&boxes[0], &boxes[7]) == 0);
  CHECK(overlap(&boxes[1], &boxes[3]) == 0);
  CHECK(overlap(&boxes[3], &boxes[7]) == 0);
  CHECK(overlap(&boxes[4], &boxes[6]) == 0);
  CHECK(overlap(&boxes[5], &boxes[7]) == 0);
  CHECK(overlap(&boxes[6], &boxes[7]) == 0);
  return 0;
}
