// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.
#include "loomcc-test.h"
typedef struct { i16 x, y; u8 w, h; } Box;
static const Box boxes[8] = {
  { -39, 4, 33, 60 },
  { -268, 280, 20, 21 },
  { -224, -203, 51, 56 },
  { -130, -17, 20, 29 },
  { 242, -239, 57, 49 },
  { -64, -118, 42, 34 },
  { 59, 145, 50, 39 },
  { -203, 250, 47, 11 }
};
static u8 overlap(const Box *a, const Box *b) {
  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;
}
int main(void) {
  u8 a, b, hits = 0;
  for (a = 0; a < 8; a++)
    for (b = (u8)(a + 1); b < 8; b++)
      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));
  CHECK(hits == 0);
  CHECK(overlap(&boxes[0], &boxes[4]) == 0);
  CHECK(overlap(&boxes[1], &boxes[2]) == 0);
  CHECK(overlap(&boxes[4], &boxes[6]) == 0);
  return 0;
}
