// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// ROM strings: length, compare, find, bounded copy, reverse, u16 to decimal.
#include "loomcc-test.h"
static const char A[] = "snes";
static const char B[] = "loom";
static char buf[24];
static u16 slen(const char *s) { const char *p = s; while (*p) p++; return (u16)(p - s); }
static i8 scmp(const char *x, const char *y) { while (*x && *x == *y) { x++; y++; } return (i8)((u8)*x > (u8)*y ? 1 : (u8)*x < (u8)*y ? -1 : 0); }
static i16 sfind(const char *s, char c) { i16 i; for (i = 0; s[i]; i++) if (s[i] == c) return i; return -1; }
static void scopy(char *d, const char *s, u8 cap) { u8 i = 0; if (!cap) return; while (s[i] && i + 1 < cap) { d[i] = s[i]; i++; } d[i] = 0; }
static void utoa(u16 v, char *d) { char t[6]; u8 n = 0; do { t[n++] = (char)('0' + v % 10); v /= 10; } while (v); while (n) *d++ = t[--n]; *d = 0; }
int main(void) {
  CHECK(slen(A) == 4 && slen(B) == 4);
  CHECK(scmp(A, B) == 1);
  CHECK(scmp(A, A) == 0);
  CHECK(sfind(A, 'o') == -1);
  scopy(buf, A, 3);
  CHECK(slen(buf) == 2 && scmp(buf, "sn") == 0);
  utoa(60034u, buf);
  CHECK(scmp(buf, "60034") == 0);
  return 0;
}
