// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// switch on a small enum stored in a i8: cases [-4, -3, -2, -1, 0, 1]
// (some fall through), as Loom's state machines do.
#include "loomcc-test.h"
enum K_negative { K_negative_m4 = -4, K_negative_m3 = -3, K_negative_m2 = -2, K_negative_m1 = -1, K_negative_0 = 0, K_negative_1 = 1 };
static u16 classify(i8 k) {
  u16 acc = 0;
  switch (k) {
  case K_negative_m4: acc += 798;
  case K_negative_m3: acc += 692; return acc;
  case K_negative_m2: acc += 277;
  case K_negative_m1: acc += 345; return acc;
  case K_negative_0: acc += 90; return acc;
  case K_negative_1: acc += 319; return acc;
  default: acc += 7; return acc;
  }
}
int main(void) {
  CHECK(classify((i8)-5) == 7);
  CHECK(classify((i8)-4) == 1490);
  CHECK(classify((i8)-3) == 692);
  CHECK(classify((i8)-2) == 622);
  CHECK(classify((i8)-1) == 345);
  CHECK(classify((i8)0) == 90);
  CHECK(classify((i8)1) == 319);
  CHECK(classify((i8)2) == 7);
  CHECK(classify((i8)50) == 7);
  CHECK(classify((i8)127) == 7);
  return 0;
}
