// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// switch on a small enum stored in a u8: cases [0, 1, 2, 3, 4, 5, 6, 7]
// (some fall through), as Loom's state machines do.
#include "loomcc-test.h"
enum K_dense8 { K_dense8_0 = 0, K_dense8_1 = 1, K_dense8_2 = 2, K_dense8_3 = 3, K_dense8_4 = 4, K_dense8_5 = 5, K_dense8_6 = 6, K_dense8_7 = 7 };
static u16 classify(u8 k) {
  u16 acc = 0;
  switch (k) {
  case K_dense8_0: acc += 463; return acc;
  case K_dense8_1: acc += 521; return acc;
  case K_dense8_2: acc += 876; return acc;
  case K_dense8_3: acc += 602; return acc;
  case K_dense8_4: acc += 195; return acc;
  case K_dense8_5: acc += 190;
  case K_dense8_6: acc += 824; return acc;
  case K_dense8_7: acc += 525;
  default: acc += 7; return acc;
  }
}
int main(void) {
  CHECK(classify((u8)0) == 463);
  CHECK(classify((u8)1) == 521);
  CHECK(classify((u8)2) == 876);
  CHECK(classify((u8)3) == 602);
  CHECK(classify((u8)4) == 195);
  CHECK(classify((u8)5) == 1014);
  CHECK(classify((u8)6) == 824);
  CHECK(classify((u8)7) == 532);
  CHECK(classify((u8)8) == 7);
  CHECK(classify((u8)50) == 7);
  CHECK(classify((u8)127) == 7);
  return 0;
}
