// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Struct-of-arrays state indexed by a u8 slot (the shape of Loom's animation,
// actor and body tables): capacity 12, positions of type i8.
#include "loomcc-test.h"
#define CAP 12
typedef struct {
  i8 pos[CAP];
  i8 vel[CAP];
  u8 active[CAP];
  u8 count;
  const u8 *names[CAP];
} State;
static State st;
static const u8 name_rom[CAP] = { 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33 };
static const i8 init_pos[CAP] = { 55, -19, 13, 69, 97, 28, 70, 25, -40, 86, 64, 117 };
static const i8 init_vel[CAP] = { 0, 4, 4, 0, -3, 3, 4, 5, 5, -5, 2, 5 };
static void setup(void) {
  u8 i;
  for (i = 0; i < CAP; i++) {
    st.pos[i] = init_pos[i];
    st.vel[i] = init_vel[i];
    st.active[i] = (u8)(i & 1);
    st.names[i] = &name_rom[i];
  }
  st.count = CAP;
}
static void step(void) {
  u8 i;
  for (i = 0; i < st.count; i++) {
    if (!st.active[i]) continue;
    st.pos[i] = (i8)(st.pos[i] + st.vel[i]);
  }
}
static u8 argmax(void) {
  u8 i, best = 0;
  for (i = 1; i < st.count; i++)
    if (st.pos[i] > st.pos[best]) best = i;
  return best;
}
int main(void) {
  u16 total = 0;
  u8 i;
  setup();
  step(); step(); step();
  for (i = 0; i < CAP; i++) total = (u16)(total + (u16)st.pos[i]);
  CHECK(total == 345u);
  CHECK(argmax() == 4);
  CHECK(*st.names[CAP - 1] == 33);
  CHECK(st.pos[11] == (i8)(-124));
  return 0;
}
