// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Struct-of-arrays state indexed by a u8 slot (the shape of Loom's animation,
// actor and body tables): capacity 4, positions of type u8.
#include "loomcc-test.h"
#define CAP 4
typedef struct {
  u8 pos[CAP];
  i8 vel[CAP];
  u8 active[CAP];
  u8 count;
  const u8 *names[CAP];
} State;
static State st;
static const u8 name_rom[CAP] = { 0, 3, 6, 9 };
static const u8 init_pos[CAP] = { 141, 252, 230, 7 };
static const i8 init_vel[CAP] = { -5, -4, 3, -4 };
static void setup(void) {
  u8 i;
  for (i = 0; i < CAP; i++) {
    st.pos[i] = init_pos[i];
    st.vel[i] = init_vel[i];
    st.active[i] = (u8)(i & 1);
    st.names[i] = &name_rom[i];
  }
  st.count = CAP;
}
static void step(void) {
  u8 i;
  for (i = 0; i < st.count; i++) {
    if (!st.active[i]) continue;
    st.pos[i] = (u8)(st.pos[i] + st.vel[i]);
  }
}
static u8 argmax(void) {
  u8 i, best = 0;
  for (i = 1; i < st.count; i++)
    if (st.pos[i] > st.pos[best]) best = i;
  return best;
}
int main(void) {
  u16 total = 0;
  u8 i;
  setup();
  step(); step(); step();
  for (i = 0; i < CAP; i++) total = (u16)(total + (u16)st.pos[i]);
  CHECK(total == 862u);
  CHECK(argmax() == 3);
  CHECK(*st.names[CAP - 1] == 9);
  CHECK(st.pos[3] == (u8)(251));
  return 0;
}
