// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern volatile unsigned short * volatile (* volatile v0)(void);
typedef unsigned short *(*T0)(void);
extern volatile short v1;
typedef short T1;
extern volatile unsigned v2;
typedef unsigned T2;
extern char v3[5];
typedef char T3[5];
extern volatile unsigned short * const v4;
typedef unsigned short *T4;
extern const unsigned short v5[3];
typedef unsigned short T5[3];
extern const unsigned **v6[7][11];
typedef unsigned **T6[7][11];
extern const char (*v7)[11];
typedef char (*T7)[11];
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0)())) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *(*)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(short));
STATIC_CHECK(sizeof(short) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 5 * (1));
STATIC_CHECK(sizeof(v3[1]) == 1);
STATIC_CHECK(sizeof(char [5]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 3 * (sizeof(short)));
STATIC_CHECK(sizeof(v5[1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short [3]) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 7 * (11 * (sizeof(void *))));
STATIC_CHECK(sizeof(v6[1]) == 11 * (sizeof(void *)));
STATIC_CHECK(sizeof(v6[1][1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v6[1][1])) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6[1][1]))) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned **[7][11]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == 11 * (1));
STATIC_CHECK(sizeof((*v7)[1]) == 1);
STATIC_CHECK(sizeof(char (*)[11]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
