// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern short * volatile * volatile (* volatile * volatile v0)(void);
typedef short **(**T0)(void);
extern const long v1;
typedef long T1;
extern unsigned char * const * const v2;
typedef unsigned char **T2;
extern volatile long v3;
typedef long T3;
extern int (*(**v4)(void))[2];
typedef int (*(**T4)(void))[2];
extern volatile int v5;
typedef int T5;
extern long (*v6)(void);
typedef long (*T6)(void);
extern const signed char v7;
typedef signed char T7;
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v0))()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v0))())) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*(*v0))()))) == sizeof(short));
STATIC_CHECK(sizeof(short **(**)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void *));
STATIC_CHECK(sizeof((*v2)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2))) == 1);
STATIC_CHECK(sizeof(unsigned char **) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v4))()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v4))())) == 2 * (sizeof(int)));
STATIC_CHECK(sizeof((*(*(*v4))())[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*(**)(void))[2]) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6)()) == sizeof(long));
STATIC_CHECK(sizeof(long (*)(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(signed char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
