// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern const signed char *(*v0)(void);
typedef signed char *(*T0)(void);
extern const long * const (* const v1)[3];
typedef long *(*T1)[3];
extern volatile signed char (*v2[3])(void);
typedef signed char (*T2[3])(void);
extern short v3[2];
typedef short T3[2];
extern const signed char v4;
typedef signed char T4;
extern const unsigned v5;
typedef unsigned T5;
extern const signed char *v6;
typedef signed char *T6;
extern unsigned char v7;
typedef unsigned char T7;
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0)())) == 1);
STATIC_CHECK(sizeof(signed char *(*)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == 3 * (sizeof(void *)));
STATIC_CHECK(sizeof((*v1)[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v1)[1])) == sizeof(long));
STATIC_CHECK(sizeof(long *(*)[3]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 3 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v2[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2[1])()) == 1);
STATIC_CHECK(sizeof(signed char (*[3])(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 2 * (sizeof(short)));
STATIC_CHECK(sizeof(v3[1]) == sizeof(short));
STATIC_CHECK(sizeof(short [2]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == 1);
STATIC_CHECK(sizeof(signed char) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 1);
STATIC_CHECK(sizeof(signed char *) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
