// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern int * volatile v0;
typedef int *T0;
extern const unsigned short v1[5][5][2];
typedef unsigned short T1[5][5][2];
extern const signed char (*v2)(void);
typedef signed char (*T2)(void);
extern unsigned short (* volatile v3)[2];
typedef unsigned short (*T3)[2];
extern volatile unsigned char * volatile v4;
typedef unsigned char *T4;
extern volatile long (* const v5)[11];
typedef long (*T5)[11];
extern const unsigned short v6;
typedef unsigned short T6;
extern short (* volatile v7)[2];
typedef short (*T7)[2];
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == sizeof(int));
STATIC_CHECK(sizeof(int *) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 5 * (5 * (2 * (sizeof(short)))));
STATIC_CHECK(sizeof(v1[1]) == 5 * (2 * (sizeof(short))));
STATIC_CHECK(sizeof(v1[1][1]) == 2 * (sizeof(short)));
STATIC_CHECK(sizeof(v1[1][1][1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short [5][5][2]) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == 1);
STATIC_CHECK(sizeof(signed char (*)(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == 2 * (sizeof(short)));
STATIC_CHECK(sizeof((*v3)[1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short (*)[2]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == 1);
STATIC_CHECK(sizeof(unsigned char *) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void *));
STATIC_CHECK(sizeof((*v5)) == 11 * (sizeof(long)));
STATIC_CHECK(sizeof((*v5)[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (*)[11]) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == 2 * (sizeof(short)));
STATIC_CHECK(sizeof((*v7)[1]) == sizeof(short));
STATIC_CHECK(sizeof(short (*)[2]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
