// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern const unsigned char **v0;
typedef unsigned char **T0;
extern char *v1;
typedef char *T1;
extern const unsigned short v2;
typedef unsigned short T2;
extern volatile long v3;
typedef long T3;
extern const short v4;
typedef short T4;
extern const unsigned char (* volatile * volatile (* volatile v5)(void))(void);
typedef unsigned char (**(*T5)(void))(void);
extern const char (****v6)[5];
typedef char (****T6)[5];
extern unsigned short v7;
typedef unsigned short T7;
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0))) == 1);
STATIC_CHECK(sizeof(unsigned char **) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == 1);
STATIC_CHECK(sizeof(char *) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(short));
STATIC_CHECK(sizeof(short) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v5)())) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*(*v5)()))()) == 1);
STATIC_CHECK(sizeof(unsigned char (**(*)(void))(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v6)))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*(*v6))))) == 5 * (1));
STATIC_CHECK(sizeof((*(*(*(*v6))))[1]) == 1);
STATIC_CHECK(sizeof(char (****)[5]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
