// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern const char v0;
typedef char T0;
extern const unsigned short v1;
typedef unsigned short T1;
extern const unsigned short * volatile v2[11];
typedef unsigned short *T2[11];
extern volatile unsigned v3;
typedef unsigned T3;
extern long (* volatile v4)(void);
typedef long (*T4)(void);
extern int (* const v5[2])(void);
typedef int (*T5[2])(void);
extern volatile signed char v6;
typedef signed char T6;
extern volatile long * const v7[5];
typedef long *T7[5];
STATIC_CHECK(sizeof(v0) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 11 * (sizeof(void *)));
STATIC_CHECK(sizeof(v2[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v2[1])) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *[11]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == sizeof(long));
STATIC_CHECK(sizeof(long (*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 2 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v5[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5[1])()) == sizeof(int));
STATIC_CHECK(sizeof(int (*[2])(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 1);
STATIC_CHECK(sizeof(signed char) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 5 * (sizeof(void *)));
STATIC_CHECK(sizeof(v7[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v7[1])) == sizeof(long));
STATIC_CHECK(sizeof(long *[5]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
