// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned * volatile (* volatile v0[2])(void);
typedef unsigned *(*T0[2])(void);
extern volatile long v1;
typedef long T1;
extern const unsigned v2;
typedef unsigned T2;
extern volatile int (*v3)[3];
typedef int (*T3)[3];
extern volatile unsigned *v4;
typedef unsigned *T4;
extern unsigned char *(**v5)(void);
typedef unsigned char *(**T5)(void);
extern const char v6;
typedef char T6;
extern const char *(***v7)[5];
typedef char *(***T7)[5];
STATIC_CHECK(sizeof(v0) == 2 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v0[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0[1])()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v0[1])())) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned *(*[2])(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == 3 * (sizeof(int)));
STATIC_CHECK(sizeof((*v3)[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*)[3]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned *) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void *));
STATIC_CHECK(sizeof((*v5)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v5))()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v5))())) == 1);
STATIC_CHECK(sizeof(unsigned char *(**)(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v7))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v7)))) == 5 * (sizeof(void *)));
STATIC_CHECK(sizeof((*(*(*v7)))[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*(*v7)))[1])) == 1);
STATIC_CHECK(sizeof(char *(***)[5]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
