// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 13 u8 indices by a u16 key table.
#include "loomcc-test.h"
static const u16 key[13] = { 0, 59577, 23706, 50985, 56991, 0, 33561, 42142, 49866, 5323, 51560, 60613, 29855 };
static const u8 want[13] = { 0, 5, 9, 2, 12, 6, 7, 8, 3, 10, 4, 1, 11 };
static u8 idx[13];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 13; i++) idx[i] = i;
  for (i = 1; i < 13; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 13; i++) CHECK(idx[i] == want[i]);
  return 0;
}
