// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 8 u8 indices by a i8 key table.
#include "loomcc-test.h"
static const i8 key[8] = { 44, 75, 30, -7, 86, -4, 34, 0 };
static const u8 want[8] = { 3, 5, 7, 2, 6, 0, 1, 4 };
static u8 idx[8];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 8; i++) idx[i] = i;
  for (i = 1; i < 8; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 8; i++) CHECK(idx[i] == want[i]);
  return 0;
}
