// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 32 u8 indices by a i16 key table.
#include "loomcc-test.h"
static const i16 key[32] = { -5213, 0, -21774, 616, -19314, 2604, -11173, 0, 24398, 11346, -24377, -30923, 8316, -7795, -19358, -10332, 21615, -31973, 871, -29998, -21043, 19875, 3011, 543, 21928, 0, -25972, 0, -27212, 13031, 7175, -23455 };
static const u8 want[32] = { 17, 11, 19, 28, 26, 10, 31, 2, 20, 14, 4, 6, 15, 13, 0, 1, 7, 25, 27, 23, 3, 18, 5, 22, 30, 12, 9, 29, 21, 16, 24, 8 };
static u8 idx[32];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 32; i++) idx[i] = i;
  for (i = 1; i < 32; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 32; i++) CHECK(idx[i] == want[i]);
  return 0;
}
