// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Stable insertion sort of 3 u8 indices by a u16 key table.
#include "loomcc-test.h"
static const u16 key[3] = { 14894, 54761, 45765 };
static const u8 want[3] = { 0, 2, 1 };
static u8 idx[3];
int main(void) {
  u8 i, j, t;
  for (i = 0; i < 3; i++) idx[i] = i;
  for (i = 1; i < 3; i++) {
    t = idx[i];
    j = i;
    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }
    idx[j] = t;
  }
  for (i = 0; i < 3; i++) CHECK(idx[i] == want[i]);
  return 0;
}
