// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// switch on a small enum stored in a u8: cases [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
// (some fall through), as Loom's state machines do.
#include "loomcc-test.h"
enum K_dense32 { K_dense32_0 = 0, K_dense32_1 = 1, K_dense32_2 = 2, K_dense32_3 = 3, K_dense32_4 = 4, K_dense32_5 = 5, K_dense32_6 = 6, K_dense32_7 = 7, K_dense32_8 = 8, K_dense32_9 = 9, K_dense32_10 = 10, K_dense32_11 = 11, K_dense32_12 = 12, K_dense32_13 = 13, K_dense32_14 = 14, K_dense32_15 = 15, K_dense32_16 = 16, K_dense32_17 = 17, K_dense32_18 = 18, K_dense32_19 = 19, K_dense32_20 = 20, K_dense32_21 = 21, K_dense32_22 = 22, K_dense32_23 = 23, K_dense32_24 = 24, K_dense32_25 = 25, K_dense32_26 = 26, K_dense32_27 = 27, K_dense32_28 = 28, K_dense32_29 = 29, K_dense32_30 = 30, K_dense32_31 = 31 };
static u16 classify(u8 k) {
  u16 acc = 0;
  switch (k) {
  case K_dense32_0: acc += 417; return acc;
  case K_dense32_1: acc += 565; return acc;
  case K_dense32_2: acc += 955;
  case K_dense32_3: acc += 861;
  case K_dense32_4: acc += 86; return acc;
  case K_dense32_5: acc += 725; return acc;
  case K_dense32_6: acc += 261;
  case K_dense32_7: acc += 323; return acc;
  case K_dense32_8: acc += 777; return acc;
  case K_dense32_9: acc += 236; return acc;
  case K_dense32_10: acc += 526; return acc;
  case K_dense32_11: acc += 296; return acc;
  case K_dense32_12: acc += 31;
  case K_dense32_13: acc += 72;
  case K_dense32_14: acc += 577; return acc;
  case K_dense32_15: acc += 785;
  case K_dense32_16: acc += 111; return acc;
  case K_dense32_17: acc += 411; return acc;
  case K_dense32_18: acc += 111;
  case K_dense32_19: acc += 867; return acc;
  case K_dense32_20: acc += 298;
  case K_dense32_21: acc += 396; return acc;
  case K_dense32_22: acc += 69;
  case K_dense32_23: acc += 982; return acc;
  case K_dense32_24: acc += 18; return acc;
  case K_dense32_25: acc += 868; return acc;
  case K_dense32_26: acc += 702; return acc;
  case K_dense32_27: acc += 1; return acc;
  case K_dense32_28: acc += 219; return acc;
  case K_dense32_29: acc += 215;
  case K_dense32_30: acc += 950; return acc;
  case K_dense32_31: acc += 933; return acc;
  default: acc += 7; return acc;
  }
}
int main(void) {
  CHECK(classify((u8)0) == 417);
  CHECK(classify((u8)1) == 565);
  CHECK(classify((u8)2) == 1902);
  CHECK(classify((u8)3) == 947);
  CHECK(classify((u8)4) == 86);
  CHECK(classify((u8)5) == 725);
  CHECK(classify((u8)6) == 584);
  CHECK(classify((u8)7) == 323);
  CHECK(classify((u8)8) == 777);
  CHECK(classify((u8)9) == 236);
  CHECK(classify((u8)10) == 526);
  CHECK(classify((u8)11) == 296);
  CHECK(classify((u8)12) == 680);
  CHECK(classify((u8)13) == 649);
  CHECK(classify((u8)14) == 577);
  CHECK(classify((u8)15) == 896);
  CHECK(classify((u8)16) == 111);
  CHECK(classify((u8)17) == 411);
  CHECK(classify((u8)18) == 978);
  CHECK(classify((u8)19) == 867);
  CHECK(classify((u8)20) == 694);
  CHECK(classify((u8)21) == 396);
  CHECK(classify((u8)22) == 1051);
  CHECK(classify((u8)23) == 982);
  CHECK(classify((u8)24) == 18);
  CHECK(classify((u8)25) == 868);
  CHECK(classify((u8)26) == 702);
  CHECK(classify((u8)27) == 1);
  CHECK(classify((u8)28) == 219);
  CHECK(classify((u8)29) == 1165);
  CHECK(classify((u8)30) == 950);
  CHECK(classify((u8)31) == 933);
  CHECK(classify((u8)32) == 7);
  CHECK(classify((u8)50) == 7);
  CHECK(classify((u8)127) == 7);
  return 0;
}
