// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// switch on a small enum stored in a u8: cases [3]
// (some fall through), as Loom's state machines do.
#include "loomcc-test.h"
enum K_single { K_single_3 = 3 };
static u16 classify(u8 k) {
  u16 acc = 0;
  switch (k) {
  case K_single_3: acc += 469; return acc;
  default: acc += 7; return acc;
  }
}
int main(void) {
  CHECK(classify((u8)2) == 7);
  CHECK(classify((u8)3) == 469);
  CHECK(classify((u8)4) == 7);
  CHECK(classify((u8)50) == 7);
  CHECK(classify((u8)127) == 7);
  return 0;
}
