// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((((29 / 13 && 39)) == 24) == (0));
STATIC_CHECK((!((37 != 31) * 3)) == (0));
STATIC_CHECK(((30 == 18) + 9) == (9));
STATIC_CHECK(((((10 ? 36 : 24) ^ 7)) << -(27 == 38)) == (35));
STATIC_CHECK((((29 ^ ~ 0)) != 21) == (1));
STATIC_CHECK((27 && 22 ? (0 ? 1 : 33) : (20) * 17) == (33));
STATIC_CHECK((9 == (((2 || 6) & 39 + 31) - 23 & (0 != (23 || 5)) < 29)) == (0));
STATIC_CHECK((7) == (7));
STATIC_CHECK((31) == (31));
STATIC_CHECK((16 == (28 ^ 31)) == (0));
STATIC_CHECK((33) == (33));
STATIC_CHECK((0) == (0));
STATIC_CHECK((11 * 29) == (319));
STATIC_CHECK((16) == (16));
STATIC_CHECK((11 + 37 && 25) == (1));
STATIC_CHECK((2 * 33 + 36 >= 9) == (1));
STATIC_CHECK((~(25 % 23)) == (-3));
STATIC_CHECK(((35 > 13) / ~ 24) == (0));
STATIC_CHECK((~ 38 == ! 32 ? ((24 > 12 / 33) + (~ 15 - 18 * 37) ? (5 < 12 != (11 ? 8 : 4)) / 25 : 37) : (30 > (30 * 21 || 18 != 9)) + (34 % 1 && !(35 ^ 12))) == (1));
STATIC_CHECK((19) == (19));
STATIC_CHECK(((35 ? 6 : 11) * 4) == (24));
STATIC_CHECK((33) == (33));
STATIC_CHECK(((((25 <= 2 % 2) && 22) >= ((22 == 25) > 38 / 39) % 36) + 3) == (4));
STATIC_CHECK(((3 ^ 17) % (28 % 22)) == (0));
STATIC_CHECK((12) == (12));
