// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((23 * (24 > (! 32 ^ 30))) == (0));
STATIC_CHECK(((~(9 && 34)) | (13 || 30 - 17)) == (-1));
STATIC_CHECK((((! 24 ? (22 ? 33 : 4) : 21) || 6) >= 27 ? (21 ? (13 || 38) == ((34 ? 3 : 7)) - (5 == 36) : 9 + ((25 < 24) + (6 ^ 31))) : 32 ? 7 : 6) == (7));
STATIC_CHECK((((21 <= 31 & (12 && 32)) >> ((31 ^ 31) & 9) ? 19 / 18 != 31 < 29 ^ (19 ^ 9) > (27 ^ 26) : 12) - (2 ? 19 : (18 | 6) ^ 18 * 15 ? 24 ^ 32 : 13 != 35 ? 36 >> 1 : 0 + 4)) == (-19));
STATIC_CHECK((34) == (34));
STATIC_CHECK((((31 && 26) <= (26 || 34)) << 0) == (1));
STATIC_CHECK((6) == (6));
STATIC_CHECK(((9 ? 12 < 33 != - 32 : ((26) >= 36) * (27 + 3)) > (4 ? 28 / 3 >> ((39) >= 30) : (4 && 12) % 2)) == (0));
STATIC_CHECK((6 < ((19 ^ 31) > ! 5 | ((27) > 27) + (17 ? 28 : 37)) - (((13 | 39)) ^ 11 * 37 | (25 && 3) * (37 != 2))) == (0));
STATIC_CHECK((13) == (13));
STATIC_CHECK((((16 ^ 4)) < (34 == 30)) == (0));
STATIC_CHECK((~(8 >= 3)) == (-2));
STATIC_CHECK((16 > 31 >= 33) == (0));
STATIC_CHECK((((25 / (24 * 11)) - 13) * ((8 == 22 + 12) == (36 == 37) << (28 || 14))) == (-13));
STATIC_CHECK((4) == (4));
STATIC_CHECK((- 27 - 13 || 25) == (1));
STATIC_CHECK((~ - 4) == (3));
STATIC_CHECK((13) == (13));
STATIC_CHECK((18) == (18));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((26 < 13) && 8) == (0));
STATIC_CHECK((((39 + 26 ? (17) + 1 : 21 < 7) == ((! 39) != ((13) || 30))) * ((21 ? 29 - 3 : 27 >= 0) | 9 > 6 <= 4)) == (0));
STATIC_CHECK(((31 | 18 != 10) != ((15 % 14 - (21 < 16)) / ((36) > (33 ? 35 : 4)) & 15)) == (1));
STATIC_CHECK((7) == (7));
STATIC_CHECK(((18) ^ (26 ^ 9) + 34) == (39));
