// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((-((31 && 10) >> 0) > (-(22 + 35) & 38) == 14) == (0));
STATIC_CHECK((27) == (27));
STATIC_CHECK((((13) * ((16 != 23) % 20)) ^ (5 * 4 == (29 || 17)) > ((26 ^ 0) >= 1)) == (13));
STATIC_CHECK((! 15 * (27 | ~(29 & 25))) == (0));
STATIC_CHECK((38) == (38));
STATIC_CHECK(((6 >> 11) % 32) == (0));
STATIC_CHECK(((16 & 8 + 25 << ((20) != 4)) >> 5) == (0));
STATIC_CHECK(((7 ? (30 && 11) + (37 ? 38 : 29) >> ((31) * 2 != 17 <= 11) : (! 31 ? 20 : 4 != 30) >= (12 != 9)) && 28) == (1));
STATIC_CHECK(((13 >= 17 || 26) + (20 == 30 | 38 == 21)) == (1));
STATIC_CHECK((8 ? ~(20 & 34) : 20 ? 4 : 28 >> 1) == (-1));
STATIC_CHECK((3 || 11 * (((37) < 14) * (32 / 29))) == (1));
STATIC_CHECK((((22 <= 36 || 1 / 10) < 35 ? (34 ? 7 : 36) * 23 != (28 ? 22 : 36) * - 19 : ((2 & 20 ^ 6 << 1)) + ((31) / 3 - (33 || 37))) >= (! - - 14 > 29)) == (1));
STATIC_CHECK(((39 < ((30) ^ ~ 2)) << 5) == (0));
STATIC_CHECK((19 == 25) == (0));
STATIC_CHECK(((21 != 22 << 1) <= -(39 / 22) ? 9 : (22 <= 25 & (26 ^ 32)) > 9 % 21 + (2 == 7)) == (0));
STATIC_CHECK((35 + (36 / 3 == 14 == 17 && 6)) == (35));
STATIC_CHECK((23 - ((0 - 19 != (13 ? 17 : 33)) >= ((23) == 2 ? 32 : 27 - 36))) == (22));
STATIC_CHECK((25) == (25));
STATIC_CHECK((36) == (36));
STATIC_CHECK((((24 | 15 >= 33 ? 8 ^ (6) >= 31 : 5 >= 6 >= (11 || 35)) && (21 ^ 15 ^ 10 * 15) * (8 < (25 < 22))) * ((((36 & 30)) == 30 ? 5 : 28) & (2 | 6 & 7) << 1)) == (0));
STATIC_CHECK((5 << !((7 ? 37 : 31) || 27 + 17)) == (5));
STATIC_CHECK(((!(32 || 35)) || 2) == (1));
STATIC_CHECK(((14 << 0) - (25 ^ 31)) == (8));
STATIC_CHECK(((33 < 39 <= 39) >> (20 > 37 <= 9)) == (0));
STATIC_CHECK(((35 || 14 >> 4) * 9 + (32) / ((31 > 29) - 2)) == (-23));
