// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((((((28 ? 38 : 21) ? 36 <= 7 : 22)) & (22 * 20) - (24 != 8) ? 27 || ~ 39 < (21 ^ 7) : 22) == (13 || ((24) && 30) <= (32 <= 16)) - 11) == (0));
STATIC_CHECK((19) == (19));
STATIC_CHECK((4 | 3 ? 18 * 4 : 2) == (72));
STATIC_CHECK(((16) && 7 + 3) == (1));
STATIC_CHECK((18) == (18));
STATIC_CHECK(((! ~ 18 | (11 == 31 || 35 < 32)) >> ((21 || 39 || (1) + 3) < 2) ? 32 && 6 : (5 - (11 > 15)) % 10 < 37) == (1));
STATIC_CHECK((~(38 > 3 == 28 * 39 && (21 ? 26 : 27) >= ! 14) ? (10 <= 3) - ((- 39 ? 28 < 24 : 0 >= 2) >= !((21) <= 38)) : 25) == (-1));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((7) / 9) == (0));
STATIC_CHECK((35 * 1 << (0 < 10 != (1 | 0))) == (35));
STATIC_CHECK((~ 22) == (-23));
STATIC_CHECK((((0 && 22) <= 4 | 0) + (((27 ^ 13) << (29 && 3)) - (~ 30 <= 13)) || 20 != ! 1 >= 4 && 4) == (1));
STATIC_CHECK((30 % 19 || (7) >> 7) == (1));
STATIC_CHECK((-(38 < 1)) == (0));
STATIC_CHECK(((38 == 12 & 0 % 8) / (9 * 26 % 5) <= 5) == (1));
STATIC_CHECK((6) == (6));
STATIC_CHECK((6 % 37 || (17) + 30) == (1));
STATIC_CHECK(((0 + 9 <= 23 ? (3 >= 11) >> ((26) >= 14) : (30 ^ 16) - (11 < 6)) ^ ~ -(27 && 7)) == (0));
STATIC_CHECK((2 || 5 > 21) == (1));
STATIC_CHECK(((28) <= 37 <= (21 < 3) >= (30 && 32) - (31 ^ 16) > 36 ^ 15) == (15));
STATIC_CHECK((24) == (24));
STATIC_CHECK((8) == (8));
STATIC_CHECK(((~(14 == ((26) == 23)) != (18 && 32 | 27 + 7)) >= 4 * (2 <= ((6 ? 2 : 9) < 19))) == (1));
STATIC_CHECK((22) == (22));
STATIC_CHECK((15 <= 0) == (0));
