// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((11) == (11));
STATIC_CHECK(((39 & ((21) != 2 && 35 / 33) || 26 < 6 < 21 + 18 ^ (33 | 4) == 22 < 38) && 4) == (1));
STATIC_CHECK((23) == (23));
STATIC_CHECK((9) == (9));
STATIC_CHECK((13 % 19 * 29) == (377));
STATIC_CHECK((34 | - 18 < 23 >= (9 - 20 | 13)) == (35));
STATIC_CHECK((32) == (32));
STATIC_CHECK(((1 ? 1 : 0) | 19 + 38) == (57));
STATIC_CHECK((!(37 & 5) ? 27 + 4 : 17) == (17));
STATIC_CHECK(((29) ^ 16 | 35) == (47));
STATIC_CHECK((12 ^ ~(13 >= 31 && (22) | 7)) == (-13));
STATIC_CHECK(((17 & 27) > (37 | 7)) == (0));
STATIC_CHECK((17) == (17));
STATIC_CHECK((25) == (25));
STATIC_CHECK(((2 ? 38 : 39) <= (16 | 23) ? (20 == 18) - 14 % 35 : (21) <= ((12) == 0)) == (0));
STATIC_CHECK((((28 ^ 19) == 1) <= 3) == (1));
STATIC_CHECK(((20 && 6) < 9) == (1));
STATIC_CHECK(((-(39 ? 21 : 6) ? (27 && 5) == (4 != 22) : 10 / 11 % 5) >> (30 & (7 & 16) != 10)) == (1));
STATIC_CHECK((3 >> (30 >= 34 % 15) ? (26 && 1) <= 4 % (25 != 23) : 6 ? ~ 0 || 30 / 17 : (28 | 26) ^ 17) == (0));
STATIC_CHECK((- 11 - 13 % 39) == (-24));
STATIC_CHECK((2 << 5) == (64));
STATIC_CHECK((!((18 | 17) + (34 ^ 2) <= -(14 <= 0))) == (1));
STATIC_CHECK((3) == (3));
STATIC_CHECK((!((3) || 1 ? ! 11 : 1)) == (1));
STATIC_CHECK((~ 26 * ((29) & 19)) == (-459));
