// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((! 15) == (0));
STATIC_CHECK(((17 / 10 & (39 ^ 37)) + (! 16 <= (2 < 23))) == (1));
STATIC_CHECK((-(1 == 27)) == (0));
STATIC_CHECK((24) == (24));
STATIC_CHECK((!((29 ^ 14) % 25)) == (0));
STATIC_CHECK((! 23) == (0));
STATIC_CHECK((11 & 5 != 21) == (1));
STATIC_CHECK(((8 < 39 >= 3 >> 10 > 16) >> (26 || 6 >= (11 ^ 30))) == (0));
STATIC_CHECK((11 * (31 != 36) + (36 > 1 == 36 >= 24)) == (12));
STATIC_CHECK((~(3 / 31 ? 20 : 38 - 30) <= 23 % 39 * (24 || 37) * 9) == (1));
STATIC_CHECK(((29) >> 1 ^ 22 << (12 == 24)) == (24));
STATIC_CHECK((1) == (1));
STATIC_CHECK(((26 != (23 == 9) == 0) >> ((7 ? 13 : 4) << 8 >= (19 * 15 && 6))) == (0));
STATIC_CHECK((37) == (37));
STATIC_CHECK(((37 > 32) << 22 / 39 == (12 % 32 || 32)) == (1));
STATIC_CHECK((18) == (18));
STATIC_CHECK(((((33) <= (19 != 32) + (37 < 10))) - ((3 || 3) > (2 != 0) ^ 2) != 22) == (1));
STATIC_CHECK((~ 4) == (-5));
STATIC_CHECK((18) == (18));
STATIC_CHECK((29) == (29));
STATIC_CHECK((19 ? (21) <= 31 != (20 | 31 > 1) - ((21 != 29) < 15) : 27 ? -((3) || 27) : 20 < 28) == (1));
STATIC_CHECK(((14 <= 6) && (5 / 3 != 22) > ((18 && 37) <= (20 ^ 24))) == (0));
STATIC_CHECK((-(-(16 ^ 4 > 33) && (34 & 15 ? 1 || 31 : 30 - 4) > ((37) + 0) << (5 & 0))) == (0));
STATIC_CHECK(((((6 < 17)) - (0 & 35)) * ((37) & 24 ? 9 >> 0 : - 34)) == (-34));
STATIC_CHECK((20 != (6 + (2 && 29 ? 32 && 32 : 23 >= 2) || (38 + 0 ? (39) * 26 : 28 / 10) >> (3 < (36 <= 9)))) == (1));
