// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((10 << (2 || 24 * 7 << (21 ^ 17))) == (20));
STATIC_CHECK((11) == (11));
STATIC_CHECK((19 < - 13) == (0));
STATIC_CHECK((25) == (25));
STATIC_CHECK((-(13 / 16)) == (0));
STATIC_CHECK((17) == (17));
STATIC_CHECK((((31) >= 34) % (2 & 6)) == (0));
STATIC_CHECK((~((8 | 2) > (19 > 20) ? 35 : 14 <= (35 > 21))) == (-36));
STATIC_CHECK((16 >= 39 != ~ 17 - 35 == ((27 ^ 10) >> (28 != 7)) - 30) == (0));
STATIC_CHECK((1) == (1));
STATIC_CHECK((((36) >= 21 - 15) % 20) == (1));
STATIC_CHECK((((33 & 12) != ((1 && 18 ? 4 : 29 || 8) || 2)) * (((~ 31) >= ((32 || 17) != 28)) / (22 && 2))) == (0));
STATIC_CHECK(((3 || 1) && (36 || 9)) == (1));
STATIC_CHECK((25) == (25));
STATIC_CHECK(((25 - 37 >= 26 % 7) / (17 % 8 && (27 ? 21 : 37)) >> (26 > (6 >= 33) < ((36 & 31) < (15 || 23))) ? 9 % 39 : 30 || (3 > 30) + (0 << 13) && (37 - 1 ? 6 * 9 : 3)) == (1));
STATIC_CHECK((-((15) - 12 > 35 < (31 <= 2 <= (13 && 23)) == ((28 + 11 | ~ 38)) % (37 / 9 != 23 % 26))) == (0));
STATIC_CHECK((-(23 == 13) != 16 >= 10 <= (33 != 2)) == (1));
STATIC_CHECK((28) == (28));
STATIC_CHECK(((19) | 25 && 26 ^ 25) == (1));
STATIC_CHECK((((((9) & 4) < (13 ? 11 : 37))) << !(24 || 5)) == (1));
STATIC_CHECK(((12 || 33 % 13) - (32 / 34 << 7 % 37)) == (1));
STATIC_CHECK(((33 & 13) == (7 & 0)) == (0));
STATIC_CHECK(((((34) && 29) < (2 > 4)) % (35 >= 18 ? 1 | 32 : 13 % 19)) == (0));
STATIC_CHECK((36) == (36));
STATIC_CHECK((((6 | 15) >= 10 ? (15) % 25 % ~ 15 : 31) ? 37 < ! 18 > (13 * 34 > 8 % 20) : (22 >= 28) % (31 < 33) / ((8 % 13) != 21 >= 18)) == (0));
