// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK(((32 + 26) / (20 || 37)) == (58));
STATIC_CHECK((! 6) == (0));
STATIC_CHECK((13 & 23 ? 11 * 15 : 11 + 9) == (165));
STATIC_CHECK((32) == (32));
STATIC_CHECK(((12) <= 6) == (0));
STATIC_CHECK((31) == (31));
STATIC_CHECK((!((8 + (7 ^ 39)) <= (((38) ^ 6) >= 5))) == (1));
STATIC_CHECK((!(27 & 17) >= 2) == (0));
STATIC_CHECK(((27 ? 16 : 19) + (33 ^ 34) < (15 ^ 13)) == (0));
STATIC_CHECK((-((10 <= 7 <= ~ 22 ? (37 - 11) / ((11) ^ 5) : (12) >= (19 || 11)) / 2)) == (0));
STATIC_CHECK((12 * (~ 4 ^ 30 >> 9) - ((3) * 28 <= 33) ^ 5 >= 3 != (16 ? 22 : 21) == 22 > ((21) ^ 27) & 37) == (-59));
STATIC_CHECK((0) == (0));
STATIC_CHECK((37 + (18 > (35 && (26 || 14)))) == (38));
STATIC_CHECK((1 == (6 >= 0 ? 6 >= 22 : 36 ? 35 : 3) > 13) == (0));
STATIC_CHECK((- -(11 >= (12 ? 19 : 12)) + ~((37 & 34) * 28 ? 17 % 34 % ~ 35 : 28)) == (-18));
STATIC_CHECK((2 <= 2) == (1));
STATIC_CHECK((15) == (15));
STATIC_CHECK(((33 || !(23 != 8) / - 8) >= - 5) == (1));
STATIC_CHECK((34 || 21 % (25 ^ 28) ^ 8 * (9 && 17)) == (1));
STATIC_CHECK((18 % 15 < ~ 13 >= 6 || 29 == (15 == 35) & 33 >= 33 != 14 / 18) == (0));
STATIC_CHECK((- 9 * ~ 3 < (4 * 19 & 17 == 21)) == (0));
STATIC_CHECK((32 << (14 < 29)) == (64));
STATIC_CHECK((16 != 23) == (1));
STATIC_CHECK((23 || (6 || (14 + 39 || 1))) == (1));
STATIC_CHECK((29 != ~(- 1 ? 18 : 9 || 32)) == (1));
