// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((6) == (6));
STATIC_CHECK((2) == (2));
STATIC_CHECK((22) == (22));
STATIC_CHECK((26) == (26));
STATIC_CHECK((~(7 ? 7 : 18) - (33 - 16 << 2) ? ((17 - 3) || 13 * 35) >= 17 : (20 <= 30 == 28) * ~ 31) == (0));
STATIC_CHECK(((39 ? 39 : 32) - (17 + 29)) == (-7));
STATIC_CHECK((30) == (30));
STATIC_CHECK((! 10 - (2 && 39)) == (-1));
STATIC_CHECK(((7 - 9) / (9 > 19 >> 8)) == (-2));
STATIC_CHECK((10 * 21) == (210));
STATIC_CHECK((21 & 24 ? (18 ? 37 : 11) : 9 < 14) == (37));
STATIC_CHECK((6 >= 9) == (0));
STATIC_CHECK((34) == (34));
STATIC_CHECK((!(25 / 31 ? 39 : 21 < 19) ^ 4) == (5));
STATIC_CHECK((! 19 < 11) == (1));
STATIC_CHECK(((4) <= 27 <= (25 >= (14 > 37))) == (1));
STATIC_CHECK((32) == (32));
STATIC_CHECK((26 || 23 + 29) == (1));
STATIC_CHECK((8 * 3 >= 8 * 33) == (0));
STATIC_CHECK((31) == (31));
STATIC_CHECK(((7) && 14 * 21) == (1));
STATIC_CHECK(((0) / ~ 1 & ! 27) == (0));
STATIC_CHECK(((26 ? (! 35 ^ 20 != 21 ? (25 <= 9) <= ~ 26 : 22 == 3 | ! 9) : ((33 == 13) > 11) / 23) << (28 * 36 >= (6 != 36) & 36 ? 19 - (30 > 25) : ~ ~ 4 & 30)) == (0));
STATIC_CHECK((6) == (6));
STATIC_CHECK((12 > 4) == (1));
