// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((8 == 38 == (0 == 23)) == (1));
STATIC_CHECK((((22 > 38 < 8 && 21 <= (15 != 38))) != (12 < 22 ? 13 : 38 ? 14 : 23) >= !(27 ? 4 : 0)) == (1));
STATIC_CHECK((38 < 1 > (31 != 1)) == (0));
STATIC_CHECK((~((20 || 36) * (24 - 20) + (2 / 9 != (20 ? 38 : 26))) != (20 ^ 3) * (22 ? 39 : 22) * ((5 && 8) < (16 > 18)) <= (30 ? - 10 > 23 : (35 & 7) > 9)) == (1));
STATIC_CHECK((10 == (2 ? 27 : 34)) == (0));
STATIC_CHECK(((13 || 9) <= (23 ? 36 : 39) && (2 ? 22 : 5) + 38) == (1));
STATIC_CHECK((31 & 4 | 14 / 22) == (4));
STATIC_CHECK((13 + (1 < 19)) == (14));
STATIC_CHECK(((15 ? 16 : 10) <= (10 && 30) || 0) == (0));
STATIC_CHECK(((28 < (- 17 ? 8 ^ 19 : (18) >> 1) ? (23 ? 17 : 9) * 4 / (~ 32 || (21) != 2) : 5) != 0 <= 29) == (1));
STATIC_CHECK((25 % 17 >= ((30 != 15) / 22 ? ! 10 : 3 / 20 | 15) & 24) == (0));
STATIC_CHECK((~(28 < 29) && (31 && 18 ? 24 | 27 : (28) <= 13)) == (1));
STATIC_CHECK(((33) < 21 ^ 19 & 1 | (8 << 1) / 5) == (3));
STATIC_CHECK((~ 30 * 13 % ((2 <= 3) * (1 ^ 32))) == (-7));
STATIC_CHECK((-(30 % (33 - 39))) == (0));
STATIC_CHECK((7) == (7));
STATIC_CHECK((((6 % ((36 <= 27) + 36) ^ 16 <= ((37 | 6)) - 7)) << ! 7) == (7));
STATIC_CHECK((~(25 >= (32 & ! 6))) == (-2));
STATIC_CHECK(((2 & 1 ? 24 + 16 : 22 >= 2) + ((8 < 10) << (39 != 11))) == (3));
STATIC_CHECK((30) == (30));
STATIC_CHECK(((!(27 * 14)) % (- 14 <= (17 < 14)) ? (5 ? 38 ^ 27 < 1 : -(7 < 27)) : 27 ? 25 <= 0 != (7 & 3) : (29 ^ 4) != 23) == (1));
STATIC_CHECK((29 & 33 || 4 < 33 ? 8 | 20 ^ 38 : 5) == (58));
STATIC_CHECK(((4) | 21 || - 6) == (1));
STATIC_CHECK(((24 ? 15 : 3) + (5 == 9)) == (15));
STATIC_CHECK((!(16 | 33) - (37 < 7 && 7)) == (0));
