// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((18) == (18));
STATIC_CHECK((~ 34 >> 6) == (-1));
STATIC_CHECK((12 ? (13 ? 8 < 1 : 32 == 33) || 27 > 20 / 25 : 39) == (1));
STATIC_CHECK((! 35 >> 11) == (0));
STATIC_CHECK((((4) + 21) >= (6 ? 17 : 6)) == (1));
STATIC_CHECK((24) == (24));
STATIC_CHECK((35) == (35));
STATIC_CHECK((- 15 && 29 / 10) == (1));
STATIC_CHECK((17) == (17));
STATIC_CHECK((((11 ? 33 && 11 : 21 % 23) && ! 29 % (26 % 15)) * -(24 / 26 == 3 >= 12) + (38 == (16 ? - 16 : 1 ? 23 : 17) || (38 == - 25) ^ (22 - 30 || 21 / 33))) == (1));
STATIC_CHECK(((-((28) | 38) > (- 6 ? (38) >= 1 : 12 == 21) & 15) < ((18 - 11 < 4) + (26 + 30 ? 39 >> 7 : 18 << 2) ? ((22 >= 3) - 12 ? (17 == 39) + 25 : 0) : -(29 && 25))) == (0));
STATIC_CHECK((16 + (! 13) / ((33 ? 37 : 9) <= (30 <= 16) ? 2 : !(16 < 9))) == (16));
STATIC_CHECK((((8) || 29) + (18 <= 30)) == (2));
STATIC_CHECK((16 >= (((22) > 38) > ~ 1 ? (39 ? 6 : 36) / (29 > 18) : (34 ^ 10) > 39)) == (1));
STATIC_CHECK((24) == (24));
STATIC_CHECK((17 - (((10 ? 21 : 25)) > 37)) == (17));
STATIC_CHECK((~ 12) == (-13));
STATIC_CHECK((-((31) * 34) <= (21 > 21 != 8) != (! 26) >= (14 && 23 ^ 21)) == (1));
STATIC_CHECK((39 != 17 / 9) == (1));
STATIC_CHECK((((22 ? 16 : 20) << (32 && 14) ^ (33 - 9 | ~ 24)) == 0 << (29 || 18) + (2 >= 5) | 25 != (- 19 ^ - 14 <= 23)) == (1));
STATIC_CHECK((!((14) || 0)) == (0));
STATIC_CHECK((39 * 5 == (15 ? 0 : 6)) == (0));
STATIC_CHECK(((23 > 32) - ((1) && 20)) == (-1));
STATIC_CHECK((30) == (30));
STATIC_CHECK((((7 + 19 && 38 == 11 || 8) ^ (2 << 9 || 24) * ((23 <= 3) >> (31 != 5))) % (((- 18 ? 11 + 23 : 12) && (14 - 29 ? 22 < 39 : ! 9)) + ((30 ? 28 : 6) < (31 ? 12 : 36) != 21 / 3 * (16 & 9)))) == (0));
