// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random int expressions with the minimum of parentheses: C's precedence and
// associativity decide the value (no expression overflows 16 bits).
#include "loomcc-test.h"
STATIC_CHECK((34 != (~ 20 ^ 2 <= 1)) == (1));
STATIC_CHECK((((16 > 11 & 4)) + (6 % 38 || 31 == 27)) == (1));
STATIC_CHECK((! 21 > ((13 % 33 * (33 > 20) ? 0 : (37 ^ 5) - (23 - 13)) == 16)) == (0));
STATIC_CHECK((12 << (8 || 12)) == (24));
STATIC_CHECK((22 != 32) == (1));
STATIC_CHECK((-(((20 > 26 ^ 4 == 1 == (3 ? 20 : 10))) != 36)) == (-1));
STATIC_CHECK((29 && 9 | 10) == (1));
STATIC_CHECK((32 == 20 > 35) == (0));
STATIC_CHECK((35 | 22) == (55));
STATIC_CHECK((((21) >= 17 && 39 ^ 33 && 25 | (15 ? 30 : 9)) & 12) == (0));
STATIC_CHECK((6) == (6));
STATIC_CHECK((16 ? 23 | ((20) <= 21 && 24) : 5) == (23));
STATIC_CHECK((((28 != 30 || 4) / 3 >= 0) != 6) == (1));
STATIC_CHECK((3) == (3));
STATIC_CHECK(((((- 19) ^ 15 / 12) * ((21 && 23) - (32 & 15)) ^ ((14 | 15) & 24) == 0 < 24 <= (34 < 10)) >> (35 && 2 * 35 >= 22 + 20 <= (15 >= 39 < 29 % 35))) == (-10));
STATIC_CHECK(((16) == ((35 / 4) <= (28 ? 35 : 23)) * 3) == (0));
STATIC_CHECK((- !(27 >> 4) / (2 > 18 / 11 && 19 & 5 | 26)) == (0));
STATIC_CHECK((-(21 | 12) == (18 == 29) * 19) == (0));
STATIC_CHECK((28 & 10) == (8));
STATIC_CHECK((17 > (29 <= (0 >= 18 | 29 != 2) > ((37 <= 28) << 2 >= (34 >= 36 <= 21)))) == (1));
STATIC_CHECK(((!(16 * 35)) & ~(6 >= 24)) == (0));
STATIC_CHECK(((30 == 1) < (22 | 24 <= 12)) == (1));
STATIC_CHECK((9 << ((19 ? 15 : 14) < 17 + 31)) == (18));
STATIC_CHECK(((2) + 29 != 7) == (1));
STATIC_CHECK((- 4 < (15 == 15)) == (1));
