// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// min, max, clamp on u16.
#include "loomcc-test.h"
#define MIN(a, b) ((a) < (b) ? (a) : (b))
static volatile u16 x, y;
static u16 max_fn(u16 a, u16 b) { return a > b ? a : b; }
static u16 clamp_fn(u16 v, u16 lo, u16 hi) { return v < lo ? lo : v > hi ? hi : v; }
int main(void) {
  x = 0u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(0));
  x = 0u; y = 255u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(255));
  x = 0u; y = 32767u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 0u; y = 65535u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 1u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(1));
  x = 1u; y = 255u; CHECK(MIN(x, y) == (u16)(1)); CHECK(max_fn(x, y) == (u16)(255));
  x = 1u; y = 32767u; CHECK(MIN(x, y) == (u16)(1)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 1u; y = 65535u; CHECK(MIN(x, y) == (u16)(1)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 2u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(2));
  x = 2u; y = 255u; CHECK(MIN(x, y) == (u16)(2)); CHECK(max_fn(x, y) == (u16)(255));
  x = 2u; y = 32767u; CHECK(MIN(x, y) == (u16)(2)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 2u; y = 65535u; CHECK(MIN(x, y) == (u16)(2)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 255u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(255));
  x = 255u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(255));
  x = 255u; y = 32767u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 255u; y = 65535u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 256u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(256));
  x = 256u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(256));
  x = 256u; y = 32767u; CHECK(MIN(x, y) == (u16)(256)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 256u; y = 65535u; CHECK(MIN(x, y) == (u16)(256)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 1000u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(1000));
  x = 1000u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(1000));
  x = 1000u; y = 32767u; CHECK(MIN(x, y) == (u16)(1000)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 1000u; y = 65535u; CHECK(MIN(x, y) == (u16)(1000)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 32767u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 32767u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 32767u; y = 32767u; CHECK(MIN(x, y) == (u16)(32767)); CHECK(max_fn(x, y) == (u16)(32767));
  x = 32767u; y = 65535u; CHECK(MIN(x, y) == (u16)(32767)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 32768u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(32768));
  x = 32768u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(32768));
  x = 32768u; y = 32767u; CHECK(MIN(x, y) == (u16)(32767)); CHECK(max_fn(x, y) == (u16)(32768));
  x = 32768u; y = 65535u; CHECK(MIN(x, y) == (u16)(32768)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 40000u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(40000));
  x = 40000u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(40000));
  x = 40000u; y = 32767u; CHECK(MIN(x, y) == (u16)(32767)); CHECK(max_fn(x, y) == (u16)(40000));
  x = 40000u; y = 65535u; CHECK(MIN(x, y) == (u16)(40000)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 65535u; y = 0u; CHECK(MIN(x, y) == (u16)(0)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 65535u; y = 255u; CHECK(MIN(x, y) == (u16)(255)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 65535u; y = 32767u; CHECK(MIN(x, y) == (u16)(32767)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 65535u; y = 65535u; CHECK(MIN(x, y) == (u16)(65535)); CHECK(max_fn(x, y) == (u16)(65535));
  x = 0u; CHECK(clamp_fn(x, 10, 200) == (u16)(10));
  x = 1u; CHECK(clamp_fn(x, 10, 200) == (u16)(10));
  x = 2u; CHECK(clamp_fn(x, 10, 200) == (u16)(10));
  x = 255u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 256u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 1000u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 32767u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 32768u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 40000u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  x = 65535u; CHECK(clamp_fn(x, 10, 200) == (u16)(200));
  return 0;
}
