// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// min, max, clamp and abs on i16.
#include "loomcc-test.h"
#define MIN(a, b) ((a) < (b) ? (a) : (b))
static volatile i16 x, y;
static i16 max_fn(i16 a, i16 b) { return a > b ? a : b; }
static i16 clamp_fn(i16 v, i16 lo, i16 hi) { return v < lo ? lo : v > hi ? hi : v; }
static i16 abs_fn(i16 v) { return (i16)(v < 0 ? -v : v); }
int main(void) {
  x = (-32767 - 1); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-32768));
  x = (-32767 - 1); y = (-256); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-256));
  x = (-32767 - 1); y = (1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(1));
  x = (-32767 - 1); y = (32767); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (-32767); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-32767));
  x = (-32767); y = (-256); CHECK(MIN(x, y) == (i16)(-32767)); CHECK(max_fn(x, y) == (i16)(-256));
  x = (-32767); y = (1); CHECK(MIN(x, y) == (i16)(-32767)); CHECK(max_fn(x, y) == (i16)(1));
  x = (-32767); y = (32767); CHECK(MIN(x, y) == (i16)(-32767)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (-1000); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-1000));
  x = (-1000); y = (-256); CHECK(MIN(x, y) == (i16)(-1000)); CHECK(max_fn(x, y) == (i16)(-256));
  x = (-1000); y = (1); CHECK(MIN(x, y) == (i16)(-1000)); CHECK(max_fn(x, y) == (i16)(1));
  x = (-1000); y = (32767); CHECK(MIN(x, y) == (i16)(-1000)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (-256); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-256));
  x = (-256); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(-256));
  x = (-256); y = (1); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(1));
  x = (-256); y = (32767); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (-1); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(-1));
  x = (-1); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(-1));
  x = (-1); y = (1); CHECK(MIN(x, y) == (i16)(-1)); CHECK(max_fn(x, y) == (i16)(1));
  x = (-1); y = (32767); CHECK(MIN(x, y) == (i16)(-1)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (0); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(0));
  x = (0); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(0));
  x = (0); y = (1); CHECK(MIN(x, y) == (i16)(0)); CHECK(max_fn(x, y) == (i16)(1));
  x = (0); y = (32767); CHECK(MIN(x, y) == (i16)(0)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (1); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(1));
  x = (1); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(1));
  x = (1); y = (1); CHECK(MIN(x, y) == (i16)(1)); CHECK(max_fn(x, y) == (i16)(1));
  x = (1); y = (32767); CHECK(MIN(x, y) == (i16)(1)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (2); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(2));
  x = (2); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(2));
  x = (2); y = (1); CHECK(MIN(x, y) == (i16)(1)); CHECK(max_fn(x, y) == (i16)(2));
  x = (2); y = (32767); CHECK(MIN(x, y) == (i16)(2)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (255); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(255));
  x = (255); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(255));
  x = (255); y = (1); CHECK(MIN(x, y) == (i16)(1)); CHECK(max_fn(x, y) == (i16)(255));
  x = (255); y = (32767); CHECK(MIN(x, y) == (i16)(255)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (32767); y = (-32767 - 1); CHECK(MIN(x, y) == (i16)(-32768)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (32767); y = (-256); CHECK(MIN(x, y) == (i16)(-256)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (32767); y = (1); CHECK(MIN(x, y) == (i16)(1)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (32767); y = (32767); CHECK(MIN(x, y) == (i16)(32767)); CHECK(max_fn(x, y) == (i16)(32767));
  x = (-32767 - 1); CHECK(clamp_fn(x, -100, 100) == (i16)(-100));
  x = (-32767); CHECK(clamp_fn(x, -100, 100) == (i16)(-100));
  x = (-1000); CHECK(clamp_fn(x, -100, 100) == (i16)(-100));
  x = (-256); CHECK(clamp_fn(x, -100, 100) == (i16)(-100));
  x = (-1); CHECK(clamp_fn(x, -100, 100) == (i16)(-1));
  x = (0); CHECK(clamp_fn(x, -100, 100) == (i16)(0));
  x = (1); CHECK(clamp_fn(x, -100, 100) == (i16)(1));
  x = (2); CHECK(clamp_fn(x, -100, 100) == (i16)(2));
  x = (255); CHECK(clamp_fn(x, -100, 100) == (i16)(100));
  x = (32767); CHECK(clamp_fn(x, -100, 100) == (i16)(100));
  x = (-32767); CHECK(abs_fn(x) == (i16)(32767));
  x = (-1000); CHECK(abs_fn(x) == (i16)(1000));
  x = (-256); CHECK(abs_fn(x) == (i16)(256));
  x = (-1); CHECK(abs_fn(x) == (i16)(1));
  x = (0); CHECK(abs_fn(x) == (i16)(0));
  x = (1); CHECK(abs_fn(x) == (i16)(1));
  x = (2); CHECK(abs_fn(x) == (i16)(2));
  x = (255); CHECK(abs_fn(x) == (i16)(255));
  x = (32767); CHECK(abs_fn(x) == (i16)(32767));
  return 0;
}
