// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// min, max, clamp on u8.
#include "loomcc-test.h"
#define MIN(a, b) ((a) < (b) ? (a) : (b))
static volatile u8 x, y;
static u8 max_fn(u8 a, u8 b) { return a > b ? a : b; }
static u8 clamp_fn(u8 v, u8 lo, u8 hi) { return v < lo ? lo : v > hi ? hi : v; }
int main(void) {
  x = 0; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(0));
  x = 0; y = 7; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(7));
  x = 0; y = 128; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(128));
  x = 1; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(1));
  x = 1; y = 7; CHECK(MIN(x, y) == (u8)(1)); CHECK(max_fn(x, y) == (u8)(7));
  x = 1; y = 128; CHECK(MIN(x, y) == (u8)(1)); CHECK(max_fn(x, y) == (u8)(128));
  x = 2; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(2));
  x = 2; y = 7; CHECK(MIN(x, y) == (u8)(2)); CHECK(max_fn(x, y) == (u8)(7));
  x = 2; y = 128; CHECK(MIN(x, y) == (u8)(2)); CHECK(max_fn(x, y) == (u8)(128));
  x = 7; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(7));
  x = 7; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(7));
  x = 7; y = 128; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(128));
  x = 100; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(100));
  x = 100; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(100));
  x = 100; y = 128; CHECK(MIN(x, y) == (u8)(100)); CHECK(max_fn(x, y) == (u8)(128));
  x = 127; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(127));
  x = 127; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(127));
  x = 127; y = 128; CHECK(MIN(x, y) == (u8)(127)); CHECK(max_fn(x, y) == (u8)(128));
  x = 128; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(128));
  x = 128; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(128));
  x = 128; y = 128; CHECK(MIN(x, y) == (u8)(128)); CHECK(max_fn(x, y) == (u8)(128));
  x = 200; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(200));
  x = 200; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(200));
  x = 200; y = 128; CHECK(MIN(x, y) == (u8)(128)); CHECK(max_fn(x, y) == (u8)(200));
  x = 255; y = 0; CHECK(MIN(x, y) == (u8)(0)); CHECK(max_fn(x, y) == (u8)(255));
  x = 255; y = 7; CHECK(MIN(x, y) == (u8)(7)); CHECK(max_fn(x, y) == (u8)(255));
  x = 255; y = 128; CHECK(MIN(x, y) == (u8)(128)); CHECK(max_fn(x, y) == (u8)(255));
  x = 0; CHECK(clamp_fn(x, 10, 200) == (u8)(10));
  x = 1; CHECK(clamp_fn(x, 10, 200) == (u8)(10));
  x = 2; CHECK(clamp_fn(x, 10, 200) == (u8)(10));
  x = 7; CHECK(clamp_fn(x, 10, 200) == (u8)(10));
  x = 100; CHECK(clamp_fn(x, 10, 200) == (u8)(100));
  x = 127; CHECK(clamp_fn(x, 10, 200) == (u8)(127));
  x = 128; CHECK(clamp_fn(x, 10, 200) == (u8)(128));
  x = 200; CHECK(clamp_fn(x, 10, 200) == (u8)(200));
  x = 255; CHECK(clamp_fn(x, 10, 200) == (u8)(200));
  return 0;
}
