// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern signed char (*v0)[7][7];
typedef signed char (*T0)[7][7];
extern unsigned short v1;
typedef unsigned short T1;
extern unsigned char v2[2];
typedef unsigned char T2[2];
extern unsigned (*v3)[5];
typedef unsigned (*T3)[5];
extern char **(*v4)(void);
typedef char **(*T4)(void);
extern long v5;
typedef long T5;
extern unsigned short *(*v6)(void);
typedef unsigned short *(*T6)(void);
extern char v7;
typedef char T7;
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == 7 * (7 * (1)));
STATIC_CHECK(sizeof((*v0)[1]) == 7 * (1));
STATIC_CHECK(sizeof((*v0)[1][1]) == 1);
STATIC_CHECK(sizeof(signed char (*)[7][7]) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 2 * (1));
STATIC_CHECK(sizeof(v2[1]) == 1);
STATIC_CHECK(sizeof(unsigned char [2]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == 5 * (sizeof(unsigned)));
STATIC_CHECK(sizeof((*v3)[1]) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (*)[5]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v4)())) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v4)()))) == 1);
STATIC_CHECK(sizeof(char **(*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6)())) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *(*)(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
