// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned v0;
typedef unsigned T0;
extern unsigned short v1;
typedef unsigned short T1;
extern signed char (*v2)[3][3];
typedef signed char (*T2)[3][3];
extern int v3;
typedef int T3;
extern short *v4[3];
typedef short *T4[3];
extern unsigned short v5[2];
typedef unsigned short T5[2];
extern int (*v6)[5];
typedef int (*T6)[5];
extern long (*v7)[5];
typedef long (*T7)[5];
STATIC_CHECK(sizeof(v0) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void *));
STATIC_CHECK(sizeof((*v2)) == 3 * (3 * (1)));
STATIC_CHECK(sizeof((*v2)[1]) == 3 * (1));
STATIC_CHECK(sizeof((*v2)[1][1]) == 1);
STATIC_CHECK(sizeof(signed char (*)[3][3]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == 3 * (sizeof(void *)));
STATIC_CHECK(sizeof(v4[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v4[1])) == sizeof(short));
STATIC_CHECK(sizeof(short *[3]) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 2 * (sizeof(short)));
STATIC_CHECK(sizeof(v5[1]) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short [2]) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 5 * (sizeof(int)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(int));
STATIC_CHECK(sizeof(int (*)[5]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == 5 * (sizeof(long)));
STATIC_CHECK(sizeof((*v7)[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (*)[5]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
