// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern char (*v0)(void);
typedef char (*T0)(void);
extern unsigned short v1;
typedef unsigned short T1;
extern unsigned short v2;
typedef unsigned short T2;
extern unsigned (**(*v3)(void))[3];
typedef unsigned (**(*T3)(void))[3];
extern long (*v4)(void);
typedef long (*T4)(void);
extern char v5;
typedef char T5;
extern long (*v6)[7];
typedef long (*T6)[7];
extern unsigned **v7;
typedef unsigned **T7;
STATIC_CHECK(sizeof(v0) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v0)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v3)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v3)())) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v3)()))) == 3 * (sizeof(unsigned)));
STATIC_CHECK(sizeof((*(*(*v3)()))[1]) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (**(*)(void))[3]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == sizeof(long));
STATIC_CHECK(sizeof(long (*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 7 * (sizeof(long)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(long));
STATIC_CHECK(sizeof(long (*)[7]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v7))) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned **) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
