// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short v0;
typedef unsigned short T0;
extern int **v1;
typedef int **T1;
extern int (*v2)(void);
typedef int (*T2)(void);
extern signed char v3[11];
typedef signed char T3[11];
extern short (*v4[5])(void);
typedef short (*T4[5])(void);
extern int (*v5)(void);
typedef int (*T5)(void);
extern unsigned (*v6)[2];
typedef unsigned (*T6)[2];
extern signed char v7;
typedef signed char T7;
STATIC_CHECK(sizeof(v0) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v1))) == sizeof(int));
STATIC_CHECK(sizeof(int **) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 11 * (1));
STATIC_CHECK(sizeof(v3[1]) == 1);
STATIC_CHECK(sizeof(signed char [11]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == 5 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v4[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4[1])()) == sizeof(short));
STATIC_CHECK(sizeof(short (*[5])(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v5)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void *));
STATIC_CHECK(sizeof((*v6)) == 2 * (sizeof(unsigned)));
STATIC_CHECK(sizeof((*v6)[1]) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned (*)[2]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 1);
STATIC_CHECK(sizeof(signed char) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
