// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned char v0;
typedef unsigned char T0;
extern int ***v1;
typedef int ***T1;
extern short (*(*v2[3])[5])(void);
typedef short (*(*T2[3])[5])(void);
extern int (*v3[3])(void);
typedef int (*T3[3])(void);
extern int v4;
typedef int T4;
extern unsigned short v5;
typedef unsigned short T5;
extern unsigned char *(*v6[3])[7];
typedef unsigned char *(*T6[3])[7];
extern unsigned v7;
typedef unsigned T7;
STATIC_CHECK(sizeof(v0) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void *));
STATIC_CHECK(sizeof((*v1)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v1))) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v1)))) == sizeof(int));
STATIC_CHECK(sizeof(int ***) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 3 * (sizeof(void *)));
STATIC_CHECK(sizeof(v2[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v2[1])) == 5 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof((*v2[1])[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v2[1])[1])()) == sizeof(short));
STATIC_CHECK(sizeof(short (*(*[3])[5])(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 3 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v3[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v3[1])()) == sizeof(int));
STATIC_CHECK(sizeof(int (*[3])(void)) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(int));
STATIC_CHECK(sizeof(int) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 3 * (sizeof(void *)));
STATIC_CHECK(sizeof(v6[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v6[1])) == 7 * (sizeof(void *)));
STATIC_CHECK(sizeof((*v6[1])[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v6[1])[1])) == 1);
STATIC_CHECK(sizeof(unsigned char *(*[3])[7]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
