// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern short v0;
typedef short T0;
extern unsigned char v1;
typedef unsigned char T1;
extern signed char **v2[2];
typedef signed char **T2[2];
extern short *(**v3)[2][2];
typedef short *(**T3)[2][2];
extern char (*v4)(void);
typedef char (*T4)(void);
extern char v5;
typedef char T5;
extern long v6[3];
typedef long T6[3];
extern unsigned short **v7;
typedef unsigned short **T7;
STATIC_CHECK(sizeof(v0) == sizeof(short));
STATIC_CHECK(sizeof(short) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == 1);
STATIC_CHECK(sizeof(unsigned char) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == 2 * (sizeof(void *)));
STATIC_CHECK(sizeof(v2[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v2[1])) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2[1]))) == 1);
STATIC_CHECK(sizeof(signed char **[2]) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(void *));
STATIC_CHECK(sizeof((*v3)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v3))) == 2 * (2 * (sizeof(void *))));
STATIC_CHECK(sizeof((*(*v3))[1]) == 2 * (sizeof(void *)));
STATIC_CHECK(sizeof((*(*v3))[1][1]) == sizeof(void *));
STATIC_CHECK(sizeof((*(*(*v3))[1][1])) == sizeof(short));
STATIC_CHECK(sizeof(short *(**)[2][2]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 1);
STATIC_CHECK(sizeof(char) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 3 * (sizeof(long)));
STATIC_CHECK(sizeof(v6[1]) == sizeof(long));
STATIC_CHECK(sizeof(long [3]) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v7))) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short **) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
