// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned v0;
typedef unsigned T0;
extern int (*v1)(void);
typedef int (*T1)(void);
extern unsigned char **v2;
typedef unsigned char **T2;
extern long v3;
typedef long T3;
extern short (*(**v4)[3])(void);
typedef short (*(**T4)[3])(void);
extern char *v5;
typedef char *T5;
extern short (*v6)(void);
typedef short (*T6)(void);
extern int (**v7)(void);
typedef int (**T7)(void);
STATIC_CHECK(sizeof(v0) == sizeof(unsigned));
STATIC_CHECK(sizeof(unsigned) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v1)()) == sizeof(int));
STATIC_CHECK(sizeof(int (*)(void)) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void *));
STATIC_CHECK(sizeof((*v2)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2))) == 1);
STATIC_CHECK(sizeof(unsigned char **) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == sizeof(long));
STATIC_CHECK(sizeof(long) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void *));
STATIC_CHECK(sizeof((*v4)) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v4))) == 3 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof((*(*v4))[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*(*v4))[1])()) == sizeof(short));
STATIC_CHECK(sizeof(short (*(**)[3])(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == sizeof(void *));
STATIC_CHECK(sizeof((*v5)) == 1);
STATIC_CHECK(sizeof(char *) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6)()) == sizeof(short));
STATIC_CHECK(sizeof(short (*)(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == sizeof(void *));
STATIC_CHECK(sizeof((*v7)) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v7))()) == sizeof(int));
STATIC_CHECK(sizeof(int (**)(void)) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
