// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Random declarators, their abstract-declarator and typedef twins, and the
// types reached through *, [] and () (sizes relative to the basic types).
#include "loomcc-test.h"
extern unsigned short *v0;
typedef unsigned short *T0;
extern char (*v1)(void);
typedef char (*T1)(void);
extern unsigned short *(*v2)(void);
typedef unsigned short *(*T2)(void);
extern int v3[5][5][2];
typedef int T3[5][5][2];
extern char (*v4)(void);
typedef char (*T4)(void);
extern short (**v5[3])(void);
typedef short (**T5[3])(void);
extern signed char (*v6[2])(void);
typedef signed char (*T6[2])(void);
extern char v7[5];
typedef char T7[5];
STATIC_CHECK(sizeof(v0) == sizeof(void *));
STATIC_CHECK(sizeof((*v0)) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *) == sizeof(v0));
STATIC_CHECK(sizeof(T0) == sizeof(v0));
STATIC_CHECK(sizeof(v1) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v1)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v1));
STATIC_CHECK(sizeof(T1) == sizeof(v1));
STATIC_CHECK(sizeof(v2) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v2)()) == sizeof(void *));
STATIC_CHECK(sizeof((*(*v2)())) == sizeof(short));
STATIC_CHECK(sizeof(unsigned short *(*)(void)) == sizeof(v2));
STATIC_CHECK(sizeof(T2) == sizeof(v2));
STATIC_CHECK(sizeof(v3) == 5 * (5 * (2 * (sizeof(int)))));
STATIC_CHECK(sizeof(v3[1]) == 5 * (2 * (sizeof(int))));
STATIC_CHECK(sizeof(v3[1][1]) == 2 * (sizeof(int)));
STATIC_CHECK(sizeof(v3[1][1][1]) == sizeof(int));
STATIC_CHECK(sizeof(int [5][5][2]) == sizeof(v3));
STATIC_CHECK(sizeof(T3) == sizeof(v3));
STATIC_CHECK(sizeof(v4) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v4)()) == 1);
STATIC_CHECK(sizeof(char (*)(void)) == sizeof(v4));
STATIC_CHECK(sizeof(T4) == sizeof(v4));
STATIC_CHECK(sizeof(v5) == 3 * (sizeof(void *)));
STATIC_CHECK(sizeof(v5[1]) == sizeof(void *));
STATIC_CHECK(sizeof((*v5[1])) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*(*v5[1]))()) == sizeof(short));
STATIC_CHECK(sizeof(short (**[3])(void)) == sizeof(v5));
STATIC_CHECK(sizeof(T5) == sizeof(v5));
STATIC_CHECK(sizeof(v6) == 2 * (sizeof(void (*)(void))));
STATIC_CHECK(sizeof(v6[1]) == sizeof(void (*)(void)));
STATIC_CHECK(sizeof((*v6[1])()) == 1);
STATIC_CHECK(sizeof(signed char (*[2])(void)) == sizeof(v6));
STATIC_CHECK(sizeof(T6) == sizeof(v6));
STATIC_CHECK(sizeof(v7) == 5 * (1));
STATIC_CHECK(sizeof(v7[1]) == 1);
STATIC_CHECK(sizeof(char [5]) == sizeof(v7));
STATIC_CHECK(sizeof(T7) == sizeof(v7));
