#include <loom/adventure.h>
#include <loom/generated/ui.h>
#include <loom/generated/user_hooks.h>
#include <loom/scene.h>
#include <loom/ui.h>

/* Portable hook generated by Loom. This authored file is yours to edit. */
static LoomUiDialogueHandle pending_dialogue = LOOM_UI_HANDLE_NONE;
static LoomUiViewHandle pending_view = LOOM_UI_HANDLE_NONE;
static loom_u8 completion_presented = LOOM_FALSE;
/* The adventure flag word the HUD last showed, 0xffff until the first tick. */
static loom_u16 shown_flags = 0xffffu;

/* BEGIN THE ROAD carries Loom's built-in restart, so starting and starting
 * over need no code here; this only puts the quest's own presentation back. */
static void reset_journey(loom_u8 return_to_title)
{
    (void)loom_adventure_initialize();
    (void)loom_scene_initialize();
    pending_dialogue = LOOM_UI_HANDLE_NONE;
    pending_view = return_to_title != LOOM_FALSE
                       ? LOOM_UI_VIEW_TITLE
                       : LOOM_UI_VIEW_GAMEPLAY;
    completion_presented = LOOM_FALSE;
    shown_flags = 0xffffu;
}

/* The HUD names the next step: the flags are the key, the open road, the
 * lit beacon and the lit home lantern, in that order. The flag word is read
 * once a tick and the bindings are written only when it changes; a UI write
 * or a flag lookup per flag every tick costs more scanlines than a 60 Hz
 * tick can spare. */
static void update_quest_step(loom_u16 flags)
{
    if (flags == shown_flags) {
        return;
    }
    shown_flags = flags;
    (void)loom_ui_set_bool(LOOM_UI_BINDING_HAS_KEY,
                           (flags & 1u) != 0u ? LOOM_TRUE : LOOM_FALSE);
    (void)loom_ui_set_message(
        LOOM_UI_BINDING_QUEST,
        (flags & 1u) == 0u   ? LOOM_UI_MESSAGE_GOAL_KEY
        : (flags & 2u) == 0u ? LOOM_UI_MESSAGE_GOAL_KEEPER
        : (flags & 4u) == 0u ? LOOM_UI_MESSAGE_GOAL_BEACON
                             : LOOM_UI_MESSAGE_GOAL_HOME);
}

static void collect_adventure_request(void)
{
    LoomAdventureRequest request;

    if (pending_dialogue != LOOM_UI_HANDLE_NONE ||
        loom_adventure_take_request(&request) != LOOM_STATUS_OK ||
        request.kind != LOOM_ADVENTURE_REQUEST_DIALOGUE) {
        return;
    }
    if (request.id == 9u) {
        pending_dialogue = LOOM_UI_DIALOGUE_KEEPER_DIALOGUE;
    } else if (request.id == 10u) {
        pending_dialogue = LOOM_UI_DIALOGUE_BEACON_DIALOGUE;
    } else if (request.id == 11u) {
        pending_dialogue = LOOM_UI_DIALOGUE_HOME_DIALOGUE;
    }
}

static void apply_ui_commands(void)
{
    LoomUiCommandHandle command;

    while (loom_ui_poll_command(&command) == LOOM_STATUS_OK) {
        if (command == LOOM_UI_COMMAND_OPEN_ROAD &&
            loom_adventure_flag_is_set(0u) != LOOM_FALSE) {
            (void)loom_adventure_flag_set(1u);
        } else if (command == LOOM_UI_COMMAND_LIGHT_BEACON) {
            (void)loom_adventure_flag_set(2u);
        } else if (command == LOOM_UI_COMMAND_LIGHT_HOME &&
                   loom_adventure_flag_is_set(2u) != LOOM_FALSE) {
            (void)loom_adventure_flag_set(3u);
        } else if (command == LOOM_UI_COMMAND_RESTART_GAME) {
            reset_journey(LOOM_FALSE);
        } else if (command == LOOM_UI_COMMAND_RETURN_TO_TITLE) {
            reset_journey(LOOM_TRUE);
        }
    }
}

void loom_game_update(void)
{
    LoomStatus status;
    loom_u16 flags;

    collect_adventure_request();
    apply_ui_commands();

    flags = loom_adventure_flags();
    update_quest_step(flags);

    if (pending_dialogue != LOOM_UI_HANDLE_NONE) {
        status = loom_ui_push_dialogue(pending_dialogue);
        if (status == LOOM_STATUS_OK) {
            pending_dialogue = LOOM_UI_HANDLE_NONE;
        }
    }

    if ((flags & 8u) != 0u && completion_presented == LOOM_FALSE) {
        pending_view = LOOM_UI_VIEW_COMPLETION;
        completion_presented = LOOM_TRUE;
    }
    if (pending_view != LOOM_UI_HANDLE_NONE) {
        status = loom_ui_replace_view(pending_view);
        if (status == LOOM_STATUS_OK) {
            pending_view = LOOM_UI_HANDLE_NONE;
        }
    }
}
