// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 17 live i16 locals updated together 2 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  i16 v0 = (i16)(-343);
  i16 v1 = (i16)(-471);
  i16 v2 = (i16)(436);
  i16 v3 = (i16)(361);
  i16 v4 = (i16)(-329);
  i16 v5 = (i16)(274);
  i16 v6 = (i16)(-17);
  i16 v7 = (i16)(313);
  i16 v8 = (i16)(-415);
  i16 v9 = (i16)(28);
  i16 v10 = (i16)(-403);
  i16 v11 = (i16)(29);
  i16 v12 = (i16)(179);
  i16 v13 = (i16)(116);
  i16 v14 = (i16)(360);
  i16 v15 = (i16)(302);
  i16 v16 = (i16)(-386);
  i16 n0, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15, n16;
  u8 s;
  u16 total;
  for (s = 0; s < 2; s++) {
    n0 = (i16)(v0 + 2 * (v1 & 7));
    n1 = (i16)(v1 + 3 * (v2 & 7));
    n2 = (i16)(v2 + 3 * (v3 & 7));
    n3 = (i16)(v3 + 3 * (v4 & 7));
    n4 = (i16)(v4 + 2 * (v5 & 7));
    n5 = (i16)(v5 + 1 * (v6 & 7));
    n6 = (i16)(v6 + 1 * (v7 & 7));
    n7 = (i16)(v7 + 3 * (v8 & 7));
    n8 = (i16)(v8 + 2 * (v9 & 7));
    n9 = (i16)(v9 + 1 * (v10 & 7));
    n10 = (i16)(v10 + 3 * (v11 & 7));
    n11 = (i16)(v11 + 3 * (v12 & 7));
    n12 = (i16)(v12 + 3 * (v13 & 7));
    n13 = (i16)(v13 + 3 * (v14 & 7));
    n14 = (i16)(v14 + 1 * (v15 & 7));
    n15 = (i16)(v15 + 3 * (v16 & 7));
    n16 = (i16)(v16 + 1 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7; v8 = n8; v9 = n9; v10 = n10; v11 = n11; v12 = n12; v13 = n13; v14 = n14; v15 = n15; v16 = n16;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7 + (u16)v8 + (u16)v9 + (u16)v10 + (u16)v11 + (u16)v12 + (u16)v13 + (u16)v14 + (u16)v15 + (u16)v16);
  CHECK(total == 327u);
  CHECK(v0 == (i16)(-331) && v16 == (i16)(-382));
  return 0;
}
