// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 14 live i8 locals updated together 4 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  i8 v0 = (i8)(127);
  i8 v1 = (i8)(-59);
  i8 v2 = (i8)(27);
  i8 v3 = (i8)(-87);
  i8 v4 = (i8)(26);
  i8 v5 = (i8)(15);
  i8 v6 = (i8)(-13);
  i8 v7 = (i8)(-32);
  i8 v8 = (i8)(54);
  i8 v9 = (i8)(65);
  i8 v10 = (i8)(-37);
  i8 v11 = (i8)(92);
  i8 v12 = (i8)(-110);
  i8 v13 = (i8)(114);
  i8 n0, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13;
  u8 s;
  u16 total;
  for (s = 0; s < 4; s++) {
    n0 = (i8)(v0 + 3 * (v1 & 7));
    n1 = (i8)(v1 + 2 * (v2 & 7));
    n2 = (i8)(v2 + 2 * (v3 & 7));
    n3 = (i8)(v3 + 1 * (v4 & 7));
    n4 = (i8)(v4 + 3 * (v5 & 7));
    n5 = (i8)(v5 + 3 * (v6 & 7));
    n6 = (i8)(v6 + 3 * (v7 & 7));
    n7 = (i8)(v7 + 1 * (v8 & 7));
    n8 = (i8)(v8 + 2 * (v9 & 7));
    n9 = (i8)(v9 + 2 * (v10 & 7));
    n10 = (i8)(v10 + 2 * (v11 & 7));
    n11 = (i8)(v11 + 2 * (v12 & 7));
    n12 = (i8)(v12 + 2 * (v13 & 7));
    n13 = (i8)(v13 + 2 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7; v8 = n8; v9 = n9; v10 = n10; v11 = n11; v12 = n12; v13 = n13;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7 + (u16)v8 + (u16)v9 + (u16)v10 + (u16)v11 + (u16)v12 + (u16)v13);
  CHECK(total == 65384u);
  CHECK(v0 == (i8)(-81) && v13 == (i8)(-90));
  return 0;
}
