// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 8 live u16 locals updated together 1 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  u16 v0 = (u16)(65054);
  u16 v1 = (u16)(65525);
  u16 v2 = (u16)(63);
  u16 v3 = (u16)(65392);
  u16 v4 = (u16)(65280);
  u16 v5 = (u16)(65482);
  u16 v6 = (u16)(402);
  u16 v7 = (u16)(65067);
  u16 n0, n1, n2, n3, n4, n5, n6, n7;
  u8 s;
  u16 total;
  for (s = 0; s < 1; s++) {
    n0 = (u16)(v0 + 2 * (v1 & 7));
    n1 = (u16)(v1 + 1 * (v2 & 7));
    n2 = (u16)(v2 + 3 * (v3 & 7));
    n3 = (u16)(v3 + 2 * (v4 & 7));
    n4 = (u16)(v4 + 2 * (v5 & 7));
    n5 = (u16)(v5 + 2 * (v6 & 7));
    n6 = (u16)(v6 + 2 * (v7 & 7));
    n7 = (u16)(v7 + 2 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7);
  CHECK(total == 64628u);
  CHECK(v0 == (u16)(65064) && v7 == (u16)(65079));
  return 0;
}
