// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 18 live i8 locals updated together 4 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  i8 v0 = (i8)(-46);
  i8 v1 = (i8)(-22);
  i8 v2 = (i8)(-107);
  i8 v3 = (i8)(-38);
  i8 v4 = (i8)(75);
  i8 v5 = (i8)(-8);
  i8 v6 = (i8)(116);
  i8 v7 = (i8)(51);
  i8 v8 = (i8)(32);
  i8 v9 = (i8)(116);
  i8 v10 = (i8)(-67);
  i8 v11 = (i8)(-21);
  i8 v12 = (i8)(-124);
  i8 v13 = (i8)(23);
  i8 v14 = (i8)(-19);
  i8 v15 = (i8)(120);
  i8 v16 = (i8)(30);
  i8 v17 = (i8)(-94);
  i8 n0, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15, n16, n17;
  u8 s;
  u16 total;
  for (s = 0; s < 4; s++) {
    n0 = (i8)(v0 + 3 * (v1 & 7));
    n1 = (i8)(v1 + 2 * (v2 & 7));
    n2 = (i8)(v2 + 1 * (v3 & 7));
    n3 = (i8)(v3 + 2 * (v4 & 7));
    n4 = (i8)(v4 + 2 * (v5 & 7));
    n5 = (i8)(v5 + 3 * (v6 & 7));
    n6 = (i8)(v6 + 2 * (v7 & 7));
    n7 = (i8)(v7 + 3 * (v8 & 7));
    n8 = (i8)(v8 + 1 * (v9 & 7));
    n9 = (i8)(v9 + 1 * (v10 & 7));
    n10 = (i8)(v10 + 3 * (v11 & 7));
    n11 = (i8)(v11 + 1 * (v12 & 7));
    n12 = (i8)(v12 + 1 * (v13 & 7));
    n13 = (i8)(v13 + 2 * (v14 & 7));
    n14 = (i8)(v14 + 1 * (v15 & 7));
    n15 = (i8)(v15 + 1 * (v16 & 7));
    n16 = (i8)(v16 + 3 * (v17 & 7));
    n17 = (i8)(v17 + 3 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7; v8 = n8; v9 = n9; v10 = n10; v11 = n11; v12 = n12; v13 = n13; v14 = n14; v15 = n15; v16 = n16; v17 = n17;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7 + (u16)v8 + (u16)v9 + (u16)v10 + (u16)v11 + (u16)v12 + (u16)v13 + (u16)v14 + (u16)v15 + (u16)v16 + (u16)v17);
  CHECK(total == 65253u);
  CHECK(v0 == (i8)(-22) && v17 == (i8)(-70));
  return 0;
}
