// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 14 live u8 locals updated together 5 times, with a call in the loop.
#include "loomcc-test.h"
static volatile u8 sink;
static void touch(u8 x) { sink = x; }
int main(void) {
  u8 v0 = (u8)(100);
  u8 v1 = (u8)(39);
  u8 v2 = (u8)(175);
  u8 v3 = (u8)(193);
  u8 v4 = (u8)(111);
  u8 v5 = (u8)(139);
  u8 v6 = (u8)(193);
  u8 v7 = (u8)(231);
  u8 v8 = (u8)(156);
  u8 v9 = (u8)(8);
  u8 v10 = (u8)(81);
  u8 v11 = (u8)(21);
  u8 v12 = (u8)(137);
  u8 v13 = (u8)(136);
  u8 n0, n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13;
  u8 s;
  u16 total;
  for (s = 0; s < 5; s++) {
    n0 = (u8)(v0 + 2 * (v1 & 7));
    n1 = (u8)(v1 + 3 * (v2 & 7));
    n2 = (u8)(v2 + 3 * (v3 & 7));
    n3 = (u8)(v3 + 1 * (v4 & 7));
    n4 = (u8)(v4 + 2 * (v5 & 7));
    n5 = (u8)(v5 + 3 * (v6 & 7));
    n6 = (u8)(v6 + 1 * (v7 & 7));
    n7 = (u8)(v7 + 2 * (v8 & 7));
    n8 = (u8)(v8 + 2 * (v9 & 7));
    n9 = (u8)(v9 + 3 * (v10 & 7));
    n10 = (u8)(v10 + 3 * (v11 & 7));
    n11 = (u8)(v11 + 1 * (v12 & 7));
    n12 = (u8)(v12 + 2 * (v13 & 7));
    n13 = (u8)(v13 + 2 * (v0 & 7));
    touch(s);
    v0 = n0; v1 = n1; v2 = n2; v3 = n3; v4 = n4; v5 = n5; v6 = n6; v7 = n7; v8 = n8; v9 = n9; v10 = n10; v11 = n11; v12 = n12; v13 = n13;
  }
  total = (u16)((u16)v0 + (u16)v1 + (u16)v2 + (u16)v3 + (u16)v4 + (u16)v5 + (u16)v6 + (u16)v7 + (u16)v8 + (u16)v9 + (u16)v10 + (u16)v11 + (u16)v12 + (u16)v13);
  CHECK(total == 2200u);
  CHECK(v0 == (u8)(132) && v13 == (u8)(176));
  return 0;
}
