// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 9 outer records, each with 2 inner records, in ROM and copied to WRAM.
#include "loomcc-test.h"
typedef struct { u16 v; u8 f; } In;
typedef struct { i16 tag; In in[2]; } Out;
static const Out rom[9] = {
  { 25611, { { 26440, 212 }, { 22530, 210 } } },
  { 1564, { { 51908, 126 }, { 21749, 245 } } },
  { -11207, { { 8154, 46 }, { 51738, 167 } } },
  { -21614, { { 15335, 209 }, { 62608, 191 } } },
  { 3669, { { 52134, 248 }, { 21220, 158 } } },
  { 22400, { { 37748, 253 }, { 328, 176 } } },
  { 22140, { { 60715, 31 }, { 12008, 188 } } },
  { 18495, { { 37832, 125 }, { 47341, 190 } } },
  { 30300, { { 25698, 244 }, { 42469, 11 } } }
};
static Out ram[9];
static volatile u8 vi, vj;
int main(void) {
  u8 i, j;
  u16 total = 0;
  for (i = 0; i < 9; i++) ram[i] = rom[i];
  for (i = 0; i < 9; i++) for (j = 0; j < 2; j++) total = (u16)(total + (u16)ram[i].in[j].v);
  CHECK(total == 8131u);
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(21749) && rom[vi].in[vj].f == 245 && ram[vi].tag == (i16)(1564));
  vi = 7; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(37832) && rom[vi].in[vj].f == 125 && ram[vi].tag == (i16)(18495));
  vi = 4; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(21220) && rom[vi].in[vj].f == 158 && ram[vi].tag == (i16)(3669));
  vi = 4; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(52134) && rom[vi].in[vj].f == 248 && ram[vi].tag == (i16)(3669));
  vi = 2; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(8154) && rom[vi].in[vj].f == 46 && ram[vi].tag == (i16)(-11207));
  vi = 3; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(15335) && rom[vi].in[vj].f == 209 && ram[vi].tag == (i16)(-21614));
  vi = 2; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(51738) && rom[vi].in[vj].f == 167 && ram[vi].tag == (i16)(-11207));
  vi = 4; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(21220) && rom[vi].in[vj].f == 158 && ram[vi].tag == (i16)(3669));
  vi = 3; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(15335) && rom[vi].in[vj].f == 209 && ram[vi].tag == (i16)(-21614));
  vi = 8; vj = 0; CHECK(ram[vi].in[vj].v == (u16)(25698) && rom[vi].in[vj].f == 244 && ram[vi].tag == (i16)(30300));
  vi = 2; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(51738) && rom[vi].in[vj].f == 167 && ram[vi].tag == (i16)(-11207));
  vi = 6; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(12008) && rom[vi].in[vj].f == 188 && ram[vi].tag == (i16)(22140));
  vi = 7; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(47341) && rom[vi].in[vj].f == 190 && ram[vi].tag == (i16)(18495));
  vi = 3; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(62608) && rom[vi].in[vj].f == 191 && ram[vi].tag == (i16)(-21614));
  vi = 4; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(21220) && rom[vi].in[vj].f == 158 && ram[vi].tag == (i16)(3669));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u16)(21749) && rom[vi].in[vj].f == 245 && ram[vi].tag == (i16)(1564));
  return 0;
}
