// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 2 outer records, each with 5 inner records, in ROM and copied to WRAM.
#include "loomcc-test.h"
typedef struct { i16 v; u8 f; } In;
typedef struct { i16 tag; In in[5]; } Out;
static const Out rom[2] = {
  { -15688, { { 26574, 176 }, { -18629, 19 }, { 13787, 111 }, { 12420, 105 }, { -21901, 48 } } },
  { -12341, { { -18324, 42 }, { 27308, 188 }, { -15222, 173 }, { -3409, 53 }, { -15150, 120 } } }
};
static Out ram[2];
static volatile u8 vi, vj;
int main(void) {
  u8 i, j;
  u16 total = 0;
  for (i = 0; i < 2; i++) ram[i] = rom[i];
  for (i = 0; i < 2; i++) for (j = 0; j < 5; j++) total = (u16)(total + (u16)ram[i].in[j].v);
  CHECK(total == 52990u);
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-18324) && rom[vi].in[vj].f == 42 && ram[vi].tag == (i16)(-12341));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(26574) && rom[vi].in[vj].f == 176 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(13787) && rom[vi].in[vj].f == 111 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 3; CHECK(ram[vi].in[vj].v == (i16)(12420) && rom[vi].in[vj].f == 105 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(13787) && rom[vi].in[vj].f == 111 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(26574) && rom[vi].in[vj].f == 176 && ram[vi].tag == (i16)(-15688));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-18324) && rom[vi].in[vj].f == 42 && ram[vi].tag == (i16)(-12341));
  vi = 1; vj = 4; CHECK(ram[vi].in[vj].v == (i16)(-15150) && rom[vi].in[vj].f == 120 && ram[vi].tag == (i16)(-12341));
  vi = 1; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(-15222) && rom[vi].in[vj].f == 173 && ram[vi].tag == (i16)(-12341));
  vi = 1; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(-15222) && rom[vi].in[vj].f == 173 && ram[vi].tag == (i16)(-12341));
  vi = 1; vj = 3; CHECK(ram[vi].in[vj].v == (i16)(-3409) && rom[vi].in[vj].f == 53 && ram[vi].tag == (i16)(-12341));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(13787) && rom[vi].in[vj].f == 111 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(13787) && rom[vi].in[vj].f == 111 && ram[vi].tag == (i16)(-15688));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (i16)(13787) && rom[vi].in[vj].f == 111 && ram[vi].tag == (i16)(-15688));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (i16)(27308) && rom[vi].in[vj].f == 188 && ram[vi].tag == (i16)(-12341));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (i16)(-18324) && rom[vi].in[vj].f == 42 && ram[vi].tag == (i16)(-12341));
  return 0;
}
