// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 2 outer records, each with 2 inner records, in ROM and copied to WRAM.
#include "loomcc-test.h"
typedef struct { u8 v; u8 f; } In;
typedef struct { u8 tag; In in[2]; } Out;
static const Out rom[2] = {
  { 159, { { 147, 90 }, { 177, 146 } } },
  { 71, { { 68, 185 }, { 173, 134 } } }
};
static Out ram[2];
static volatile u8 vi, vj;
int main(void) {
  u8 i, j;
  u16 total = 0;
  for (i = 0; i < 2; i++) ram[i] = rom[i];
  for (i = 0; i < 2; i++) for (j = 0; j < 2; j++) total = (u16)(total + (u16)ram[i].in[j].v);
  CHECK(total == 565u);
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(68) && rom[vi].in[vj].f == 185 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(177) && rom[vi].in[vj].f == 146 && ram[vi].tag == (u8)(159));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(68) && rom[vi].in[vj].f == 185 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(177) && rom[vi].in[vj].f == 146 && ram[vi].tag == (u8)(159));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(68) && rom[vi].in[vj].f == 185 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(177) && rom[vi].in[vj].f == 146 && ram[vi].tag == (u8)(159));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(173) && rom[vi].in[vj].f == 134 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(147) && rom[vi].in[vj].f == 90 && ram[vi].tag == (u8)(159));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(147) && rom[vi].in[vj].f == 90 && ram[vi].tag == (u8)(159));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(68) && rom[vi].in[vj].f == 185 && ram[vi].tag == (u8)(71));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(68) && rom[vi].in[vj].f == 185 && ram[vi].tag == (u8)(71));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(173) && rom[vi].in[vj].f == 134 && ram[vi].tag == (u8)(71));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(173) && rom[vi].in[vj].f == 134 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(147) && rom[vi].in[vj].f == 90 && ram[vi].tag == (u8)(159));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(173) && rom[vi].in[vj].f == 134 && ram[vi].tag == (u8)(71));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(147) && rom[vi].in[vj].f == 90 && ram[vi].tag == (u8)(159));
  return 0;
}
