// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// 3 outer records, each with 3 inner records, in ROM and copied to WRAM.
#include "loomcc-test.h"
typedef struct { u8 v; u8 f; } In;
typedef struct { u8 tag; In in[3]; } Out;
static const Out rom[3] = {
  { 226, { { 31, 166 }, { 235, 67 }, { 221, 241 } } },
  { 236, { { 18, 142 }, { 154, 154 }, { 8, 77 } } },
  { 213, { { 142, 151 }, { 100, 217 }, { 196, 39 } } }
};
static Out ram[3];
static volatile u8 vi, vj;
int main(void) {
  u8 i, j;
  u16 total = 0;
  for (i = 0; i < 3; i++) ram[i] = rom[i];
  for (i = 0; i < 3; i++) for (j = 0; j < 3; j++) total = (u16)(total + (u16)ram[i].in[j].v);
  CHECK(total == 1105u);
  vi = 2; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(100) && rom[vi].in[vj].f == 217 && ram[vi].tag == (u8)(213));
  vi = 1; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(8) && rom[vi].in[vj].f == 77 && ram[vi].tag == (u8)(236));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(18) && rom[vi].in[vj].f == 142 && ram[vi].tag == (u8)(236));
  vi = 2; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(142) && rom[vi].in[vj].f == 151 && ram[vi].tag == (u8)(213));
  vi = 1; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(154) && rom[vi].in[vj].f == 154 && ram[vi].tag == (u8)(236));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(221) && rom[vi].in[vj].f == 241 && ram[vi].tag == (u8)(226));
  vi = 2; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(142) && rom[vi].in[vj].f == 151 && ram[vi].tag == (u8)(213));
  vi = 2; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(196) && rom[vi].in[vj].f == 39 && ram[vi].tag == (u8)(213));
  vi = 1; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(8) && rom[vi].in[vj].f == 77 && ram[vi].tag == (u8)(236));
  vi = 1; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(8) && rom[vi].in[vj].f == 77 && ram[vi].tag == (u8)(236));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(221) && rom[vi].in[vj].f == 241 && ram[vi].tag == (u8)(226));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(18) && rom[vi].in[vj].f == 142 && ram[vi].tag == (u8)(236));
  vi = 0; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(31) && rom[vi].in[vj].f == 166 && ram[vi].tag == (u8)(226));
  vi = 1; vj = 0; CHECK(ram[vi].in[vj].v == (u8)(18) && rom[vi].in[vj].f == 142 && ram[vi].tag == (u8)(236));
  vi = 0; vj = 1; CHECK(ram[vi].in[vj].v == (u8)(235) && rom[vi].in[vj].f == 67 && ram[vi].tag == (u8)(226));
  vi = 0; vj = 2; CHECK(ram[vi].in[vj].v == (u8)(221) && rom[vi].in[vj].f == 241 && ram[vi].tag == (u8)(226));
  return 0;
}
