// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u8): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 2, 3, 6, 3, 1, 5, 1, 4, 2, 7, 3, 2, 2, 1, 5, 7, 2, 0, 4, 2 };
static volatile u8 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 62u;
  f = (u8)(f | (u8)(1u << bit[0]));
  CHECK(f == 62u);
  f = (u8)(f | (u8)(1u << bit[1]));
  CHECK(f == 62u);
  CHECK((f & 211u) == 18u);
  CHECK(f == 62u);
  f = (u8)(f | (u8)(1u << bit[3]));
  CHECK(f == 62u);
  CHECK((f & 202u) == 10u);
  CHECK(f == 62u);
  CHECK((f & 166u) == 38u);
  CHECK(f == 62u);
  f = (u8)(f & (u8)~(u8)(1u << bit[6]));
  CHECK(f == 60u);
  f = (u8)(f | (u8)(1u << bit[7]));
  CHECK(f == 60u);
  f ^= (u8)(1u << bit[8]);
  CHECK(f == 56u);
  f ^= (u8)(1u << bit[9]);
  CHECK(f == 184u);
  CHECK(((f >> bit[10]) & 1u) == 1);
  CHECK(f == 184u);
  f = (u8)(f | (u8)(1u << bit[11]));
  CHECK(f == 188u);
  CHECK(((f >> bit[12]) & 1u) == 1);
  CHECK(f == 188u);
  CHECK(((f >> bit[13]) & 1u) == 0);
  CHECK(f == 188u);
  f ^= (u8)(1u << bit[14]);
  CHECK(f == 156u);
  CHECK(((f >> bit[15]) & 1u) == 1);
  CHECK(f == 156u);
  f = (u8)(f | (u8)(1u << bit[16]));
  CHECK(f == 156u);
  f ^= (u8)(1u << bit[17]);
  CHECK(f == 157u);
  f ^= (u8)(1u << bit[18]);
  CHECK(f == 141u);
  f = (u8)(f | (u8)(1u << bit[19]));
  CHECK(f == 141u);
  return 0;
}
