// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u16): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 11, 11, 9, 4, 3, 14, 8, 11, 9, 0, 3, 10, 8, 1, 4, 8, 12, 14, 14, 3 };
static volatile u16 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 7021u;
  f = (u16)(f | (u16)(1u << bit[0]));
  CHECK(f == 7021u);
  CHECK(((f >> bit[1]) & 1u) == 1);
  CHECK(f == 7021u);
  CHECK(((f >> bit[2]) & 1u) == 1);
  CHECK(f == 7021u);
  f = (u16)(f & (u16)~(u16)(1u << bit[3]));
  CHECK(f == 7021u);
  f = (u16)(f | (u16)(1u << bit[4]));
  CHECK(f == 7021u);
  CHECK(((f >> bit[5]) & 1u) == 0);
  CHECK(f == 7021u);
  f = (u16)(f & (u16)~(u16)(1u << bit[6]));
  CHECK(f == 6765u);
  CHECK((f & 60034u) == 2560u);
  CHECK(f == 6765u);
  f = (u16)(f & (u16)~(u16)(1u << bit[8]));
  CHECK(f == 6253u);
  f = (u16)(f & (u16)~(u16)(1u << bit[9]));
  CHECK(f == 6252u);
  f = (u16)(f | (u16)(1u << bit[10]));
  CHECK(f == 6252u);
  f ^= (u16)(1u << bit[11]);
  CHECK(f == 7276u);
  CHECK((f & 53186u) == 3136u);
  CHECK(f == 7276u);
  f = (u16)(f | (u16)(1u << bit[13]));
  CHECK(f == 7278u);
  f ^= (u16)(1u << bit[14]);
  CHECK(f == 7294u);
  CHECK((f & 10102u) == 1142u);
  CHECK(f == 7294u);
  CHECK(((f >> bit[16]) & 1u) == 1);
  CHECK(f == 7294u);
  CHECK(((f >> bit[17]) & 1u) == 0);
  CHECK(f == 7294u);
  CHECK(((f >> bit[18]) & 1u) == 0);
  CHECK(f == 7294u);
  f ^= (u16)(1u << bit[19]);
  CHECK(f == 7286u);
  return 0;
}
