// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u8): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 7, 7, 6, 6, 2, 6, 7, 3, 6, 3, 7, 1, 7, 2, 4, 1, 2, 4, 6, 1 };
static volatile u8 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 53u;
  f = (u8)(f | (u8)(1u << bit[0]));
  CHECK(f == 181u);
  f = (u8)(f & (u8)~(u8)(1u << bit[1]));
  CHECK(f == 53u);
  f = (u8)(f | (u8)(1u << bit[2]));
  CHECK(f == 117u);
  f ^= (u8)(1u << bit[3]);
  CHECK(f == 53u);
  f = (u8)(f & (u8)~(u8)(1u << bit[4]));
  CHECK(f == 49u);
  f ^= (u8)(1u << bit[5]);
  CHECK(f == 113u);
  f ^= (u8)(1u << bit[6]);
  CHECK(f == 241u);
  CHECK(((f >> bit[7]) & 1u) == 0);
  CHECK(f == 241u);
  f = (u8)(f & (u8)~(u8)(1u << bit[8]));
  CHECK(f == 177u);
  CHECK((f & 165u) == 161u);
  CHECK(f == 177u);
  f = (u8)(f & (u8)~(u8)(1u << bit[10]));
  CHECK(f == 49u);
  f ^= (u8)(1u << bit[11]);
  CHECK(f == 51u);
  f = (u8)(f & (u8)~(u8)(1u << bit[12]));
  CHECK(f == 51u);
  f = (u8)(f & (u8)~(u8)(1u << bit[13]));
  CHECK(f == 51u);
  f ^= (u8)(1u << bit[14]);
  CHECK(f == 35u);
  f ^= (u8)(1u << bit[15]);
  CHECK(f == 33u);
  CHECK((f & 21u) == 1u);
  CHECK(f == 33u);
  CHECK(((f >> bit[17]) & 1u) == 0);
  CHECK(f == 33u);
  f = (u8)(f | (u8)(1u << bit[18]));
  CHECK(f == 97u);
  f = (u8)(f | (u8)(1u << bit[19]));
  CHECK(f == 99u);
  return 0;
}
