// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// u16 divided by 16: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((u16)16)
static volatile u16 v;
static u16 floor_div(u16 a) { u16 q = (u16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static u16 pos_mod(u16 a) { u16 m = (u16)(a % D); if (m < 0) m = (u16)(m + D); return m; }
static u16 round_div(u16 a) { return (u16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = 0u; CHECK(v / D == 0u); CHECK(v % D == 0u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 0u); CHECK((v >> 4) == 0u);
  v = 1u; CHECK(v / D == 0u); CHECK(v % D == 1u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 1u); CHECK((v >> 4) == 0u);
  v = 2u; CHECK(v / D == 0u); CHECK(v % D == 2u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 2u); CHECK((v >> 4) == 0u);
  v = 255u; CHECK(v / D == 15u); CHECK(v % D == 15u); CHECK(floor_div(v) == 15u); CHECK(pos_mod(v) == 15u); CHECK(round_div(v) == 16u); CHECK((v >> 4) == 15u);
  v = 256u; CHECK(v / D == 16u); CHECK(v % D == 0u); CHECK(floor_div(v) == 16u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 16u); CHECK((v >> 4) == 16u);
  v = 1000u; CHECK(v / D == 62u); CHECK(v % D == 8u); CHECK(floor_div(v) == 62u); CHECK(pos_mod(v) == 8u); CHECK(round_div(v) == 63u); CHECK((v >> 4) == 62u);
  v = 32767u; CHECK(v / D == 2047u); CHECK(v % D == 15u); CHECK(floor_div(v) == 2047u); CHECK(pos_mod(v) == 15u); CHECK(round_div(v) == 2048u); CHECK((v >> 4) == 2047u);
  v = 32768u; CHECK(v / D == 2048u); CHECK(v % D == 0u); CHECK(floor_div(v) == 2048u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 2048u); CHECK((v >> 4) == 2048u);
  v = 40000u; CHECK(v / D == 2500u); CHECK(v % D == 0u); CHECK(floor_div(v) == 2500u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 2500u); CHECK((v >> 4) == 2500u);
  v = 65535u; CHECK(v / D == 4095u); CHECK(v % D == 15u); CHECK(floor_div(v) == 4095u); CHECK(pos_mod(v) == 15u); CHECK((v >> 4) == 4095u);
  v = 5u; CHECK(v / D == 0u); CHECK(v % D == 5u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 5u); CHECK((v >> 4) == 0u);
  v = 9u; CHECK(v / D == 0u); CHECK(v % D == 9u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 9u); CHECK(round_div(v) == 1u); CHECK((v >> 4) == 0u);
  v = 15u; CHECK(v / D == 0u); CHECK(v % D == 15u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 15u); CHECK(round_div(v) == 1u); CHECK((v >> 4) == 0u);
  v = 16u; CHECK(v / D == 1u); CHECK(v % D == 0u); CHECK(floor_div(v) == 1u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 1u); CHECK((v >> 4) == 1u);
  v = 17u; CHECK(v / D == 1u); CHECK(v % D == 1u); CHECK(floor_div(v) == 1u); CHECK(pos_mod(v) == 1u); CHECK(round_div(v) == 1u); CHECK((v >> 4) == 1u);
  return 0;
}
