// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// i16 divided by 16: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((i16)16)
static volatile i16 v;
static i16 floor_div(i16 a) { i16 q = (i16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static i16 pos_mod(i16 a) { i16 m = (i16)(a % D); if (m < 0) m = (i16)(m + D); return m; }
static i16 round_div(i16 a) { return (i16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = (-32767 - 1); CHECK(v / D == (-2048)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-2048)); CHECK(pos_mod(v) == (0)); CHECK((v >> 4) == (-2048));
  v = (-32767); CHECK(v / D == (-2047)); CHECK(v % D == (-15)); CHECK(floor_div(v) == (-2048)); CHECK(pos_mod(v) == (1)); CHECK((v >> 4) == (-2048));
  v = (-1000); CHECK(v / D == (-62)); CHECK(v % D == (-8)); CHECK(floor_div(v) == (-63)); CHECK(pos_mod(v) == (8)); CHECK(round_div(v) == (-63)); CHECK((v >> 4) == (-63));
  v = (-256); CHECK(v / D == (-16)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-16)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-16)); CHECK((v >> 4) == (-16));
  v = (-1); CHECK(v / D == (0)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (15)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (-1));
  v = (0); CHECK(v / D == (0)); CHECK(v % D == (0)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (0));
  v = (1); CHECK(v / D == (0)); CHECK(v % D == (1)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (0));
  v = (2); CHECK(v / D == (0)); CHECK(v % D == (2)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (2)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (0));
  v = (255); CHECK(v / D == (15)); CHECK(v % D == (15)); CHECK(floor_div(v) == (15)); CHECK(pos_mod(v) == (15)); CHECK(round_div(v) == (16)); CHECK((v >> 4) == (15));
  v = (32767); CHECK(v / D == (2047)); CHECK(v % D == (15)); CHECK(floor_div(v) == (2047)); CHECK(pos_mod(v) == (15)); CHECK((v >> 4) == (2047));
  v = (-7); CHECK(v / D == (0)); CHECK(v % D == (-7)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (9)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (-1));
  v = (-8); CHECK(v / D == (0)); CHECK(v % D == (-8)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (8)); CHECK(round_div(v) == (-1)); CHECK((v >> 4) == (-1));
  v = (-9); CHECK(v / D == (0)); CHECK(v % D == (-9)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (7)); CHECK(round_div(v) == (-1)); CHECK((v >> 4) == (-1));
  v = (-15); CHECK(v / D == (0)); CHECK(v % D == (-15)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-1)); CHECK((v >> 4) == (-1));
  v = (-16); CHECK(v / D == (-1)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-1)); CHECK((v >> 4) == (-1));
  v = (-17); CHECK(v / D == (-1)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-2)); CHECK(pos_mod(v) == (15)); CHECK(round_div(v) == (-1)); CHECK((v >> 4) == (-2));
  v = (5); CHECK(v / D == (0)); CHECK(v % D == (5)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (5)); CHECK(round_div(v) == (0)); CHECK((v >> 4) == (0));
  v = (9); CHECK(v / D == (0)); CHECK(v % D == (9)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (9)); CHECK(round_div(v) == (1)); CHECK((v >> 4) == (0));
  return 0;
}
