// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// i16 divided by 7: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((i16)7)
static volatile i16 v;
static i16 floor_div(i16 a) { i16 q = (i16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static i16 pos_mod(i16 a) { i16 m = (i16)(a % D); if (m < 0) m = (i16)(m + D); return m; }
static i16 round_div(i16 a) { return (i16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = (-32767 - 1); CHECK(v / D == (-4681)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-4682)); CHECK(pos_mod(v) == (6));
  v = (-32767); CHECK(v / D == (-4681)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-4681)); CHECK(pos_mod(v) == (0));
  v = (-1000); CHECK(v / D == (-142)); CHECK(v % D == (-6)); CHECK(floor_div(v) == (-143)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-143));
  v = (-256); CHECK(v / D == (-36)); CHECK(v % D == (-4)); CHECK(floor_div(v) == (-37)); CHECK(pos_mod(v) == (3)); CHECK(round_div(v) == (-37));
  v = (-1); CHECK(v / D == (0)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (6)); CHECK(round_div(v) == (0));
  v = (0); CHECK(v / D == (0)); CHECK(v % D == (0)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (0));
  v = (1); CHECK(v / D == (0)); CHECK(v % D == (1)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (0));
  v = (2); CHECK(v / D == (0)); CHECK(v % D == (2)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (2)); CHECK(round_div(v) == (0));
  v = (255); CHECK(v / D == (36)); CHECK(v % D == (3)); CHECK(floor_div(v) == (36)); CHECK(pos_mod(v) == (3)); CHECK(round_div(v) == (36));
  v = (32767); CHECK(v / D == (4681)); CHECK(v % D == (0)); CHECK(floor_div(v) == (4681)); CHECK(pos_mod(v) == (0));
  v = (-7); CHECK(v / D == (-1)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-1));
  v = (-8); CHECK(v / D == (-1)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-2)); CHECK(pos_mod(v) == (6)); CHECK(round_div(v) == (-1));
  v = (-9); CHECK(v / D == (-1)); CHECK(v % D == (-2)); CHECK(floor_div(v) == (-2)); CHECK(pos_mod(v) == (5)); CHECK(round_div(v) == (-1));
  v = (-15); CHECK(v / D == (-2)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-3)); CHECK(pos_mod(v) == (6)); CHECK(round_div(v) == (-2));
  v = (-16); CHECK(v / D == (-2)); CHECK(v % D == (-2)); CHECK(floor_div(v) == (-3)); CHECK(pos_mod(v) == (5)); CHECK(round_div(v) == (-2));
  v = (-17); CHECK(v / D == (-2)); CHECK(v % D == (-3)); CHECK(floor_div(v) == (-3)); CHECK(pos_mod(v) == (4)); CHECK(round_div(v) == (-2));
  v = (5); CHECK(v / D == (0)); CHECK(v % D == (5)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (5)); CHECK(round_div(v) == (1));
  v = (9); CHECK(v / D == (1)); CHECK(v % D == (2)); CHECK(floor_div(v) == (1)); CHECK(pos_mod(v) == (2)); CHECK(round_div(v) == (1));
  return 0;
}
