// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// u16 divided by 7: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((u16)7)
static volatile u16 v;
static u16 floor_div(u16 a) { u16 q = (u16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static u16 pos_mod(u16 a) { u16 m = (u16)(a % D); if (m < 0) m = (u16)(m + D); return m; }
static u16 round_div(u16 a) { return (u16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = 0u; CHECK(v / D == 0u); CHECK(v % D == 0u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 0u);
  v = 1u; CHECK(v / D == 0u); CHECK(v % D == 1u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 1u);
  v = 2u; CHECK(v / D == 0u); CHECK(v % D == 2u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 2u);
  v = 255u; CHECK(v / D == 36u); CHECK(v % D == 3u); CHECK(floor_div(v) == 36u); CHECK(pos_mod(v) == 3u); CHECK(round_div(v) == 36u);
  v = 256u; CHECK(v / D == 36u); CHECK(v % D == 4u); CHECK(floor_div(v) == 36u); CHECK(pos_mod(v) == 4u); CHECK(round_div(v) == 37u);
  v = 1000u; CHECK(v / D == 142u); CHECK(v % D == 6u); CHECK(floor_div(v) == 142u); CHECK(pos_mod(v) == 6u); CHECK(round_div(v) == 143u);
  v = 32767u; CHECK(v / D == 4681u); CHECK(v % D == 0u); CHECK(floor_div(v) == 4681u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 4681u);
  v = 32768u; CHECK(v / D == 4681u); CHECK(v % D == 1u); CHECK(floor_div(v) == 4681u); CHECK(pos_mod(v) == 1u); CHECK(round_div(v) == 4681u);
  v = 40000u; CHECK(v / D == 5714u); CHECK(v % D == 2u); CHECK(floor_div(v) == 5714u); CHECK(pos_mod(v) == 2u); CHECK(round_div(v) == 5714u);
  v = 65535u; CHECK(v / D == 9362u); CHECK(v % D == 1u); CHECK(floor_div(v) == 9362u); CHECK(pos_mod(v) == 1u);
  v = 5u; CHECK(v / D == 0u); CHECK(v % D == 5u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 5u); CHECK(round_div(v) == 1u);
  v = 9u; CHECK(v / D == 1u); CHECK(v % D == 2u); CHECK(floor_div(v) == 1u); CHECK(pos_mod(v) == 2u); CHECK(round_div(v) == 1u);
  v = 15u; CHECK(v / D == 2u); CHECK(v % D == 1u); CHECK(floor_div(v) == 2u); CHECK(pos_mod(v) == 1u); CHECK(round_div(v) == 2u);
  v = 16u; CHECK(v / D == 2u); CHECK(v % D == 2u); CHECK(floor_div(v) == 2u); CHECK(pos_mod(v) == 2u); CHECK(round_div(v) == 2u);
  v = 17u; CHECK(v / D == 2u); CHECK(v % D == 3u); CHECK(floor_div(v) == 2u); CHECK(pos_mod(v) == 3u); CHECK(round_div(v) == 2u);
  return 0;
}
