// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// u16 divided by 100: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((u16)100)
static volatile u16 v;
static u16 floor_div(u16 a) { u16 q = (u16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static u16 pos_mod(u16 a) { u16 m = (u16)(a % D); if (m < 0) m = (u16)(m + D); return m; }
static u16 round_div(u16 a) { return (u16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = 0u; CHECK(v / D == 0u); CHECK(v % D == 0u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 0u);
  v = 1u; CHECK(v / D == 0u); CHECK(v % D == 1u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 1u);
  v = 2u; CHECK(v / D == 0u); CHECK(v % D == 2u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 2u);
  v = 255u; CHECK(v / D == 2u); CHECK(v % D == 55u); CHECK(floor_div(v) == 2u); CHECK(pos_mod(v) == 55u); CHECK(round_div(v) == 3u);
  v = 256u; CHECK(v / D == 2u); CHECK(v % D == 56u); CHECK(floor_div(v) == 2u); CHECK(pos_mod(v) == 56u); CHECK(round_div(v) == 3u);
  v = 1000u; CHECK(v / D == 10u); CHECK(v % D == 0u); CHECK(floor_div(v) == 10u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 10u);
  v = 32767u; CHECK(v / D == 327u); CHECK(v % D == 67u); CHECK(floor_div(v) == 327u); CHECK(pos_mod(v) == 67u); CHECK(round_div(v) == 328u);
  v = 32768u; CHECK(v / D == 327u); CHECK(v % D == 68u); CHECK(floor_div(v) == 327u); CHECK(pos_mod(v) == 68u); CHECK(round_div(v) == 328u);
  v = 40000u; CHECK(v / D == 400u); CHECK(v % D == 0u); CHECK(floor_div(v) == 400u); CHECK(pos_mod(v) == 0u); CHECK(round_div(v) == 400u);
  v = 65535u; CHECK(v / D == 655u); CHECK(v % D == 35u); CHECK(floor_div(v) == 655u); CHECK(pos_mod(v) == 35u);
  v = 5u; CHECK(v / D == 0u); CHECK(v % D == 5u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 5u);
  v = 9u; CHECK(v / D == 0u); CHECK(v % D == 9u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 9u);
  v = 15u; CHECK(v / D == 0u); CHECK(v % D == 15u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 15u);
  v = 16u; CHECK(v / D == 0u); CHECK(v % D == 16u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 16u);
  v = 17u; CHECK(v / D == 0u); CHECK(v % D == 17u); CHECK(floor_div(v) == 0u); CHECK(pos_mod(v) == 17u);
  return 0;
}
