// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// i16 divided by 2: C's truncating / and %, floor division, a
// positive modulo and round-to-nearest built on them, and >> for powers of two.
#include "loomcc-test.h"
#define D ((i16)2)
static volatile i16 v;
static i16 floor_div(i16 a) { i16 q = (i16)(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }
static i16 pos_mod(i16 a) { i16 m = (i16)(a % D); if (m < 0) m = (i16)(m + D); return m; }
static i16 round_div(i16 a) { return (i16)((a >= 0 ? a + D / 2 : a - D / 2) / D); }
int main(void) {
  v = (-32767 - 1); CHECK(v / D == (-16384)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-16384)); CHECK(pos_mod(v) == (0)); CHECK((v >> 1) == (-16384));
  v = (-32767); CHECK(v / D == (-16383)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-16384)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-16384)); CHECK((v >> 1) == (-16384));
  v = (-1000); CHECK(v / D == (-500)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-500)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-500)); CHECK((v >> 1) == (-500));
  v = (-256); CHECK(v / D == (-128)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-128)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-128)); CHECK((v >> 1) == (-128));
  v = (-1); CHECK(v / D == (0)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-1)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-1)); CHECK((v >> 1) == (-1));
  v = (0); CHECK(v / D == (0)); CHECK(v % D == (0)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (0)); CHECK((v >> 1) == (0));
  v = (1); CHECK(v / D == (0)); CHECK(v % D == (1)); CHECK(floor_div(v) == (0)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (1)); CHECK((v >> 1) == (0));
  v = (2); CHECK(v / D == (1)); CHECK(v % D == (0)); CHECK(floor_div(v) == (1)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (1)); CHECK((v >> 1) == (1));
  v = (255); CHECK(v / D == (127)); CHECK(v % D == (1)); CHECK(floor_div(v) == (127)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (128)); CHECK((v >> 1) == (127));
  v = (32767); CHECK(v / D == (16383)); CHECK(v % D == (1)); CHECK(floor_div(v) == (16383)); CHECK(pos_mod(v) == (1)); CHECK((v >> 1) == (16383));
  v = (-7); CHECK(v / D == (-3)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-4)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-4)); CHECK((v >> 1) == (-4));
  v = (-8); CHECK(v / D == (-4)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-4)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-4)); CHECK((v >> 1) == (-4));
  v = (-9); CHECK(v / D == (-4)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-5)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-5)); CHECK((v >> 1) == (-5));
  v = (-15); CHECK(v / D == (-7)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-8)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-8)); CHECK((v >> 1) == (-8));
  v = (-16); CHECK(v / D == (-8)); CHECK(v % D == (0)); CHECK(floor_div(v) == (-8)); CHECK(pos_mod(v) == (0)); CHECK(round_div(v) == (-8)); CHECK((v >> 1) == (-8));
  v = (-17); CHECK(v / D == (-8)); CHECK(v % D == (-1)); CHECK(floor_div(v) == (-9)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (-9)); CHECK((v >> 1) == (-9));
  v = (5); CHECK(v / D == (2)); CHECK(v % D == (1)); CHECK(floor_div(v) == (2)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (3)); CHECK((v >> 1) == (2));
  v = (9); CHECK(v / D == (4)); CHECK(v % D == (1)); CHECK(floor_div(v) == (4)); CHECK(pos_mod(v) == (1)); CHECK(round_div(v) == (5)); CHECK((v >> 1) == (4));
  return 0;
}
