// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [10] = 110, [13] = 113, [17] = 117, [14] = 114, 115 };
static const i16 a1[] = { [0] = 100, 101, 102, 103, 104, [4] = 104, 105 };
static const i16 a2[] = { [12] = 112, 113, 114 };
static const i16 a3[] = { [16] = 116, 117, [10] = 110, 111, [11] = 111 };
static const i16 a4[] = { [17] = 117, 118, 119, 120, 121, 122 };
static const i16 a5[] = { 100, 101 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 18);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 6);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 15);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 18);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 23);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 2);
