// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [0] = 100 };
static const i16 a1[] = { [11] = 111, 112 };
static const i16 a2[] = { [16] = 116, 117, [13] = 113, 114, [7] = 107, 108 };
static const i16 a3[] = { 100, 101, 102 };
static const i16 a4[] = { 100, [4] = 104, 105, [10] = 110, [7] = 107 };
static const i16 a5[] = { 100 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 1);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 13);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 18);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 3);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 11);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 1);
