// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [4] = 104, [19] = 119, 120, 121, [18] = 118, [15] = 115 };
static const i16 a1[] = { [7] = 107, [13] = 113, 114, [14] = 114, [8] = 108, 109 };
static const i16 a2[] = { [2] = 102, [12] = 112, [4] = 104, 105, 106, 107, 108 };
static const i16 a3[] = { 100, 101, 102, [11] = 111 };
static const i16 a4[] = { 100, 101 };
static const i16 a5[] = { 100 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 22);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 15);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 13);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 12);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 2);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 1);
