// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [3] = 103, [13] = 113, [8] = 108, 109 };
static const i16 a1[] = { 100, 101, [3] = 103, 104, [12] = 112, 113 };
static const i16 a2[] = { 100, 101 };
static const i16 a3[] = { [16] = 116, [3] = 103, [5] = 105, [7] = 107, [14] = 114, [15] = 115 };
static const i16 a4[] = { 100, 101, 102, 103, [9] = 109, [16] = 116 };
static const i16 a5[] = { 100, 101 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 14);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 14);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 2);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 17);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 17);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 2);
