// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, 101, [0] = 100, 101, 102, 103, [8] = 108 };
static const i16 a1[] = { 100, 101, [17] = 117, [9] = 109 };
static const i16 a2[] = { 100, 101, [18] = 118, 119, 120 };
static const i16 a3[] = { 100, 101, [11] = 111 };
static const i16 a4[] = { 100, [11] = 111, 112, 113 };
static const i16 a5[] = { [12] = 112, 113, 114, [18] = 118, 119 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 9);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 18);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 21);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 12);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 14);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 20);
