// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100 };
static const i16 a1[] = { 100, [18] = 118, 119, 120 };
static const i16 a2[] = { 100, [4] = 104, [1] = 101, 102, [14] = 114 };
static const i16 a3[] = { 100 };
static const i16 a4[] = { [0] = 100, [7] = 107, 108, 109, 110, [4] = 104, 105 };
static const i16 a5[] = { [19] = 119, 120 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 1);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 21);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 15);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 1);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 11);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 21);
