// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, [8] = 108 };
static const i16 a1[] = { [13] = 113, [12] = 112 };
static const i16 a2[] = { [0] = 100, 101, [7] = 107, 108, [15] = 115, 116 };
static const i16 a3[] = { 100, 101 };
static const i16 a4[] = { [7] = 107, [4] = 104, [5] = 105 };
static const i16 a5[] = { 100, [7] = 107, [1] = 101, 102, [18] = 118, [17] = 117 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 9);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 14);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 17);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 2);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 8);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 19);
