// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { [2] = 102, 103 };
static const i16 a1[] = { 100 };
static const i16 a2[] = { [14] = 114, 115, 116, [19] = 119, 120 };
static const i16 a3[] = { [8] = 108, 109, [8] = 108, [9] = 109 };
static const i16 a4[] = { [7] = 107, [12] = 112, 113, 114, 115, [17] = 117, [5] = 105 };
static const i16 a5[] = { [13] = 113, [1] = 101, [0] = 100, [14] = 114, 115, 116 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 4);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 1);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 21);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 10);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 18);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 17);
