// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: syntax
// Array length from designated and positional initialisers: the largest
// index initialised, plus one (6.7.9p22); a later designator may go back.
#include "loomcc-test.h"
static const i16 a0[] = { 100, 101, 102, [8] = 108 };
static const i16 a1[] = { [8] = 108, 109, 110, [0] = 100 };
static const i16 a2[] = { 100 };
static const i16 a3[] = { 100, [17] = 117, [8] = 108 };
static const i16 a4[] = { 100, [3] = 103, 104, 105, 106, [15] = 115, [14] = 114 };
static const i16 a5[] = { [1] = 101, [18] = 118, 119, 120, 121, [11] = 111 };
STATIC_CHECK(sizeof(a0) / sizeof(a0[0]) == 9);
STATIC_CHECK(sizeof(a1) / sizeof(a1[0]) == 11);
STATIC_CHECK(sizeof(a2) / sizeof(a2[0]) == 1);
STATIC_CHECK(sizeof(a3) / sizeof(a3[0]) == 18);
STATIC_CHECK(sizeof(a4) / sizeof(a4[0]) == 16);
STATIC_CHECK(sizeof(a5) / sizeof(a5[0]) == 22);
