// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A ring buffer of 12 u8 entries indexed by u8 head/tail (% wrap).
#include "loomcc-test.h"
#define CAP 12
static u8 buf[CAP];
static u8 head, tail, count;
static u8 push(u8 v) { if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) % 12); count++; return 1; }
static u8 pop(u8 *v) { if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) % 12); count--; return 1; }
int main(void) {
  u8 v = 0;
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(push(27) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 27);
  CHECK(push(223) == 1);
  CHECK(push(31) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 223);
  CHECK(push(215) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 31);
  CHECK(pop(&v) == 1); CHECK(v == 215);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(push(145) == 1);
  CHECK(push(78) == 1);
  CHECK(push(225) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 145);
  CHECK(push(55) == 1);
  CHECK(push(116) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 78);
  CHECK(pop(&v) == 1); CHECK(v == 225);
  CHECK(push(186) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 55);
  CHECK(push(80) == 1);
  CHECK(push(185) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 116);
  CHECK(pop(&v) == 1); CHECK(v == 186);
  CHECK(push(144) == 1);
  CHECK(push(66) == 1);
  CHECK(push(74) == 1);
  CHECK(push(113) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 80);
  CHECK(push(68) == 1);
  CHECK(push(234) == 1);
  CHECK(push(211) == 1);
  CHECK(push(34) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 185);
  CHECK(push(164) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 144);
  CHECK(push(10) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 66);
  CHECK(push(99) == 1);
  CHECK(push(34) == 1);
  CHECK(push(227) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 74);
  CHECK(push(14) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 113);
  CHECK(pop(&v) == 1); CHECK(v == 68);
  CHECK(push(166) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 234);
  CHECK(push(160) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 211);
  CHECK(push(81) == 1);
  CHECK(push(178) == 1);
  CHECK(push(197) == 1);
  CHECK(push(254) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 34);
  CHECK(pop(&v) == 1); CHECK(v == 164);
  CHECK(pop(&v) == 1); CHECK(v == 10);
  CHECK(pop(&v) == 1); CHECK(v == 99);
  return 0;
}
