// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A ring buffer of 12 u8 entries indexed by u8 head/tail (% wrap).
#include "loomcc-test.h"
#define CAP 12
static u8 buf[CAP];
static u8 head, tail, count;
static u8 push(u8 v) { if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) % 12); count++; return 1; }
static u8 pop(u8 *v) { if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) % 12); count--; return 1; }
int main(void) {
  u8 v = 0;
  CHECK(push(132) == 1);
  CHECK(push(77) == 1);
  CHECK(push(152) == 1);
  CHECK(push(230) == 1);
  CHECK(push(225) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 132);
  CHECK(push(106) == 1);
  CHECK(push(68) == 1);
  CHECK(push(222) == 1);
  CHECK(push(183) == 1);
  CHECK(push(239) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 77);
  CHECK(push(207) == 1);
  CHECK(push(22) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 152);
  CHECK(pop(&v) == 1); CHECK(v == 230);
  CHECK(push(217) == 1);
  CHECK(push(110) == 1);
  CHECK(push(226) == 1);
  CHECK(push(146) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 225);
  CHECK(pop(&v) == 1); CHECK(v == 106);
  CHECK(pop(&v) == 1); CHECK(v == 68);
  CHECK(push(151) == 1);
  CHECK(push(117) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 222);
  CHECK(push(183) == 1);
  CHECK(push(116) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 183);
  CHECK(push(176) == 1);
  CHECK(push(126) == 0);
  CHECK(push(40) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 239);
  CHECK(push(86) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 207);
  CHECK(pop(&v) == 1); CHECK(v == 22);
  CHECK(push(196) == 1);
  CHECK(push(37) == 1);
  CHECK(push(78) == 0);
  CHECK(push(93) == 0);
  CHECK(push(126) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 217);
  CHECK(push(81) == 1);
  CHECK(push(196) == 0);
  CHECK(push(80) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 110);
  CHECK(pop(&v) == 1); CHECK(v == 226);
  CHECK(pop(&v) == 1); CHECK(v == 146);
  CHECK(push(114) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 151);
  CHECK(push(71) == 1);
  CHECK(push(229) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 117);
  CHECK(push(213) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 183);
  CHECK(push(113) == 1);
  CHECK(push(210) == 1);
  CHECK(push(6) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 116);
  CHECK(pop(&v) == 1); CHECK(v == 176);
  return 0;
}
