// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A ring buffer of 4 u8 entries indexed by u8 head/tail (& wrap).
#include "loomcc-test.h"
#define CAP 4
static u8 buf[CAP];
static u8 head, tail, count;
static u8 push(u8 v) { if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) & 3); count++; return 1; }
static u8 pop(u8 *v) { if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) & 3); count--; return 1; }
int main(void) {
  u8 v = 0;
  CHECK(pop(&v) == 0);
  CHECK(push(226) == 1);
  CHECK(push(106) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 226);
  CHECK(pop(&v) == 1); CHECK(v == 106);
  CHECK(pop(&v) == 0);
  CHECK(pop(&v) == 0);
  CHECK(push(118) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 118);
  CHECK(push(237) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 237);
  CHECK(push(196) == 1);
  CHECK(push(54) == 1);
  CHECK(push(74) == 1);
  CHECK(push(154) == 1);
  CHECK(push(204) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 196);
  CHECK(push(163) == 1);
  CHECK(push(211) == 0);
  CHECK(push(216) == 0);
  CHECK(push(157) == 0);
  CHECK(push(143) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 54);
  CHECK(pop(&v) == 1); CHECK(v == 74);
  CHECK(push(7) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 154);
  CHECK(pop(&v) == 1); CHECK(v == 163);
  CHECK(push(21) == 1);
  CHECK(push(168) == 1);
  CHECK(push(139) == 1);
  CHECK(push(229) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 7);
  CHECK(push(246) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 21);
  CHECK(pop(&v) == 1); CHECK(v == 168);
  CHECK(pop(&v) == 1); CHECK(v == 139);
  CHECK(push(61) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 246);
  CHECK(pop(&v) == 1); CHECK(v == 61);
  CHECK(push(21) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 21);
  CHECK(pop(&v) == 0);
  CHECK(push(127) == 1);
  CHECK(push(252) == 1);
  CHECK(push(113) == 1);
  CHECK(push(136) == 1);
  CHECK(push(241) == 0);
  CHECK(pop(&v) == 1); CHECK(v == 127);
  CHECK(pop(&v) == 1); CHECK(v == 252);
  CHECK(pop(&v) == 1); CHECK(v == 113);
  CHECK(push(7) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 136);
  CHECK(pop(&v) == 1); CHECK(v == 7);
  CHECK(pop(&v) == 0);
  CHECK(push(60) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 60);
  CHECK(push(15) == 1);
  CHECK(push(240) == 1);
  CHECK(push(48) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 15);
  return 0;
}
