// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A ring buffer of 12 u8 entries indexed by u8 head/tail (% wrap).
#include "loomcc-test.h"
#define CAP 12
static u8 buf[CAP];
static u8 head, tail, count;
static u8 push(u8 v) { if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) % 12); count++; return 1; }
static u8 pop(u8 *v) { if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) % 12); count--; return 1; }
int main(void) {
  u8 v = 0;
  CHECK(push(47) == 1);
  CHECK(push(57) == 1);
  CHECK(push(188) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 47);
  CHECK(pop(&v) == 1); CHECK(v == 57);
  CHECK(push(238) == 1);
  CHECK(push(123) == 1);
  CHECK(push(229) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 188);
  CHECK(push(172) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 238);
  CHECK(pop(&v) == 1); CHECK(v == 123);
  CHECK(push(165) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 229);
  CHECK(push(222) == 1);
  CHECK(push(74) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 172);
  CHECK(pop(&v) == 1); CHECK(v == 165);
  CHECK(pop(&v) == 1); CHECK(v == 222);
  CHECK(push(46) == 1);
  CHECK(push(75) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 74);
  CHECK(push(183) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 46);
  CHECK(push(172) == 1);
  CHECK(push(227) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 75);
  CHECK(push(193) == 1);
  CHECK(push(213) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 183);
  CHECK(push(198) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 172);
  CHECK(push(237) == 1);
  CHECK(push(164) == 1);
  CHECK(push(99) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 227);
  CHECK(push(185) == 1);
  CHECK(push(46) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 193);
  CHECK(push(81) == 1);
  CHECK(push(171) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 213);
  CHECK(pop(&v) == 1); CHECK(v == 198);
  CHECK(push(116) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 237);
  CHECK(pop(&v) == 1); CHECK(v == 164);
  CHECK(pop(&v) == 1); CHECK(v == 99);
  CHECK(push(140) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 185);
  CHECK(pop(&v) == 1); CHECK(v == 46);
  CHECK(pop(&v) == 1); CHECK(v == 81);
  CHECK(push(244) == 1);
  CHECK(push(221) == 1);
  CHECK(push(243) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 171);
  CHECK(pop(&v) == 1); CHECK(v == 116);
  CHECK(push(79) == 1);
  CHECK(push(20) == 1);
  CHECK(pop(&v) == 1); CHECK(v == 140);
  CHECK(push(139) == 1);
  return 0;
}
