// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 8x8 table of u8 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const u8 lut[8][8] = {
  { 243, 139, 69, 137, 82, 62, 83, 152 },
  { 5, 172, 0, 217, 96, 100, 99, 46 },
  { 179, 127, 145, 131, 237, 91, 254, 21 },
  { 244, 122, 215, 72, 13, 241, 119, 219 },
  { 187, 41, 24, 145, 197, 95, 161, 48 },
  { 104, 64, 86, 65, 238, 27, 54, 107 },
  { 99, 9, 141, 154, 135, 198, 230, 255 },
  { 151, 115, 143, 241, 30, 88, 30, 29 }
};
static const u8 *const rowp[8] = { lut[0], lut[1], lut[2], lut[3], lut[4], lut[5], lut[6], lut[7] };
static volatile u8 vi, vj;
static i32 row_sum(const u8 *row) { u16 j; i32 s = 0; for (j = 0; j < 8; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 2; vj = 7; CHECK(lut[vi][vj] == (u8)(21)); CHECK(rowp[vi][vj] == (u8)(21));
  vi = 2; vj = 4; CHECK(lut[vi][vj] == (u8)(237)); CHECK(rowp[vi][vj] == (u8)(237));
  vi = 5; vj = 7; CHECK(lut[vi][vj] == (u8)(107)); CHECK(rowp[vi][vj] == (u8)(107));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (u8)(27)); CHECK(rowp[vi][vj] == (u8)(27));
  vi = 6; vj = 0; CHECK(lut[vi][vj] == (u8)(99)); CHECK(rowp[vi][vj] == (u8)(99));
  vi = 6; vj = 5; CHECK(lut[vi][vj] == (u8)(198)); CHECK(rowp[vi][vj] == (u8)(198));
  vi = 0; vj = 2; CHECK(lut[vi][vj] == (u8)(69)); CHECK(rowp[vi][vj] == (u8)(69));
  vi = 6; vj = 5; CHECK(lut[vi][vj] == (u8)(198)); CHECK(rowp[vi][vj] == (u8)(198));
  vi = 6; vj = 0; CHECK(lut[vi][vj] == (u8)(99)); CHECK(rowp[vi][vj] == (u8)(99));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (u8)(27)); CHECK(rowp[vi][vj] == (u8)(27));
  vi = 3; vj = 4; CHECK(lut[vi][vj] == (u8)(13)); CHECK(rowp[vi][vj] == (u8)(13));
  vi = 7; vj = 3; CHECK(lut[vi][vj] == (u8)(241)); CHECK(rowp[vi][vj] == (u8)(241));
  vi = 6; vj = 4; CHECK(lut[vi][vj] == (u8)(135)); CHECK(rowp[vi][vj] == (u8)(135));
  vi = 6; vj = 1; CHECK(lut[vi][vj] == (u8)(9)); CHECK(rowp[vi][vj] == (u8)(9));
  vi = 0; vj = 1; CHECK(lut[vi][vj] == (u8)(139)); CHECK(rowp[vi][vj] == (u8)(139));
  vi = 4; vj = 3; CHECK(lut[vi][vj] == (u8)(145)); CHECK(rowp[vi][vj] == (u8)(145));
  vi = 1; vj = 1; CHECK(lut[vi][vj] == (u8)(172)); CHECK(rowp[vi][vj] == (u8)(172));
  vi = 7; vj = 2; CHECK(lut[vi][vj] == (u8)(143)); CHECK(rowp[vi][vj] == (u8)(143));
  vi = 4; vj = 4; CHECK(lut[vi][vj] == (u8)(197)); CHECK(rowp[vi][vj] == (u8)(197));
  vi = 7; vj = 0; CHECK(lut[vi][vj] == (u8)(151)); CHECK(rowp[vi][vj] == (u8)(151));
  vi = 4; vj = 3; CHECK(lut[vi][vj] == (u8)(145)); CHECK(rowp[vi][vj] == (u8)(145));
  vi = 6; vj = 4; CHECK(lut[vi][vj] == (u8)(135)); CHECK(rowp[vi][vj] == (u8)(135));
  vi = 0; vj = 7; CHECK(lut[vi][vj] == (u8)(152)); CHECK(rowp[vi][vj] == (u8)(152));
  vi = 7; vj = 7; CHECK(lut[vi][vj] == (u8)(29)); CHECK(rowp[vi][vj] == (u8)(29));
  for (i = 0; i < 8; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)967LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)735LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)1185LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)1245LL);
    if (i == 4) CHECK(row_sum(rowp[i]) == (i32)898LL);
    if (i == 5) CHECK(row_sum(rowp[i]) == (i32)745LL);
    if (i == 6) CHECK(row_sum(rowp[i]) == (i32)1221LL);
    if (i == 7) CHECK(row_sum(rowp[i]) == (i32)827LL);
  }
  return 0;
}
