// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 8x8 table of i16 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const i16 lut[8][8] = {
  { 13052, 24623, -997, -23165, 5434, 4905, 26947, -11182 },
  { 26227, 14868, 29597, 14070, 9136, 19672, -14643, 22356 },
  { 1014, -25417, 3108, -2872, -24784, -12126, -6595, -16919 },
  { -22256, 29296, 10924, -25615, -28263, 10117, 21595, -12930 },
  { -17730, -3955, 10148, 11268, -31724, 3983, -15684, -15644 },
  { -1304, 22619, -950, -1181, 2389, -16396, -28265, -13644 },
  { 23686, -16628, -9834, -22734, 7204, -24906, -8004, 27172 },
  { -11680, 2884, -13022, -23726, 29387, 24374, -23902, 28000 }
};
static const i16 *const rowp[8] = { lut[0], lut[1], lut[2], lut[3], lut[4], lut[5], lut[6], lut[7] };
static volatile u8 vi, vj;
static i32 row_sum(const i16 *row) { u16 j; i32 s = 0; for (j = 0; j < 8; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 3; vj = 5; CHECK(lut[vi][vj] == (i16)(10117)); CHECK(rowp[vi][vj] == (i16)(10117));
  vi = 5; vj = 3; CHECK(lut[vi][vj] == (i16)(-1181)); CHECK(rowp[vi][vj] == (i16)(-1181));
  vi = 1; vj = 1; CHECK(lut[vi][vj] == (i16)(14868)); CHECK(rowp[vi][vj] == (i16)(14868));
  vi = 4; vj = 7; CHECK(lut[vi][vj] == (i16)(-15644)); CHECK(rowp[vi][vj] == (i16)(-15644));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (i16)(-16396)); CHECK(rowp[vi][vj] == (i16)(-16396));
  vi = 1; vj = 7; CHECK(lut[vi][vj] == (i16)(22356)); CHECK(rowp[vi][vj] == (i16)(22356));
  vi = 1; vj = 0; CHECK(lut[vi][vj] == (i16)(26227)); CHECK(rowp[vi][vj] == (i16)(26227));
  vi = 4; vj = 4; CHECK(lut[vi][vj] == (i16)(-31724)); CHECK(rowp[vi][vj] == (i16)(-31724));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (i16)(-16396)); CHECK(rowp[vi][vj] == (i16)(-16396));
  vi = 1; vj = 1; CHECK(lut[vi][vj] == (i16)(14868)); CHECK(rowp[vi][vj] == (i16)(14868));
  vi = 7; vj = 0; CHECK(lut[vi][vj] == (i16)(-11680)); CHECK(rowp[vi][vj] == (i16)(-11680));
  vi = 7; vj = 2; CHECK(lut[vi][vj] == (i16)(-13022)); CHECK(rowp[vi][vj] == (i16)(-13022));
  vi = 2; vj = 4; CHECK(lut[vi][vj] == (i16)(-24784)); CHECK(rowp[vi][vj] == (i16)(-24784));
  vi = 3; vj = 1; CHECK(lut[vi][vj] == (i16)(29296)); CHECK(rowp[vi][vj] == (i16)(29296));
  vi = 0; vj = 3; CHECK(lut[vi][vj] == (i16)(-23165)); CHECK(rowp[vi][vj] == (i16)(-23165));
  vi = 3; vj = 6; CHECK(lut[vi][vj] == (i16)(21595)); CHECK(rowp[vi][vj] == (i16)(21595));
  vi = 5; vj = 1; CHECK(lut[vi][vj] == (i16)(22619)); CHECK(rowp[vi][vj] == (i16)(22619));
  vi = 6; vj = 0; CHECK(lut[vi][vj] == (i16)(23686)); CHECK(rowp[vi][vj] == (i16)(23686));
  vi = 4; vj = 7; CHECK(lut[vi][vj] == (i16)(-15644)); CHECK(rowp[vi][vj] == (i16)(-15644));
  vi = 7; vj = 5; CHECK(lut[vi][vj] == (i16)(24374)); CHECK(rowp[vi][vj] == (i16)(24374));
  vi = 3; vj = 2; CHECK(lut[vi][vj] == (i16)(10924)); CHECK(rowp[vi][vj] == (i16)(10924));
  vi = 0; vj = 4; CHECK(lut[vi][vj] == (i16)(5434)); CHECK(rowp[vi][vj] == (i16)(5434));
  vi = 1; vj = 7; CHECK(lut[vi][vj] == (i16)(22356)); CHECK(rowp[vi][vj] == (i16)(22356));
  vi = 3; vj = 3; CHECK(lut[vi][vj] == (i16)(-25615)); CHECK(rowp[vi][vj] == (i16)(-25615));
  for (i = 0; i < 8; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)39617LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)121283LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)-84591LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)-17132LL);
    if (i == 4) CHECK(row_sum(rowp[i]) == (i32)-59338LL);
    if (i == 5) CHECK(row_sum(rowp[i]) == (i32)-36732LL);
    if (i == 6) CHECK(row_sum(rowp[i]) == (i32)-24044LL);
    if (i == 7) CHECK(row_sum(rowp[i]) == (i32)12315LL);
  }
  return 0;
}
