// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 16x12 table of i8 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const i8 lut[16][12] = {
  { -60, -14, -36, 94, 17, 90, 117, -110, -20, 66, -62, 105 },
  { 124, -23, 87, 90, 34, 102, -71, -50, 25, 85, -4, -47 },
  { 117, -55, -67, 96, 14, -33, -16, 15, 88, 90, -14, -81 },
  { 27, -98, -42, -119, 1, -88, 25, -36, -18, -11, -2, 101 },
  { 3, 1, -1, 79, -119, -113, 18, -61, 4, -118, 78, -55 },
  { -82, 91, -93, -32, 118, -14, 124, 25, 124, -78, 3, 107 },
  { -63, -75, 22, -9, 26, 104, 33, 58, 76, 85, -67, -35 },
  { -103, 28, -86, -104, -25, -50, 39, -107, -27, -27, -37, -88 },
  { 30, -22, -122, -49, 16, 88, -61, 73, 74, -124, 59, -115 },
  { 106, -93, 12, 36, -19, 80, -81, -87, -114, -52, 61, 24 },
  { -46, 90, -101, -62, -12, -44, -48, 19, -92, -87, 30, -41 },
  { 111, 33, 74, 47, -84, -85, -38, 79, -18, 50, 73, 1 },
  { 103, 20, -127, -88, -41, 71, 102, 102, -125, 104, -118, -92 },
  { -60, -33, -4, 39, 58, 7, 73, -27, -68, -47, -106, -89 },
  { -8, -56, 20, -78, -73, 53, -117, 62, 4, 124, -116, 93 },
  { 57, -98, -68, -100, -42, 24, -123, 108, -76, -81, 92, -76 }
};
static const i8 *const rowp[16] = { lut[0], lut[1], lut[2], lut[3], lut[4], lut[5], lut[6], lut[7], lut[8], lut[9], lut[10], lut[11], lut[12], lut[13], lut[14], lut[15] };
static volatile u8 vi, vj;
static i32 row_sum(const i8 *row) { u16 j; i32 s = 0; for (j = 0; j < 12; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 8; vj = 1; CHECK(lut[vi][vj] == (i8)(-22)); CHECK(rowp[vi][vj] == (i8)(-22));
  vi = 10; vj = 7; CHECK(lut[vi][vj] == (i8)(19)); CHECK(rowp[vi][vj] == (i8)(19));
  vi = 13; vj = 6; CHECK(lut[vi][vj] == (i8)(73)); CHECK(rowp[vi][vj] == (i8)(73));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (i8)(-14)); CHECK(rowp[vi][vj] == (i8)(-14));
  vi = 13; vj = 11; CHECK(lut[vi][vj] == (i8)(-89)); CHECK(rowp[vi][vj] == (i8)(-89));
  vi = 14; vj = 2; CHECK(lut[vi][vj] == (i8)(20)); CHECK(rowp[vi][vj] == (i8)(20));
  vi = 3; vj = 11; CHECK(lut[vi][vj] == (i8)(101)); CHECK(rowp[vi][vj] == (i8)(101));
  vi = 12; vj = 8; CHECK(lut[vi][vj] == (i8)(-125)); CHECK(rowp[vi][vj] == (i8)(-125));
  vi = 4; vj = 7; CHECK(lut[vi][vj] == (i8)(-61)); CHECK(rowp[vi][vj] == (i8)(-61));
  vi = 6; vj = 8; CHECK(lut[vi][vj] == (i8)(76)); CHECK(rowp[vi][vj] == (i8)(76));
  vi = 8; vj = 8; CHECK(lut[vi][vj] == (i8)(74)); CHECK(rowp[vi][vj] == (i8)(74));
  vi = 4; vj = 3; CHECK(lut[vi][vj] == (i8)(79)); CHECK(rowp[vi][vj] == (i8)(79));
  vi = 7; vj = 11; CHECK(lut[vi][vj] == (i8)(-88)); CHECK(rowp[vi][vj] == (i8)(-88));
  vi = 14; vj = 1; CHECK(lut[vi][vj] == (i8)(-56)); CHECK(rowp[vi][vj] == (i8)(-56));
  vi = 15; vj = 8; CHECK(lut[vi][vj] == (i8)(-76)); CHECK(rowp[vi][vj] == (i8)(-76));
  vi = 4; vj = 5; CHECK(lut[vi][vj] == (i8)(-113)); CHECK(rowp[vi][vj] == (i8)(-113));
  vi = 0; vj = 9; CHECK(lut[vi][vj] == (i8)(66)); CHECK(rowp[vi][vj] == (i8)(66));
  vi = 3; vj = 11; CHECK(lut[vi][vj] == (i8)(101)); CHECK(rowp[vi][vj] == (i8)(101));
  vi = 12; vj = 5; CHECK(lut[vi][vj] == (i8)(71)); CHECK(rowp[vi][vj] == (i8)(71));
  vi = 13; vj = 8; CHECK(lut[vi][vj] == (i8)(-68)); CHECK(rowp[vi][vj] == (i8)(-68));
  vi = 3; vj = 2; CHECK(lut[vi][vj] == (i8)(-42)); CHECK(rowp[vi][vj] == (i8)(-42));
  vi = 7; vj = 8; CHECK(lut[vi][vj] == (i8)(-27)); CHECK(rowp[vi][vj] == (i8)(-27));
  vi = 1; vj = 1; CHECK(lut[vi][vj] == (i8)(-23)); CHECK(rowp[vi][vj] == (i8)(-23));
  vi = 9; vj = 3; CHECK(lut[vi][vj] == (i8)(36)); CHECK(rowp[vi][vj] == (i8)(36));
  for (i = 0; i < 16; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)187LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)352LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)154LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)-260LL);
    if (i == 4) CHECK(row_sum(rowp[i]) == (i32)-284LL);
    if (i == 5) CHECK(row_sum(rowp[i]) == (i32)293LL);
    if (i == 6) CHECK(row_sum(rowp[i]) == (i32)155LL);
    if (i == 7) CHECK(row_sum(rowp[i]) == (i32)-587LL);
    if (i == 8) CHECK(row_sum(rowp[i]) == (i32)-153LL);
    if (i == 9) CHECK(row_sum(rowp[i]) == (i32)-127LL);
    if (i == 10) CHECK(row_sum(rowp[i]) == (i32)-394LL);
    if (i == 11) CHECK(row_sum(rowp[i]) == (i32)243LL);
    if (i == 12) CHECK(row_sum(rowp[i]) == (i32)-89LL);
    if (i == 13) CHECK(row_sum(rowp[i]) == (i32)-257LL);
    if (i == 14) CHECK(row_sum(rowp[i]) == (i32)-92LL);
    if (i == 15) CHECK(row_sum(rowp[i]) == (i32)-383LL);
  }
  return 0;
}
