// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 16x12 table of u16 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const u16 lut[16][12] = {
  { 23988, 36975, 59125, 18754, 41275, 64845, 8904, 60840, 56179, 56554, 8339, 57089 },
  { 45504, 59602, 57222, 42217, 12492, 7377, 46306, 51838, 13416, 45300, 64859, 52149 },
  { 46672, 25550, 16320, 14294, 26048, 22443, 23871, 7120, 31467, 11103, 30888, 48621 },
  { 61803, 55054, 17724, 51635, 13608, 59614, 1327, 55870, 63833, 47813, 30134, 31434 },
  { 63900, 41847, 54341, 58796, 23453, 499, 21830, 4101, 63862, 13105, 43970, 628 },
  { 11673, 65523, 47922, 48597, 60421, 1107, 14081, 37457, 14846, 56898, 45241, 40625 },
  { 22643, 58873, 46460, 46701, 6417, 15542, 29973, 41401, 17661, 45845, 8832, 23020 },
  { 11007, 35884, 34765, 50970, 22442, 10853, 59881, 56036, 51107, 48169, 54732, 15160 },
  { 52653, 42378, 15148, 4903, 19050, 329, 2524, 60942, 14015, 33088, 36670, 37503 },
  { 45789, 45997, 64131, 49643, 55967, 57887, 37611, 26911, 52501, 35407, 61726, 55256 },
  { 24839, 48016, 57677, 56460, 7079, 26511, 43690, 25019, 45238, 36535, 17958, 12834 },
  { 6591, 51493, 13197, 63856, 48816, 51197, 38849, 52890, 54280, 8752, 52359, 15253 },
  { 40033, 31140, 28383, 29870, 44636, 56363, 38142, 51308, 28263, 62007, 47077, 16527 },
  { 40626, 12393, 22742, 19607, 28307, 43237, 33216, 21582, 14401, 520, 10404, 62862 },
  { 58329, 31367, 19214, 12366, 38709, 54030, 26469, 46222, 27532, 2705, 5909, 10807 },
  { 32331, 57090, 51983, 21014, 14172, 59473, 11258, 29749, 31367, 39851, 51500, 48129 }
};
static const u16 *const rowp[16] = { lut[0], lut[1], lut[2], lut[3], lut[4], lut[5], lut[6], lut[7], lut[8], lut[9], lut[10], lut[11], lut[12], lut[13], lut[14], lut[15] };
static volatile u8 vi, vj;
static i32 row_sum(const u16 *row) { u16 j; i32 s = 0; for (j = 0; j < 12; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 13; vj = 4; CHECK(lut[vi][vj] == (u16)(28307)); CHECK(rowp[vi][vj] == (u16)(28307));
  vi = 7; vj = 11; CHECK(lut[vi][vj] == (u16)(15160)); CHECK(rowp[vi][vj] == (u16)(15160));
  vi = 0; vj = 10; CHECK(lut[vi][vj] == (u16)(8339)); CHECK(rowp[vi][vj] == (u16)(8339));
  vi = 1; vj = 10; CHECK(lut[vi][vj] == (u16)(64859)); CHECK(rowp[vi][vj] == (u16)(64859));
  vi = 5; vj = 5; CHECK(lut[vi][vj] == (u16)(1107)); CHECK(rowp[vi][vj] == (u16)(1107));
  vi = 11; vj = 10; CHECK(lut[vi][vj] == (u16)(52359)); CHECK(rowp[vi][vj] == (u16)(52359));
  vi = 2; vj = 0; CHECK(lut[vi][vj] == (u16)(46672)); CHECK(rowp[vi][vj] == (u16)(46672));
  vi = 9; vj = 5; CHECK(lut[vi][vj] == (u16)(57887)); CHECK(rowp[vi][vj] == (u16)(57887));
  vi = 5; vj = 2; CHECK(lut[vi][vj] == (u16)(47922)); CHECK(rowp[vi][vj] == (u16)(47922));
  vi = 15; vj = 4; CHECK(lut[vi][vj] == (u16)(14172)); CHECK(rowp[vi][vj] == (u16)(14172));
  vi = 2; vj = 0; CHECK(lut[vi][vj] == (u16)(46672)); CHECK(rowp[vi][vj] == (u16)(46672));
  vi = 14; vj = 2; CHECK(lut[vi][vj] == (u16)(19214)); CHECK(rowp[vi][vj] == (u16)(19214));
  vi = 12; vj = 4; CHECK(lut[vi][vj] == (u16)(44636)); CHECK(rowp[vi][vj] == (u16)(44636));
  vi = 12; vj = 1; CHECK(lut[vi][vj] == (u16)(31140)); CHECK(rowp[vi][vj] == (u16)(31140));
  vi = 2; vj = 10; CHECK(lut[vi][vj] == (u16)(30888)); CHECK(rowp[vi][vj] == (u16)(30888));
  vi = 6; vj = 4; CHECK(lut[vi][vj] == (u16)(6417)); CHECK(rowp[vi][vj] == (u16)(6417));
  vi = 10; vj = 3; CHECK(lut[vi][vj] == (u16)(56460)); CHECK(rowp[vi][vj] == (u16)(56460));
  vi = 0; vj = 11; CHECK(lut[vi][vj] == (u16)(57089)); CHECK(rowp[vi][vj] == (u16)(57089));
  vi = 3; vj = 9; CHECK(lut[vi][vj] == (u16)(47813)); CHECK(rowp[vi][vj] == (u16)(47813));
  vi = 6; vj = 7; CHECK(lut[vi][vj] == (u16)(41401)); CHECK(rowp[vi][vj] == (u16)(41401));
  vi = 9; vj = 7; CHECK(lut[vi][vj] == (u16)(26911)); CHECK(rowp[vi][vj] == (u16)(26911));
  vi = 4; vj = 8; CHECK(lut[vi][vj] == (u16)(63862)); CHECK(rowp[vi][vj] == (u16)(63862));
  vi = 11; vj = 3; CHECK(lut[vi][vj] == (u16)(63856)); CHECK(rowp[vi][vj] == (u16)(63856));
  vi = 3; vj = 8; CHECK(lut[vi][vj] == (u16)(63833)); CHECK(rowp[vi][vj] == (u16)(63833));
  for (i = 0; i < 16; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)492867LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)498282LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)304397LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)489849LL);
    if (i == 4) CHECK(row_sum(rowp[i]) == (i32)390332LL);
    if (i == 5) CHECK(row_sum(rowp[i]) == (i32)444391LL);
    if (i == 6) CHECK(row_sum(rowp[i]) == (i32)363368LL);
    if (i == 7) CHECK(row_sum(rowp[i]) == (i32)451006LL);
    if (i == 8) CHECK(row_sum(rowp[i]) == (i32)319203LL);
    if (i == 9) CHECK(row_sum(rowp[i]) == (i32)588826LL);
    if (i == 10) CHECK(row_sum(rowp[i]) == (i32)401856LL);
    if (i == 11) CHECK(row_sum(rowp[i]) == (i32)457533LL);
    if (i == 12) CHECK(row_sum(rowp[i]) == (i32)473749LL);
    if (i == 13) CHECK(row_sum(rowp[i]) == (i32)309897LL);
    if (i == 14) CHECK(row_sum(rowp[i]) == (i32)333659LL);
    if (i == 15) CHECK(row_sum(rowp[i]) == (i32)447917LL);
  }
  return 0;
}
