// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 4x16 table of u16 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const u16 lut[4][16] = {
  { 1062, 53691, 14792, 42388, 41393, 63265, 50963, 14715, 49858, 46645, 7568, 60441, 14189, 50007, 1865, 61330 },
  { 60584, 30865, 9869, 16656, 32299, 11999, 45215, 17451, 32498, 54145, 5984, 36153, 29123, 40707, 29178, 38795 },
  { 8569, 50136, 55215, 47740, 25251, 23683, 41766, 51041, 50670, 27221, 13653, 59733, 25040, 61118, 7349, 33053 },
  { 6397, 64327, 37069, 58414, 42507, 63074, 54343, 39815, 22233, 22087, 56588, 56315, 27922, 47731, 18492, 40853 }
};
static const u16 *const rowp[4] = { lut[0], lut[1], lut[2], lut[3] };
static volatile u8 vi, vj;
static i32 row_sum(const u16 *row) { u16 j; i32 s = 0; for (j = 0; j < 16; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 3; vj = 7; CHECK(lut[vi][vj] == (u16)(39815)); CHECK(rowp[vi][vj] == (u16)(39815));
  vi = 3; vj = 6; CHECK(lut[vi][vj] == (u16)(54343)); CHECK(rowp[vi][vj] == (u16)(54343));
  vi = 2; vj = 9; CHECK(lut[vi][vj] == (u16)(27221)); CHECK(rowp[vi][vj] == (u16)(27221));
  vi = 1; vj = 14; CHECK(lut[vi][vj] == (u16)(29178)); CHECK(rowp[vi][vj] == (u16)(29178));
  vi = 3; vj = 15; CHECK(lut[vi][vj] == (u16)(40853)); CHECK(rowp[vi][vj] == (u16)(40853));
  vi = 1; vj = 15; CHECK(lut[vi][vj] == (u16)(38795)); CHECK(rowp[vi][vj] == (u16)(38795));
  vi = 3; vj = 14; CHECK(lut[vi][vj] == (u16)(18492)); CHECK(rowp[vi][vj] == (u16)(18492));
  vi = 1; vj = 5; CHECK(lut[vi][vj] == (u16)(11999)); CHECK(rowp[vi][vj] == (u16)(11999));
  vi = 1; vj = 13; CHECK(lut[vi][vj] == (u16)(40707)); CHECK(rowp[vi][vj] == (u16)(40707));
  vi = 1; vj = 7; CHECK(lut[vi][vj] == (u16)(17451)); CHECK(rowp[vi][vj] == (u16)(17451));
  vi = 3; vj = 3; CHECK(lut[vi][vj] == (u16)(58414)); CHECK(rowp[vi][vj] == (u16)(58414));
  vi = 1; vj = 12; CHECK(lut[vi][vj] == (u16)(29123)); CHECK(rowp[vi][vj] == (u16)(29123));
  vi = 1; vj = 14; CHECK(lut[vi][vj] == (u16)(29178)); CHECK(rowp[vi][vj] == (u16)(29178));
  vi = 3; vj = 14; CHECK(lut[vi][vj] == (u16)(18492)); CHECK(rowp[vi][vj] == (u16)(18492));
  vi = 3; vj = 3; CHECK(lut[vi][vj] == (u16)(58414)); CHECK(rowp[vi][vj] == (u16)(58414));
  vi = 0; vj = 4; CHECK(lut[vi][vj] == (u16)(41393)); CHECK(rowp[vi][vj] == (u16)(41393));
  vi = 3; vj = 13; CHECK(lut[vi][vj] == (u16)(47731)); CHECK(rowp[vi][vj] == (u16)(47731));
  vi = 1; vj = 14; CHECK(lut[vi][vj] == (u16)(29178)); CHECK(rowp[vi][vj] == (u16)(29178));
  vi = 1; vj = 2; CHECK(lut[vi][vj] == (u16)(9869)); CHECK(rowp[vi][vj] == (u16)(9869));
  vi = 0; vj = 11; CHECK(lut[vi][vj] == (u16)(60441)); CHECK(rowp[vi][vj] == (u16)(60441));
  vi = 3; vj = 7; CHECK(lut[vi][vj] == (u16)(39815)); CHECK(rowp[vi][vj] == (u16)(39815));
  vi = 3; vj = 12; CHECK(lut[vi][vj] == (u16)(27922)); CHECK(rowp[vi][vj] == (u16)(27922));
  vi = 2; vj = 9; CHECK(lut[vi][vj] == (u16)(27221)); CHECK(rowp[vi][vj] == (u16)(27221));
  vi = 2; vj = 9; CHECK(lut[vi][vj] == (u16)(27221)); CHECK(rowp[vi][vj] == (u16)(27221));
  for (i = 0; i < 4; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)574172LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)491521LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)581238LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)658167LL);
  }
  return 0;
}
