#!/usr/bin/env python3
"""Differential testing with generated programs (T7).

    tests/t7-random/run.py --seeds 1-100 [--dir DIR] [--stmts N] [runner options...]

For each seed: gen.py writes a program; host16 (clang --target=msp430,
16-bit int, run by lli) computes its checksum; the program is written as a
runner test with `-DEXPECTED=<checksum>`; then the runner runs loomcc (`ir`,
`rom`) and 816-tcc's ROM (`--refs tcc-rom`) over the lot. A seed where
loomcc disagrees with host16 while 816-tcc agrees is reported as a likely
loomcc bug; the test file stays in DIR for reduction (see README).

Generated programs are written to DIR (default: a scratch directory; pass
--dir tests/t7-random/corpus to keep them as regression tests).
"""
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
LLVM = Path(os.environ.get("LLVM_BIN", "/opt/homebrew/opt/llvm/bin"))
HARNESS = ROOT / "harness/include"


def host16_checksum(src, work):
    ll = work / (src.stem + ".ll")
    r = subprocess.run(["nice", "-n", "19", str(LLVM / "clang"), "--target=msp430-none-elf", "-fsigned-char", "-std=c17", "-O0",
                        "-w", "-S", "-emit-llvm", "-DLOOMCC_T7_PRINT=1", f"-I{HARNESS}", str(src), "-o", str(ll)],
                       capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError("clang: " + r.stderr[-500:])
    ll.write_text(ll.read_text().replace("p:16:16", "p:64:64").replace(" optnone", ""))
    opt = work / (src.stem + ".opt.ll")
    r = subprocess.run(["nice", "-n", "19", str(LLVM / "opt"), "-S", "-passes=instcombine<no-verify-fixpoint>", str(ll), "-o", str(opt)],
                       capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError("opt: " + r.stderr[-500:])
    opt.write_text(re.sub(r"= freeze (\S+) (.+)$", r"= bitcast \1 \2 to \1", opt.read_text(), flags=re.M))
    r = subprocess.run(["nice", "-n", "19", str(LLVM / "lli"), "-force-interpreter", str(opt)], capture_output=True, text=True, timeout=120)
    if r.returncode:
        raise RuntimeError(f"lli exit {r.returncode}: " + r.stderr[-300:])
    return int(r.stdout.split()[-1])


def main(argv):
    args = argv[1:]
    def take(flag, default=None):
        if flag in args:
            i = args.index(flag)
            v = args[i + 1]
            del args[i:i + 2]
            return v
        return default
    seeds = take("--seeds", "1-20")
    lo, _, hi = seeds.partition("-")
    seeds = range(int(lo), int(hi or lo) + 1)
    stmts = take("--stmts", "12")
    narrow = "--narrow" in args
    if narrow:
        args.remove("--narrow")
    out = Path(take("--dir") or tempfile.mkdtemp(prefix="loomcc-t7-")).resolve()
    out.mkdir(parents=True, exist_ok=True)
    work = Path(tempfile.mkdtemp(prefix="loomcc-t7-work-"))
    made = []
    for s in seeds:
        prog = subprocess.run([sys.executable, str(HERE / "gen.py"), str(s), "--stmts", stmts] + (["--narrow"] if narrow else []),
                              capture_output=True, text=True, check=True).stdout
        tmp = work / f"seed-{s}.c"
        tmp.write_text(prog)
        try:
            ck = host16_checksum(tmp, work)
        except Exception as e:  # a generator bug: report, skip
            print(f"seed {s}: host16 failed ({e}); skipped")
            continue
        test = out / f"seed-{s}.c"
        test.write_text("// loomcc-do: run\n// loomcc-int: 16\n"
                        f"// loomcc-options: -DEXPECTED={ck}u\n"
                        f"// loomcc-note: generated by tests/t7-random/gen.py {s} --stmts {stmts}{' --narrow' if narrow else ''}; checksum from host16\n"
                        "// loomcc-ref: tcc-rom\n" + prog)
        made.append(test)
    print(f"{len(made)} programs in {out}")
    js = work / "results.json"
    subprocess.run([str(ROOT / "run-tests"), "--refs", "tcc-rom", "--json", str(js)] + args + [str(out)])
    res = {}
    for line in js.read_text().splitlines():
        r = json.loads(line)
        res.setdefault(r["test"], {})[r["mode"]] = r
    suspects = 0
    for t, m in sorted(res.items()):
        st = {k: m.get(k, {}).get("status", "-") for k in ("ir", "rom", "ref:tcc-rom")}
        real = [k for k in ("ir", "rom") if st[k] == "FAIL" and "not supported yet" not in m[k]["detail"]]
        if real:
            suspects += 1
            print(f"LIKELY LOOMCC BUG: {t} [{', '.join(real)}] (816-tcc ROM: {st['ref:tcc-rom']}): "
                  + "; ".join(m[k]["detail"].splitlines()[0] for k in real))
    print(f"{suspects} likely loomcc bugs")
    return 1 if suspects else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
