#!/usr/bin/env python3
"""Generates families of small tests whose expected values come from a model
of C at 16-bit int (C17 6.3.1 promotions and usual arithmetic conversions,
int 16 bits, long 32). Every generated test is also checked by the reference
tools (host16, the 816-tcc ROM, clang --target=msp430), so a mistake in the
model shows up as a reference failure, never as a silent wrong expectation.

    scripts/gen-families.py            # (re)writes every family

Families (weighted toward the patterns Loom's C uses):
  t4-exec/gen-arith/<op>-<ltype>.c   u8/i8/u16/i16 operands, every operator, run time
  t3-sema/gen-fold/<op>-<ltype>.c    the same expressions as constant expressions
  t4-exec/gen-soa/*.c                struct-of-arrays state indexed by u8
  t4-exec/gen-switch/*.c             switch on small enums, dense to sparse
  t4-exec/gen-romwalk/*.c            pointer walks over const ROM tables
  t2-parse/gen-declarator/*.c        random declarators, abstract and typedef twins
  t2-parse/gen-precedence/*.c        random expressions with minimal parentheses
  t3-sema/gen-conversions/*.c        the type of T1 op T2 for every integer pair
  t3-sema/gen-layout/*.c             random struct layouts per 816-tcc's rules (tcc reference)
  t2-parse/gen-designators/*.c       array lengths from designated initialisers
  t4-exec/gen-truncate/*.c           results stored into narrower/other types
  t4-exec/gen-flags, gen-lut, gen-subpixel, gen-dispatch   flag bytes, ROM lookup
                                     tables, fixed-point motion, handler tables
  t4-exec/gen-loops, gen-aabb, gen-sort, gen-ring, gen-tilemap, gen-minmax,
          gen-outparam               counted loops, box overlap, sprite ordering,
                                     queues, tile lookups, clamps, out-parameters
  t4-exec/gen-bitpack, gen-fsm, gen-divround, gen-strings, gen-callchain
  t4-exec/gen-pressure, gen-bigframe, gen-nested   many live values, large frames,
                                     a[i].b[j].c indexing

Do not edit generated files; change this script and rerun it.
"""
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "tests"
HEADER = "// Generated by scripts/gen-families.py; do not edit.\n"

T = {"u8": (8, False), "i8": (8, True), "u16": (16, False), "i16": (16, True), "u32": (32, False), "i32": (32, True)}
VALUES = {
    "u8": [0, 1, 2, 7, 100, 127, 128, 200, 255],
    "i8": [-128, -127, -3, -1, 0, 1, 2, 100, 127],
    "u16": [0, 1, 2, 255, 256, 1000, 32767, 32768, 40000, 65535],
    "i16": [-32768, -32767, -1000, -256, -1, 0, 1, 2, 255, 32767],
    "u32": [0, 1, 65535, 65536, 100000, 2147483647, 2147483648, 4294967295],
    "i32": [-2147483648, -100000, -65536, -1, 0, 1, 65535, 2147483647],
}
INT = ("i16",)          # int is 16 bits


def promote(t):
    bits, signed = T[t]
    if bits < 16:
        return "i16"
    return t


def usual(a, b):
    a, b = promote(a), promote(b)
    if a == b:
        return a
    (wa, sa), (wb, sb) = T[a], T[b]
    if sa == sb:
        return a if wa >= wb else b
    u, s = (a, b) if not sa else (b, a)
    if T[u][0] >= T[s][0]:
        return u
    return s  # the signed type is wider and holds every unsigned value


def wrap(v, t):
    bits, signed = T[t]
    v &= (1 << bits) - 1
    if signed and v >= 1 << (bits - 1):
        v -= 1 << bits
    return v


def fits(v, t):
    bits, signed = T[t]
    return (-(1 << (bits - 1)) <= v < (1 << (bits - 1))) if signed else (0 <= v < (1 << bits))


def lit(v, t):
    """A literal of exactly type t with value v (t is i16/u16/i32/u32)."""
    bits, signed = T[t]
    if t == "i16":
        return f"({v})" if v != -32768 else "(-32767 - 1)"
    if t == "u16":
        return f"{v}u"
    return f"(({t}){v}LL)"


def cdiv(a, b):
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b >= 0) else -q


def evaluate(op, a, ta, b, tb):
    """(result, result type) or None when the expression is undefined."""
    if op in ("<<", ">>"):
        rt = promote(ta)
        width = T[rt][0]
        if b < 0 or b >= width:
            return None
        av = wrap(a, rt)
        if op == "<<":
            if T[rt][1]:
                if av < 0 or not fits(av << b, rt):
                    return None
                return av << b, rt
            return wrap(av << b, rt), rt
        return av >> b, rt  # arithmetic for negative values (implementation-defined, same everywhere here)
    ct = usual(ta, tb)
    x, y = wrap(a, ct), wrap(b, ct)
    signed = T[ct][1]
    if op in ("<", "<=", ">", ">=", "==", "!="):
        r = {"<": x < y, "<=": x <= y, ">": x > y, ">=": x >= y, "==": x == y, "!=": x != y}[op]
        return int(r), "i16"
    if op in ("/", "%"):
        if y == 0:
            return None
        q = cdiv(x, y)
        if signed and not fits(q, ct):   # INT_MIN / -1: both / and % are undefined
            return None
        r = q if op == "/" else x - q * y
        return wrap(r, ct), ct
    r = {"+": x + y, "-": x - y, "*": x * y, "&": x & y, "|": x | y, "^": x ^ y}[op]
    if signed and not fits(r, ct):
        return None
    return wrap(r, ct), ct


OPS = {"add": "+", "sub": "-", "mul": "*", "div": "/", "mod": "%", "and": "&", "or": "|", "xor": "^",
       "shl": "<<", "shr": ">>", "lt": "<", "le": "<=", "gt": ">", "ge": ">=", "eq": "==", "ne": "!="}
SMALL = ["u8", "i8", "u16", "i16"]


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def arith_family(lefts=None, rights_all=None, suffix=""):
    lefts = lefts or SMALL
    rights_all = rights_all or SMALL
    n = 0
    for name, op in OPS.items():
        for ta in lefts:
            runtime, folded = [], []
            rights = rights_all if op not in ("<<", ">>") else ["u8"]
            for tb in rights:
                bvals = VALUES[tb] if op not in ("<<", ">>") else ([0, 1, 3, 7, 8, 15] if T[promote(ta)][0] == 16 else [0, 1, 8, 15, 16, 31])
                for a in VALUES[ta]:
                    for b in bvals:
                        r = evaluate(op, a, ta, b, tb)
                        if r is None:
                            continue
                        v, rt = r
                        runtime.append((ta, a, tb, b, v, rt))
            body = []
            decl = {}
            for i, (ta_, a, tb_, b, v, rt) in enumerate(runtime):
                la = lit(a, promote(ta_)) if T[ta_][0] >= 16 else a
                lb = lit(b, promote(tb_)) if T[tb_][0] >= 16 else b
                body.append(f"  x_{ta_} = {la}; y_{tb_} = {lb}; CHECK((x_{ta_} {op} y_{tb_}) == {lit(v, rt)});")
            used = sorted(set(lefts) | set(rights_all), key=list(T).index)
            declares = "\n".join(f"static volatile {t} x_{t};" for t in used) + "\n" + "\n".join(f"static volatile {t} y_{t};" for t in used)
            # Checks in chunks of 32 per function: 816-tcc gives every
            # comparison its own stack slot and cannot address past 255 bytes.
            chunks = [body[i:i + 32] for i in range(0, len(body), 32)]
            funcs = "".join(f"static void part{k}(void) {{\n" + "\n".join(c) + "\n}\n" for k, c in enumerate(chunks))
            calls = "".join(f"  part{k}();\n" for k in range(len(chunks)))
            write(ROOT / f"t4-exec/gen-arith{suffix}/{name}-{ta}.c", HEADER +
                  f"// loomcc-do: run\n// loomcc-int: 16\n"
                  + ("// loomcc-ref: host16\n// loomcc-note: no 816-tcc reference: its 32-bit type is long long, with its\n"
                     "// loomcc-note: own helpers and folding bugs (docs/TCC-BUGS.md).\n" if suffix else "") +
                  f"// {ta} {op} (u8, i8, u16, i16) at run time: the operands promote to int or\n"
                  f"// unsigned int (16 bits) and the usual arithmetic conversions apply.\n"
                  '#include "loomcc-test.h"\n' + declares + "\n" + funcs + "int main(void) {\n" + calls + "  return 0;\n}\n")
            # The constant-expression twin: every check as a STATIC_CHECK.
            checks = [f"STATIC_CHECK((({ta_})({lit(a, promote(ta_)) if T[ta_][0] >= 16 else a}) {op} (({tb_})({lit(b, promote(tb_)) if T[tb_][0] >= 16 else b}))) == {lit(v, rt)});"
                      for (ta_, a, tb_, b, v, rt) in runtime]
            write(ROOT / f"t3-sema/gen-fold{suffix}/{name}-{ta}.c", HEADER +
                  f"// loomcc-do: syntax\n// {ta} {op} (u8, i8, u16, i16) as integer constant expressions at 16-bit int.\n"
                  "// loomcc-ref: clang16\n"
                  "// loomcc-note: no 816-tcc reference: its constant folder does unsigned int\n"
                  "// loomcc-note: arithmetic in 32 bits (docs/TCC-BUGS.md, bug 3).\n"
                  '#include "loomcc-test.h"\n' + "\n".join(checks) + "\n")
            n += 2
    return n


def soa_family():
    r = random.Random(7)
    n = 0
    shapes = [(4, "u8"), (8, "i16"), (16, "u16"), (24, "u8"), (32, "i16"), (12, "i8"), (6, "u16"), (20, "i16")]
    for cap, t in shapes:
        vals = [wrap(r.randrange(-40000, 70000), t) for _ in range(cap)]
        vels = [wrap(r.randrange(-5, 6), "i8") for _ in range(cap)]
        # Model: pos[i] += vel[i] for active[i] (i odd) three times, then sums.
        pos = list(vals)
        active = [i % 2 for i in range(cap)]
        for _ in range(3):
            for i in range(cap):
                if active[i]:
                    pos[i] = wrap(pos[i] + vels[i], t)
        total = wrap(sum(pos), "u16")
        maxi = max(range(cap), key=lambda i: (pos[i], -i))
        src = HEADER + f"""// loomcc-do: run
// loomcc-int: agnostic
// Struct-of-arrays state indexed by a u8 slot (the shape of Loom's animation,
// actor and body tables): capacity {cap}, positions of type {t}.
#include "loomcc-test.h"
#define CAP {cap}
typedef struct {{
  {t} pos[CAP];
  i8 vel[CAP];
  u8 active[CAP];
  u8 count;
  const u8 *names[CAP];
}} State;
static State st;
static const u8 name_rom[CAP] = {{ {", ".join(str(i * 3 % 251) for i in range(cap))} }};
static const {t} init_pos[CAP] = {{ {", ".join(str(v) for v in vals)} }};
static const i8 init_vel[CAP] = {{ {", ".join(str(v) for v in vels)} }};
static void setup(void) {{
  u8 i;
  for (i = 0; i < CAP; i++) {{
    st.pos[i] = init_pos[i];
    st.vel[i] = init_vel[i];
    st.active[i] = (u8)(i & 1);
    st.names[i] = &name_rom[i];
  }}
  st.count = CAP;
}}
static void step(void) {{
  u8 i;
  for (i = 0; i < st.count; i++) {{
    if (!st.active[i]) continue;
    st.pos[i] = ({t})(st.pos[i] + st.vel[i]);
  }}
}}
static u8 argmax(void) {{
  u8 i, best = 0;
  for (i = 1; i < st.count; i++)
    if (st.pos[i] > st.pos[best]) best = i;
  return best;
}}
int main(void) {{
  u16 total = 0;
  u8 i;
  setup();
  step(); step(); step();
  for (i = 0; i < CAP; i++) total = (u16)(total + (u16)st.pos[i]);
  CHECK(total == {total}u);
  CHECK(argmax() == {maxi});
  CHECK(*st.names[CAP - 1] == {(cap - 1) * 3 % 251});
  CHECK(st.pos[{cap - 1}] == ({t})({pos[cap - 1]}));
  return 0;
}}
"""
        write(ROOT / f"t4-exec/gen-soa/soa-{cap}-{t}.c", src)
        n += 1
    return n


def switch_family():
    r = random.Random(11)
    n = 0
    specs = [("dense4", list(range(4))), ("dense8", list(range(8))), ("dense16", list(range(16))),
             ("offset8", list(range(10, 18))), ("gap", [0, 1, 2, 5, 6, 9]), ("sparse", [0, 7, 30, 31, 100, 200]),
             ("single", [3]), ("two", [0, 255]), ("dense32", list(range(32))), ("negative", [-4, -3, -2, -1, 0, 1])]
    for name, cases in specs:
        t = "i8" if min(cases) < 0 else "u8"
        rets = {c: r.randrange(1, 1000) for c in cases}
        fall = set(r.sample(cases, len(cases) // 3)) if len(cases) > 2 else set()
        # Model the fall-through: a case in `fall` adds its value and falls to the next.
        order = cases
        def result(v):
            if v not in rets:
                return 7
            i = order.index(v)
            acc = 0
            while True:
                c = order[i]
                acc += rets[c]
                if c not in fall or i + 1 >= len(order):
                    return acc if c not in fall else acc + 7   # falls into default at the end
                i += 1
        enum_members = ", ".join(f"K_{name}_{('m' + str(-c)) if c < 0 else c} = {c}" for c in cases)
        lines = []
        for c in order:
            lines.append(f"  case K_{name}_{('m' + str(-c)) if c < 0 else c}: acc += {rets[c]};" + ("" if c in fall else " return acc;"))
        lines.append("  default: acc += 7; return acc;")
        probes = sorted(set(cases + [min(cases) - 1 if min(cases) > -128 else 127, max(cases) + 1 if max(cases) < 127 else -128, 50, 127]))
        if t == "u8":
            probes = [p for p in probes if 0 <= p <= 255]
        else:
            probes = [p for p in probes if -128 <= p <= 127]
        checks = "\n".join(f"  CHECK(classify(({t}){p}) == {result(p)});" for p in probes)
        src = HEADER + f"""// loomcc-do: run
// loomcc-int: agnostic
// switch on a small enum stored in a {t}: cases {cases}
// (some fall through), as Loom's state machines do.
#include "loomcc-test.h"
enum K_{name} {{ {enum_members} }};
static u16 classify({t} k) {{
  u16 acc = 0;
  switch (k) {{
{chr(10).join(lines)}
  }}
}}
int main(void) {{
{checks}
  return 0;
}}
"""
        write(ROOT / f"t4-exec/gen-switch/switch-{name}.c", src)
        n += 1
    return n


def backward_max(rows):
    """What last_max() returns: walk from the end, keep a strictly greater one."""
    best = 0
    for i in range(len(rows) - 1, -1, -1):
        if rows[i][-1] > rows[best][-1]:
            best = i
    return best


def romwalk_family():
    r = random.Random(5)
    n = 0
    for k, (count, fields) in enumerate([(5, ["u8", "i8"]), (9, ["u8", "i16", "u8"]), (16, ["i16", "i16"]),
                                         (3, ["u8", "u16", "i8", "u8"]), (30, ["u8"]), (12, ["i8", "i8", "u8", "u8"])]):
        rows = [[wrap(r.randrange(-300, 70000), f) for f in fields] for _ in range(count)]
        # sentinel: first field == 0xff (u8) or -128 (i8) or 0x7fff... use a separate end pointer walk instead
        fdecl = "\n".join(f"  {f} f{j};" for j, f in enumerate(fields))
        init = ",\n".join("  { " + ", ".join(str(v) for v in row) + " }" for row in rows)
        sums = [wrap(sum(row[j] for row in rows), "i32") for j in range(len(fields))]
        last_pos = max(range(count), key=lambda i: (rows[i][-1], i))
        src = HEADER + f"""// loomcc-do: run
// loomcc-int: agnostic
// Pointer walks over a const ROM table of {count} records ({", ".join(fields)}):
// by pointer increment to an end pointer, by index, and backwards.
#include "loomcc-test.h"
typedef struct {{
{fdecl}
}} Rec;
static const Rec table[{count}] = {{
{init}
}};
static const Rec *const table_end = table + {count};
static i32 sum_forward(u8 field) {{
  const Rec *p;
  i32 s = 0;
  for (p = table; p != table_end; p++) {{
    switch (field) {{
{chr(10).join(f"    case {j}: s += p->f{j}; break;" for j in range(len(fields)))}
    }}
  }}
  return s;
}}
static const Rec *last_max(void) {{
  const Rec *p = table_end, *best = table;
  while (p != table) {{
    p--;
    if (p->f{len(fields) - 1} > best->f{len(fields) - 1}) best = p;
  }}
  return best;
}}
int main(void) {{
  u8 i;
{chr(10).join(f"  CHECK(sum_forward({j}) == (i32){sums[j]}LL);" for j in range(len(fields)))}
  for (i = 0; i < {count}; i++) CHECK(&table[i] - table == i);
  CHECK(table_end - table == {count});
  CHECK(last_max() - table == {backward_max(rows)});
  return 0;
}}
"""
        write(ROOT / f"t4-exec/gen-romwalk/romwalk-{k}.c", src)
        n += 1
    return n




# ---------------------------------------------------------------- T2 families

BASES = [("char", "1"), ("short", "sizeof(short)"), ("int", "sizeof(int)"), ("long", "sizeof(long)"),
         ("unsigned char", "1"), ("unsigned", "sizeof(unsigned)"), ("signed char", "1"), ("unsigned short", "sizeof(short)")]
DIMS = [2, 3, 5, 7, 11]


def gen_type(r, depth):
    """A random derived type: ('base', name, size) | ('ptr', t) | ('arr', n, t) | ('fn', t)."""
    if depth == 0 or r.random() < 0.2:
        b = r.choice(BASES)
        return ("base", b[0], b[1])
    k = r.random()
    inner = gen_type(r, depth - 1)
    if k < 0.45:
        return ("ptr", inner)
    if k < 0.75:
        if inner[0] == "fn":
            return ("ptr", inner)
        return ("arr", r.choice(DIMS), inner)
    if inner[0] in ("fn", "arr"):
        return ("ptr", inner)
    return ("fn", inner)


def declarator(t, inner):
    """C declarator text for type t around `inner` (a name or empty)."""
    kind = t[0]
    if kind == "base":
        return t[1], inner
    if kind == "ptr":
        sub = t[1]
        s = "*" + inner
        if sub[0] in ("arr", "fn"):
            s = "(" + s + ")"
        return declarator(sub, s)
    if kind == "arr":
        return declarator(t[2], f"{inner}[{t[1]}]")
    return declarator(t[1], f"{inner}(void)")


def decl(t, name):
    base, d = declarator(t, name)
    return f"{base} {d}".rstrip()


def size_of(t):
    """A C expression for sizeof(t) built from basic sizes (layout-independent)."""
    kind = t[0]
    if kind == "base":
        return t[2]
    if kind == "ptr":
        return "sizeof(void (*)(void))" if t[1][0] == "fn" else "sizeof(void *)"
    if kind == "arr":
        return f"{t[1]} * ({size_of(t[2])})"
    raise ValueError("function")


def walk(t, expr):
    """(expression, type) pairs reached by *, [1] and calls from expr."""
    out = []
    while True:
        if t[0] != "fn":
            out.append((expr, t))
        if t[0] == "ptr":
            expr, t = f"(*{expr})", t[1]
        elif t[0] == "arr":
            expr, t = f"{expr}[1]", t[2]
        elif t[0] == "fn":
            expr, t = f"{expr}()", t[1]
        else:
            return out


def declarator_family(seed=23, count=60, qualified=False, subdir="gen-declarator"):
    r = random.Random(seed)
    n = 0
    for k in range(count):
        lines, checks = [], []
        for j in range(8):
            t = gen_type(r, r.randint(2, 5))
            if t[0] == "fn":
                t = ("ptr", t)
            name = f"v{j}"
            d = decl(t, name)
            if qualified:
                # Qualifiers do not change sizes: sprinkle const/volatile on
                # the declarator's pointers and the base type.
                d = d.replace("*", r.choice(["*", "* const ", "* volatile ", "*"]))
                d = r.choice(["const ", "volatile ", ""]) + d
            lines.append(f"extern {d};")
            lines.append(f"typedef {decl(t, f'T{j}')};")
            for expr, st in walk(t, name):
                if st[0] == "ptr" and st[1][0] == "base" and False:
                    pass
                if st[0] == "fn":
                    continue
                checks.append(f"STATIC_CHECK(sizeof({expr}) == {size_of(st)});")
            abstract = decl(t, "").strip()
            checks.append(f"STATIC_CHECK(sizeof({abstract}) == sizeof({name}));")
            checks.append(f"STATIC_CHECK(sizeof(T{j}) == sizeof({name}));")
        src = HEADER + ("// loomcc-do: syntax\n"
                        "// Random declarators, their abstract-declarator and typedef twins, and the\n"
                        "// types reached through *, [] and () (sizes relative to the basic types).\n"
                        '#include "loomcc-test.h"\n' + "\n".join(lines) + "\n" + "\n".join(checks) + "\n")
        write(ROOT / f"t2-parse/{subdir}/decl-{k:02d}.c", src)
        n += 1
    return n


PREC = [("*", 13), ("/", 13), ("%", 13), ("+", 12), ("-", 12), ("<<", 11), (">>", 11), ("<", 10), (">", 10),
        ("<=", 10), (">=", 10), ("==", 9), ("!=", 9), ("&", 8), ("^", 7), ("|", 6), ("&&", 5), ("||", 4)]


def gen_expr(r, depth):
    """(text, value, precedence) of a random int expression with no overflow at 16 bits."""
    if depth == 0 or r.random() < 0.25:
        v = r.randrange(0, 40)
        return str(v), v, 100
    k = r.random()
    if k < 0.12:
        t, v, p = gen_expr(r, depth - 1)
        op = r.choice(["-", "~", "!"])
        t = f"{op} {t}" if p >= 14 else f"{op}({t})"   # the space keeps `- -5` from becoming `--5`
        v = {"-": -v, "~": ~v, "!": int(not v)}[op]
        if not fits(v, "i16"):
            return gen_expr(r, depth)
        return t, v, 14
    if k < 0.2:
        c, cv, cp = gen_expr(r, depth - 1)
        a, av, ap = gen_expr(r, depth - 1)
        b, bv, bp = gen_expr(r, depth - 1)
        c = c if cp > 3 else f"({c})"
        a = a if ap > 3 else f"({a})"
        b = b if bp >= 3 else f"({b})"
        return f"{c} ? {a} : {b}", (av if cv else bv), 3
    op, prec = r.choice(PREC)
    a, av, ap = gen_expr(r, depth - 1)
    b, bv, bp = gen_expr(r, depth - 1)
    if op in ("/", "%") and bv == 0:
        return gen_expr(r, depth)
    if op in ("<<", ">>") and not (0 <= bv < 15):
        return gen_expr(r, depth)
    if op == "<<" and (av < 0 or not fits(av << bv, "i16")):
        return gen_expr(r, depth)
    # Parenthesise only where precedence (left associativity) needs it; add
    # an occasional redundant pair.
    a = a if ap >= prec else f"({a})"
    b = b if bp > prec else f"({b})"
    if r.random() < 0.1:
        a = f"({a})"
    if op == "/" or op == "%":
        q = cdiv(av, bv)
        v = q if op == "/" else av - q * bv
    elif op == ">>":
        v = av >> bv
    elif op == "<<":
        v = av << bv
    else:
        v = {"*": av * bv, "+": av + bv, "-": av - bv, "<": int(av < bv), ">": int(av > bv), "<=": int(av <= bv),
             ">=": int(av >= bv), "==": int(av == bv), "!=": int(av != bv), "&": av & bv, "^": av ^ bv, "|": av | bv,
             "&&": int(bool(av) and bool(bv)), "||": int(bool(av) or bool(bv))}[op]
    if not fits(v, "i16"):
        return gen_expr(r, depth)
    return f"{a} {op} {b}", v, prec


def precedence_family():
    r = random.Random(31)
    n = 0
    for k in range(40):
        checks = []
        for _ in range(25):
            t, v, _p = gen_expr(r, r.randint(2, 5))
            checks.append(f"STATIC_CHECK(({t}) == {lit(v, 'i16')});")
        src = HEADER + ("// loomcc-do: syntax\n"
                        "// Random int expressions with the minimum of parentheses: C's precedence and\n"
                        "// associativity decide the value (no expression overflows 16 bits).\n"
                        '#include "loomcc-test.h"\n' + "\n".join(checks) + "\n")
        write(ROOT / f"t2-parse/gen-precedence/prec-{k:02d}.c", src)
        n += 1
    return n


def conversion_family():
    n = 0
    TYPES6 = ["u8", "i8", "u16", "i16", "u32", "i32"]
    for ta in TYPES6:
        checks = []
        for tb in TYPES6:
            rt = usual(ta, tb)
            bits, signed = T[rt]
            checks.append(f"STATIC_CHECK(sizeof(({ta})0 + ({tb})0) == {bits // 8});")
            checks.append(f"STATIC_CHECK(((({ta})0 + ({tb})0) - 1 < 0) == {int(signed)});")
        pa = promote(ta)
        checks.append(f"STATIC_CHECK(sizeof(+({ta})0) == {T[pa][0] // 8});")
        checks.append(f"STATIC_CHECK((-({ta})1 < 0) == {int(T[pa][1])});")
        checks.append(f"STATIC_CHECK(sizeof(({ta})0 << 1) == {T[pa][0] // 8});")
        src = HEADER + (f"// loomcc-do: syntax\n// The type of {ta} op T for every integer type T, at 16-bit int and 32-bit\n"
                        "// long: integer promotions and the usual arithmetic conversions (6.3.1).\n"
                        '#include "loomcc-test.h"\n' + "\n".join(checks) + "\n")
        write(ROOT / f"t3-sema/gen-conversions/usual-{ta}.c", src)
        n += 1
    return n




# ----------------------------------------------------- layout, per 816-tcc

# (C type, size, align) inside structs, per 816-tcc (loomcc PLAN section 1):
# pointers are 4 bytes and 4-aligned; the 32-bit integer (i32: long for
# loomcc, long long for 816-tcc) is 4-aligned too.
LAYOUT_SCALARS = [("u8", 1, 1), ("i8", 1, 1), ("i16", 2, 2), ("u16", 2, 2), ("int", 2, 2), ("i32", 4, 4),
                  ("u8 *", 4, 4), ("const i16 *", 4, 4), ("void (*)(void)", 4, 4)]


def member_decl(ctype, name, dims):
    suffix = "".join(f"[{d}]" for d in dims)
    if ctype == "void (*)(void)":
        return f"void (*{name}{suffix})(void);"
    return f"{ctype} {name}{suffix};"


def gen_struct(r, tag, depth, structs):
    members = []
    for i in range(r.randint(1, 6)):
        if depth > 0 and structs and r.random() < 0.2:
            sname, ssize, salign, _ = r.choice(structs)
            dims = [r.choice([2, 3])] if r.random() < 0.3 else []
            members.append((f"struct {sname}", ssize, salign, f"m{i}", dims))
            continue
        c, sz, al = r.choice(LAYOUT_SCALARS)
        dims = [r.choice([1, 2, 3, 5])] if r.random() < 0.3 else []
        members.append((c, sz, al, f"m{i}", dims))
    off, align, offsets = 0, 1, []
    for c, sz, al, name, dims in members:
        total = sz
        for d in dims:
            total *= d
        off = (off + al - 1) // al * al
        offsets.append((name, off))
        off += total
        align = max(align, al)
    size = (off + align - 1) // align * align
    body = "\n".join("  " + (member_decl(c, name, dims) if not c.startswith("struct") else f"{c} {name}{''.join(f'[{d}]' for d in dims)};")
                     for c, sz, al, name, dims in members)
    return tag, size, align, offsets, f"struct {tag} {{\n{body}\n}};"


def layout_family():
    r = random.Random(41)
    n = 0
    for k in range(66):
        structs, text, checks = [], [], []
        for j in range(6):
            tag, size, align, offsets, src = gen_struct(r, f"S{k}_{j}", 1, structs)
            structs.append((tag, size, align, offsets))
            text.append(src)
            checks.append(f"STATIC_CHECK(sizeof(struct {tag}) == {size});")
            checks.append(f"STATIC_CHECK(sizeof(struct {tag}[3]) == {3 * size});")
            for name, off in offsets:
                checks.append(f"STATIC_CHECK(offsetof(struct {tag}, {name}) == {off});")
        src = HEADER + ("// loomcc-do: syntax\n"
                        "// Random struct shapes laid out by 816-tcc's rules (pointers and 32-bit\n"
                        "// integers 4-aligned inside structs, size rounded to the largest alignment):\n"
                        "// the layout Loom's hand-written assembly reads by offset.\n"
                        "// loomcc-ref: tcc\n"
                        '#include <stddef.h>\n#include "loomcc-test.h"\n' + "\n".join(text) + "\n" + "\n".join(checks) + "\n")
        write(ROOT / f"t3-sema/gen-layout/layout-{k:02d}.c", src)
        n += 1
    return n


def designator_family():
    r = random.Random(43)
    n = 0
    for k in range(40):
        checks, decls = [], []
        for j in range(6):
            items, pos, top = [], 0, 0
            vals = {}
            for _ in range(r.randint(1, 7)):
                if r.random() < 0.5:
                    pos = r.randrange(0, 20)
                    items.append(f"[{pos}] = {pos + 100}")
                else:
                    items.append(f"{pos + 100}")
                vals[pos] = pos + 100
                pos += 1
                top = max(top, pos)
            decls.append(f"static const i16 a{j}[] = {{ {', '.join(items)} }};")
            checks.append(f"STATIC_CHECK(sizeof(a{j}) / sizeof(a{j}[0]) == {top});")
        src = HEADER + ("// loomcc-do: syntax\n"
                        "// Array length from designated and positional initialisers: the largest\n"
                        "// index initialised, plus one (6.7.9p22); a later designator may go back.\n"
                        '#include "loomcc-test.h"\n' + "\n".join(decls) + "\n" + "\n".join(checks) + "\n")
        write(ROOT / f"t2-parse/gen-designators/desig-{k:02d}.c", src)
        n += 1
    return n


def truncation_family():
    r = random.Random(47)
    n = 0
    small = ["u8", "i8", "u16", "i16"]
    for src_t in small:
        for dst_t in small:
            lines = []
            for _ in range(24):
                a, b = r.choice(VALUES[src_t]), r.choice(VALUES[src_t])
                op = r.choice(["+", "-", "^", "|", "&"])
                res = evaluate(op, a, src_t, b, src_t)
                if res is None:
                    continue
                v, rt = res
                lines.append(f"  a = {a}; b = {b}; d = a {op} b; CHECK(d == ({dst_t})({lit(v, rt) if rt in ('u16', 'i16') else v}));")
            src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n"
                            f"// {src_t} op {src_t} stored into a {dst_t}: the value converts (wraps) on assignment.\n"
                            '#include "loomcc-test.h"\n'
                            f"static volatile {src_t} a, b;\nstatic volatile {dst_t} d;\n"
                            "int main(void) {\n" + "\n".join(lines) + "\n  return 0;\n}\n")
            write(ROOT / f"t4-exec/gen-truncate/{src_t}-to-{dst_t}.c", src)
            n += 1
    return n


# --------------------------------------------- more Loom-shaped run families

def flags_family():
    """u8/u16 flag words: set, clear, toggle and test with constant and
    variable masks, as Loom's per-slot state bytes are used."""
    r = random.Random(53)
    n = 0
    for k in range(16):
        t = "u8" if k % 2 == 0 else "u16"
        bits = T[t][0]
        init = r.getrandbits(bits)
        v = init
        ops, lines = [], []
        for _ in range(20):
            bit = r.randrange(bits)
            kind = r.choice(["set", "clear", "toggle", "test", "mask"])
            m = 1 << bit
            idx = len(ops)
            if kind == "set":
                v |= m
                lines.append(f"  f = ({t})(f | ({t})(1u << bit[{idx}]));")
            elif kind == "clear":
                v &= ~m & ((1 << bits) - 1)
                lines.append(f"  f = ({t})(f & ({t})~({t})(1u << bit[{idx}]));")
            elif kind == "toggle":
                v ^= m
                lines.append(f"  f ^= ({t})(1u << bit[{idx}]);")
            elif kind == "test":
                lines.append(f"  CHECK(((f >> bit[{idx}]) & 1u) == {(v >> bit) & 1});")
            else:
                mask = r.getrandbits(bits)
                lines.append(f"  CHECK((f & {mask}u) == {v & mask}u);")
            ops.append(bit)
            lines.append(f"  CHECK(f == {v}u);")
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// Flag words ({t}): set, clear, toggle and test bits chosen at run time.\n"
                        '#include "loomcc-test.h"\n'
                        f"static const u8 bit_rom[{len(ops)}] = {{ {', '.join(map(str, ops))} }};\n"
                        f"static volatile {t} f;\nstatic u8 bit[{len(ops)}];\n"
                        "int main(void) {\n  u8 i;\n"
                        f"  for (i = 0; i < {len(ops)}; i++) bit[i] = bit_rom[i];\n"
                        f"  f = {init}u;\n" + "\n".join(lines) + "\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-flags/flags-{k:02d}.c", src)
        n += 1
    return n


def lut_family():
    """Const lookup tables indexed by u8 expressions, 1-D and 2-D, and tables
    of pointers to tables (level and animation data)."""
    r = random.Random(59)
    n = 0
    for k in range(14):
        t = r.choice(["u8", "i8", "u16", "i16"])
        rows, cols = r.choice([(1, 256), (4, 16), (8, 8), (3, 40), (16, 12)])
        data = [[wrap(r.getrandbits(16), t) for _ in range(cols)] for _ in range(rows)]
        probes = []
        for _ in range(24):
            i, j = r.randrange(rows), r.randrange(cols)
            probes.append((i, j, data[i][j]))
        row_sums = [wrap(sum(row), "i32") for row in data]
        table = ",\n".join("  { " + ", ".join(str(x) for x in row) + " }" for row in data)
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A const {rows}x{cols} table of {t} in ROM, read through u8 indices, a row\n"
                        "// pointer, and a table of row pointers.\n"
                        '#include "loomcc-test.h"\n'
                        f"static const {t} lut[{rows}][{cols}] = {{\n{table}\n}};\n"
                        f"static const {t} *const rowp[{rows}] = {{ {', '.join(f'lut[{i}]' for i in range(rows))} }};\n"
                        f"static volatile u8 vi, vj;\n"
                        f"static i32 row_sum(const {t} *row) {{ u16 j; i32 s = 0; for (j = 0; j < {cols}; j++) s += row[j]; return s; }}\n"
                        "int main(void) {\n  u8 i;\n"
                        + "\n".join(f"  vi = {i}; vj = {j}; CHECK(lut[vi][vj] == ({t})({v})); CHECK(rowp[vi][vj] == ({t})({v}));" for i, j, v in probes)
                        + "\n" + f"  for (i = 0; i < {rows}; i++) {{\n"
                        + "".join(f"    if (i == {i}) CHECK(row_sum(rowp[i]) == (i32){s}LL);\n" for i, s in enumerate(row_sums))
                        + "  }\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-lut/lut-{k:02d}.c", src)
        n += 1
    return n


def subpixel_family():
    """8.8 and 12.4 subpixel movement with s16 velocities, gravity, clamps and
    the integer part taken by an arithmetic shift, as Loom's movement does."""
    r = random.Random(61)
    n = 0
    for k in range(12):
        frac = r.choice([4, 8])
        pos = r.randrange(-2000, 2000) << frac
        vel = r.randrange(-300, 300)
        grav = r.randrange(1, 40)
        vmax = r.randrange(200, 1200)
        steps = r.randrange(10, 60)
        trace = []
        p, v = pos, vel
        for s in range(steps):
            v = v + grav
            if v > vmax:
                v = vmax
            p = wrap(p + v, "i16")
            if s % 7 == 6:
                trace.append((s, p, v, p >> frac))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// Subpixel motion: position in {16 - frac}.{frac} fixed point (s16), velocity\n"
                        "// clamped to a maximum, integer part by an arithmetic shift.\n"
                        '#include "loomcc-test.h"\n'
                        "typedef struct { i16 pos; i16 vel; } Body;\n"
                        f"static Body b;\nstatic volatile i16 grav = {grav}, vmax = {vmax};\n"
                        "static void tick(Body *p) {\n  p->vel = (i16)(p->vel + grav);\n  if (p->vel > vmax) p->vel = vmax;\n  p->pos = (i16)(p->pos + p->vel);\n}\n"
                        f"int main(void) {{\n  u8 s;\n  b.pos = (i16)({wrap(pos, 'i16')}); b.vel = {vel};\n"
                        f"  for (s = 0; s < {steps}; s++) {{\n    tick(&b);\n"
                        + "".join(f"    if (s == {s}) {{ CHECK(b.pos == ({lit(pp, 'i16')})); CHECK(b.vel == {vv}); CHECK((b.pos >> {frac}) == ({lit(ip, 'i16')})); }}\n" for s, pp, vv, ip in trace)
                        + "  }\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-subpixel/subpixel-{k:02d}.c", src)
        n += 1
    return n


def dispatch_family():
    """Tables of function pointers indexed by a small enum (Loom's hook and
    handler tables), with u8 and s16 arguments and results."""
    r = random.Random(67)
    n = 0
    for k in range(10):
        count = r.randint(2, 9)
        consts = [r.randrange(-100, 100) for _ in range(count)]
        ops = [r.choice(["+", "-", "^"]) for _ in range(count)]
        funcs = "".join(f"static i16 h{i}(u8 a, i16 b) {{ return (i16)(((i16)a {ops[i]} b) + ({consts[i]})); }}\n" for i in range(count))
        enum = ", ".join(f"EV_{i}" for i in range(count))
        checks = []
        for _ in range(16):
            e, a, b = r.randrange(count), r.randrange(256), r.randrange(-1000, 1000)
            x = {"+": a + b, "-": a - b, "^": a ^ b}[ops[e]] + consts[e]
            checks.append(f"  CHECK(dispatch(EV_{e}, {a}, {b}) == ({lit(wrap(x, 'i16'), 'i16')}));")
        src = HEADER + ("// loomcc-do: run\n// loomcc-int: agnostic\n// A const table of handlers indexed by an enum, called through a pointer.\n"
                        '#include "loomcc-test.h"\n' + funcs
                        + f"enum Ev {{ {enum}, EV_COUNT }};\n"
                        + f"typedef i16 (*Handler)(u8, i16);\nstatic const Handler handlers[EV_COUNT] = {{ {', '.join(f'h{i}' for i in range(count))} }};\n"
                        + "static i16 dispatch(enum Ev e, u8 a, i16 b) { return (u8)e < EV_COUNT ? handlers[e](a, b) : 0; }\n"
                        + "int main(void) {\n" + "\n".join(checks) + "\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-dispatch/dispatch-{k:02d}.c", src)
        n += 1
    return n



def loops_family():
    """Counted loops over u8/u16/i16 counters: up and down, steps, wrap-around
    stops, early exits (Loom's per-slot and per-tile loops)."""
    r = random.Random(71)
    n = 0
    for k in range(32):
        t = r.choice(["u8", "u16", "i16", "i8"])
        start = wrap(r.randrange(-200, 300), t)
        step = r.choice([1, 2, 3, 5, -1, -2, -4])
        count = r.randrange(1, 60)
        stop_at = r.choice([None, r.randrange(count)])
        # simulate: for (i = start, n = 0; n < count; i += step, n++) { if (n == stop) break; acc += i; }
        i, acc, iters = start, 0, 0
        for nn in range(count):
            if stop_at is not None and nn == stop_at:
                break
            acc = wrap(acc + i, "u16")
            iters += 1
            i = wrap(i + step, t)
        final_i = i
        stop = f"    if (n == {stop_at}) break;\n" if stop_at is not None else ""
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A counted loop over a {t} counter from {start} in steps of {step}, "
                        f"{count} iterations{'' if stop_at is None else f', leaving at {stop_at}'}.\n"
                        '#include "loomcc-test.h"\n'
                        f"static volatile u8 limit = {count};\n"
                        "int main(void) {\n"
                        f"  {t} i;\n  u8 n;\n  u16 acc = 0, iters = 0;\n"
                        f"  for (i = ({t})({start}), n = 0; n < limit; i = ({t})(i + ({step})), n++) {{\n{stop}"
                        "    acc = (u16)(acc + (u16)i);\n    iters++;\n  }\n"
                        f"  CHECK(acc == {acc}u);\n  CHECK(iters == {iters});\n"
                        + (f"  CHECK(i == ({t})({final_i}));\n" if stop_at is None else "")
                        + "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-loops/loop-{k:02d}.c", src)
        n += 1
    return n


def aabb_family():
    """Axis-aligned box overlap tests with s16 coordinates and u8 sizes, the
    shape of Loom's collision checks."""
    r = random.Random(73)
    n = 0
    for k in range(15):
        boxes = [(r.randrange(-300, 300), r.randrange(-300, 300), r.randrange(1, 64), r.randrange(1, 64)) for _ in range(8)]
        pairs = []
        for a in range(8):
            for b in range(a + 1, 8):
                ax, ay, aw, ah = boxes[a]
                bx, by, bw, bh = boxes[b]
                hit = ax < bx + bw and bx < ax + aw and ay < by + bh and by < ay + ah
                pairs.append((a, b, int(hit)))
        hits = sum(p[2] for p in pairs)
        rows = ",\n".join(f"  {{ {x}, {y}, {w}, {h} }}" for x, y, w, h in boxes)
        src = HEADER + ("// loomcc-do: run\n// loomcc-int: agnostic\n// Box overlap with s16 positions and u8 sizes over every pair of 8 boxes.\n"
                        '#include "loomcc-test.h"\n'
                        "typedef struct { i16 x, y; u8 w, h; } Box;\n"
                        f"static const Box boxes[8] = {{\n{rows}\n}};\n"
                        "static u8 overlap(const Box *a, const Box *b) {\n"
                        "  return a->x < b->x + b->w && b->x < a->x + a->w && a->y < b->y + b->h && b->y < a->y + a->h;\n}\n"
                        "int main(void) {\n  u8 a, b, hits = 0;\n"
                        "  for (a = 0; a < 8; a++)\n    for (b = (u8)(a + 1); b < 8; b++)\n      hits = (u8)(hits + overlap(&boxes[a], &boxes[b]));\n"
                        f"  CHECK(hits == {hits});\n"
                        + "".join(f"  CHECK(overlap(&boxes[{a}], &boxes[{b}]) == {h});\n" for a, b, h in pairs if r.random() < 0.3)
                        + "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-aabb/aabb-{k:02d}.c", src)
        n += 1
    return n


def sort_family():
    """Insertion sort of an index array by a key table (sprite ordering by y),
    for several sizes and key types; stable."""
    r = random.Random(79)
    n = 0
    for k in range(24):
        t = r.choice(["u8", "i8", "u16", "i16"])
        size = r.choice([2, 3, 5, 8, 13, 24, 32])
        keys = [wrap(r.randrange(-40000, 70000), t) if r.random() < 0.8 else 0 for _ in range(size)]
        order = sorted(range(size), key=lambda i: (keys[i], i))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// Stable insertion sort of {size} u8 indices by a {t} key table.\n"
                        '#include "loomcc-test.h"\n'
                        f"static const {t} key[{size}] = {{ {', '.join(map(str, keys))} }};\n"
                        f"static const u8 want[{size}] = {{ {', '.join(map(str, order))} }};\n"
                        f"static u8 idx[{size}];\n"
                        "int main(void) {\n  u8 i, j, t;\n"
                        f"  for (i = 0; i < {size}; i++) idx[i] = i;\n"
                        f"  for (i = 1; i < {size}; i++) {{\n    t = idx[i];\n    j = i;\n"
                        "    while (j > 0 && key[idx[j - 1]] > key[t]) { idx[j] = idx[j - 1]; j--; }\n    idx[j] = t;\n  }\n"
                        f"  for (i = 0; i < {size}; i++) CHECK(idx[i] == want[i]);\n  return 0;\n}}\n")
        write(ROOT / f"t4-exec/gen-sort/sort-{k:02d}.c", src)
        n += 1
    return n


def ring_family():
    """A u8-indexed ring buffer with power-of-two and other capacities: push,
    pop, wrap-around, full and empty (Loom's input and audio queues)."""
    r = random.Random(83)
    n = 0
    for k in range(12):
        cap = r.choice([4, 8, 16, 5, 7, 12])
        ops, q, out = [], [], []
        for _ in range(60):
            if r.random() < 0.55:
                v = r.randrange(256)
                ok = len(q) < cap
                if ok:
                    q.append(v)
                ops.append(("push", v, int(ok)))
            else:
                if q:
                    ops.append(("pop", q.pop(0), 1))
                else:
                    ops.append(("pop", 0, 0))
        mod = f"& {cap - 1}" if cap & (cap - 1) == 0 else f"% {cap}"
        body = []
        for op, v, ok in ops:
            if op == "push":
                body.append(f"  CHECK(push({v}) == {ok});")
            else:
                body.append(f"  CHECK(pop(&v) == {ok});" + (f" CHECK(v == {v});" if ok else ""))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A ring buffer of {cap} u8 entries indexed by u8 head/tail ({mod.split()[0]} wrap).\n"
                        '#include "loomcc-test.h"\n'
                        f"#define CAP {cap}\nstatic u8 buf[CAP];\nstatic u8 head, tail, count;\n"
                        f"static u8 push(u8 v) {{ if (count == CAP) return 0; buf[tail] = v; tail = (u8)((tail + 1) {mod}); count++; return 1; }}\n"
                        f"static u8 pop(u8 *v) {{ if (!count) return 0; *v = buf[head]; head = (u8)((head + 1) {mod}); count--; return 1; }}\n"
                        "int main(void) {\n  u8 v = 0;\n" + "\n".join(body) + "\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-ring/ring-{k:02d}.c", src)
        n += 1
    return n


def tilemap_family():
    """A const tilemap (u8 tiles, width a power of two or not) read at pixel
    coordinates: x >> 3, y >> 3, row * width + column, solid-tile tests."""
    r = random.Random(89)
    n = 0
    for k in range(20):
        w, h = r.choice([(16, 14), (32, 8), (20, 10), (64, 4), (12, 12)])
        tiles = [r.choice([0, 0, 0, 1, 2, 3, 7, 255]) for _ in range(w * h)]
        probes = []
        for _ in range(24):
            px, py = r.randrange(-8, w * 8 + 8), r.randrange(-8, h * 8 + 8)
            if 0 <= px < w * 8 and 0 <= py < h * 8:
                t = tiles[(py >> 3) * w + (px >> 3)]
            else:
                t = 1   # outside: solid
            probes.append((px, py, t, int(t != 0 and t != 255)))
        rows = ",\n".join("  " + ", ".join(str(tiles[y * w + x]) for x in range(w)) for y in range(h))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A {w}x{h} tilemap in ROM read at s16 pixel coordinates; outside the map is solid.\n"
                        '#include "loomcc-test.h"\n'
                        f"#define W {w}\n#define H {h}\nstatic const u8 map[W * H] = {{\n{rows}\n}};\n"
                        "static u8 tile_at(i16 px, i16 py) {\n  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;\n"
                        "  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];\n}\n"
                        "static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }\n"
                        "int main(void) {\n"
                        + "".join(f"  CHECK(tile_at({px}, {py}) == {t}); CHECK(solid({px}, {py}) == {s});\n" for px, py, t, s in probes)
                        + "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-tilemap/tilemap-{k:02d}.c", src)
        n += 1
    return n


def minmax_family():
    """min/max/clamp/abs helpers on each small type, as macros and functions."""
    n = 0
    for t in ["u8", "i8", "u16", "i16"]:
        vals = VALUES[t]
        lines = []
        for a in vals:
            for b in vals[::3]:
                lo, hi = min(a, b), max(a, b)
                lines.append(f"  x = {lit(a, promote(t)) if T[t][0] == 16 else a}; y = {lit(b, promote(t)) if T[t][0] == 16 else b}; "
                             f"CHECK(MIN(x, y) == ({t})({lo})); CHECK(max_fn(x, y) == ({t})({hi}));")
        clamp = []
        for a in vals:
            lo, hi = (10, 200) if not T[t][1] else (-100, 100)
            c = min(max(a, lo), hi)
            clamp.append(f"  x = {lit(a, promote(t)) if T[t][0] == 16 else a}; CHECK(clamp_fn(x, {lo}, {hi}) == ({t})({c}));")
        if T[t][1]:
            for a in vals:
                if a == -(1 << (T[t][0] - 1)):
                    continue
                clamp.append(f"  x = {lit(a, promote(t)) if T[t][0] == 16 else a}; CHECK(abs_fn(x) == ({t})({abs(a)}));")
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// min, max, clamp{' and abs' if T[t][1] else ''} on {t}.\n"
                        '#include "loomcc-test.h"\n#define MIN(a, b) ((a) < (b) ? (a) : (b))\n'
                        f"static volatile {t} x, y;\n"
                        f"static {t} max_fn({t} a, {t} b) {{ return a > b ? a : b; }}\n"
                        f"static {t} clamp_fn({t} v, {t} lo, {t} hi) {{ return v < lo ? lo : v > hi ? hi : v; }}\n"
                        + (f"static {t} abs_fn({t} v) {{ return ({t})(v < 0 ? -v : v); }}\n" if T[t][1] else "")
                        + "int main(void) {\n" + "\n".join(lines + clamp) + "\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-minmax/minmax-{t}.c", src)
        n += 1
    return n


def outparam_family():
    """Functions that return several results through pointers into structs,
    arrays and locals (Loom's query functions)."""
    r = random.Random(97)
    n = 0
    for k in range(10):
        vals = [r.randrange(-30000, 30000) for _ in range(r.randint(3, 12))]
        lo, hi, s = min(vals), max(vals), wrap(sum(vals), "i16")
        src = HEADER + ("// loomcc-do: run\n// loomcc-int: agnostic\n// Results through pointers to a struct member, an array element and a local.\n"
                        '#include "loomcc-test.h"\n'
                        f"static const i16 data[{len(vals)}] = {{ {', '.join(map(str, vals))} }};\n"
                        "typedef struct { i16 lo; u8 pad; i16 hi; } Range;\n"
                        "static void scan(const i16 *p, u8 n, i16 *lo, i16 *hi, i16 *sum) {\n"
                        "  u8 i;\n  *lo = *hi = p[0];\n  *sum = 0;\n"
                        "  for (i = 0; i < n; i++) { if (p[i] < *lo) *lo = p[i]; if (p[i] > *hi) *hi = p[i]; *sum = (i16)(*sum + p[i]); }\n}\n"
                        "int main(void) {\n  Range r;\n  i16 sums[3];\n  i16 hi2;\n"
                        f"  scan(data, {len(vals)}, &r.lo, &r.hi, &sums[1]);\n"
                        f"  CHECK(r.lo == {lit(lo, 'i16')} && r.hi == {lit(hi, 'i16')} && sums[1] == {lit(s, 'i16')});\n"
                        f"  scan(data + 1, {len(vals) - 1}, &sums[0], &hi2, &sums[2]);\n"
                        f"  CHECK(sums[0] == {lit(min(vals[1:]), 'i16')} && hi2 == {lit(max(vals[1:]), 'i16')} && sums[2] == {lit(wrap(sum(vals[1:]), 'i16'), 'i16')});\n"
                        "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-outparam/outparam-{k:02d}.c", src)
        n += 1
    return n



def bitpack_family():
    """Pack and unpack fields into u16/u32 words with shifts and masks (OAM
    attributes, tile entries, packed drive keys)."""
    r = random.Random(101)
    n = 0
    for k in range(16):
        word = "u16" if k % 2 == 0 else "u32"
        bits = T[word][0]
        widths, total = [], 0
        while total < bits:
            w = r.randint(1, min(8, bits - total))
            widths.append(w)
            total += w
        vals = [r.getrandbits(w) for w in widths]
        packed, sh = 0, 0
        for w, v in zip(widths, vals):
            packed |= v << sh
            sh += w
        lines, sh = [], 0
        for j, (w, v) in enumerate(zip(widths, vals)):
            m = (1 << w) - 1
            lines.append(f"  CHECK((u16)((p >> {sh}) & {m}u) == {v});")
            sh += w
        pack_expr = " | ".join(f"(({word})f[{j}] << {sum(widths[:j])})" for j in range(len(widths)))
        wl = lambda v: f"{v}u" if word == "u16" else f"(u32){v}ULL"
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// {len(widths)} fields of widths {widths} packed into a {word} and unpacked.\n"
                        + ("// loomcc-ref: host host16\n// loomcc-note: no 816-tcc reference for u32: its 32-bit shifts need a helper libtcc lacks.\n" if word == "u32" else "")
                        + '#include "loomcc-test.h"\n'
                        f"static const u8 f_rom[{len(widths)}] = {{ {', '.join(map(str, vals))} }};\n"
                        f"static u8 f[{len(widths)}];\n"
                        "int main(void) {\n  u8 i;\n"
                        f"  {word} p;\n  for (i = 0; i < {len(widths)}; i++) f[i] = f_rom[i];\n"
                        f"  p = ({word})({pack_expr});\n  CHECK(p == {wl(packed)});\n" + "\n".join(lines) + "\n  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-bitpack/bitpack-{k:02d}.c", src)
        n += 1
    return n


def fsm_family():
    """A ROM transition table (state x input -> next state, action) driven by
    an input sequence: Loom's generated state machines."""
    r = random.Random(103)
    n = 0
    for k in range(20):
        ns, ni = r.randint(2, 8), r.randint(2, 5)
        nxt = [[r.randrange(ns) for _ in range(ni)] for _ in range(ns)]
        act = [[r.randrange(0, 5) for _ in range(ni)] for _ in range(ns)]
        seq = [r.randrange(ni) for _ in range(r.randint(5, 40))]
        s_, score, visits = 0, 0, [0] * ns
        for x in seq:
            score = wrap(score + act[s_][x] * (s_ + 1), "u16")
            s_ = nxt[s_][x]
            visits[s_] += 1
        tbl = lambda t: ",\n".join("  { " + ", ".join(map(str, row)) + " }" for row in t)
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A {ns}-state machine over {ni} inputs from ROM tables, fed {len(seq)} inputs.\n"
                        '#include "loomcc-test.h"\n'
                        f"static const u8 next_state[{ns}][{ni}] = {{\n{tbl(nxt)}\n}};\n"
                        f"static const u8 action[{ns}][{ni}] = {{\n{tbl(act)}\n}};\n"
                        f"static const u8 inputs[{len(seq)}] = {{ {', '.join(map(str, seq))} }};\n"
                        f"static u8 visits[{ns}];\n"
                        "int main(void) {\n  u8 s = 0, i;\n  u16 score = 0;\n"
                        f"  for (i = 0; i < {len(seq)}; i++) {{\n    u8 x = inputs[i];\n    score = (u16)(score + action[s][x] * (s + 1));\n    s = next_state[s][x];\n    visits[s]++;\n  }}\n"
                        f"  CHECK(s == {s_});\n  CHECK(score == {score}u);\n"
                        + "".join(f"  CHECK(visits[{j}] == {v});\n" for j, v in enumerate(visits))
                        + "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-fsm/fsm-{k:02d}.c", src)
        n += 1
    return n


def divround_family():
    """Integer division helpers on s16/u16: floor division and a positive
    modulo for negative values, rounding to nearest, division by powers of two
    with a shift (and why that differs for negatives)."""
    n = 0
    for t in ["i16", "u16"]:
        for divisor in [2, 3, 7, 8, 10, 16, 100]:
            vals = [v for v in VALUES[t]] + ([-7, -8, -9, -15, -16, -17, 5, 9] if t == "i16" else [5, 9, 15, 16, 17])
            lines = []
            for a in vals:
                q = cdiv(a, divisor)
                rmd = a - q * divisor
                fl = a // divisor
                pm = a % divisor
                near = cdiv(a + (divisor // 2 if a >= 0 else -(divisor // 2)), divisor) if fits(a + divisor // 2, t) and fits(a - divisor // 2, t) else None
                la = lit(a, t)
                line = f"  v = {la}; CHECK(v / D == {lit(q, t)}); CHECK(v % D == {lit(rmd, t)}); CHECK(floor_div(v) == {lit(fl, t)}); CHECK(pos_mod(v) == {lit(pm, t)});"
                if near is not None:
                    line += f" CHECK(round_div(v) == {lit(near, t)});"
                if divisor & (divisor - 1) == 0:
                    line += f" CHECK((v >> {divisor.bit_length() - 1}) == {lit(a >> (divisor.bit_length() - 1), t)});"
                lines.append(line)
            src = HEADER + (f"// loomcc-do: run\n// loomcc-int: 16\n// {t} divided by {divisor}: C's truncating / and %, floor division, a\n"
                            "// positive modulo and round-to-nearest built on them, and >> for powers of two.\n"
                            '#include "loomcc-test.h"\n'
                            f"#define D (({t}){divisor})\nstatic volatile {t} v;\n"
                            f"static {t} floor_div({t} a) {{ {t} q = ({t})(a / D); if ((a % D) != 0 && (a < 0)) q--; return q; }}\n"
                            f"static {t} pos_mod({t} a) {{ {t} m = ({t})(a % D); if (m < 0) m = ({t})(m + D); return m; }}\n"
                            f"static {t} round_div({t} a) {{ return ({t})((a >= 0 ? a + D / 2 : a - D / 2) / D); }}\n"
                            "int main(void) {\n" + "\n".join(lines) + "\n  return 0;\n}\n")
            write(ROOT / f"t4-exec/gen-divround/div-{t}-{divisor}.c", src)
            n += 1
    return n


def strings_family():
    """String handling on ROM text without libc: length, compare, find, bounded
    copy into a WRAM buffer, reversal and number formatting (Loom's UI text)."""
    r = random.Random(107)
    words = ["", "a", "loom", "snes", "Cliffside", "hello world", "0123456789", "The quick brown fox", "x" * 40]
    n = 0
    for k in range(12):
        a, b = r.choice(words), r.choice(words)
        num = r.randrange(0, 65536)
        cmp = (a > b) - (a < b)
        ch = r.choice("aeoxl ")
        idx = a.find(ch)
        cap = r.randint(1, 16)
        copied = a[:cap - 1]
        esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
        src = HEADER + ("// loomcc-do: run\n// loomcc-int: agnostic\n// ROM strings: length, compare, find, bounded copy, reverse, u16 to decimal.\n"
                        '#include "loomcc-test.h"\n'
                        f'static const char A[] = "{esc(a)}";\nstatic const char B[] = "{esc(b)}";\nstatic char buf[24];\n'
                        "static u16 slen(const char *s) { const char *p = s; while (*p) p++; return (u16)(p - s); }\n"
                        "static i8 scmp(const char *x, const char *y) { while (*x && *x == *y) { x++; y++; } return (i8)((u8)*x > (u8)*y ? 1 : (u8)*x < (u8)*y ? -1 : 0); }\n"
                        "static i16 sfind(const char *s, char c) { i16 i; for (i = 0; s[i]; i++) if (s[i] == c) return i; return -1; }\n"
                        "static void scopy(char *d, const char *s, u8 cap) { u8 i = 0; if (!cap) return; while (s[i] && i + 1 < cap) { d[i] = s[i]; i++; } d[i] = 0; }\n"
                        "static void utoa(u16 v, char *d) { char t[6]; u8 n = 0; do { t[n++] = (char)('0' + v % 10); v /= 10; } while (v); while (n) *d++ = t[--n]; *d = 0; }\n"
                        "int main(void) {\n"
                        f"  CHECK(slen(A) == {len(a)} && slen(B) == {len(b)});\n"
                        f"  CHECK(scmp(A, B) == {cmp});\n  CHECK(scmp(A, A) == 0);\n"
                        f"  CHECK(sfind(A, '{ch}') == {idx});\n"
                        f"  scopy(buf, A, {cap});\n  CHECK(slen(buf) == {len(copied)} && scmp(buf, \"{esc(copied)}\") == 0);\n"
                        f"  utoa({num}u, buf);\n  CHECK(scmp(buf, \"{num}\") == 0);\n"
                        "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-strings/strings-{k:02d}.c", src)
        n += 1
    return n


def callchain_family():
    """Chains of distinct functions with mixed-width arguments and live values
    across calls (no recursion): argument slots of 1, 2 and 4 bytes."""
    r = random.Random(109)
    n = 0
    for k in range(10):
        depth = r.randint(2, 7)
        types = [r.sample(["u8", "i8", "u16", "i16", "i32"], r.randint(1, 4)) for _ in range(depth)]
        funcs, calls = [], []
        # f_j(params) = sum(params) + f_{j+1}(params transformed), last returns sum
        for j in range(depth - 1, -1, -1):
            ps = ", ".join(f"{t} a{i}" for i, t in enumerate(types[j]))
            ssum = " + ".join(f"(i32)a{i}" for i in range(len(types[j])))
            if j == depth - 1:
                body = f"return {ssum};"
            else:
                nxt = types[j + 1]
                args = ", ".join(f"({t})(a0 + {i + 1})" for i, t in enumerate(nxt))
                body = f"i32 keep = {ssum}; i32 rest = f{j + 1}({args}); return keep + keep + rest;"
            funcs.append(f"static i32 f{j}({ps}) {{ {body} }}")
        # model
        def f(j, args):
            s = sum(args)
            if j == depth - 1:
                return s
            nxt = types[j + 1]
            a = [wrap(args[0] + i + 1, t) for i, t in enumerate(nxt)]
            return s * 2 + f(j + 1, a)
        init = [wrap(r.randrange(-300, 300), t) for t in types[0]]
        res = wrap(f(0, init), "i32")
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// A chain of {depth} calls with argument types {types}.\n"
                        '#include "loomcc-test.h"\n' + "\n".join(funcs) + "\n"
                        f"int main(void) {{\n  CHECK(f0({', '.join(f'({t})({v})' for t, v in zip(types[0], init))}) == (i32){res}LL);\n  return 0;\n}}\n")
        write(ROOT / f"t4-exec/gen-callchain/chain-{k:02d}.c", src)
        n += 1
    return n



def pressure_family():
    """Many values live at once across a loop and a call: more than the 65816
    has registers or the direct page has scratch words."""
    r = random.Random(113)
    n = 0
    for k in range(15):
        nv = r.randint(8, 28)
        t = r.choice(["u8", "i16", "u16", "i8"])
        init = [wrap(r.randrange(-500, 500), t) for _ in range(nv)]
        steps = r.randint(1, 6)
        coef = [r.randrange(1, 4) for _ in range(nv)]
        vals = list(init)
        for _ in range(steps):
            vals = [wrap(vals[j] + coef[j] * (vals[(j + 1) % nv] & 7), t) for j in range(nv)]
        total = wrap(sum(vals), "u16")
        decl = "\n".join(f"  {t} v{j} = ({t})({init[j]});" for j in range(nv))
        upd = "\n".join(f"    n{j} = ({t})(v{j} + {coef[j]} * (v{(j + 1) % nv} & 7));" for j in range(nv))
        cp = " ".join(f"v{j} = n{j};" for j in range(nv))
        ndecl = ", ".join(f"n{j}" for j in range(nv))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// {nv} live {t} locals updated together {steps} times, with a call in the loop.\n"
                        '#include "loomcc-test.h"\n'
                        "static volatile u8 sink;\nstatic void touch(u8 x) { sink = x; }\n"
                        f"int main(void) {{\n{decl}\n  {t} {ndecl};\n  u8 s;\n  u16 total;\n"
                        f"  for (s = 0; s < {steps}; s++) {{\n{upd}\n    touch(s);\n    {cp}\n  }}\n"
                        f"  total = (u16)({' + '.join(f'(u16)v{j}' for j in range(nv))});\n"
                        f"  CHECK(total == {total}u);\n  CHECK(v0 == ({t})({vals[0]}) && v{nv - 1} == ({t})({vals[-1]}));\n  return 0;\n}}\n")
        write(ROOT / f"t4-exec/gen-pressure/pressure-{k:02d}.c", src)
        n += 1
    return n


def bigframe_family():
    """Local arrays from a few bytes to over 256 bytes (past 8-bit stack
    offsets) and several arrays in one frame."""
    n = 0
    for k, sizes in enumerate([[4], [40], [130], [200, 70], [300], [16, 16, 16, 16], [500], [255, 2], [256], [90, 90, 90]]):
        decl = "\n".join(f"  u8 a{j}[{sz}];" for j, sz in enumerate(sizes))
        fill = "\n".join(f"  for (i = 0; i < {sz}; i++) a{j}[i] = (u8)(i * {j + 3} + {j});" for j, sz in enumerate(sizes))
        exp = [sum(((i * (j + 3) + j) & 0xff) for i in range(sz)) & 0xffff for j, sz in enumerate(sizes)]
        sums = "\n".join(f"  s = 0; for (i = 0; i < {sz}; i++) s = (u16)(s + a{j}[i]); CHECK(s == {e}u); CHECK(a{j}[{sz - 1}] == {((sz - 1) * (j + 3) + j) & 0xff});"
                         for j, (sz, e) in enumerate(zip(sizes, exp)))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// Local arrays of {sizes} bytes in one frame.\n"
                        '#include "loomcc-test.h"\n'
                        f"static void work(void) {{\n{decl}\n  u16 i, s;\n{fill}\n{sums}\n}}\n"
                        "int main(void) { work(); return 0; }\n")
        write(ROOT / f"t4-exec/gen-bigframe/frame-{k:02d}.c", src)
        n += 1
    return n


def nested_index_family():
    """a[i].b[j].c: arrays of structs containing arrays of structs, indexed by
    u8 and u16 values (Loom's scene and animation data)."""
    r = random.Random(127)
    n = 0
    for k in range(15):
        no, ni = r.randint(2, 9), r.randint(1, 6)
        inner_t, outer_t = r.choice(["u8", "i16", "u16"]), r.choice(["u8", "i8", "i16"])
        data = [[(wrap(r.getrandbits(16), inner_t), wrap(r.getrandbits(16), "u8")) for _ in range(ni)] for _ in range(no)]
        tags = [wrap(r.getrandbits(16), outer_t) for _ in range(no)]
        probes = [(r.randrange(no), r.randrange(ni)) for _ in range(16)]
        total = wrap(sum(v for row in data for v, _ in row), "u16")
        init = ",\n".join("  { " + str(tags[i]) + ", { " + ", ".join(f"{{ {v}, {f} }}" for v, f in data[i]) + " } }" for i in range(no))
        src = HEADER + (f"// loomcc-do: run\n// loomcc-int: agnostic\n// {no} outer records, each with {ni} inner records, in ROM and copied to WRAM.\n"
                        '#include "loomcc-test.h"\n'
                        f"typedef struct {{ {inner_t} v; u8 f; }} In;\ntypedef struct {{ {outer_t} tag; In in[{ni}]; }} Out;\n"
                        f"static const Out rom[{no}] = {{\n{init}\n}};\nstatic Out ram[{no}];\nstatic volatile u8 vi, vj;\n"
                        "int main(void) {\n  u8 i, j;\n  u16 total = 0;\n"
                        f"  for (i = 0; i < {no}; i++) ram[i] = rom[i];\n"
                        f"  for (i = 0; i < {no}; i++) for (j = 0; j < {ni}; j++) total = (u16)(total + (u16)ram[i].in[j].v);\n"
                        f"  CHECK(total == {total}u);\n"
                        + "".join(f"  vi = {a}; vj = {b}; CHECK(ram[vi].in[vj].v == ({inner_t})({data[a][b][0]}) && rom[vi].in[vj].f == {data[a][b][1]} && ram[vi].tag == ({outer_t})({tags[a]}));\n" for a, b in probes)
                        + "  return 0;\n}\n")
        write(ROOT / f"t4-exec/gen-nested/nested-{k:02d}.c", src)
        n += 1
    return n


if __name__ == "__main__":
    total = (arith_family() + arith_family(["u32", "i32"], SMALL + ["u32", "i32"], "32") + soa_family() + switch_family() + romwalk_family()
             + declarator_family() + declarator_family(29, 40, True, "gen-declarator-qualified") + precedence_family() + conversion_family()
             + layout_family() + designator_family() + truncation_family()
             + flags_family() + lut_family() + subpixel_family() + dispatch_family()
             + loops_family() + aabb_family() + sort_family() + ring_family() + tilemap_family()
             + minmax_family() + outparam_family() + bitpack_family() + fsm_family() + divround_family()
             + strings_family() + callchain_family() + pressure_family() + bigframe_family() + nested_index_family())
    print(f"wrote {total} generated tests")
