// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A chain of 3 calls with argument types [['i8', 'i16', 'u16'], ['u8'], ['u8', 'u16']].
#include "loomcc-test.h"
static i32 f2(u8 a0, u16 a1) { return (i32)a0 + (i32)a1; }
static i32 f1(u8 a0) { i32 keep = (i32)a0; i32 rest = f2((u8)(a0 + 1), (u16)(a0 + 2)); return keep + keep + rest; }
static i32 f0(i8 a0, i16 a1, u16 a2) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2; i32 rest = f1((u8)(a0 + 1)); return keep + keep + rest; }
int main(void) {
  CHECK(f0((i8)(35), (i16)(293), (u16)(283)) == (i32)1369LL);
  return 0;
}
