// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u16): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 3, 12, 6, 12, 5, 8, 9, 11, 9, 1, 2, 6, 4, 5, 3, 5, 1, 4, 1, 11 };
static volatile u16 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 41619u;
  f = (u16)(f & (u16)~(u16)(1u << bit[0]));
  CHECK(f == 41619u);
  CHECK((f & 25067u) == 8323u);
  CHECK(f == 41619u);
  f = (u16)(f | (u16)(1u << bit[2]));
  CHECK(f == 41683u);
  CHECK((f & 9352u) == 8320u);
  CHECK(f == 41683u);
  f = (u16)(f | (u16)(1u << bit[4]));
  CHECK(f == 41715u);
  f ^= (u16)(1u << bit[5]);
  CHECK(f == 41971u);
  CHECK((f & 59358u) == 41938u);
  CHECK(f == 41971u);
  f = (u16)(f & (u16)~(u16)(1u << bit[7]));
  CHECK(f == 41971u);
  f = (u16)(f & (u16)~(u16)(1u << bit[8]));
  CHECK(f == 41459u);
  f = (u16)(f | (u16)(1u << bit[9]));
  CHECK(f == 41459u);
  f ^= (u16)(1u << bit[10]);
  CHECK(f == 41463u);
  f = (u16)(f | (u16)(1u << bit[11]));
  CHECK(f == 41463u);
  f = (u16)(f | (u16)(1u << bit[12]));
  CHECK(f == 41463u);
  CHECK(((f >> bit[13]) & 1u) == 1);
  CHECK(f == 41463u);
  CHECK(((f >> bit[14]) & 1u) == 0);
  CHECK(f == 41463u);
  f = (u16)(f | (u16)(1u << bit[15]));
  CHECK(f == 41463u);
  f = (u16)(f | (u16)(1u << bit[16]));
  CHECK(f == 41463u);
  f ^= (u16)(1u << bit[17]);
  CHECK(f == 41447u);
  CHECK(((f >> bit[18]) & 1u) == 1);
  CHECK(f == 41447u);
  f ^= (u16)(1u << bit[19]);
  CHECK(f == 43495u);
  return 0;
}
