// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u16): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 12, 1, 0, 14, 2, 7, 11, 0, 10, 6, 2, 6, 6, 1, 5, 12, 1, 15, 6, 2 };
static volatile u16 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 46388u;
  CHECK((f & 25142u) == 8244u);
  CHECK(f == 46388u);
  f ^= (u16)(1u << bit[1]);
  CHECK(f == 46390u);
  f = (u16)(f & (u16)~(u16)(1u << bit[2]));
  CHECK(f == 46390u);
  CHECK(((f >> bit[3]) & 1u) == 0);
  CHECK(f == 46390u);
  f ^= (u16)(1u << bit[4]);
  CHECK(f == 46386u);
  f = (u16)(f | (u16)(1u << bit[5]));
  CHECK(f == 46514u);
  f ^= (u16)(1u << bit[6]);
  CHECK(f == 48562u);
  f = (u16)(f | (u16)(1u << bit[7]));
  CHECK(f == 48563u);
  f ^= (u16)(1u << bit[8]);
  CHECK(f == 47539u);
  CHECK(((f >> bit[9]) & 1u) == 0);
  CHECK(f == 47539u);
  CHECK((f & 54383u) == 36899u);
  CHECK(f == 47539u);
  CHECK(((f >> bit[11]) & 1u) == 0);
  CHECK(f == 47539u);
  f = (u16)(f & (u16)~(u16)(1u << bit[12]));
  CHECK(f == 47539u);
  f = (u16)(f | (u16)(1u << bit[13]));
  CHECK(f == 47539u);
  f = (u16)(f | (u16)(1u << bit[14]));
  CHECK(f == 47539u);
  f ^= (u16)(1u << bit[15]);
  CHECK(f == 43443u);
  f = (u16)(f & (u16)~(u16)(1u << bit[16]));
  CHECK(f == 43441u);
  CHECK(((f >> bit[17]) & 1u) == 1);
  CHECK(f == 43441u);
  CHECK((f & 57913u) == 41009u);
  CHECK(f == 43441u);
  f = (u16)(f & (u16)~(u16)(1u << bit[19]));
  CHECK(f == 43441u);
  return 0;
}
