// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u8): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 7, 6, 2, 5, 7, 6, 1, 2, 2, 7, 5, 3, 0, 4, 5, 5, 4, 7, 6, 2 };
static volatile u8 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 164u;
  CHECK((f & 67u) == 0u);
  CHECK(f == 164u);
  f = (u8)(f | (u8)(1u << bit[1]));
  CHECK(f == 228u);
  f = (u8)(f & (u8)~(u8)(1u << bit[2]));
  CHECK(f == 224u);
  f ^= (u8)(1u << bit[3]);
  CHECK(f == 192u);
  f ^= (u8)(1u << bit[4]);
  CHECK(f == 64u);
  f = (u8)(f & (u8)~(u8)(1u << bit[5]));
  CHECK(f == 0u);
  CHECK(((f >> bit[6]) & 1u) == 0);
  CHECK(f == 0u);
  f = (u8)(f | (u8)(1u << bit[7]));
  CHECK(f == 4u);
  f = (u8)(f | (u8)(1u << bit[8]));
  CHECK(f == 4u);
  f = (u8)(f | (u8)(1u << bit[9]));
  CHECK(f == 132u);
  CHECK((f & 17u) == 0u);
  CHECK(f == 132u);
  f ^= (u8)(1u << bit[11]);
  CHECK(f == 140u);
  CHECK((f & 155u) == 136u);
  CHECK(f == 140u);
  f = (u8)(f & (u8)~(u8)(1u << bit[13]));
  CHECK(f == 140u);
  f = (u8)(f | (u8)(1u << bit[14]));
  CHECK(f == 172u);
  CHECK((f & 144u) == 128u);
  CHECK(f == 172u);
  f = (u8)(f | (u8)(1u << bit[16]));
  CHECK(f == 188u);
  f = (u8)(f | (u8)(1u << bit[17]));
  CHECK(f == 188u);
  f ^= (u8)(1u << bit[18]);
  CHECK(f == 252u);
  CHECK(((f >> bit[19]) & 1u) == 1);
  CHECK(f == 252u);
  return 0;
}
