// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u8): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 3, 7, 7, 0, 5, 4, 2, 5, 7, 3, 2, 5, 6, 5, 2, 6, 7, 2, 7, 3 };
static volatile u8 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 157u;
  CHECK(((f >> bit[0]) & 1u) == 1);
  CHECK(f == 157u);
  CHECK((f & 92u) == 28u);
  CHECK(f == 157u);
  f = (u8)(f | (u8)(1u << bit[2]));
  CHECK(f == 157u);
  f = (u8)(f & (u8)~(u8)(1u << bit[3]));
  CHECK(f == 156u);
  f = (u8)(f & (u8)~(u8)(1u << bit[4]));
  CHECK(f == 156u);
  f = (u8)(f | (u8)(1u << bit[5]));
  CHECK(f == 156u);
  f = (u8)(f | (u8)(1u << bit[6]));
  CHECK(f == 156u);
  f = (u8)(f & (u8)~(u8)(1u << bit[7]));
  CHECK(f == 156u);
  f = (u8)(f & (u8)~(u8)(1u << bit[8]));
  CHECK(f == 28u);
  f = (u8)(f & (u8)~(u8)(1u << bit[9]));
  CHECK(f == 20u);
  f ^= (u8)(1u << bit[10]);
  CHECK(f == 16u);
  CHECK((f & 169u) == 0u);
  CHECK(f == 16u);
  f = (u8)(f | (u8)(1u << bit[12]));
  CHECK(f == 80u);
  f ^= (u8)(1u << bit[13]);
  CHECK(f == 112u);
  f = (u8)(f | (u8)(1u << bit[14]));
  CHECK(f == 116u);
  CHECK(((f >> bit[15]) & 1u) == 1);
  CHECK(f == 116u);
  f = (u8)(f & (u8)~(u8)(1u << bit[16]));
  CHECK(f == 116u);
  f = (u8)(f | (u8)(1u << bit[17]));
  CHECK(f == 116u);
  CHECK(((f >> bit[18]) & 1u) == 0);
  CHECK(f == 116u);
  f ^= (u8)(1u << bit[19]);
  CHECK(f == 124u);
  return 0;
}
