// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u16): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 2, 0, 14, 3, 5, 7, 15, 3, 3, 11, 4, 3, 6, 5, 7, 8, 6, 7, 1, 11 };
static volatile u16 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 30725u;
  f ^= (u16)(1u << bit[0]);
  CHECK(f == 30721u);
  f ^= (u16)(1u << bit[1]);
  CHECK(f == 30720u);
  CHECK((f & 34862u) == 2048u);
  CHECK(f == 30720u);
  CHECK(((f >> bit[3]) & 1u) == 0);
  CHECK(f == 30720u);
  f = (u16)(f & (u16)~(u16)(1u << bit[4]));
  CHECK(f == 30720u);
  CHECK(((f >> bit[5]) & 1u) == 0);
  CHECK(f == 30720u);
  f = (u16)(f & (u16)~(u16)(1u << bit[6]));
  CHECK(f == 30720u);
  f ^= (u16)(1u << bit[7]);
  CHECK(f == 30728u);
  f = (u16)(f | (u16)(1u << bit[8]));
  CHECK(f == 30728u);
  CHECK((f & 3259u) == 2056u);
  CHECK(f == 30728u);
  f = (u16)(f & (u16)~(u16)(1u << bit[10]));
  CHECK(f == 30728u);
  CHECK((f & 17048u) == 16392u);
  CHECK(f == 30728u);
  f = (u16)(f | (u16)(1u << bit[12]));
  CHECK(f == 30792u);
  CHECK(((f >> bit[13]) & 1u) == 0);
  CHECK(f == 30792u);
  f ^= (u16)(1u << bit[14]);
  CHECK(f == 30920u);
  f = (u16)(f | (u16)(1u << bit[15]));
  CHECK(f == 31176u);
  f = (u16)(f & (u16)~(u16)(1u << bit[16]));
  CHECK(f == 31112u);
  CHECK(((f >> bit[17]) & 1u) == 1);
  CHECK(f == 31112u);
  f = (u16)(f | (u16)(1u << bit[18]));
  CHECK(f == 31114u);
  f = (u16)(f | (u16)(1u << bit[19]));
  CHECK(f == 31114u);
  return 0;
}
