// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Flag words (u16): set, clear, toggle and test bits chosen at run time.
#include "loomcc-test.h"
static const u8 bit_rom[20] = { 12, 11, 7, 13, 0, 10, 10, 2, 1, 1, 1, 4, 3, 13, 1, 13, 1, 8, 6, 12 };
static volatile u16 f;
static u8 bit[20];
int main(void) {
  u8 i;
  for (i = 0; i < 20; i++) bit[i] = bit_rom[i];
  f = 43344u;
  f = (u16)(f & (u16)~(u16)(1u << bit[0]));
  CHECK(f == 43344u);
  f = (u16)(f | (u16)(1u << bit[1]));
  CHECK(f == 43344u);
  f ^= (u16)(1u << bit[2]);
  CHECK(f == 43472u);
  CHECK((f & 49584u) == 33168u);
  CHECK(f == 43472u);
  CHECK((f & 39489u) == 34880u);
  CHECK(f == 43472u);
  f = (u16)(f | (u16)(1u << bit[5]));
  CHECK(f == 44496u);
  f ^= (u16)(1u << bit[6]);
  CHECK(f == 43472u);
  CHECK(((f >> bit[7]) & 1u) == 0);
  CHECK(f == 43472u);
  f = (u16)(f | (u16)(1u << bit[8]));
  CHECK(f == 43474u);
  CHECK((f & 25639u) == 8194u);
  CHECK(f == 43474u);
  CHECK(((f >> bit[10]) & 1u) == 1);
  CHECK(f == 43474u);
  f ^= (u16)(1u << bit[11]);
  CHECK(f == 43458u);
  CHECK(((f >> bit[12]) & 1u) == 0);
  CHECK(f == 43458u);
  f = (u16)(f | (u16)(1u << bit[13]));
  CHECK(f == 43458u);
  CHECK(((f >> bit[14]) & 1u) == 1);
  CHECK(f == 43458u);
  f = (u16)(f & (u16)~(u16)(1u << bit[15]));
  CHECK(f == 35266u);
  CHECK(((f >> bit[16]) & 1u) == 1);
  CHECK(f == 35266u);
  f ^= (u16)(1u << bit[17]);
  CHECK(f == 35010u);
  f = (u16)(f & (u16)~(u16)(1u << bit[18]));
  CHECK(f == 34946u);
  f ^= (u16)(1u << bit[19]);
  CHECK(f == 39042u);
  return 0;
}
