// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 12x12 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 12
#define H 12
static const u8 map[W * H] = {
  0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 255, 0,
  0, 0, 2, 0, 7, 7, 7, 0, 7, 1, 7, 2,
  2, 1, 0, 0, 1, 2, 0, 7, 0, 255, 3, 0,
  7, 1, 255, 0, 0, 0, 255, 2, 1, 2, 7, 7,
  0, 0, 2, 255, 0, 1, 0, 2, 255, 255, 3, 0,
  255, 0, 3, 0, 1, 0, 0, 2, 255, 3, 3, 7,
  2, 7, 3, 0, 0, 0, 3, 0, 0, 255, 2, 0,
  0, 0, 0, 255, 3, 0, 1, 0, 7, 2, 7, 0,
  0, 0, 255, 3, 2, 3, 0, 3, 3, 7, 255, 2,
  255, 0, 0, 0, 2, 0, 7, 1, 0, 2, 2, 2,
  7, 7, 0, 3, 0, 0, 7, 2, 1, 0, 3, 2,
  7, 0, 1, 3, 0, 255, 0, 3, 2, 3, 3, 0
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(23, 48) == 3); CHECK(solid(23, 48) == 1);
  CHECK(tile_at(21, 2) == 0); CHECK(solid(21, 2) == 0);
  CHECK(tile_at(88, 99) == 1); CHECK(solid(88, 99) == 1);
  CHECK(tile_at(80, 48) == 2); CHECK(solid(80, 48) == 1);
  CHECK(tile_at(50, 67) == 0); CHECK(solid(50, 67) == 0);
  CHECK(tile_at(16, 73) == 0); CHECK(solid(16, 73) == 0);
  CHECK(tile_at(48, 94) == 0); CHECK(solid(48, 94) == 0);
  CHECK(tile_at(19, 75) == 0); CHECK(solid(19, 75) == 0);
  CHECK(tile_at(61, 42) == 2); CHECK(solid(61, 42) == 1);
  CHECK(tile_at(-2, 50) == 1); CHECK(solid(-2, 50) == 1);
  CHECK(tile_at(18, 12) == 2); CHECK(solid(18, 12) == 1);
  CHECK(tile_at(49, 85) == 7); CHECK(solid(49, 85) == 1);
  CHECK(tile_at(102, 76) == 1); CHECK(solid(102, 76) == 1);
  CHECK(tile_at(16, 49) == 3); CHECK(solid(16, 49) == 1);
  CHECK(tile_at(25, 71) == 3); CHECK(solid(25, 71) == 1);
  CHECK(tile_at(63, 89) == 3); CHECK(solid(63, 89) == 1);
  CHECK(tile_at(75, 24) == 2); CHECK(solid(75, 24) == 1);
  CHECK(tile_at(58, 40) == 2); CHECK(solid(58, 40) == 1);
  CHECK(tile_at(6, 13) == 0); CHECK(solid(6, 13) == 0);
  CHECK(tile_at(87, 41) == 3); CHECK(solid(87, 41) == 1);
  CHECK(tile_at(-2, 73) == 1); CHECK(solid(-2, 73) == 1);
  CHECK(tile_at(56, 48) == 0); CHECK(solid(56, 48) == 0);
  CHECK(tile_at(0, 72) == 255); CHECK(solid(0, 72) == 0);
  CHECK(tile_at(78, 14) == 1); CHECK(solid(78, 14) == 1);
  return 0;
}
