// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 32x8 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 32
#define H 8
static const u8 map[W * H] = {
  1, 1, 0, 0, 1, 3, 0, 2, 2, 1, 3, 0, 255, 3, 255, 7, 0, 0, 255, 255, 0, 7, 0, 7, 7, 7, 0, 0, 0, 2, 1, 3,
  0, 0, 0, 255, 3, 0, 1, 0, 0, 2, 3, 255, 0, 2, 0, 1, 1, 0, 255, 1, 3, 0, 3, 7, 0, 1, 0, 2, 255, 0, 0, 7,
  3, 2, 2, 2, 0, 0, 0, 7, 0, 0, 0, 3, 255, 0, 3, 0, 2, 255, 3, 1, 2, 1, 1, 1, 0, 0, 3, 255, 0, 0, 2, 255,
  0, 0, 0, 3, 0, 0, 0, 0, 255, 3, 0, 255, 0, 0, 255, 0, 0, 2, 255, 7, 255, 2, 255, 0, 3, 2, 255, 3, 1, 0, 0, 1,
  7, 0, 1, 2, 3, 0, 255, 255, 0, 0, 3, 2, 7, 7, 7, 2, 0, 0, 1, 0, 3, 1, 7, 255, 2, 0, 3, 1, 2, 7, 2, 3,
  0, 0, 7, 255, 0, 7, 1, 7, 255, 0, 2, 2, 0, 2, 7, 3, 2, 255, 0, 0, 0, 1, 3, 0, 2, 3, 0, 0, 1, 0, 0, 7,
  0, 3, 3, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 0, 3, 2, 1, 0, 1, 0, 3, 3, 7, 2, 0, 1, 0, 0, 0, 2, 0, 1,
  1, 7, 0, 7, 0, 0, 255, 0, 0, 255, 0, 0, 1, 255, 255, 1, 2, 0, 255, 2, 7, 0, 0, 0, 255, 0, 0, 255, 1, 0, 2, 0
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(214, 18) == 3); CHECK(solid(214, 18) == 1);
  CHECK(tile_at(40, 34) == 0); CHECK(solid(40, 34) == 0);
  CHECK(tile_at(0, 10) == 0); CHECK(solid(0, 10) == 0);
  CHECK(tile_at(164, -2) == 1); CHECK(solid(164, -2) == 1);
  CHECK(tile_at(78, 26) == 3); CHECK(solid(78, 26) == 1);
  CHECK(tile_at(-3, 48) == 1); CHECK(solid(-3, 48) == 1);
  CHECK(tile_at(62, 34) == 255); CHECK(solid(62, 34) == 0);
  CHECK(tile_at(92, 67) == 1); CHECK(solid(92, 67) == 1);
  CHECK(tile_at(156, 27) == 7); CHECK(solid(156, 27) == 1);
  CHECK(tile_at(41, 15) == 0); CHECK(solid(41, 15) == 0);
  CHECK(tile_at(-1, 16) == 1); CHECK(solid(-1, 16) == 1);
  CHECK(tile_at(180, -1) == 1); CHECK(solid(180, -1) == 1);
  CHECK(tile_at(85, 24) == 0); CHECK(solid(85, 24) == 0);
  CHECK(tile_at(76, 46) == 0); CHECK(solid(76, 46) == 0);
  CHECK(tile_at(63, 7) == 2); CHECK(solid(63, 7) == 1);
  CHECK(tile_at(79, 6) == 1); CHECK(solid(79, 6) == 1);
  CHECK(tile_at(9, 19) == 2); CHECK(solid(9, 19) == 1);
  CHECK(tile_at(76, 34) == 0); CHECK(solid(76, 34) == 0);
  CHECK(tile_at(0, 27) == 0); CHECK(solid(0, 27) == 0);
  CHECK(tile_at(128, 32) == 0); CHECK(solid(128, 32) == 0);
  CHECK(tile_at(136, 0) == 0); CHECK(solid(136, 0) == 0);
  CHECK(tile_at(8, 18) == 2); CHECK(solid(8, 18) == 1);
  CHECK(tile_at(259, 57) == 1); CHECK(solid(259, 57) == 1);
  CHECK(tile_at(41, 31) == 0); CHECK(solid(41, 31) == 0);
  return 0;
}
