// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 16x14 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 16
#define H 14
static const u8 map[W * H] = {
  0, 1, 1, 3, 0, 1, 7, 0, 0, 0, 255, 7, 2, 0, 0, 0,
  3, 3, 3, 7, 2, 3, 2, 7, 0, 1, 2, 0, 3, 1, 0, 0,
  0, 0, 2, 0, 1, 1, 3, 3, 3, 255, 255, 2, 255, 0, 3, 3,
  7, 3, 1, 2, 7, 2, 0, 0, 1, 3, 0, 0, 2, 2, 2, 0,
  7, 255, 1, 7, 0, 1, 0, 0, 2, 0, 0, 3, 1, 0, 255, 0,
  0, 0, 3, 0, 255, 1, 0, 255, 0, 0, 0, 2, 2, 255, 0, 2,
  7, 255, 0, 1, 1, 255, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1,
  7, 2, 1, 3, 3, 0, 0, 1, 0, 1, 0, 3, 255, 0, 0, 0,
  1, 1, 0, 1, 1, 0, 7, 7, 1, 7, 0, 255, 255, 255, 2, 0,
  0, 255, 0, 3, 1, 1, 3, 255, 255, 1, 255, 0, 1, 3, 255, 7,
  0, 0, 0, 7, 255, 3, 0, 1, 1, 0, 7, 7, 0, 1, 0, 1,
  0, 255, 0, 0, 255, 0, 255, 255, 3, 3, 2, 0, 0, 2, 2, 2,
  0, 7, 3, 3, 0, 0, 1, 7, 0, 0, 3, 0, 2, 0, 0, 3,
  0, 255, 0, 0, 1, 0, 0, 3, 0, 0, 7, 0, 1, 255, 0, 1
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(107, 89) == 2); CHECK(solid(107, 89) == 1);
  CHECK(tile_at(60, 11) == 7); CHECK(solid(60, 11) == 1);
  CHECK(tile_at(43, 34) == 1); CHECK(solid(43, 34) == 1);
  CHECK(tile_at(106, 117) == 1); CHECK(solid(106, 117) == 1);
  CHECK(tile_at(86, 12) == 2); CHECK(solid(86, 12) == 1);
  CHECK(tile_at(48, -2) == 1); CHECK(solid(48, -2) == 1);
  CHECK(tile_at(116, 37) == 255); CHECK(solid(116, 37) == 0);
  CHECK(tile_at(10, 88) == 255); CHECK(solid(10, 88) == 0);
  CHECK(tile_at(103, 95) == 0); CHECK(solid(103, 95) == 0);
  CHECK(tile_at(21, 72) == 0); CHECK(solid(21, 72) == 0);
  CHECK(tile_at(77, 91) == 3); CHECK(solid(77, 91) == 1);
  CHECK(tile_at(55, 76) == 3); CHECK(solid(55, 76) == 1);
  CHECK(tile_at(53, 97) == 1); CHECK(solid(53, 97) == 1);
  CHECK(tile_at(81, 105) == 7); CHECK(solid(81, 105) == 1);
  CHECK(tile_at(97, 79) == 1); CHECK(solid(97, 79) == 1);
  CHECK(tile_at(113, 67) == 2); CHECK(solid(113, 67) == 1);
  CHECK(tile_at(79, 67) == 7); CHECK(solid(79, 67) == 1);
  CHECK(tile_at(19, 54) == 0); CHECK(solid(19, 54) == 0);
  CHECK(tile_at(133, 0) == 1); CHECK(solid(133, 0) == 1);
  CHECK(tile_at(-3, 9) == 1); CHECK(solid(-3, 9) == 1);
  CHECK(tile_at(45, 113) == 1); CHECK(solid(45, 113) == 1);
  CHECK(tile_at(103, 77) == 1); CHECK(solid(103, 77) == 1);
  CHECK(tile_at(50, 115) == 1); CHECK(solid(50, 115) == 1);
  CHECK(tile_at(63, 105) == 3); CHECK(solid(63, 105) == 1);
  return 0;
}
