// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 32x8 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 32
#define H 8
static const u8 map[W * H] = {
  255, 1, 7, 7, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 3, 1, 1, 0, 7, 7, 2, 3, 255, 2, 0, 0, 7, 0, 0, 2, 255, 7,
  0, 1, 255, 2, 0, 7, 7, 0, 255, 2, 7, 0, 0, 1, 255, 255, 0, 0, 0, 0, 0, 3, 0, 0, 255, 1, 0, 255, 255, 3, 3, 7,
  0, 0, 1, 0, 2, 7, 7, 255, 1, 3, 2, 0, 255, 0, 7, 1, 255, 7, 1, 7, 1, 0, 0, 1, 255, 0, 7, 7, 2, 3, 2, 0,
  255, 0, 3, 7, 3, 1, 0, 0, 255, 2, 7, 0, 255, 255, 255, 7, 0, 1, 2, 2, 1, 1, 2, 0, 2, 7, 0, 7, 1, 7, 3, 1,
  0, 3, 3, 0, 0, 255, 0, 3, 0, 255, 0, 0, 0, 255, 0, 255, 7, 0, 1, 2, 7, 1, 0, 0, 0, 2, 2, 2, 1, 255, 1, 0,
  3, 3, 3, 2, 0, 3, 0, 3, 3, 2, 0, 3, 0, 0, 0, 1, 7, 2, 7, 0, 0, 1, 0, 2, 3, 255, 0, 0, 0, 2, 2, 0,
  1, 3, 2, 7, 0, 255, 255, 3, 3, 3, 0, 255, 0, 2, 3, 1, 0, 2, 0, 0, 1, 0, 3, 255, 0, 255, 2, 7, 0, 1, 255, 0,
  0, 0, 7, 0, 255, 255, 0, 0, 0, 0, 7, 0, 2, 7, 7, 1, 255, 1, 7, 2, 7, 0, 0, 0, 0, 0, 2, 0, 0, 255, 3, 3
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(9, 23) == 0); CHECK(solid(9, 23) == 0);
  CHECK(tile_at(211, 43) == 0); CHECK(solid(211, 43) == 0);
  CHECK(tile_at(140, 1) == 0); CHECK(solid(140, 1) == 0);
  CHECK(tile_at(64, 39) == 0); CHECK(solid(64, 39) == 0);
  CHECK(tile_at(241, 7) == 255); CHECK(solid(241, 7) == 0);
  CHECK(tile_at(135, -4) == 1); CHECK(solid(135, -4) == 1);
  CHECK(tile_at(84, 2) == 2); CHECK(solid(84, 2) == 1);
  CHECK(tile_at(64, 9) == 255); CHECK(solid(64, 9) == 0);
  CHECK(tile_at(-4, 68) == 1); CHECK(solid(-4, 68) == 1);
  CHECK(tile_at(138, 25) == 1); CHECK(solid(138, 25) == 1);
  CHECK(tile_at(64, -8) == 1); CHECK(solid(64, -8) == 1);
  CHECK(tile_at(225, 70) == 1); CHECK(solid(225, 70) == 1);
  CHECK(tile_at(167, 67) == 1); CHECK(solid(167, 67) == 1);
  CHECK(tile_at(102, 43) == 0); CHECK(solid(102, 43) == 0);
  CHECK(tile_at(81, 9) == 7); CHECK(solid(81, 9) == 1);
  CHECK(tile_at(75, 56) == 0); CHECK(solid(75, 56) == 0);
  CHECK(tile_at(74, 21) == 3); CHECK(solid(74, 21) == 1);
  CHECK(tile_at(201, 46) == 255); CHECK(solid(201, 46) == 0);
  CHECK(tile_at(181, 55) == 3); CHECK(solid(181, 55) == 1);
  CHECK(tile_at(250, -7) == 1); CHECK(solid(250, -7) == 1);
  CHECK(tile_at(71, 64) == 1); CHECK(solid(71, 64) == 1);
  CHECK(tile_at(178, 57) == 0); CHECK(solid(178, 57) == 0);
  CHECK(tile_at(240, 42) == 2); CHECK(solid(240, 42) == 1);
  CHECK(tile_at(79, 33) == 255); CHECK(solid(79, 33) == 0);
  return 0;
}
