// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 16x14 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 16
#define H 14
static const u8 map[W * H] = {
  255, 0, 3, 1, 3, 1, 2, 7, 0, 2, 255, 1, 3, 0, 7, 255,
  0, 2, 0, 7, 0, 1, 0, 0, 2, 1, 1, 0, 3, 255, 1, 1,
  3, 3, 0, 0, 2, 0, 0, 1, 0, 1, 0, 255, 3, 1, 0, 255,
  1, 3, 0, 0, 3, 0, 0, 2, 0, 2, 7, 7, 255, 3, 3, 255,
  3, 255, 3, 7, 2, 3, 1, 0, 0, 0, 7, 1, 0, 2, 0, 0,
  0, 3, 0, 7, 0, 1, 0, 7, 0, 7, 0, 0, 0, 0, 2, 3,
  1, 0, 0, 7, 7, 0, 7, 2, 7, 2, 1, 2, 0, 1, 1, 255,
  0, 0, 255, 1, 0, 255, 7, 3, 2, 0, 0, 2, 2, 7, 0, 1,
  7, 3, 0, 7, 0, 0, 2, 1, 0, 255, 0, 0, 3, 2, 0, 1,
  1, 2, 7, 255, 1, 3, 7, 7, 1, 7, 2, 0, 7, 7, 0, 255,
  0, 255, 255, 0, 0, 0, 3, 3, 0, 0, 2, 1, 3, 255, 2, 7,
  0, 2, 0, 255, 7, 3, 3, 0, 0, 2, 0, 0, 3, 1, 1, 7,
  0, 7, 1, 7, 255, 2, 0, 2, 255, 0, 2, 7, 3, 0, 7, 0,
  0, 3, 2, 0, 7, 0, 3, 7, 255, 2, 7, 7, 0, 0, 0, 2
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(69, 61) == 2); CHECK(solid(69, 61) == 1);
  CHECK(tile_at(2, 84) == 0); CHECK(solid(2, 84) == 0);
  CHECK(tile_at(-8, 22) == 1); CHECK(solid(-8, 22) == 1);
  CHECK(tile_at(115, 88) == 1); CHECK(solid(115, 88) == 1);
  CHECK(tile_at(5, 19) == 3); CHECK(solid(5, 19) == 1);
  CHECK(tile_at(75, 58) == 0); CHECK(solid(75, 58) == 0);
  CHECK(tile_at(112, 31) == 3); CHECK(solid(112, 31) == 1);
  CHECK(tile_at(0, 4) == 255); CHECK(solid(0, 4) == 0);
  CHECK(tile_at(42, 107) == 0); CHECK(solid(42, 107) == 0);
  CHECK(tile_at(12, 46) == 3); CHECK(solid(12, 46) == 1);
  CHECK(tile_at(70, 58) == 2); CHECK(solid(70, 58) == 1);
  CHECK(tile_at(75, 113) == 1); CHECK(solid(75, 113) == 1);
  CHECK(tile_at(99, 91) == 3); CHECK(solid(99, 91) == 1);
  CHECK(tile_at(15, 4) == 0); CHECK(solid(15, 4) == 0);
  CHECK(tile_at(125, 44) == 3); CHECK(solid(125, 44) == 1);
  CHECK(tile_at(51, 28) == 0); CHECK(solid(51, 28) == 0);
  CHECK(tile_at(105, 32) == 2); CHECK(solid(105, 32) == 1);
  CHECK(tile_at(40, 115) == 1); CHECK(solid(40, 115) == 1);
  CHECK(tile_at(112, -5) == 1); CHECK(solid(112, -5) == 1);
  CHECK(tile_at(70, 14) == 2); CHECK(solid(70, 14) == 1);
  CHECK(tile_at(40, 24) == 0); CHECK(solid(40, 24) == 0);
  CHECK(tile_at(23, 63) == 255); CHECK(solid(23, 63) == 0);
  CHECK(tile_at(9, 65) == 3); CHECK(solid(9, 65) == 1);
  CHECK(tile_at(14, 3) == 0); CHECK(solid(14, 3) == 0);
  return 0;
}
