// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 64x4 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 64
#define H 4
static const u8 map[W * H] = {
  0, 0, 0, 7, 1, 2, 0, 1, 0, 7, 7, 255, 2, 7, 3, 2, 2, 2, 7, 2, 0, 2, 2, 7, 255, 255, 0, 0, 0, 255, 0, 2, 0, 1, 0, 255, 3, 1, 0, 0, 1, 3, 2, 0, 0, 2, 0, 7, 1, 0, 3, 3, 255, 255, 0, 1, 7, 0, 1, 0, 0, 0, 0, 0,
  1, 0, 2, 0, 0, 3, 3, 1, 2, 3, 0, 0, 0, 7, 0, 0, 0, 3, 7, 7, 2, 1, 0, 2, 0, 3, 1, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 1, 1, 255, 3, 7, 1, 1, 1, 0, 7, 255, 1, 7, 0, 0, 1, 3, 1, 0, 255, 7, 1, 0, 0, 255, 0, 7,
  0, 0, 255, 0, 0, 7, 7, 2, 255, 2, 1, 2, 0, 0, 255, 7, 7, 1, 7, 2, 2, 0, 0, 1, 7, 0, 1, 255, 1, 1, 1, 3, 7, 7, 1, 0, 1, 3, 255, 0, 3, 255, 0, 3, 7, 0, 3, 3, 2, 0, 1, 0, 3, 255, 0, 0, 0, 1, 7, 0, 0, 3, 0, 255,
  255, 0, 255, 7, 255, 3, 2, 255, 3, 3, 0, 2, 255, 1, 0, 0, 255, 0, 0, 1, 0, 255, 255, 3, 255, 0, 2, 3, 255, 0, 255, 0, 0, 3, 1, 255, 3, 3, 0, 0, 0, 0, 7, 0, 1, 7, 0, 0, 2, 0, 0, 7, 2, 0, 7, 0, 7, 0, 1, 255, 2, 1, 0, 255
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(478, 12) == 0); CHECK(solid(478, 12) == 0);
  CHECK(tile_at(74, 7) == 7); CHECK(solid(74, 7) == 1);
  CHECK(tile_at(24, 12) == 0); CHECK(solid(24, 12) == 0);
  CHECK(tile_at(-3, -7) == 1); CHECK(solid(-3, -7) == 1);
  CHECK(tile_at(373, 4) == 0); CHECK(solid(373, 4) == 0);
  CHECK(tile_at(435, 36) == 1); CHECK(solid(435, 36) == 1);
  CHECK(tile_at(251, 31) == 0); CHECK(solid(251, 31) == 0);
  CHECK(tile_at(15, 38) == 1); CHECK(solid(15, 38) == 1);
  CHECK(tile_at(150, 27) == 0); CHECK(solid(150, 27) == 0);
  CHECK(tile_at(460, 24) == 0); CHECK(solid(460, 24) == 0);
  CHECK(tile_at(255, 14) == 255); CHECK(solid(255, 14) == 0);
  CHECK(tile_at(443, 23) == 0); CHECK(solid(443, 23) == 0);
  CHECK(tile_at(201, 19) == 0); CHECK(solid(201, 19) == 0);
  CHECK(tile_at(414, 34) == 1); CHECK(solid(414, 34) == 1);
  CHECK(tile_at(420, 9) == 1); CHECK(solid(420, 9) == 1);
  CHECK(tile_at(42, 17) == 7); CHECK(solid(42, 17) == 1);
  CHECK(tile_at(238, 28) == 0); CHECK(solid(238, 28) == 0);
  CHECK(tile_at(157, 31) == 1); CHECK(solid(157, 31) == 1);
  CHECK(tile_at(275, -7) == 1); CHECK(solid(275, -7) == 1);
  CHECK(tile_at(434, -3) == 1); CHECK(solid(434, -3) == 1);
  CHECK(tile_at(261, 38) == 1); CHECK(solid(261, 38) == 1);
  CHECK(tile_at(166, -8) == 1); CHECK(solid(166, -8) == 1);
  CHECK(tile_at(118, 30) == 0); CHECK(solid(118, 30) == 0);
  CHECK(tile_at(193, 22) == 7); CHECK(solid(193, 22) == 1);
  return 0;
}
