// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A 20x10 tilemap in ROM read at s16 pixel coordinates; outside the map is solid.
#include "loomcc-test.h"
#define W 20
#define H 10
static const u8 map[W * H] = {
  0, 0, 0, 1, 2, 0, 7, 255, 0, 255, 2, 0, 0, 255, 0, 0, 7, 0, 7, 1,
  0, 0, 1, 7, 0, 3, 0, 1, 255, 255, 3, 3, 2, 255, 7, 0, 0, 1, 3, 3,
  1, 2, 7, 0, 255, 0, 0, 3, 1, 0, 255, 3, 3, 1, 2, 255, 3, 7, 0, 0,
  0, 3, 2, 3, 255, 255, 2, 7, 7, 255, 3, 0, 255, 0, 0, 7, 0, 255, 255, 7,
  0, 7, 0, 1, 0, 3, 0, 7, 2, 3, 255, 0, 255, 0, 1, 1, 2, 255, 3, 0,
  3, 0, 1, 7, 1, 7, 0, 3, 2, 0, 0, 0, 7, 7, 2, 0, 0, 0, 7, 0,
  7, 2, 0, 0, 0, 0, 1, 1, 0, 3, 3, 255, 2, 0, 7, 255, 7, 0, 3, 2,
  0, 1, 3, 7, 2, 0, 0, 255, 1, 0, 0, 7, 0, 0, 0, 1, 1, 3, 0, 0,
  255, 0, 7, 255, 7, 2, 0, 7, 3, 0, 2, 0, 7, 0, 3, 0, 0, 0, 2, 0,
  2, 0, 0, 0, 1, 7, 0, 2, 3, 0, 1, 0, 0, 7, 7, 3, 0, 3, 0, 7
};
static u8 tile_at(i16 px, i16 py) {
  if (px < 0 || py < 0 || px >= W * 8 || py >= H * 8) return 1;
  return map[(u16)(py >> 3) * W + (u16)(px >> 3)];
}
static u8 solid(i16 px, i16 py) { u8 t = tile_at(px, py); return t != 0 && t != 255; }
int main(void) {
  CHECK(tile_at(76, 46) == 0); CHECK(solid(76, 46) == 0);
  CHECK(tile_at(151, -4) == 1); CHECK(solid(151, -4) == 1);
  CHECK(tile_at(167, 41) == 1); CHECK(solid(167, 41) == 1);
  CHECK(tile_at(159, 72) == 7); CHECK(solid(159, 72) == 1);
  CHECK(tile_at(51, 34) == 0); CHECK(solid(51, 34) == 0);
  CHECK(tile_at(136, 20) == 7); CHECK(solid(136, 20) == 1);
  CHECK(tile_at(25, 65) == 255); CHECK(solid(25, 65) == 0);
  CHECK(tile_at(25, 51) == 0); CHECK(solid(25, 51) == 0);
  CHECK(tile_at(67, 84) == 1); CHECK(solid(67, 84) == 1);
  CHECK(tile_at(96, 72) == 0); CHECK(solid(96, 72) == 0);
  CHECK(tile_at(146, 17) == 0); CHECK(solid(146, 17) == 0);
  CHECK(tile_at(167, 2) == 1); CHECK(solid(167, 2) == 1);
  CHECK(tile_at(98, -1) == 1); CHECK(solid(98, -1) == 1);
  CHECK(tile_at(64, -6) == 1); CHECK(solid(64, -6) == 1);
  CHECK(tile_at(67, 37) == 2); CHECK(solid(67, 37) == 1);
  CHECK(tile_at(112, 15) == 7); CHECK(solid(112, 15) == 1);
  CHECK(tile_at(84, 8) == 3); CHECK(solid(84, 8) == 1);
  CHECK(tile_at(145, 40) == 7); CHECK(solid(145, 40) == 1);
  CHECK(tile_at(141, 7) == 0); CHECK(solid(141, 7) == 0);
  CHECK(tile_at(60, 39) == 7); CHECK(solid(60, 39) == 1);
  CHECK(tile_at(49, 56) == 0); CHECK(solid(49, 56) == 0);
  CHECK(tile_at(71, 35) == 2); CHECK(solid(71, 35) == 1);
  CHECK(tile_at(155, 5) == 1); CHECK(solid(155, 5) == 1);
  CHECK(tile_at(102, 1) == 0); CHECK(solid(102, 1) == 0);
  return 0;
}
