// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A chain of 7 calls with argument types [['i32', 'u8'], ['i16', 'i32', 'u8'], ['u16'], ['u8'], ['i32', 'u16', 'u8'], ['i32', 'u8', 'u16'], ['i8']].
#include "loomcc-test.h"
static i32 f6(i8 a0) { return (i32)a0; }
static i32 f5(i32 a0, u8 a1, u16 a2) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2; i32 rest = f6((i8)(a0 + 1)); return keep + keep + rest; }
static i32 f4(i32 a0, u16 a1, u8 a2) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2; i32 rest = f5((i32)(a0 + 1), (u8)(a0 + 2), (u16)(a0 + 3)); return keep + keep + rest; }
static i32 f3(u8 a0) { i32 keep = (i32)a0; i32 rest = f4((i32)(a0 + 1), (u16)(a0 + 2), (u8)(a0 + 3)); return keep + keep + rest; }
static i32 f2(u16 a0) { i32 keep = (i32)a0; i32 rest = f3((u8)(a0 + 1)); return keep + keep + rest; }
static i32 f1(i16 a0, i32 a1, u8 a2) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2; i32 rest = f2((u16)(a0 + 1)); return keep + keep + rest; }
static i32 f0(i32 a0, u8 a1) { i32 keep = (i32)a0 + (i32)a1; i32 rest = f1((i16)(a0 + 1), (i32)(a0 + 2), (u8)(a0 + 3)); return keep + keep + rest; }
int main(void) {
  CHECK(f0((i32)(-56), (u8)(162)) == (i32)134186LL);
  return 0;
}
