// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A chain of 2 calls with argument types [['i16', 'i8', 'i32', 'u8'], ['i8', 'i32', 'u8']].
#include "loomcc-test.h"
static i32 f1(i8 a0, i32 a1, u8 a2) { return (i32)a0 + (i32)a1 + (i32)a2; }
static i32 f0(i16 a0, i8 a1, i32 a2, u8 a3) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2 + (i32)a3; i32 rest = f1((i8)(a0 + 1), (i32)(a0 + 2), (u8)(a0 + 3)); return keep + keep + rest; }
int main(void) {
  CHECK(f0((i16)(-221), (i8)(25), (i32)(-242), (u8)(101)) == (i32)-819LL);
  return 0;
}
