// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A chain of 5 calls with argument types [['u8', 'u16'], ['u8', 'i32', 'i16', 'u16'], ['i8', 'i16'], ['u8', 'i32', 'i16', 'u16'], ['i8', 'u8', 'i16', 'u16']].
#include "loomcc-test.h"
static i32 f4(i8 a0, u8 a1, i16 a2, u16 a3) { return (i32)a0 + (i32)a1 + (i32)a2 + (i32)a3; }
static i32 f3(u8 a0, i32 a1, i16 a2, u16 a3) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2 + (i32)a3; i32 rest = f4((i8)(a0 + 1), (u8)(a0 + 2), (i16)(a0 + 3), (u16)(a0 + 4)); return keep + keep + rest; }
static i32 f2(i8 a0, i16 a1) { i32 keep = (i32)a0 + (i32)a1; i32 rest = f3((u8)(a0 + 1), (i32)(a0 + 2), (i16)(a0 + 3), (u16)(a0 + 4)); return keep + keep + rest; }
static i32 f1(u8 a0, i32 a1, i16 a2, u16 a3) { i32 keep = (i32)a0 + (i32)a1 + (i32)a2 + (i32)a3; i32 rest = f2((i8)(a0 + 1), (i16)(a0 + 2)); return keep + keep + rest; }
static i32 f0(u8 a0, u16 a1) { i32 keep = (i32)a0 + (i32)a1; i32 rest = f1((u8)(a0 + 1), (i32)(a0 + 2), (i16)(a0 + 3), (u16)(a0 + 4)); return keep + keep + rest; }
int main(void) {
  CHECK(f0((u8)(72), (u16)(65396)) == (i32)132752LL);
  return 0;
}
