// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A chain of 4 calls with argument types [['i16', 'i32'], ['u8'], ['i32', 'i16'], ['i32', 'u8', 'i16']].
#include "loomcc-test.h"
static i32 f3(i32 a0, u8 a1, i16 a2) { return (i32)a0 + (i32)a1 + (i32)a2; }
static i32 f2(i32 a0, i16 a1) { i32 keep = (i32)a0 + (i32)a1; i32 rest = f3((i32)(a0 + 1), (u8)(a0 + 2), (i16)(a0 + 3)); return keep + keep + rest; }
static i32 f1(u8 a0) { i32 keep = (i32)a0; i32 rest = f2((i32)(a0 + 1), (i16)(a0 + 2)); return keep + keep + rest; }
static i32 f0(i16 a0, i32 a1) { i32 keep = (i32)a0 + (i32)a1; i32 rest = f1((u8)(a0 + 1)); return keep + keep + rest; }
int main(void) {
  CHECK(f0((i16)(161), (i32)(218)) == (i32)2231LL);
  return 0;
}
