// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// u8 << (u8, i8, u16, i16) at run time: the operands promote to int or
// unsigned int (16 bits) and the usual arithmetic conversions apply.
#include "loomcc-test.h"
static volatile u8 x_u8;
static volatile i8 x_i8;
static volatile u16 x_u16;
static volatile i16 x_i16;
static volatile u8 y_u8;
static volatile i8 y_i8;
static volatile u16 y_u16;
static volatile i16 y_i16;
static void part0(void) {
  x_u8 = 0; y_u8 = 0; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 0; y_u8 = 1; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 0; y_u8 = 3; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 0; y_u8 = 7; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 0; y_u8 = 8; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 0; y_u8 = 15; CHECK((x_u8 << y_u8) == (0));
  x_u8 = 1; y_u8 = 0; CHECK((x_u8 << y_u8) == (1));
  x_u8 = 1; y_u8 = 1; CHECK((x_u8 << y_u8) == (2));
  x_u8 = 1; y_u8 = 3; CHECK((x_u8 << y_u8) == (8));
  x_u8 = 1; y_u8 = 7; CHECK((x_u8 << y_u8) == (128));
  x_u8 = 1; y_u8 = 8; CHECK((x_u8 << y_u8) == (256));
  x_u8 = 2; y_u8 = 0; CHECK((x_u8 << y_u8) == (2));
  x_u8 = 2; y_u8 = 1; CHECK((x_u8 << y_u8) == (4));
  x_u8 = 2; y_u8 = 3; CHECK((x_u8 << y_u8) == (16));
  x_u8 = 2; y_u8 = 7; CHECK((x_u8 << y_u8) == (256));
  x_u8 = 2; y_u8 = 8; CHECK((x_u8 << y_u8) == (512));
  x_u8 = 7; y_u8 = 0; CHECK((x_u8 << y_u8) == (7));
  x_u8 = 7; y_u8 = 1; CHECK((x_u8 << y_u8) == (14));
  x_u8 = 7; y_u8 = 3; CHECK((x_u8 << y_u8) == (56));
  x_u8 = 7; y_u8 = 7; CHECK((x_u8 << y_u8) == (896));
  x_u8 = 7; y_u8 = 8; CHECK((x_u8 << y_u8) == (1792));
  x_u8 = 100; y_u8 = 0; CHECK((x_u8 << y_u8) == (100));
  x_u8 = 100; y_u8 = 1; CHECK((x_u8 << y_u8) == (200));
  x_u8 = 100; y_u8 = 3; CHECK((x_u8 << y_u8) == (800));
  x_u8 = 100; y_u8 = 7; CHECK((x_u8 << y_u8) == (12800));
  x_u8 = 100; y_u8 = 8; CHECK((x_u8 << y_u8) == (25600));
  x_u8 = 127; y_u8 = 0; CHECK((x_u8 << y_u8) == (127));
  x_u8 = 127; y_u8 = 1; CHECK((x_u8 << y_u8) == (254));
  x_u8 = 127; y_u8 = 3; CHECK((x_u8 << y_u8) == (1016));
  x_u8 = 127; y_u8 = 7; CHECK((x_u8 << y_u8) == (16256));
  x_u8 = 127; y_u8 = 8; CHECK((x_u8 << y_u8) == (32512));
  x_u8 = 128; y_u8 = 0; CHECK((x_u8 << y_u8) == (128));
}
static void part1(void) {
  x_u8 = 128; y_u8 = 1; CHECK((x_u8 << y_u8) == (256));
  x_u8 = 128; y_u8 = 3; CHECK((x_u8 << y_u8) == (1024));
  x_u8 = 128; y_u8 = 7; CHECK((x_u8 << y_u8) == (16384));
  x_u8 = 200; y_u8 = 0; CHECK((x_u8 << y_u8) == (200));
  x_u8 = 200; y_u8 = 1; CHECK((x_u8 << y_u8) == (400));
  x_u8 = 200; y_u8 = 3; CHECK((x_u8 << y_u8) == (1600));
  x_u8 = 200; y_u8 = 7; CHECK((x_u8 << y_u8) == (25600));
  x_u8 = 255; y_u8 = 0; CHECK((x_u8 << y_u8) == (255));
  x_u8 = 255; y_u8 = 1; CHECK((x_u8 << y_u8) == (510));
  x_u8 = 255; y_u8 = 3; CHECK((x_u8 << y_u8) == (2040));
  x_u8 = 255; y_u8 = 7; CHECK((x_u8 << y_u8) == (32640));
}
int main(void) {
  part0();
  part1();
  return 0;
}
