// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: 16
// u16 >> (u8, i8, u16, i16) at run time: the operands promote to int or
// unsigned int (16 bits) and the usual arithmetic conversions apply.
#include "loomcc-test.h"
static volatile u8 x_u8;
static volatile i8 x_i8;
static volatile u16 x_u16;
static volatile i16 x_i16;
static volatile u8 y_u8;
static volatile i8 y_i8;
static volatile u16 y_u16;
static volatile i16 y_i16;
static void part0(void) {
  x_u16 = 0u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 0u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 0u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 0u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 0u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 0u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 1u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 2u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 2u);
  x_u16 = 2u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 2u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 2u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 2u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 2u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 255u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 255u);
  x_u16 = 255u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 127u);
  x_u16 = 255u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 31u);
  x_u16 = 255u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 255u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 255u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 256u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 256u);
  x_u16 = 256u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 128u);
  x_u16 = 256u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 32u);
  x_u16 = 256u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 2u);
  x_u16 = 256u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 256u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 1000u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 1000u);
  x_u16 = 1000u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 500u);
}
static void part1(void) {
  x_u16 = 1000u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 125u);
  x_u16 = 1000u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 7u);
  x_u16 = 1000u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 3u);
  x_u16 = 1000u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 32767u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 32767u);
  x_u16 = 32767u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 16383u);
  x_u16 = 32767u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 4095u);
  x_u16 = 32767u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 255u);
  x_u16 = 32767u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 127u);
  x_u16 = 32767u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 0u);
  x_u16 = 32768u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 32768u);
  x_u16 = 32768u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 16384u);
  x_u16 = 32768u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 4096u);
  x_u16 = 32768u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 256u);
  x_u16 = 32768u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 128u);
  x_u16 = 32768u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 40000u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 40000u);
  x_u16 = 40000u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 20000u);
  x_u16 = 40000u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 5000u);
  x_u16 = 40000u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 312u);
  x_u16 = 40000u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 156u);
  x_u16 = 40000u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 1u);
  x_u16 = 65535u; y_u8 = 0; CHECK((x_u16 >> y_u8) == 65535u);
  x_u16 = 65535u; y_u8 = 1; CHECK((x_u16 >> y_u8) == 32767u);
  x_u16 = 65535u; y_u8 = 3; CHECK((x_u16 >> y_u8) == 8191u);
  x_u16 = 65535u; y_u8 = 7; CHECK((x_u16 >> y_u8) == 511u);
  x_u16 = 65535u; y_u8 = 8; CHECK((x_u16 >> y_u8) == 255u);
  x_u16 = 65535u; y_u8 = 15; CHECK((x_u16 >> y_u8) == 1u);
}
int main(void) {
  part0();
  part1();
  return 0;
}
