// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Pointer walks over a const ROM table of 9 records (u8, i16, u8):
// by pointer increment to an end pointer, by index, and backwards.
#include "loomcc-test.h"
typedef struct {
  u8 f0;
  i16 f1;
  u8 f2;
} Rec;
static const Rec table[9] = {
  { 253, 32018, 198 },
  { 9, 32380, 138 },
  { 203, -12339, 236 },
  { 13, -14792, 139 },
  { 168, 17888, 149 },
  { 178, 17033, 188 },
  { 140, 27153, 39 },
  { 191, 21521, 243 },
  { 106, 25768, 172 }
};
static const Rec *const table_end = table + 9;
static i32 sum_forward(u8 field) {
  const Rec *p;
  i32 s = 0;
  for (p = table; p != table_end; p++) {
    switch (field) {
    case 0: s += p->f0; break;
    case 1: s += p->f1; break;
    case 2: s += p->f2; break;
    }
  }
  return s;
}
static const Rec *last_max(void) {
  const Rec *p = table_end, *best = table;
  while (p != table) {
    p--;
    if (p->f2 > best->f2) best = p;
  }
  return best;
}
int main(void) {
  u8 i;
  CHECK(sum_forward(0) == (i32)1261LL);
  CHECK(sum_forward(1) == (i32)146630LL);
  CHECK(sum_forward(2) == (i32)1502LL);
  for (i = 0; i < 9; i++) CHECK(&table[i] - table == i);
  CHECK(table_end - table == 9);
  CHECK(last_max() - table == 7);
  return 0;
}
