// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Pointer walks over a const ROM table of 16 records (i16, i16):
// by pointer increment to an end pointer, by index, and backwards.
#include "loomcc-test.h"
typedef struct {
  i16 f0;
  i16 f1;
} Rec;
static const Rec table[16] = {
  { 23511, 25505 },
  { -15607, -26674 },
  { 2527, -18495 },
  { -11454, 21452 },
  { 18797, -31258 },
  { 8237, -22340 },
  { -26337, 143 },
  { -21548, 8353 },
  { -25210, -19260 },
  { -25720, -2824 },
  { -24445, 23918 },
  { -2762, -3900 },
  { 22784, 7171 },
  { -32258, 2697 },
  { -18959, -12845 },
  { 2068, -10940 }
};
static const Rec *const table_end = table + 16;
static i32 sum_forward(u8 field) {
  const Rec *p;
  i32 s = 0;
  for (p = table; p != table_end; p++) {
    switch (field) {
    case 0: s += p->f0; break;
    case 1: s += p->f1; break;
    }
  }
  return s;
}
static const Rec *last_max(void) {
  const Rec *p = table_end, *best = table;
  while (p != table) {
    p--;
    if (p->f1 > best->f1) best = p;
  }
  return best;
}
int main(void) {
  u8 i;
  CHECK(sum_forward(0) == (i32)-126376LL);
  CHECK(sum_forward(1) == (i32)-59297LL);
  for (i = 0; i < 16; i++) CHECK(&table[i] - table == i);
  CHECK(table_end - table == 16);
  CHECK(last_max() - table == 0);
  return 0;
}
