// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 8.8 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 32, vmax = 566;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(20992); b.vel = -272;
  for (s = 0; s < 32; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((19984))); CHECK(b.vel == -48); CHECK((b.pos >> 8) == ((78))); }
    if (s == 13) { CHECK(b.pos == ((20544))); CHECK(b.vel == 176); CHECK((b.pos >> 8) == ((80))); }
    if (s == 20) { CHECK(b.pos == ((22672))); CHECK(b.vel == 400); CHECK((b.pos >> 8) == ((88))); }
    if (s == 27) { CHECK(b.pos == ((26284))); CHECK(b.vel == 566); CHECK((b.pos >> 8) == ((102))); }
  }
  return 0;
}
