// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 27, vmax = 617;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(19232); b.vel = -36;
  for (s = 0; s < 24; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((19736))); CHECK(b.vel == 153); CHECK((b.pos >> 4) == ((1233))); }
    if (s == 13) { CHECK(b.pos == ((21563))); CHECK(b.vel == 342); CHECK((b.pos >> 4) == ((1347))); }
    if (s == 20) { CHECK(b.pos == ((24713))); CHECK(b.vel == 531); CHECK((b.pos >> 4) == ((1544))); }
  }
  return 0;
}
