// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 28, vmax = 1025;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(-9888); b.vel = -273;
  for (s = 0; s < 19; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((-11015))); CHECK(b.vel == -77); CHECK((b.pos >> 4) == ((-689))); }
    if (s == 13) { CHECK(b.pos == ((-10770))); CHECK(b.vel == 119); CHECK((b.pos >> 4) == ((-674))); }
  }
  return 0;
}
