// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 7, vmax = 678;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(-4288); b.vel = -118;
  for (s = 0; s < 32; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((-4918))); CHECK(b.vel == -69); CHECK((b.pos >> 4) == ((-308))); }
    if (s == 13) { CHECK(b.pos == ((-5205))); CHECK(b.vel == -20); CHECK((b.pos >> 4) == ((-326))); }
    if (s == 20) { CHECK(b.pos == ((-5149))); CHECK(b.vel == 29); CHECK((b.pos >> 4) == ((-322))); }
    if (s == 27) { CHECK(b.pos == ((-4750))); CHECK(b.vel == 78); CHECK((b.pos >> 4) == ((-297))); }
  }
  return 0;
}
