// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 6, vmax = 1070;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(3344); b.vel = 94;
  for (s = 0; s < 29; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((4170))); CHECK(b.vel == 136); CHECK((b.pos >> 4) == ((260))); }
    if (s == 13) { CHECK(b.pos == ((5290))); CHECK(b.vel == 178); CHECK((b.pos >> 4) == ((330))); }
    if (s == 20) { CHECK(b.pos == ((6704))); CHECK(b.vel == 220); CHECK((b.pos >> 4) == ((419))); }
    if (s == 27) { CHECK(b.pos == ((8412))); CHECK(b.vel == 262); CHECK((b.pos >> 4) == ((525))); }
  }
  return 0;
}
