// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 35, vmax = 576;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(-20160); b.vel = -241;
  for (s = 0; s < 40; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((-20867))); CHECK(b.vel == 4); CHECK((b.pos >> 4) == ((-1305))); }
    if (s == 13) { CHECK(b.pos == ((-19859))); CHECK(b.vel == 249); CHECK((b.pos >> 4) == ((-1242))); }
    if (s == 20) { CHECK(b.pos == ((-17136))); CHECK(b.vel == 494); CHECK((b.pos >> 4) == ((-1071))); }
    if (s == 27) { CHECK(b.pos == ((-13163))); CHECK(b.vel == 576); CHECK((b.pos >> 4) == ((-823))); }
    if (s == 34) { CHECK(b.pos == ((-9131))); CHECK(b.vel == 576); CHECK((b.pos >> 4) == ((-571))); }
  }
  return 0;
}
