// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 12.4 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 8, vmax = 836;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(-6208); b.vel = -78;
  for (s = 0; s < 32; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((-6530))); CHECK(b.vel == -22); CHECK((b.pos >> 4) == ((-409))); }
    if (s == 13) { CHECK(b.pos == ((-6460))); CHECK(b.vel == 34); CHECK((b.pos >> 4) == ((-404))); }
    if (s == 20) { CHECK(b.pos == ((-5998))); CHECK(b.vel == 90); CHECK((b.pos >> 4) == ((-375))); }
    if (s == 27) { CHECK(b.pos == ((-5144))); CHECK(b.vel == 146); CHECK((b.pos >> 4) == ((-322))); }
  }
  return 0;
}
