// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Subpixel motion: position in 8.8 fixed point (s16), velocity
// clamped to a maximum, integer part by an arithmetic shift.
#include "loomcc-test.h"
typedef struct { i16 pos; i16 vel; } Body;
static Body b;
static volatile i16 grav = 24, vmax = 979;
static void tick(Body *p) {
  p->vel = (i16)(p->vel + grav);
  if (p->vel > vmax) p->vel = vmax;
  p->pos = (i16)(p->pos + p->vel);
}
int main(void) {
  u8 s;
  b.pos = (i16)(15360); b.vel = 26;
  for (s = 0; s < 50; s++) {
    tick(&b);
    if (s == 6) { CHECK(b.pos == ((16214))); CHECK(b.vel == 194); CHECK((b.pos >> 8) == ((63))); }
    if (s == 13) { CHECK(b.pos == ((18244))); CHECK(b.vel == 362); CHECK((b.pos >> 8) == ((71))); }
    if (s == 20) { CHECK(b.pos == ((21450))); CHECK(b.vel == 530); CHECK((b.pos >> 8) == ((83))); }
    if (s == 27) { CHECK(b.pos == ((25832))); CHECK(b.vel == 698); CHECK((b.pos >> 8) == ((100))); }
    if (s == 34) { CHECK(b.pos == ((31390))); CHECK(b.vel == 866); CHECK((b.pos >> 8) == ((122))); }
    if (s == 41) { CHECK(b.pos == ((-27505))); CHECK(b.vel == 979); CHECK((b.pos >> 8) == ((-108))); }
    if (s == 48) { CHECK(b.pos == ((-20652))); CHECK(b.vel == 979); CHECK((b.pos >> 8) == ((-81))); }
  }
  return 0;
}
