// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 1x256 table of i8 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const i8 lut[1][256] = {
  { 37, -44, -89, -78, -87, -12, 30, 120, 26, -127, 108, 91, -15, 19, 16, -25, -79, -28, -62, 3, 127, 54, -91, -21, 98, -87, -68, 110, -108, 113, -111, 46, -57, 84, -62, -53, 126, -69, 58, 37, 4, 71, -123, -112, 104, -120, -46, 23, -77, -46, 3, 79, -102, -48, -100, 67, -8, 10, -5, -57, -102, -29, -16, 75, -48, -98, -77, 15, 27, 47, -117, -53, -79, 16, 88, -54, 123, -102, 91, -80, -96, 17, -32, 3, 119, 89, -11, 28, 26, -75, 37, 94, 84, 11, 120, -51, -63, -96, -82, 110, 75, -42, -3, -89, -68, -118, 3, 26, 25, 111, 61, 31, 96, -42, -96, 1, -94, -76, 81, 27, -72, 23, -70, -47, 95, -82, 26, 81, 54, 80, -15, -98, -28, 111, 45, -109, -66, 121, 42, 15, 71, -61, 109, 35, 123, -71, -44, 101, -32, -106, -95, -88, 76, -6, -109, -64, -47, 50, -14, 62, -74, -89, -59, -13, 71, 83, -84, -105, -61, -104, 64, -24, 24, 110, 94, 68, 86, -44, -35, -49, 39, -71, 3, 103, 26, 122, 69, -116, -49, -5, -46, -112, 84, 46, -5, 31, 83, 100, -5, -112, -26, -93, -51, -47, 78, -83, 48, 30, 96, 88, -21, -97, -23, 6, 63, -37, 103, -53, -29, 4, -28, 33, -54, -99, -97, 4, 63, -84, 115, -96, -42, 102, 94, -80, -87, -76, 103, -83, 43, 84, 0, 103, 30, 89, 78, -52, -1, 49, 90, 76, -103, -98, 118, -1, 58, -71 }
};
static const i8 *const rowp[1] = { lut[0] };
static volatile u8 vi, vj;
static i32 row_sum(const i8 *row) { u16 j; i32 s = 0; for (j = 0; j < 256; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 0; vj = 255; CHECK(lut[vi][vj] == (i8)(-71)); CHECK(rowp[vi][vj] == (i8)(-71));
  vi = 0; vj = 164; CHECK(lut[vi][vj] == (i8)(71)); CHECK(rowp[vi][vj] == (i8)(71));
  vi = 0; vj = 6; CHECK(lut[vi][vj] == (i8)(30)); CHECK(rowp[vi][vj] == (i8)(30));
  vi = 0; vj = 17; CHECK(lut[vi][vj] == (i8)(-28)); CHECK(rowp[vi][vj] == (i8)(-28));
  vi = 0; vj = 215; CHECK(lut[vi][vj] == (i8)(-37)); CHECK(rowp[vi][vj] == (i8)(-37));
  vi = 0; vj = 206; CHECK(lut[vi][vj] == (i8)(48)); CHECK(rowp[vi][vj] == (i8)(48));
  vi = 0; vj = 20; CHECK(lut[vi][vj] == (i8)(127)); CHECK(rowp[vi][vj] == (i8)(127));
  vi = 0; vj = 23; CHECK(lut[vi][vj] == (i8)(-21)); CHECK(rowp[vi][vj] == (i8)(-21));
  vi = 0; vj = 149; CHECK(lut[vi][vj] == (i8)(-106)); CHECK(rowp[vi][vj] == (i8)(-106));
  vi = 0; vj = 103; CHECK(lut[vi][vj] == (i8)(-89)); CHECK(rowp[vi][vj] == (i8)(-89));
  vi = 0; vj = 52; CHECK(lut[vi][vj] == (i8)(-102)); CHECK(rowp[vi][vj] == (i8)(-102));
  vi = 0; vj = 52; CHECK(lut[vi][vj] == (i8)(-102)); CHECK(rowp[vi][vj] == (i8)(-102));
  vi = 0; vj = 177; CHECK(lut[vi][vj] == (i8)(-44)); CHECK(rowp[vi][vj] == (i8)(-44));
  vi = 0; vj = 32; CHECK(lut[vi][vj] == (i8)(-57)); CHECK(rowp[vi][vj] == (i8)(-57));
  vi = 0; vj = 51; CHECK(lut[vi][vj] == (i8)(79)); CHECK(rowp[vi][vj] == (i8)(79));
  vi = 0; vj = 11; CHECK(lut[vi][vj] == (i8)(91)); CHECK(rowp[vi][vj] == (i8)(91));
  vi = 0; vj = 127; CHECK(lut[vi][vj] == (i8)(81)); CHECK(rowp[vi][vj] == (i8)(81));
  vi = 0; vj = 247; CHECK(lut[vi][vj] == (i8)(49)); CHECK(rowp[vi][vj] == (i8)(49));
  vi = 0; vj = 246; CHECK(lut[vi][vj] == (i8)(-1)); CHECK(rowp[vi][vj] == (i8)(-1));
  vi = 0; vj = 64; CHECK(lut[vi][vj] == (i8)(-48)); CHECK(rowp[vi][vj] == (i8)(-48));
  vi = 0; vj = 189; CHECK(lut[vi][vj] == (i8)(-5)); CHECK(rowp[vi][vj] == (i8)(-5));
  vi = 0; vj = 77; CHECK(lut[vi][vj] == (i8)(-102)); CHECK(rowp[vi][vj] == (i8)(-102));
  vi = 0; vj = 173; CHECK(lut[vi][vj] == (i8)(110)); CHECK(rowp[vi][vj] == (i8)(110));
  vi = 0; vj = 182; CHECK(lut[vi][vj] == (i8)(3)); CHECK(rowp[vi][vj] == (i8)(3));
  for (i = 0; i < 1; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)-609LL);
  }
  return 0;
}
