// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const 8x8 table of i16 in ROM, read through u8 indices, a row
// pointer, and a table of row pointers.
#include "loomcc-test.h"
static const i16 lut[8][8] = {
  { -217, -5246, -30498, -18398, 12947, 26867, 15737, 3082 },
  { -16218, 31844, 26351, -14695, 28471, 2506, -27, -12851 },
  { -4414, 28567, -1261, -29075, -3585, -10087, 9463, 21327 },
  { 19119, -27507, 17861, 17702, -32515, -6885, -15372, -3573 },
  { -16785, 27220, 11119, -32141, 26841, 8576, 32678, 32248 },
  { 26306, -7985, -32477, 29451, 30639, 23155, 14659, 27860 },
  { 28570, -17426, 11214, 7157, -9809, -6070, -9321, -6760 },
  { 5181, -10742, 7151, -286, 9480, -21861, -26889, 12230 }
};
static const i16 *const rowp[8] = { lut[0], lut[1], lut[2], lut[3], lut[4], lut[5], lut[6], lut[7] };
static volatile u8 vi, vj;
static i32 row_sum(const i16 *row) { u16 j; i32 s = 0; for (j = 0; j < 8; j++) s += row[j]; return s; }
int main(void) {
  u8 i;
  vi = 5; vj = 2; CHECK(lut[vi][vj] == (i16)(-32477)); CHECK(rowp[vi][vj] == (i16)(-32477));
  vi = 1; vj = 3; CHECK(lut[vi][vj] == (i16)(-14695)); CHECK(rowp[vi][vj] == (i16)(-14695));
  vi = 3; vj = 2; CHECK(lut[vi][vj] == (i16)(17861)); CHECK(rowp[vi][vj] == (i16)(17861));
  vi = 3; vj = 5; CHECK(lut[vi][vj] == (i16)(-6885)); CHECK(rowp[vi][vj] == (i16)(-6885));
  vi = 3; vj = 2; CHECK(lut[vi][vj] == (i16)(17861)); CHECK(rowp[vi][vj] == (i16)(17861));
  vi = 6; vj = 1; CHECK(lut[vi][vj] == (i16)(-17426)); CHECK(rowp[vi][vj] == (i16)(-17426));
  vi = 6; vj = 2; CHECK(lut[vi][vj] == (i16)(11214)); CHECK(rowp[vi][vj] == (i16)(11214));
  vi = 3; vj = 4; CHECK(lut[vi][vj] == (i16)(-32515)); CHECK(rowp[vi][vj] == (i16)(-32515));
  vi = 7; vj = 2; CHECK(lut[vi][vj] == (i16)(7151)); CHECK(rowp[vi][vj] == (i16)(7151));
  vi = 4; vj = 5; CHECK(lut[vi][vj] == (i16)(8576)); CHECK(rowp[vi][vj] == (i16)(8576));
  vi = 1; vj = 7; CHECK(lut[vi][vj] == (i16)(-12851)); CHECK(rowp[vi][vj] == (i16)(-12851));
  vi = 7; vj = 5; CHECK(lut[vi][vj] == (i16)(-21861)); CHECK(rowp[vi][vj] == (i16)(-21861));
  vi = 7; vj = 6; CHECK(lut[vi][vj] == (i16)(-26889)); CHECK(rowp[vi][vj] == (i16)(-26889));
  vi = 6; vj = 6; CHECK(lut[vi][vj] == (i16)(-9321)); CHECK(rowp[vi][vj] == (i16)(-9321));
  vi = 1; vj = 5; CHECK(lut[vi][vj] == (i16)(2506)); CHECK(rowp[vi][vj] == (i16)(2506));
  vi = 7; vj = 2; CHECK(lut[vi][vj] == (i16)(7151)); CHECK(rowp[vi][vj] == (i16)(7151));
  vi = 6; vj = 4; CHECK(lut[vi][vj] == (i16)(-9809)); CHECK(rowp[vi][vj] == (i16)(-9809));
  vi = 5; vj = 3; CHECK(lut[vi][vj] == (i16)(29451)); CHECK(rowp[vi][vj] == (i16)(29451));
  vi = 7; vj = 2; CHECK(lut[vi][vj] == (i16)(7151)); CHECK(rowp[vi][vj] == (i16)(7151));
  vi = 3; vj = 2; CHECK(lut[vi][vj] == (i16)(17861)); CHECK(rowp[vi][vj] == (i16)(17861));
  vi = 1; vj = 6; CHECK(lut[vi][vj] == (i16)(-27)); CHECK(rowp[vi][vj] == (i16)(-27));
  vi = 7; vj = 3; CHECK(lut[vi][vj] == (i16)(-286)); CHECK(rowp[vi][vj] == (i16)(-286));
  vi = 3; vj = 7; CHECK(lut[vi][vj] == (i16)(-3573)); CHECK(rowp[vi][vj] == (i16)(-3573));
  vi = 0; vj = 4; CHECK(lut[vi][vj] == (i16)(12947)); CHECK(rowp[vi][vj] == (i16)(12947));
  for (i = 0; i < 8; i++) {
    if (i == 0) CHECK(row_sum(rowp[i]) == (i32)4274LL);
    if (i == 1) CHECK(row_sum(rowp[i]) == (i32)45381LL);
    if (i == 2) CHECK(row_sum(rowp[i]) == (i32)10935LL);
    if (i == 3) CHECK(row_sum(rowp[i]) == (i32)-31170LL);
    if (i == 4) CHECK(row_sum(rowp[i]) == (i32)89756LL);
    if (i == 5) CHECK(row_sum(rowp[i]) == (i32)111608LL);
    if (i == 6) CHECK(row_sum(rowp[i]) == (i32)-2445LL);
    if (i == 7) CHECK(row_sum(rowp[i]) == (i32)-25736LL);
  }
  return 0;
}
