// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const table of handlers indexed by an enum, called through a pointer.
#include "loomcc-test.h"
static i16 h0(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (72)); }
static i16 h1(u8 a, i16 b) { return (i16)(((i16)a + b) + (-52)); }
static i16 h2(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (-79)); }
static i16 h3(u8 a, i16 b) { return (i16)(((i16)a + b) + (-49)); }
static i16 h4(u8 a, i16 b) { return (i16)(((i16)a + b) + (64)); }
static i16 h5(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (-24)); }
static i16 h6(u8 a, i16 b) { return (i16)(((i16)a - b) + (-96)); }
static i16 h7(u8 a, i16 b) { return (i16)(((i16)a + b) + (-97)); }
static i16 h8(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (51)); }
enum Ev { EV_0, EV_1, EV_2, EV_3, EV_4, EV_5, EV_6, EV_7, EV_8, EV_COUNT };
typedef i16 (*Handler)(u8, i16);
static const Handler handlers[EV_COUNT] = { h0, h1, h2, h3, h4, h5, h6, h7, h8 };
static i16 dispatch(enum Ev e, u8 a, i16 b) { return (u8)e < EV_COUNT ? handlers[e](a, b) : 0; }
int main(void) {
  CHECK(dispatch(EV_1, 186, 531) == ((665)));
  CHECK(dispatch(EV_0, 39, -174) == ((-67)));
  CHECK(dispatch(EV_2, 143, -232) == ((-184)));
  CHECK(dispatch(EV_0, 77, 798) == ((923)));
  CHECK(dispatch(EV_8, 224, 143) == ((162)));
  CHECK(dispatch(EV_8, 101, -829) == ((-807)));
  CHECK(dispatch(EV_5, 12, -259) == ((-295)));
  CHECK(dispatch(EV_6, 113, -697) == ((714)));
  CHECK(dispatch(EV_3, 47, 344) == ((342)));
  CHECK(dispatch(EV_2, 142, -428) == ((-373)));
  CHECK(dispatch(EV_7, 116, -676) == ((-657)));
  CHECK(dispatch(EV_7, 111, -403) == ((-389)));
  CHECK(dispatch(EV_7, 148, -461) == ((-410)));
  CHECK(dispatch(EV_8, 236, 877) == ((948)));
  CHECK(dispatch(EV_8, 143, -149) == ((23)));
  CHECK(dispatch(EV_8, 24, -840) == ((-813)));
  return 0;
}
