// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const table of handlers indexed by an enum, called through a pointer.
#include "loomcc-test.h"
static i16 h0(u8 a, i16 b) { return (i16)(((i16)a + b) + (-66)); }
static i16 h1(u8 a, i16 b) { return (i16)(((i16)a + b) + (54)); }
enum Ev { EV_0, EV_1, EV_COUNT };
typedef i16 (*Handler)(u8, i16);
static const Handler handlers[EV_COUNT] = { h0, h1 };
static i16 dispatch(enum Ev e, u8 a, i16 b) { return (u8)e < EV_COUNT ? handlers[e](a, b) : 0; }
int main(void) {
  CHECK(dispatch(EV_0, 224, -841) == ((-683)));
  CHECK(dispatch(EV_1, 12, -471) == ((-405)));
  CHECK(dispatch(EV_1, 68, 511) == ((633)));
  CHECK(dispatch(EV_0, 11, 418) == ((363)));
  CHECK(dispatch(EV_1, 153, 120) == ((327)));
  CHECK(dispatch(EV_0, 196, -872) == ((-742)));
  CHECK(dispatch(EV_1, 224, -219) == ((59)));
  CHECK(dispatch(EV_0, 3, 717) == ((654)));
  CHECK(dispatch(EV_0, 232, 748) == ((914)));
  CHECK(dispatch(EV_1, 125, -357) == ((-178)));
  CHECK(dispatch(EV_0, 246, 653) == ((833)));
  CHECK(dispatch(EV_1, 157, 200) == ((411)));
  CHECK(dispatch(EV_1, 184, -925) == ((-687)));
  CHECK(dispatch(EV_0, 138, -848) == ((-776)));
  CHECK(dispatch(EV_0, 235, -748) == ((-579)));
  CHECK(dispatch(EV_0, 149, 797) == ((880)));
  return 0;
}
