// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const table of handlers indexed by an enum, called through a pointer.
#include "loomcc-test.h"
static i16 h0(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (70)); }
static i16 h1(u8 a, i16 b) { return (i16)(((i16)a + b) + (-39)); }
static i16 h2(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (37)); }
static i16 h3(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (-87)); }
static i16 h4(u8 a, i16 b) { return (i16)(((i16)a - b) + (14)); }
static i16 h5(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (53)); }
enum Ev { EV_0, EV_1, EV_2, EV_3, EV_4, EV_5, EV_COUNT };
typedef i16 (*Handler)(u8, i16);
static const Handler handlers[EV_COUNT] = { h0, h1, h2, h3, h4, h5 };
static i16 dispatch(enum Ev e, u8 a, i16 b) { return (u8)e < EV_COUNT ? handlers[e](a, b) : 0; }
int main(void) {
  CHECK(dispatch(EV_4, 155, -881) == ((1050)));
  CHECK(dispatch(EV_5, 115, -670) == ((-698)));
  CHECK(dispatch(EV_1, 229, 551) == ((741)));
  CHECK(dispatch(EV_0, 235, 962) == ((879)));
  CHECK(dispatch(EV_4, 177, -693) == ((884)));
  CHECK(dispatch(EV_0, 176, 405) == ((363)));
  CHECK(dispatch(EV_4, 32, 950) == ((-904)));
  CHECK(dispatch(EV_4, 183, 227) == ((-30)));
  CHECK(dispatch(EV_5, 30, -276) == ((-217)));
  CHECK(dispatch(EV_4, 101, 770) == ((-655)));
  CHECK(dispatch(EV_0, 102, -18) == ((-50)));
  CHECK(dispatch(EV_0, 48, 964) == ((1082)));
  CHECK(dispatch(EV_4, 16, -11) == ((41)));
  CHECK(dispatch(EV_2, 186, 523) == ((726)));
  CHECK(dispatch(EV_4, 157, -939) == ((1110)));
  CHECK(dispatch(EV_4, 62, -76) == ((152)));
  return 0;
}
