// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// A const table of handlers indexed by an enum, called through a pointer.
#include "loomcc-test.h"
static i16 h0(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (34)); }
static i16 h1(u8 a, i16 b) { return (i16)(((i16)a ^ b) + (34)); }
static i16 h2(u8 a, i16 b) { return (i16)(((i16)a + b) + (10)); }
static i16 h3(u8 a, i16 b) { return (i16)(((i16)a - b) + (-30)); }
enum Ev { EV_0, EV_1, EV_2, EV_3, EV_COUNT };
typedef i16 (*Handler)(u8, i16);
static const Handler handlers[EV_COUNT] = { h0, h1, h2, h3 };
static i16 dispatch(enum Ev e, u8 a, i16 b) { return (u8)e < EV_COUNT ? handlers[e](a, b) : 0; }
int main(void) {
  CHECK(dispatch(EV_2, 133, 460) == ((603)));
  CHECK(dispatch(EV_1, 156, 858) == ((1000)));
  CHECK(dispatch(EV_2, 186, -16) == ((180)));
  CHECK(dispatch(EV_0, 222, -582) == ((-634)));
  CHECK(dispatch(EV_0, 226, 254) == ((62)));
  CHECK(dispatch(EV_0, 186, -224) == ((-68)));
  CHECK(dispatch(EV_2, 4, -932) == ((-918)));
  CHECK(dispatch(EV_0, 199, 192) == ((41)));
  CHECK(dispatch(EV_2, 200, 508) == ((718)));
  CHECK(dispatch(EV_2, 176, -348) == ((-162)));
  CHECK(dispatch(EV_2, 139, -145) == ((4)));
  CHECK(dispatch(EV_3, 33, -872) == ((875)));
  CHECK(dispatch(EV_1, 187, 868) == ((1025)));
  CHECK(dispatch(EV_1, 54, 141) == ((221)));
  CHECK(dispatch(EV_0, 238, -894) == ((-882)));
  CHECK(dispatch(EV_3, 25, 688) == ((-693)));
  return 0;
}
