// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [90, 90, 90] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[90];
  u8 a1[90];
  u8 a2[90];
  u16 i, s;
  for (i = 0; i < 90; i++) a0[i] = (u8)(i * 3 + 0);
  for (i = 0; i < 90; i++) a1[i] = (u8)(i * 4 + 1);
  for (i = 0; i < 90; i++) a2[i] = (u8)(i * 5 + 2);
  s = 0; for (i = 0; i < 90; i++) s = (u16)(s + a0[i]); CHECK(s == 10991u); CHECK(a0[89] == 11);
  s = 0; for (i = 0; i < 90; i++) s = (u16)(s + a1[i]); CHECK(s == 9454u); CHECK(a1[89] == 101);
  s = 0; for (i = 0; i < 90; i++) s = (u16)(s + a2[i]); CHECK(s == 10221u); CHECK(a2[89] == 191);
}
int main(void) { work(); return 0; }
