// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [255, 2] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[255];
  u8 a1[2];
  u16 i, s;
  for (i = 0; i < 255; i++) a0[i] = (u8)(i * 3 + 0);
  for (i = 0; i < 2; i++) a1[i] = (u8)(i * 4 + 1);
  s = 0; for (i = 0; i < 255; i++) s = (u16)(s + a0[i]); CHECK(s == 32387u); CHECK(a0[254] == 250);
  s = 0; for (i = 0; i < 2; i++) s = (u16)(s + a1[i]); CHECK(s == 6u); CHECK(a1[1] == 5);
}
int main(void) { work(); return 0; }
