// Generated by scripts/gen-families.py; do not edit.
// loomcc-do: run
// loomcc-int: agnostic
// Local arrays of [130] bytes in one frame.
#include "loomcc-test.h"
static void work(void) {
  u8 a0[130];
  u16 i, s;
  for (i = 0; i < 130; i++) a0[i] = (u8)(i * 3 + 0);
  s = 0; for (i = 0; i < 130; i++) s = (u16)(s + a0[i]); CHECK(s == 13891u); CHECK(a0[129] == 131);
}
int main(void) { work(); return 0; }
