#!/usr/bin/env python3
"""Lists every declared reference-tool divergence, grouped by tool and code.

    scripts/divergences.py            # print the markdown index
    scripts/divergences.py --write    # replace the index at the end of docs/DIVERGENCES.md
"""
import io
import re
import sys
from collections import defaultdict
from pathlib import Path

root = Path(__file__).resolve().parent.parent / "tests"
pat = re.compile(r"loomcc-ref-diverges:\s*(\S+)\s+(?:\[([^\]]+)\])?\s*(.*?)\s*(?:\*/)?$")
groups = defaultdict(list)
reasons = {}
for f in sorted(root.rglob("*.c")):
    for line in f.read_text(errors="replace").splitlines():
        m = pat.search(line)
        if m:
            tool, code, reason = m.group(1), m.group(2) or "uncoded", m.group(3)
            groups[(tool, code)].append(str(f.relative_to(root)))
            reasons.setdefault((tool, code), reason)
out = io.StringIO()
for (tool, code), files in sorted(groups.items()):
    print(f"### `{code}` ({tool}, {len(files)} test{'s' if len(files) != 1 else ''})\n", file=out)
    print(f"{reasons[(tool, code)]}\n", file=out)
    for f in files:
        print(f"- `{f}`", file=out)
    print(file=out)
marker = "## Index (generated by scripts/divergences.py)"
if "--write" in sys.argv:
    doc = root.parent / "docs" / "DIVERGENCES.md"
    head = doc.read_text().split(marker)[0]
    doc.write_text(head + marker + "\n\n" + out.getvalue())
else:
    print(out.getvalue(), end="")
